### ISSUE TITLE
Drop and recreate database require for release 12.0

### ISSUE THREAD

**Issue by jower999** [input-output-hk/cardano-db-sync#1001]
Hey

Why is it required to drop and recreate the database for this release?
It seems to have worked fin just to update for me. I was previously on version 11.04 and a fully synced database following cardano-node 1.31

**Comment by DamjanOstrelic** [comment]
Any major version upgrade requires a full DB re-sync AFAIK since the DB schema changes in that case.
You can use a [db-sync state snapshot](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/state-snapshot.md) to speed up the re-syncing.

**Comment by jower999** [comment]
But there seems to be migrations scripts running at startup. Of course there could be new data columns not populatable from old data, if that is what you mean?

**Comment by DamjanOstrelic** [comment]
Imagine you have a table `example` with columns `A | B | C` in your synced DB.

The new DB wants a table also called `example` with columns `A | D | E`. How can you get there? Although there are probably some PostgreSQL commands using `ALTER TABLE` that could do the trick in simple scenarios, for something as complicated and requiring as much data validation as `cardano-db-sync`, it is much easier (and safer) to fully re-create and populate the table.

At least that is how I understand it, maybe some of the db-sync devs can give a better explanation.

**Comment by erikd** [comment]
If the database schema changes to add a new table or add an new column to an existing table, the only way to correctly populate these new tables/columns is to sync from scratch,

If you look at the [release notes](https://github.com/input-output-hk/cardano-db-sync/releases/tag/12.0.0) for this release you will see that existing tables were modified and new tables were added.

If you have not dropped the existing database and either resynced or used the snapshot, your current database will not be correct.

**Comment by jower999** [comment]
Thanks for the responses here. I have now restored the latest snapshot. I would like to know how one would handle this in a production setup where I need to be able to present updated data all the time. Is there anyway to restore the latest snapshot while still keeping the old version running and the do a switchover once the new version is fully updated? How often are snapshots produced?

**Comment by rdlrt** [comment]
>  I would like to know how one would handle this in a production setup where I need to be able to present updated data all the time

You wouldn't want to run production  using single instance, you'd need to run a cluster and perform rolling maintenance.

**Comment by erikd** [comment]
Closing this.
