### ISSUE TITLE
Nix compilation error: "go tool dist: Failed: exit status 1"

### ISSUE THREAD

**Issue by tooLateForTown** [input-output-hk/cardano-db-sync#1002]
**OS**
Your OS: Ubuntu Server 20.04.3 LTS (Focal Fossa)

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): Latest tag
PostgreSQL version:

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:
Followed the official instructions.
nix-build -A cardano-db-sync -o db-sync-node

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):  n/a

**Additional context**
The nix-build runs for at least an hour and fails everytime at this point.  This is a fresh installation of the linux server and only has cardano-node and nix installed.  I tried re-running multiple times but always halts on this error

**Problem Report**
end of compilation output:
ok      cmd/go/internal/modfetch/codehost       0.021s
ok      cmd/go/internal/modfetch/zip_sum_test   0.053s
ok      cmd/go/internal/modload 0.053s
ok      cmd/go/internal/mvs     0.023s
ok      cmd/go/internal/par     0.099s
ok      cmd/go/internal/renameio        0.298s
ok      cmd/go/internal/search  0.027s
ok      cmd/go/internal/str     0.035s
ok      cmd/go/internal/test    0.040s
ok      cmd/go/internal/txtar   0.034s
ok      cmd/go/internal/vcs     0.046s
ok      cmd/go/internal/web     0.034s
ok      cmd/go/internal/work    0.038s
ok      cmd/gofmt       0.071s
ok      cmd/internal/archive    1.869s
ok      cmd/internal/buildid    0.179s
ok      cmd/internal/dwarf      0.008s
ok      cmd/internal/edit       0.015s
ok      cmd/internal/goobj      0.013s
ok      cmd/internal/moddeps    1.571s
ok      cmd/internal/obj        0.100s
ok      cmd/internal/obj/ppc64  0.121s
ok      cmd/internal/obj/riscv  0.109s
ok      cmd/internal/obj/s390x  0.014s
ok      cmd/internal/obj/x86    0.471s
ok      cmd/internal/objabi     0.028s
ok      cmd/internal/pkgpath    0.070s
ok      cmd/internal/src        0.021s
ok      cmd/internal/sys        0.028s
ok      cmd/internal/test2json  0.135s
ok      cmd/link        16.328s
ok      cmd/link/internal/benchmark     0.065s
ok      cmd/link/internal/ld    6.089s
ok      cmd/link/internal/loader        0.069s
ok      cmd/nm  5.833s
ok      cmd/objdump     7.012s
ok      cmd/pack        5.024s
ok      cmd/trace       0.414s
ok      cmd/vet 10.260s
FAIL
go tool dist: Failed: exit status 1
error: builder for '/nix/store/z13apyc6mav56dbbhrmqy92w0j4d08rc-go-1.16.9.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/dwc4pv63z8ymfx0hci9am3ir2b8l5dcr-git-lfs-3.0.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f26gk5qfyc80kdwpk1i0apbdp1sjbwkr-nix-prefetch-git.drv' failed to build
building '/nix/store/cjfxz7bliblfl39ql2faj2gwn7dijz1f-vector-0.12.3.1-1.cabal.drv'...
error: 1 dependencies of derivation '/nix/store/gpvpv8rgaa4y06mzjkayp5d997fj3lnp-nix-tools.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sf6rr5nnl3lnb4z1nanx6zjvn5q3wnbv-haskell-project-plan-to-nix-pkgs.drv' failed to build
(use '--show-trace' to show detailed location information)

**Comment by sorki** [comment]
You should install NixOS/IOHK binary caches rather than compiling everything from scratch. Such failure is not related to db-sync.

**Comment by tooLateForTown** [comment]
Thank seems to work.  Thanks.  The instructions I found made it appear that the binary caches were optional so I ignored it.
