### ISSUE TITLE
Need help / virtual server / image of synced db-sync

### ISSUE THREAD

**Issue by dorijan** [input-output-hk/cardano-db-sync#1008]
Hi to all, 
my sync is taking long time for sync, is there anywhere fully synced images of anyone willing to share?
Thank you...

**Comment by rdlrt** [comment]
Check release notes to download snapshots for database synched to recent epoch

**Comment by dorijan** [comment]
> Check release notes to download snapshots for database synched to recent epoch

thank you for replay, I am doing that, but it is still slow :(

**Comment by erikd** [comment]
Restoring from a snapshot takes 1-3 hours. Syncing from scratch takes many days.

**Comment by dorijan** [comment]
I am not sure how you managed to sync it in 1-3 hours, I have started import 24h ago and now it is at insertShelleyBlock(Mary): epoch 255, slot 24882039, block 5495000, hash 535c643f5c77874966593c08b6bef4ada30a1b25dd3b5e5bc1f84a9061f8596a

My server is 24 x Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz (2 Sockets), 64gb ram and fast nvme disk

Of course, I used this command:

`RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-12-block-6693499-x86_64.tgz NETWORK=mainnet docker-compose up && docker-compose logs -f`

**Comment by erikd** [comment]
I did not sync in 1-3 hours. I restored from a recent snapshot in 1-3 hours.

Syncing from scratch will likely take days.

**Comment by dorijan** [comment]
This is restore from recent snapshot, if you look above, I used snapshot RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-12-block-6693499-x86_64.tgz

**Comment by erikd** [comment]
I know close to nothing about docker. I suspect you are running into known bug with the docker script where `db-sync` is forced to roll back to genesis (and hence resync) if the `node` sync is behind the snapshot. There is a GH issue for this somewhere but I cannot currently find it.

**Comment by dorijan** [comment]
yes, I know this problem, but this not the case. I first get the node fully synced and then start the db restore :(

**Comment by erikd** [comment]
If that is the case then there must be something else in the logs. The snapshot you used (`db-sync-snapshot-schema-12-block-6693499-x86_64.tgz`) starts at epoch `311` but your log message above talks about epoch `255`. This suggests that either the database rolled back or the snapshot was not restored correctly.
