### ISSUE TITLE
Excessive rollback on restart

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#1018]
Just stoppped and restarted my `db-sync` instance (running `master` with a WIP commit) and got:

```
[2022-01-12 07:34:41.03 UTC] Deleting 287956 blocks up to slot 48428762
```

This is rolling back more than 10 epochs which is obviously insane. The ledger state files looks like:

```
-rw-r--r-- 1 nix nix  844770454 Jan 11 12:03 40780785-307ddb9cbe-291.lstate
-rw-r--r-- 1 nix nix  869286380 Jan 11 13:06 41212785-75f06c4e4f-292.lstate
-rw-r--r-- 1 nix nix  886866715 Jan 11 14:09 41644786-12d253ab96-293.lstate
-rw-r--r-- 1 nix nix  890836821 Jan 11 15:16 42076780-dbeeb69efb-294.lstate
-rw-r--r-- 1 nix nix  901405497 Jan 11 16:13 42508793-3b078f7932-295.lstate
-rw-r--r-- 1 nix nix 1195347245 Jan 12 18:26 48435066-606c4616f1.lstate
-rw-r--r-- 1 nix nix 1195594762 Jan 12 18:28 48444932-d9b2c18efd.lstate
-rw-r--r-- 1 nix nix  650161487 Jan 12 18:31 48455630-256fc8b7b3.lstate
```

I think this is due to 5a0a96f9ad3c3aaaa9259b72207e58718a312356 (not in any releases) which disables the storing of snapshots at epoch boundaries, but it looks like restarts **only** start from an epoch boundary and since a more recent boundary ledger state does not exist, it rolls back to epoch `295`.

**Comment by kderme** [comment]
Something looks strange about it. It should rollback to the latest snapshot, slot 1195594762, even if it's not an epoch boundary snapshot.

**Comment by erikd** [comment]
Can't seem to be able to reproduce this.

**Comment by erikd** [comment]
Confirmed than after #1014 something really strange has happened to rollbacks.

**Comment by erikd** [comment]
:sob: Now at epoch `298` I get a `validateEpochRewards` failure. That is with PR #1014 merged, I think that will need to be reverted.

**Comment by erikd** [comment]
I do not see any solution other than to revert PR #1014 . Debugging this issue is difficult.

The logic that PR #1014 removes is only there because of the incredibly sub optimal way rewards and the epoch stake distribution are currently calculated. If these issues were fixed, we would only need to rollback (at the maximum) a couple of blocks on restart.

**Comment by sorki** [comment]
Good catch, feel free to revert it - reading to code I wasn't even able to figure out what triggers larger rollbacks (e.g. to start of an epoch) and why this would cause such issues. I'm slowly working through internals and rollback logic so might come with better patch but you are probably right that this won't be doable unless the underlying ledger submits rewards/stake gradually instead of large batches at start.
