### ISSUE TITLE
Empty TX inputs/outputs

### ISSUE THREAD

**Issue by dmitrystas** [input-output-hk/cardano-db-sync#1019]
**OS**
Debian

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): cardano-db-sync-extended 12.0.0 - linux-x86_64 - ghc-8.10
git revision 9d0180571482ee4c6acb6fbc6bf55b5a4e2ee833
PostgreSQL version: 14.1

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Hydra binaries

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): systemd

**Additional context**
The database restored from snapshot db-sync-snapshot-schema-12-block-6647999-x86_64.tgz

**Problem Report**
There are no rows for tx f9ed2fef27cdcf60c863ba03f27d0e38f39c5047cf73ffdf2428b48edbe83234 in the tx_out table in DB Sync 12

```
SELECT id FROM tx WHERE hash = '\xf9ed2fef27cdcf60c863ba03f27d0e38f39c5047cf73ffdf2428b48edbe83234';

    id
----------
 25318047
(1 row)
```

```
SELECT id
FROM tx_out
WHERE tx_id = (SELECT id FROM tx WHERE hash = '\xf9ed2fef27cdcf60c863ba03f27d0e38f39c5047cf73ffdf2428b48edbe83234');

 id
----
(0 rows)

```

DB Sync 11 (cardano-db-sync-extended 11.0.4 - linux-x86_64 - ghc-8.10
git revision b5cd53d2e86f45127d98de429e8a2b6879fd8a56) feels good

```
SELECT id
FROM tx_out
WHERE tx_id = (SELECT id FROM tx WHERE hash = '\xf9ed2fef27cdcf60c863ba03f27d0e38f39c5047cf73ffdf2428b48edbe83234');

    id
----------
 67617947
(1 row)

```

**Comment by dmitrystas** [comment]
But what's interesting - dbsync 11 has completely different data about this tx

**Comment by dmitrystas** [comment]
In the Guild we found out that this failed contract tx, and entire input of tx was burned, so probably DB Sync 12 is right, and there are no tx outputs. But the problem is that besides the outputs, I also don't see any tx inputs

```
SELECT tx_in.id
FROM tx_in
LEFT JOIN tx_out ON (tx_out.tx_id = tx_in.tx_out_id AND tx_out.index = tx_in.tx_out_index)
WHERE tx_in.tx_in_id = (SELECT id FROM tx WHERE hash = '\xf9ed2fef27cdcf60c863ba03f27d0e38f39c5047cf73ffdf2428b48edbe83234');
```

DB Sync 12
```
 id
----
(0 rows)
```


DB Sync 11
```
    id
----------
 62482962
(1 row)
```

**Comment by dmitrystas** [comment]
And collateral_tx_in also does not contain data for this tx

```
SELECT collateral_tx_in.id
FROM collateral_tx_in
LEFT JOIN tx_out ON (tx_out.tx_id = collateral_tx_in.tx_out_id AND tx_out.index = collateral_tx_in.tx_out_index)
WHERE collateral_tx_in.tx_in_id = (SELECT id FROM tx WHERE hash = '\xf9ed2fef27cdcf60c863ba03f27d0e38f39c5047cf73ffdf2428b48edbe83234');
```

DB Sync 12

```
 id
----
(0 rows)
```

DB Sync 11

```
    id
----------
 151912
(1 row)
```

**Comment by sorki** [comment]
This is expected in v12 as no inputs (and bunch of other information) are stored if phase 2 validation fails, see https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Insert.hs#L281-L305

**Comment by kderme** [comment]
Yes that's a bug, `tx_in` table should contain the collateral inputs for txs with invalid scripts.
