### ISSUE TITLE
Make Cardano.Db.Query a haskell package?

### ISSUE THREAD

**Issue by marijanp** [input-output-hk/cardano-db-sync#1025]
I'm building a Haskell App which needs to query some of the information available in the database and I found myself rewriting queries and parts of the schema which are already available in Cardano.Db.Query and Cardano.Db.Schema, but unfortunately not available as a Haskell package.

I know I could use CardanoGraphQL but I feel it would just shift the problem. Using GraphQl I would still be required to write client functions and parse the data into custom types.

**Comment by erikd** [comment]
`cardano-db` is already a package and includes the two modules you ask about (and not much else). Why not just use that?

**Comment by marijanp** [comment]
I'm trying to avoid adding and maintaining all the dependencies (i.e. all dependencies of cardano-db-sync's `cabal.project`) manually in my `cabal.project`. To make use of `cardano-db` I would need to add a `source-repository-package` for `cardano-db-sync `and all the other cardano related packages which are not available on hackage...
But I decided to move on with GraphQl since I don't want my code to rely on database layer related structures, which are probably subject to change. Better to implement against a more abstract layer.

**Comment by erikd** [comment]
Can we close this then?
