### ISSUE TITLE
Ledger state distributed with cardano-db-sync appears to be corrupt

### ISSUE THREAD

**Issue by rxdn** [input-output-hk/cardano-db-sync#1027]
**OS**
Your OS: Ubuntu 21.04

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): cardano-db-sync 12.0.1 - linux-x86_64 - ghc-8.10
git revision 6a5ea215f525d4136548f25f6859af444a7a9f93

PostgreSQL version: 13.5

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: From the [docs](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/building-running.md)
```
git clone https://github.com/input-output-hk/cardano-db-sync
cd cardano-db-sync
nix-build -A cardano-db-sync -o db-sync-node
```

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): None
```
PGPASSFILE=pgpass ./db-sync --config mainnet-config.yaml --socket-path ../node/state-node-mainnet/node.socket --state-dir ledger-state/mainnet --schema-dir schema/
```

**Additional context**
N/A

**Problem Report**
It appears that the ledger states distributed with the database [snapshots](https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#12/) are corrupt.

After successfully restoring the snapshots via
```
PGPASSFILE=pgpass ./postgresql-setup.sh --restore-snapshot snapshot.tgz ledger-state/mainnet/
```

I am presented with an error while booting cardano-db-sync. For `db-sync-snapshot-schema-12-block-6764999-x86_64.tgz` the error is as follows:
```
[db-sync-node:Warning:66] [2022-01-23 14:51:04.56 UTC] Failed to parse ledger state file ledger-state/mainnet/50800917-06a934b7fe.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 58026 "expected list len or indef")'. Deleting it.
```

I then tried the second newest snapshot (`db-sync-snapshot-schema-12-block-6746999-x86_64.tgz`), which presented me with a similar but slightly different error:
```
[db-sync-node:Info:56] [2022-01-23 17:12:57.45 UTC] Cardano.Db tip is at slot 50418212, block 6746999
[db-sync-node:Info:67] [2022-01-23 17:12:57.45 UTC] Running Offline fetch thread
[db-sync-node:Info:66] [2022-01-23 17:12:57.45 UTC] Running DB thread
[db-sync-node:Info:66] [2022-01-23 17:12:57.46 UTC] Rolling back to slot 50418212, hash 8ec6d11b1f8976f7a13e26e21c92ce34d00e53bacdd822c6f51893f382d7849a
[db-sync-node:Info:66] [2022-01-23 17:12:57.46 UTC] No blocks need to be deleted
[db-sync-node:Warning:66] [2022-01-23 17:12:58.19 UTC] Failed to parse ledger state file ledger-state/mainnet/50418212-8ec6d11b1f.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 61203 "expected list len or indef")'. Deleting it.
[db-sync-node:Warning:66] [2022-01-23 17:12:58.33 UTC] Rollback failed. No more ledger state files.
[db-sync-node:Info:66] [2022-01-23 17:12:58.55 UTC] Rolling back to genesis
```

Cheers

**Comment by erikd** [comment]
> It appears that the ledger states

My understanding is that many people have already successfully used the snapshots.

My guess is that the snapshot you are using is corrrect, but that the version of `db-sync` you are running is not what you think it it. You say you ran:

```
git clone https://github.com/input-output-hk/cardano-db-sync
cd cardano-db-sync
nix-build -A cardano-db-sync -o db-sync-node
```

If you did not check out the `12.0.0` then you are not running `12.0.0`.

**Comment by rxdn** [comment]
Can confirm that running 12.0.0 rather than 12.0.1 fixed the issue - thank you!

I got the instructions from [doc/building-running.md](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/building-running.md) (Set up and run the db-sync node
-> with nix) which is linked in the README.md:
![README.md](https://i.imgur.com/jc9c4pv.png)

**Comment by erikd** [comment]
> Can confirm that running 12.0.0 rather than 12.0.1 fixed the issue - thank you!

It was not actually `12.0.1` that was the issue, it was that you were building from the `master` branch rather than an official release tag.

PR #1030 updates those docs to strongly advises the use of latest release tag (which are compatible with the snapshots).
