### ISSUE TITLE
Sum of transaction sizes for a block exceeds block size

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/cardano-db-sync#1045]
**OS**
ubuntu

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): cardano-db-sync 12.0.0 - linux-x86_64 - ghc-8.10, git revision 9d0180571482ee4c6acb6fbc6bf55b5a4e2ee833
PostgreSQL version: 14

**Build/Install Method**
cabal

**Run method**
systemd

Sample mainnet query demonstrating the issue:

```
psql -d cexplorer -c 'select b.block_no, b.size as block_size, (select sum(t.size) from tx t where
t.block_id = b.id) sum_tx_sizes from block b where b.block_no in ('6826761', '6825528', '6824958');'
```

yields:
```
 block_no | block_size  | sum_tx_sizes 
----------+-------------+--------------
  6824958 | 62470       |        62480
  6825528 | 63797       |        63811
  6826761 | 60800       |        60818
```

**Comment by erikd** [comment]
Tweaking the query a little:
```
 # select block_no, block.size, sum(tx.size) as sum_tx_size from block inner join tx
     on tx.block_id = block.id group by block_no, block.size
     having block.size < sum (tx.size) order by block_no asc limit 10 ;
 block_no | size | sum_tx_size 
----------+------+-------------
  4490522 | 1438 |        1441
  4490523 |  595 |         596
  4490524 |  887 |         890
  4490525 | 1060 |        1063
  4490526 | 1915 |        1918
  4490527 | 3533 |        3534
  4490528 | 5655 |        5664
  4490529 | 4152 |        4163
  4490530 | 3727 |        3738
  4490531 | 2657 |        2662
(10 rows)
```
suggesting its more than just a small number of blocks that are out.

**Comment by erikd** [comment]
In `cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Generic/Block.hs` we have:
```
    , blkSize = blockSize blk
```
so `db-sync` is simply grabbing the block size using the functionality from the `ledger`.

Similarly, for the transactions:

```
      , txSize = fromIntegral $ getField @"txsize" tx
```
again, just grabbing the value provided by the `ledger`.

**Comment by erikd** [comment]
According to the `ledger` people, this is a side effect of the CBOR encoding. The CBOR encoding of a block body (which includes a sequence of txs) can be smaller than sum of the lengths of the CBOR encodings of the individual txs.

This will be addressed with documentation.

**Comment by erikd** [comment]
@hodlonaut Is that sufficient explanation?
