### ISSUE TITLE
Get unsupported error message "Node configs that don't fork to Shelley directly..." running cardano-db-sync against private Cardano testnet

### ISSUE THREAD

**Issue by woofpool** [input-output-hk/cardano-db-sync#1046]
**OS**
Your OS: Ubuntu 20.04

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 12.0.0
PostgreSQL version: 13.5 (ubuntu)

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: from haskell sources using cabal 3.4.0.0 and ghc 8.10.7

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): command line `cardano-db-sync` passing in config, socket-path, state-dir, and schema-dir args.

**Additional context**
My backend cardano-node is a private network bootstrapped using the `cardano-node` scripts as described by this readme.md
https://github.com/input-output-hk/cardano-node/tree/master/scripts#byron-to-alonzo

**Problem Report**
When I run `cardano-db-sync`, it starts up, but it encounters error due to a validation check "Node configs that don't fork to Shelley directly and initiate funds or stakes in Shelley Genesis are not supported."  How can I satisfy this check, but still run a private cardano testnet locally?

log output
```
kurt@pop-os:~/IdeaProjects/cardano-private-testnet-setup$ ./scripts/db-sync-start.sh
[db-sync-node:Info:6] [2022-02-02 19:54:28.99 UTC] Schema migration files validated
[db-sync-node:Info:6] [2022-02-02 19:54:28.99 UTC] Running database migrations
[db-sync-node:Info:6] [2022-02-02 19:54:28.99 UTC] Enviroment variable DbSyncAbortOnPanic: False
[db-sync-node:Info:6] [2022-02-02 19:54:30.25 UTC] Using byron genesis file from: "private-testnet/./byron/genesis.json"
[db-sync-node:Info:6] [2022-02-02 19:54:30.25 UTC] Using shelley genesis file from: "private-testnet/./shelley/genesis.json"
[db-sync-node:Info:6] [2022-02-02 19:54:30.25 UTC] Using alonzo genesis file from: "private-testnet/./shelley/genesis.alonzo.json"
[db-sync-node:Info:6] [2022-02-02 19:54:30.25 UTC] NetworkMagic: 42
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.25 UTC] SELECT "block"."id"
FROM "block"
WHERE "block"."hash" = ?
; [PersistByteString "\253\227\153b4\249\224\DC1\ESC)\131\153\229\184\SUB\177s\207\140\187u\247\ETB\129z\SUB\234\EOT\208_\193\154"]
[db-sync-node:Info:6] [2022-02-02 19:54:30.25 UTC] Inserting Byron Genesis distribution
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.25 UTC] SELECT COUNT(*)
FROM "block"
; []
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.25 UTC] INSERT INTO meta ("start_time", "network_name", "version") VALUES (?, ?, ?) ON CONFLICT ON CONSTRAINT unique_meta DO UPDATE SET "start_time" = EXCLUDED."start_time" RETURNING id ;; [PersistUTCTime 2022-02-02 18:56:29 UTC,PersistText "privatenet",PersistText "Version {versionBranch = [12,0,0], versionTags = []}"]
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.25 UTC] INSERT INTO slot_leader ("hash", "pool_hash_id", "description") VALUES (?, ?, ?) ON CONFLICT ON CONSTRAINT unique_slot_leader DO UPDATE SET "hash" = EXCLUDED."hash" RETURNING id ;; [PersistByteString "\253\227\153b4\249\224\DC1\ESC)\131\153\229\184\SUB\177s\207\140\187u\247\ETB\129z\SUB\234\EOT",PersistNull,PersistText "Genesis slot leader"]
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.25 UTC] INSERT INTO "block"("hash","epoch_no","slot_no","epoch_slot_no","block_no","previous_id","slot_leader_id","size","time","tx_count","proto_major","proto_minor","vrf_key","op_cert","op_cert_counter") VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistByteString "\253\227\153b4\249\224\DC1\ESC)\131\153\229\184\SUB\177s\207\140\187u\247\ETB\129z\SUB\234\EOT\208_\193\154",PersistNull,PersistNull,PersistNull,PersistNull,PersistNull,PersistInt64 1,PersistInt64 0,PersistUTCTime 2022-02-02 18:56:29 UTC,PersistInt64 2,PersistInt64 0,PersistInt64 0,PersistNull,PersistNull,PersistNull]
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.25 UTC] INSERT INTO "tx"("hash","block_id","block_index","out_sum","fee","deposit","size","invalid_before","invalid_hereafter","valid_contract","script_size") VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistByteString "w\EM\152>\132\182\223\n]nb\170\236\253Nv\235AM\EM\178>\184oO`\202\163\184\209\fK",PersistInt64 1,PersistInt64 0,PersistText "503000000",PersistText "0",PersistInt64 0,PersistInt64 0,PersistNull,PersistNull,PersistBool True,PersistInt64 0]
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.25 UTC] INSERT INTO "tx_out"("tx_id","index","address","address_raw","address_has_script","payment_cred","stake_address_id","value","data_hash") VALUES(?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistInt64 1,PersistInt64 0,PersistText "2657WMsDfac7Bc8VwNgWqBV4525yLQCweHTguEizhvJoi9EZ3wsGsDy8Rq9E9vdC7",PersistByteString "\130\216\CANX%\131X\FS\199\168/37\129\210\154T7\237\248\154Z\US\175\164\163=\140~uC0g\244~?\161\STXB\CAN*\NUL\SUB\166W\US|",PersistBool False,PersistNull,PersistNull,PersistText "503000000",PersistNull]
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.25 UTC] INSERT INTO "tx"("hash","block_id","block_index","out_sum","fee","deposit","size","invalid_before","invalid_hereafter","valid_contract","script_size") VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistByteString "\168[\tE\179u\242\DC2\226\175\168\236\228\164:/Q5\CAN\152'h\134[\146y\n\248K>\140\171",PersistInt64 1,PersistInt64 0,PersistText "503000000",PersistText "0",PersistInt64 0,PersistInt64 0,PersistNull,PersistNull,PersistBool True,PersistInt64 0]
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.26 UTC] INSERT INTO "tx_out"("tx_id","index","address","address_raw","address_has_script","payment_cred","stake_address_id","value","data_hash") VALUES(?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistInt64 2,PersistInt64 0,PersistText "2657WMsDfac7FJoBc9R1jvHn94hsWogPzBwwabRWjNs9p1qgcnBi1wd8FqqbvV4HX",PersistByteString "\130\216\CANX%\131X\FS\205SW1\211\201\230\218\n\228wT\214\186\210\174\ACK\DC4\194\250\173\196\DLE\177)\235\199Y\161\STXB\CAN*\NUL\SUB\EOT\a\227\SUB",PersistBool False,PersistNull,PersistNull,PersistText "503000000",PersistNull]
[db-sync-node:Info:6] [2022-02-02 19:54:30.26 UTC] Initial genesis distribution populated. Hash fde3996234f9e0111b298399e5b81ab173cf8cbb75f717817a1aea04d05fc19a
[db-sync-node.db-sync:Debug:6] [2022-02-02 19:54:30.26 UTC] SELECT SUM("tx_out"."value")
FROM "tx_out"
WHERE NOT EXISTS (SELECT ?
FROM "tx_in"
WHERE ("tx_out"."tx_id" = "tx_in"."tx_out_id") AND ("tx_out"."index" = "tx_in"."tx_out_index")
)
; [PersistBool True]
[db-sync-node:Info:6] [2022-02-02 19:54:30.26 UTC] Total genesis supply of Ada: 1006.000000
Node configs that don't fork [db-sync-node:Error:6] [2022-02-02 19:54:30.26 UTC] Node configs that don't fork to Shelley directly and initiate funds or stakes in Shelley Genesis are not supported.
to Shelley directly and initiate funds or stakes in Shelley Genesis are not supported.
```

**Comment by erikd** [comment]
This is not a big. This is a misconfiguration on your part.

The last line:
```
Node configs that don't fork to Shelley directly and initiate funds or stakes in Shelley Genesis are not supported.
```
Your network starts in the `Byron` era but has a `Shelley` genesis file that contains a non-empty `initialFunds` map. That field should say:
```
  "initialFunds": {},
```

**Comment by woofpool** [comment]
Hi @erikd ,
Thanks for the reply.  I figured out how to cause the initialFunds property to be an empty object by changing the `--gen-utxo-keys` parameter to `0` instead of `1` (see below).   But, after doing this, when I try to run the update proposal #3, [update-3](https://github.com/input-output-hk/cardano-node/blob/master/scripts/byron-to-alonzo/update-3.sh), it gives me a failure submitting the transaction (see error below).  I assume this is due to the config change to disable generation of UTXO keys, which causes it not to find one to submit update-3 vote.

As a complete hack, I tried leaving the `gen-utxo-keys` set to `1` and then changing the `initialFunds` property to `{}` in the `shelley\genesis.json` after bootstrapping the network into Alonzo (major 6).  I also re-calculated the alonzoGenesisHash of the genesis.json file, and put that into my `configuration.yaml`.  But, then db-sync fails still. I don't have the logs handy, but it was some other kind of checksum type error.

So, would you have a suggestion for how to work around this issue?  As I understand it, the idea is to fork into shelley directly, but I don't understand how to do that with a script or in the context of the scripts used by IOG to move from Bryon to Alonzo.  (https://github.com/input-output-hk/cardano-node/tree/master/scripts/byron-to-alonzo)

Thanks

```
cardano-cli genesis create \
    --testnet-magic ${NETWORK_MAGIC} \
    --start-time $START_TIME_UTC \
    --genesis-dir shelley/ \
    --gen-genesis-keys ${NUM_BFT_NODES} \
    --gen-utxo-keys 0
```
Error trying to run update-3
```
request to run update-3 script
~/IdeaProjects/cardano-private-testnet-setup/private-testnet ~/IdeaProjects/cardano-private-testnet-setup
Command failed: transaction sign  Error: Error reading signing key: shelley/utxo-keys/utxo1.skey: shelley/utxo-keys/utxo1.skey: openBinaryFile: does not exist (No such file or directory)
```

**Comment by rdlrt** [comment]
> But, then db-sync fails still. I don't have the logs handy, but it was some other kind of checksum type error.

You might want to chase this and add more info here, it is likely hash mismatch for genesis or byron keys.

Also, note that if you're using for testing, you can skip the fork tx submission as per [here](https://github.com/input-output-hk/cardano-node/blob/master/scripts/byron-to-alonzo/mkfiles.sh#L16-L41)

**Comment by woofpool** [comment]
> You might want to chase this and add more info here, it is likely hash mismatch for hash of shelley/ byron genesis file, you would see the hash in the error message.
At the bottom, I pasted the error I'm seeing when trying to attach `cardano-db-sync`.  Would you have a suggestion for how to overcome this?  The configuration files in the `private-testnet` were created by running the mkfiles.sh from `cardano-node` project and booting directly to `alonzo`.  I also appended the genesis hash for each era into the configuration.yaml file, since `cardano-db-sync` needs to find it.
```
byronGenesisHash=$(cardano-cli byron genesis print-genesis-hash --genesis-json byron/genesis.json)
echo "ByronGenesisHash: $byronGenesisHash" >> configuration.yaml

shelleyGenesisHash=$(cardano-cli genesis hash --genesis shelley/genesis.json)
echo "ShelleyGenesisHash: $shelleyGenesisHash" >> configuration.yaml

alonzoGenesisHash=$(cardano-cli genesis hash --genesis shelley/genesis.alonzo.json)
echo "AlonzoGenesisHash: $alonzoGenesisHash" >> configuration.yaml
```
Error:
```
kurt@pop-os:~/src/cardano-private-testnet-setup$ ./scripts/db-sync-start.sh 
[db-sync-node:Info:6] [2022-02-06 11:44:17.09 UTC] Schema migration files validated
[db-sync-node:Info:6] [2022-02-06 11:44:17.09 UTC] Running database migrations
[db-sync-node:Info:6] [2022-02-06 11:44:17.09 UTC] Enviroment variable DbSyncAbortOnPanic: False
[db-sync-node:Info:6] [2022-02-06 11:44:17.92 UTC] Using byron genesis file from: "private-testnet/./byron/genesis.json"
[db-sync-node:Info:6] [2022-02-06 11:44:17.92 UTC] Using shelley genesis file from: "private-testnet/./shelley/genesis.json"
[db-sync-node:Info:6] [2022-02-06 11:44:17.92 UTC] Using alonzo genesis file from: "private-testnet/./shelley/genesis.alonzo.json"
[db-sync-node:Info:6] [2022-02-06 11:44:17.93 UTC] NetworkMagic: 42
[db-sync-node.db-sync:Debug:6] [2022-02-06 11:44:17.93 UTC] SELECT "block"."id"
FROM "block"
WHERE "block"."hash" = ?
; [PersistByteString "0\195\255\179\129\185\155\209\209\153\197\179\220@\212Z\250C\218\136G\178kc\f\242\223\231\186\DLE\248\245"]
[db-sync-node:Info:6] [2022-02-06 11:44:17.93 UTC] Inserting Byron Genesis distribution
[db-sync-node.db-sync:Debug:6] [2022-02-06 11:44:17.93 UTC] SELECT COUNT(*)
FROM "block"
; []
Error: insertValidateGenesisDist: Genesis data mismatch.
```

**Comment by rdlrt** [comment]
I cannot find your script (containing hash insertion) in mentioned repository, which makes it slightly difficult to troubleshoot - to check steps prior/after to insertion:
1. Restart node after update of config (the validation of hash would occur at node displaying if there is a genesis hash mismatch with corresponding genesis file and expected vs current hash).
2. Ensure dbsync DB is empty post every such attempt. you dont want pre-existing data from previous genesis when starting DB.
3. It will be more predictable for you to use JSON w/jq to update hash in-place than append a key-value pair to the end of config in YAML file (which could result in duplicates)

**Comment by erikd** [comment]
> Genesis data mismatch

That suggests that you started `db-sync` with different genesis data between the previous and the current run. Try dropping the database.

**Comment by woofpool** [comment]
Hi @rdlrt , @erikd , 
After dropping and re-creating the database, it's now getting past the mismatch error for Byron era hash.  I'm now running into a new error on startup of db-sync process.  When it tries to insert a block (Alonzo era), it says the block hash is missing.  (I included the error logs below).  This pattern keeps repeating itself as new blocks are attempted to be added.
> I cannot find your script (containing hash insertion) in mentioned repository, which makes it slightly difficult to troubleshoot - to check steps prior/after to insertion:
> 
Here is the location of the script I'm using: https://github.com/woofpool/cardano-private-testnet-setup/blob/kurt/fix-db-sync-startup/scripts/mkfiles.sh  .  Note: I have not switched to your suggestion of using JSON w/ `jq` in place, b/c I'm not sure how to do this.

Error logs
```
[db-sync-node.ChainSync:Debug:61] [2022-02-07 20:31:46.31 UTC] fromList [("kind",String "Recv"),("msg",Object (fromList [("agency",String "ServerAgency TokNext TokCanAwait"),("kind",String "MsgRollForward")]))]
[db-sync-node.Mux:Debug:52] [2022-02-07 20:31:46.31 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "private-testnet/node-bft1/node.sock"} event: Bearer Receive Start: length 8
[db-sync-node.ChainSync:Debug:61] [2022-02-07 20:31:46.31 UTC] fromList [("kind",String "Recv"),("msg",Object (fromList [("agency",String "ServerAgency TokNext TokCanAwait"),("kind",String "MsgRollForward")]))]
[db-sync-node.ChainSync:Debug:61] [2022-02-07 20:31:46.31 UTC] fromList [("kind",String "Recv"),("msg",Object (fromList [("agency",String "ServerAgency TokNext TokCanAwait"),("kind",String "MsgRollForward")]))]
[db-sync-node.ChainSync:Debug:61] [2022-02-07 20:31:46.31 UTC] fromList [("kind",String "Recv"),("msg",Object (fromList [("agency",String "ServerAgency TokNext TokCanAwait"),("kind",String "MsgRollForward")]))]
[db-sync-node.Mux:Debug:61] [2022-02-07 20:31:46.31 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "private-testnet/node-bft1/node.sock"} event: Channel Receive Start on MiniProtocolNum 5
[db-sync-node.Mux:Debug:61] [2022-02-07 20:31:46.31 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "private-testnet/node-bft1/node.sock"} event: Channel Receive End on (MiniProtocolNum 5) 1053
[db-sync-node.ChainSync:Debug:61] [2022-02-07 20:31:46.31 UTC] fromList [("kind",String "Recv"),("msg",Object (fromList [("agency",String "ServerAgency TokNext TokCanAwait"),("kind",String "MsgRollForward")]))]
[db-sync-node.Mux:Debug:61] [2022-02-07 20:31:46.31 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "private-testnet/node-bft1/node.sock"} event: Channel Receive Start on MiniProtocolNum 5

[db-sync-node:Error:59] [2022-02-07 20:31:46.31 UTC] Error: insertShelleyBlock(Alonzo)The block hash 43617264616e6f2e446253796e632e4572612e5368656c6c65792e47656e657269632e426c6f636b2e626c6f636b5072657648617368 is missing from the DB.
[db-sync-node:Info:59] [2022-02-07 20:31:46.31 UTC] Shutting down DB thread

[db-sync-node.Mux:Debug:54] [2022-02-07 20:31:46.31 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "private-testnet/node-bft1/node.sock"} event: Terminating (MiniProtocolNum 5) in InitiatorDir
[db-sync-node.Mux:Debug:50] [2022-02-07 20:31:46.31 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "private-testnet/node-bft1/node.sock"} event: Bearer DeltaQ Sample: duration 2.580e-2 packets 31 sumBytes 85644 DeltaQ_S 2.012e-7 DeltaQ_VMean 5.830e-4 DeltaQ_VVar 7.704e-7 DeltaQ_estR 8.303e-1 sizeDist [(2,1,-2.8856e-5),(7,1,0.0),(45,1,2.9561e-5),(109,1,-9.9804e-5),(1053,17,4.1838e-5),(2106,1,6.5986e-5),(4212,3,-5.145e-6),(5265,2,-6.9913e-5),(6318,1,1.095651e-3),(11414,1,2.629139e-3),(12288,2,2.248067e-3)]
[db-sync-node.Mux:Notice:50] [2022-02-07 20:31:46.31 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "private-testnet/node-bft1/node.sock"} event: Miniprotocol (MiniProtocolNum 5) InitiatorDir terminated cleanly
[db-sync-node.Mux:Debug:50] [2022-02-07 20:31:46.31 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "private-testnet/node-bft1/node.sock"} event: Mux shutdown
[db-sync-node.Subscription:Debug:49] [2022-02-07 20:31:46.31 UTC] Identity Closed socket to LocalAddress "private-testnet/node-bft1/node.sock"
[db-sync-node.Subscription:Notice:48] [2022-02-07 20:31:47.31 UTC] Identity Restarting Subscription after 1.027340778s desired valency 1 current valency 0
```

**Comment by erikd** [comment]
```
[db-sync-node:Error:59] [2022-02-07 20:31:46.31 UTC] Error: insertShelleyBlock(Alonzo)The block hash 
43617264616e6f2e446253796e632e4572612e5368656c6c65792e47656e657269632e426c6f636b2e626c6f636b5072657648617368 
is missing from the DB.
```
That is the crux of the matter. Something is terribly wrong and since this does not happen on mainnet or any of the test nets I regularly test on, its highly likley that this is something specific to your setup.

**Comment by woofpool** [comment]
> That is the crux of the matter. Something is terribly wrong and since this does not happen on mainnet or any of the test nets I regularly test on, its highly likley that this is something specific to your setup.
>
It probably has something to do with the fact I'm bootstrapping directly into `Alonzo` and not using the update endorsements to increment through the protocol versions.  Prior to when the `initialFunds` validation was added, I could successfully attach `cardano-db-sync`, but it only worked when I ran the full bootstrapping process (i.e. with all the protocol update endorsement). It's probably a very subtle difference in terms of some transaction data stored in the blocks.

**Comment by kderme** [comment]
The node config has a field `"TestShelleyHardForkAtEpoch"` which lets you fork to Shelley at a specified epoch. If it's 0 it will directly fork to Shelley without going through a Byron phase. When it's 0, you can specify `"initialFunds"` and `"staking"` in the shelley genesis file, to bootstrap the network. Otherwise these fields have to be empty `{ }`. There was another issue which was fixed in https://github.com/input-output-hk/cardano-db-sync/pull/972, but I think didn't make it to the release 12 that you're using. But I'm not sure if it affects you.

**Comment by woofpool** [comment]
Hi @kderme ,
> There was another issue which was fixed in #972, but I think didn't make it to the release 12 that you're using. But I'm not sure if it affects you.

I took a look at issue #972, and it appears to be the same issue as mine.  The issue shows the same block hash error I got as follows:
```
Error: insertShelleyBlock(Alonzo)The block hash 43617264616e6f2e446253796e632e4572612e5368656c6c65792e47656e657269632e426c6f636b2e626c6f636b5072657648617368 is missing from the DB.
```
It looks like that issue got closed by this PR: https://github.com/input-output-hk/cardano-db-sync/pull/972.  **Can I assume this PR has not made it into a tagged release?**  I tried `12.0.2` just now and get the same error about the hash missing from the DB.

**Comment by erikd** [comment]
Correct #972 was merged after the release of `12.0.0` and since this really only affects testnets, it was not made part of any of the `12.0.x` point release.

If you want this patch, I suggest you start at the `12.0.1` or `12.0.2` tag, and cherry pick commit bff6e182cf41f6f7a9ff3d08bb1fc9984e2d0f66 .

**Comment by woofpool** [comment]
> Correct, #972 was merged to `master` after the release of `12.0.0` and since this really only affects testnets, it was not made part of any of the `12.0.x` point release.
> 
> If you want this patch, I suggest you start at the `12.0.1` or `12.0.2` tag, and cherry pick commit [bff6e18](https://github.com/input-output-hk/cardano-db-sync/commit/bff6e182cf41f6f7a9ff3d08bb1fc9984e2d0f66) .

Thanks @erikd .  I also had to apply this change, [ Fix fork to Shelley at 0 #963 ](https://github.com/input-output-hk/cardano-db-sync/pull/963/files) .  But, now it's working!

Any ideas if these changes will be merged into a tagged release and the timing of that?  Sorry, I know these kinds of questions are hard to answer.
Thanks to everyone for helping on this one!

**Comment by erikd** [comment]
The release process specifies that for the next major release (`13.0.0`) will branch whatever is on the `master`. Both of those commits are on `master` so will be in the next major release. Not sure when that will be.

**Comment by erikd** [comment]
@woofpool Can this be closed?

**Comment by woofpool** [comment]
> @woofpool Can this be closed?

Yes, thanks for the heads up.
