### ISSUE TITLE
Avoid using TBQueue for StakeDistribution

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1060]
Currently stake distribution is extracted from the `set` snapshot at the start of epoch, inserted in a TBQueue and finally inserted in the db in chunks 1000 per block.

We could avoid using the TBQueue and insert stake distribution directly from the snapshot. To do this we want a way to index how many entries have already been registered, without keeping any volatile in memory data. I think we could directly query this number from the db. This would let us remove the DBQueues (since rewards will also become incrementally available through events) and would drastically simplify code and reduce memory usage.

Other things we need to consider are:
- At which slot should we start extracting from the `set` snapshot. At the beginning of the epoch or we can go later? How soon do we need there entries after the epoch boundary?
- How many entries per block should db-sync insert? This also depends on how fast we want these entries inserted.

**Comment by erikd** [comment]
> insert stake distribution directly from the snapshot

You mean the ledger state right?

> To do this we want a way to index how many entries have already been registered, without keeping any volatile in memory data

Yes, this solution requires that we store some state. I think we need proper support for this in ledger rather than trying to hack around the problem here in `db-sync`.

**Comment by kderme** [comment]
>> insert stake distribution directly from the snapshot

> You mean the ledger state right?

Yes the `set` stake distribution snapshot that lives in the ledger state

**Comment by kderme** [comment]
Fixed in https://github.com/input-output-hk/cardano-db-sync/pull/1094
