### ISSUE TITLE
Automatic build of database schema diagram

### ISSUE THREAD

**Issue by mgajda** [input-output-hk/cardano-db-sync#1071]
**Context**
The schema of CardanoDBSync is [quite large](https://hydra.iohk.io/job/Cardano/cardano-db-sync/native.haskellPackages.cardano-db.checks.test-db.x86_64-linux/latest/download/1). It would be much easier to look through if schema diagram was generated.

**Problem Report**
We can add running of [`autodoc`](https://github.com/cbbrowne/autodoc) to generate documentation and show it as an artifact on a website.

#migamake

**Comment by erikd** [comment]
We already have generated [schema documentation](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/schema.md).

If you submit a PR (or even instructions) for generating a diagram, that could be added (you can assume that `autodoc` is already installed).

**Comment by erikd** [comment]
I ran into a [problem](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006990) with the `autodoc` from the Debian archives.

Installing it manually I I was able to generated some files. The HTML and XML files do not look very interesting (and strictly not better than the current `schema.md` file). Which of these files is useful and what do I view it with?
