### ISSUE TITLE
[Suggestion] Include Hydra binaries in the release

### ISSUE THREAD

**Issue by longngn** [input-output-hk/cardano-db-sync#1072]
For example, here is the Hydra build for tag `12.0.2`: https://hydra.iohk.io/build/12591437
It runs well on Ubuntu 20.04, so I think we should include these Hydra builds in release page so users don't have to install Nix and build from scratch which is the biggest friction when setting up `cardano-db-sync`.

**Comment by erikd** [comment]
A link to the hydra binaries has been included in the release notes for the [latest release](https://github.com/input-output-hk/cardano-db-sync/releases/tag/12.0.2) and will be included in all future releases.
