### ISSUE TITLE
No multisig type in script table.

### ISSUE THREAD

**Issue by Scitz0** [input-output-hk/cardano-db-sync#1073]
**OS**
Your OS: Ubuntu 20.04

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 12.0.0
PostgreSQL version: 14.0

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: cabal

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): systemd

**Problem Report**
Looking at mainnet script table, all native scripts are tagged as type timelock, even those that doesn't contain any time locks in script.

**Comment by kderme** [comment]
Did you sync from genesis or restored some snapshot for this?
Also there should probably be 'plutus' script types appart from 'timelock'.

**Comment by Scitz0** [comment]
Restore from snapshot, but this was 1-2 month ago, since then normal sync. And yes, plutus type is also there, thats why I mentioned specifically that for all native scripts, there are no entry tagged as multisig, only timelock.

**Comment by sorki** [comment]
Not a bug - no multisig type scripts were used on mainnet. You can find couple on testnet. Multisig predates timelock scripts and timelocks have multisig functionality.

**Comment by kderme** [comment]
Yup, I synced mainnet and found no multisigs. Then synced testnet and found some
```
   1 |  36420 | \xdf22511a7957d47745f5019c2d9f8636cf465afc9e014228c39c708d | multisig | {"type": "atLeast", "scripts": [{"type": "sig", "keyHash": "654891a4db2ea44b5263f4079a33efa0358ba90769e3d8f86a4a0f8
1"}, {"type": "sig", "keyHash": "8685ad48f9bebb8fdb6447abbe140645e0bf743ff98da62e63e2147f"}, {"type": "sig", "keyHash": "cb0f3b3f91693374ff7ce1d473cf6e721c7bab52b0737f04164e5a2d"}], "required": 2}       
                                                                                  |       |                
   2 |  36423 | \xc2287941693f27466b90eee087b6a0c3a28ecb7151579b554b79e481 | multisig | {"type": "all", "scripts": [{"type": "sig", "keyHash": "cb0f3b3f91693374ff7ce1d473cf6e721c7bab52b0737f04164e5a2d"},
 {"type": "sig", "keyHash": "654891a4db2ea44b5263f4079a33efa0358ba90769e3d8f86a4a0f81"}]}                                                                                                                  
                                                                                  |       |                
   3 |  37227 | \xde1cf53eb63dde7c94c5689bcc6d7f4472da400d6e100fc67460cf84 | multisig | {"type": "atLeast", "scripts": [{"type": "sig", "keyHash": "cb0f3b3f91693374ff7ce1d473cf6e721c7bab52b0737f04164e5a2
d"}, {"type": "sig", "keyHash": "525085a057042a837a8c35c9d26693dd52882d7e6f78bbd708c23f42"}, {"type": "sig", "keyHash": "0fe6862d913501289254770751bae0cbabbe5065a0f09f6d75d587ed"}, {"type": "sig", "keyHa
sh": "654891a4db2ea44b5263f4079a33efa0358ba90769e3d8f86a4a0f81"}], "required": 3} |       |                
```

Note that multisigs existed only during Shelley era, that is before epoch 236 on mainnet. After that they were generalized by timelocks.

**Comment by Scitz0** [comment]
Ok thanks for clarification of difference.
