### ISSUE TITLE
getPoolOfflineMetadata set Cache-Control to "no-store", preventing efficient caching.

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-db-sync#1075]
cf. https://github.com/input-output-hk/cardano-db-sync/blob/3805d40c3eb448af422ddf4ac024cf95d33f95ad/cardano-smash-server/src/Cardano/SMASH/Server/Impl.hs#L93

**Comment by kderme** [comment]
This is done in https://github.com/input-output-hk/cardano-db-sync/pull/1092
