### ISSUE TITLE
v12.0.0 lags behind by 5 days.

### ISSUE THREAD

**Issue by grim-i-am** [input-output-hk/cardano-db-sync#1085]
I have 2 identical physical machines with 24 GB RAM, each running Debian v5.10 and cardano-node v1.34.1, both fully synced at 100%.

One machine is running db-sync v11.0.4, and on average lags behind by 3 - 15 minutes.

The other machine is running db-sync v12.0.0 and is lagging behind by almost 6 days.

**Comment by erikd** [comment]
How long has it been running 6 days behind? Are you running if solid state or electo-magnetic disks? How old is the hardware?

**Comment by grim-i-am** [comment]
it's at 7 days 21 hours now.

I'm running on 240GB ssds.

Processor specs:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
Stepping:                        11
CPU MHz:                         962.559
CPU max MHz:                     4600.0000
CPU min MHz:                     400.0000
BogoMIPS:                        3999.93
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB
                                  filling
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts a
                                 cpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch
                                 _perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq 
                                 dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2
                                 apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefe
                                 tch cpuid_fault invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept 
                                 vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap 
                                 clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_no
                                 tify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities

**Comment by erikd** [comment]
> it's at 7 days 21 hours now.
>
> I'm running on 240GB ssds.

There is no reason I can see for that machine to be running so slow.  I run an instance on 3 year old hardware and sync from genesis to chain tip in about 6 days.

Is your node syncing correctly and at chain tip? Anything in the logs? Either `node` or `db-sync` ?

**Comment by grim-i-am** [comment]
Turns out that the service didn't restart after a power out. I'm sorry for wasting your time.

**Comment by Titan-C** [comment]
> There is no reason I can see for that machine to be running so slow. I run an instance on 4 year old hardware and `db-sync` syncs from genesis to chain tip in a bit less than 6 days.

@erikd Can you share your specific hardware and setup? I'm running on a 8 core + 32G Ram + 40GB Swap + 800GB SSD with mainnet node and db-sync and I cannot sync beyond epoch 326. I am within the specified requirements on the Readme for the 12.0 release and even what is shown now in master.

It took me 13 days to get there. Since then there is always a failure, there connection to the node socket seems to shortly drop, thus subscription is lost then restarted, thus rollback triggered and a full day goes away just deleting blocks, before it restarts and hits the same problem.

Cardano node 1.34.0
DB-Sync 12.0.2

**Comment by erikd** [comment]
@Titan-C The machine is more than adequate for running `db-sync`. 

> I cannot sync beyond epoch 326.

What happens?

> It took me 13 days to get there.

That machine should sync the whole chain in under 10 days. You are not running this on an AWS instance by any chance?

**Comment by Titan-C** [comment]
> What happens?

The error log, from going fine, to error to restart :

[db-sync-node:Info:58] [2022-04-30 22:29:25.56 UTC] insertEpochInterleaved: Epoch 326, 1102152 rewards
[db-sync-node:Info:58] [2022-04-30 22:37:17.53 UTC] Offline pool metadata fetch: 74 results, 25 fetch errors
[db-sync-node.Mux:Info:50] [2022-04-30 23:30:51.11 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node-mainnet/socket"} event: State: Dead
[db-sync-node:Error:58] [2022-04-30 23:30:55.58 UTC] runDBThread: AsyncCancelled
[db-sync-node:Error:53] [2022-04-30 23:30:55.58 UTC] ChainSyncWithBlocksPtcl: AsyncCancelled
[db-sync-node.Subscription:Error:49] [2022-04-30 23:30:55.59 UTC] Identity Application Exception: LocalAddress "/run/cardano-node-mainnet/socket" MuxError MuxBearerClosed "<socket: 22> closed when reading data, waiting on next header True"
[db-sync-node.ErrorPolicy:Warning:6] [2022-04-30 23:30:55.59 UTC] IP LocalAddress "/run/cardano-node-mainnet/socket" ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (MuxError MuxBearerClosed "<socket: 22> closed when reading data, waiting on next header Tru>
[db-sync-node.Subscription:Notice:48] [2022-04-30 23:30:57.56 UTC] Identity Restarting Subscription after 183050.489260766s desired valency 1 current valency 0
[db-sync-node.Subscription:Notice:48] [2022-04-30 23:30:57.56 UTC] Identity Starting Subscription Worker, valency 1
[db-sync-node.Subscription:Notice:3835] [2022-04-30 23:30:57.56 UTC] Identity Connection Attempt Start, destination LocalAddress "/run/cardano-node-mainnet/socket"
[db-sync-node.Subscription:Notice:3835] [2022-04-30 23:30:57.56 UTC] Identity Connection Attempt End, destination LocalAddress "/run/cardano-node-mainnet/socket" outcome: ConnectSuccessLast
[db-sync-node.Handshake:Info:3835] [2022-04-30 23:30:57.56 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node-mainnet/socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV>
[db-sync-node.Subscription:Notice:48] [2022-04-30 23:30:57.59 UTC] Identity Required subscriptions started
[db-sync-node.Handshake:Info:3835] [2022-04-30 23:30:57.78 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node-mainnet/socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_10 (TInt 7648>
[db-sync-node.Mux:Info:3835] [2022-04-30 23:30:57.78 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node-mainnet/socket"} event: Handshake Client end, duration 0.217621065s
[db-sync-node.Mux:Info:3836] [2022-04-30 23:30:57.78 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node-mainnet/socket"} event: State: Mature
[db-sync-node:Info:3839] [2022-04-30 23:30:57.78 UTC] Starting chainSyncClient
[db-sync-node:Info:3839] [2022-04-30 23:30:57.91 UTC] Cardano.Db tip is at slot 56177748, block 7018468
[db-sync-node:Info:3844] [2022-04-30 23:30:57.91 UTC] Running DB thread
[db-sync-node:Info:3844] [2022-04-30 23:30:58.16 UTC] Rolling back to slot 55999628, hash 0a122e44ecd20e2f78c8afcfc720d6afce4c79954fb059e22ff5c723ccf85782
[db-sync-node:Info:3844] [2022-04-30 23:30:58.36 UTC] Deleting 8469 blocks up to slot 56177748

> That machine should sync the whole chain in under 10 days. You are not running this on an AWS instance by any chance?

That is way better than any of my experiences. I'm not on AWS, yet it is
a VPS from Contabo, the VPS-L. Are VPSs an issue?

I first had the NVMe offer but I ran out
of space 200GB where not enough for node & db-sync. It never
synchronized. From Feb-26 till April-2nd it was syncing, 36 days, it
didn't reach chain-tip and but I ran out of space. After some slow
customer service I changed my plan to the VPS-L on SSD and 800GB. In
between I also learned to tune Postgresql out of the default config. I
started the new VPS on April 15th, node and db-sync launched
simultaneously. The node reached the chain tip in a little more than a
day, db-sync was a lot slower. By April 27th db-sync started showing
these errors. There is no progress from there on. Stuck at epoch 326,
insert->Error->delete blocks->loop.

Last attempt was on PostgreSQL 13.6

shared_buffers = 1GB
work_mem = 128MB
maintenance_work_mem = 1GB
wal_level = minimal
max_wal_senders = 0

**Comment by erikd** [comment]
Everything seems to point to you VPS not being up to scratch. Check out the IOPS of that machine. As suggested in the [system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements), you will need 60k IOPS a second or better.
