### ISSUE TITLE
Newest snapshot contains interleaved epoch_stake ids

### ISSUE THREAD

**Issue by 1000101** [input-output-hk/cardano-db-sync#1088]
**Problem Report**
[Newest snapshot](https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-12-block-6965999-x86_64.tgz) contains interleaved epoch_stake ids - most likely due to restarts (rollbacks during restarts on epoch switch).

```
SELECT COUNT(*)
FROM (
    SELECT all_ids AS missing_ids
    FROM generate_series(
        (
          SELECT MIN(id)
          FROM epoch_stake
        ),
        (
          SELECT MAX(id)
          FROM epoch_stake
        )
      ) all_ids
    EXCEPT
    SELECT id
    FROM epoch_stake
    ORDER BY missing_ids
  ) AS interleaved_ids;


  count   
----------
 28129049
(1 row)
```

Now I know there's no guarantee these will be consecutive and we should work around that fact, but it would be great to have a "clean" snapshot. Anyway, having consecutive ids in this case would help in some easy out of box optimizations, mainly it allows for parallel pagination using ids instead of limit / offset.

**Comment by kderme** [comment]
Yes, there can be holes in the autoincremental id, in case of chain rollbacks (even without restarts). So there's not much we can do to avoid them. Actually we consider removing many of these primary keys https://github.com/input-output-hk/cardano-db-sync/issues/1087

**Comment by 1000101** [comment]
> Yes, there can be holes in the autoincremental id, in case of chain rollbacks (even without restarts). So there's not much we can do to avoid them. Actually we consider removing many of these primary keys #1087

I've seen that one, however, I think ids are handy at least while retrieving data with pagination. You **have to** order the data before using limit and I can't think of any other property by which to order these data, than id. However, if the insert mechanism is not deterministic (values are not inserted in the same order each time), this could present another problem (data inconsistency depending on the dbsync instance).

**Comment by kderme** [comment]
You can probably order on (epoch_no, addr_id, pool_id) or even (epoch_no, addr_id) but I'm hesitant to say the ordering will be deterministic across different instances and probably you shouldn't depend on it. If you really want deterministic results you need to find other solutions, like joining tables and ordering on hashes.

**Comment by 1000101** [comment]
> You can probably order on (epoch_no, addr_id, pool_id) or even (epoch_no, addr_id) but I'm hesitant to say the ordering will be deterministic across different instances and probably you shouldn't depend on it. If you really want deterministic results you need to find other solutions, like joining tables and ordering on hashes.

Thanks for the info!

**Comment by erikd** [comment]
> You have to order the data before using limit and I can't think of any other property by which to order these data,

The primary key is guaranteed unique, and they are auto generated in such a way as the guaranteeing that rows inserted later have a higher `id` than earlier entries. As @kderme suggested, there may be gaps in the `id`s due to insertion followed by deletion due to rollbacks.

Furthermore, two `db-sync` instances may not have the same `id` fields for the same entity. This can happen is the node connected to once instance may see a rollback that the node connected to another instance may not.

**Comment by erikd** [comment]
@1000101 Can this be closed?
