### ISSUE TITLE
entrypoint script in Docker fails to restore mainnet snapshot

### ISSUE THREAD

**Issue by BisonDee** [input-output-hk/cardano-db-sync#1098]
**OS**
macOS

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 12.0.2
PostgreSQL version: 12.0

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Docker from IOHK

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Problem Report**

When using the default entrypoint script in the bundled Docker image, it checks for "https" when given a URL for the `RESTORE_SNAPSHOT` variable. However, for mainnet, the bucket in S3 contains a "`.`" which is known to have TLS cert issues. 

For instance 
```
RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io.s3-ap-southeast-1.amazonaws.com/cardano-db-sync/12/db-sync-snapshot-schema-12-block-7107980-x86_64.tgz
```
results in curl errors refusing to download bad cert

Using TLS-less URL is no better. It results in a tar error because the logic falls through assuming that because the URL does not contain "https", its a tarball. 

A few potential solutions:
* Let curl download from http or https (-k) and regex for either in the conditional
* Rename the mainnet snapshot bucket to not have "`.`" in the name `update-cardano-mainnet.iohk.io => update-cardano-mainnet-iohk-io`

The issue is in this section of script (not sure where this is in the repo)
```bash
  if [[ "$RESTORE_SNAPSHOT" =~ ^https://.* ]]; then
    echo "Downloading snapshot $RESTORE_SNAPSHOT ..."
    /nix/store/2ybz4gc2gyrwpnaz3cmclgibhgvqwir5-curl-7.76.1-bin/bin/curl -LOC - "$RESTORE_SNAPSHOT"

    /nix/store/2ybz4gc2gyrwpnaz3cmclgibhgvqwir5-curl-7.76.1-bin/bin/curl -LO "$RESTORE_SNAPSHOT.sha256sum"
    /nix/store/0vkw1m51q34dr64z5i87dy99an4hfmyg-coreutils-8.32/bin/sha256sum -c "$SNAPSHOT_BASENAME.sha256sum"

    SNAPSHOT="$SNAPSHOT_BASENAME"
  else
    SNAPSHOT="$RESTORE_SNAPSHOT"
  fi
  rm -f /var/lib/cdbsync/*.lstate
  /nix/store/1vxssaidg7iy756mg8324svfppq415r9-postgresql-setup.sh --restore-snapshot "$SNAPSHOT" /var/lib/cdbsync
  touch $RESTORED_MARKER
  rm -f $SNAPSHOT{,.sha256sum,.asc}
```

**Comment by tmcgilchrist** [comment]
@BisonDee that url for `RESTORE_SNAPSHOT` looks different to what I expect. 
You should use (minus the amazon domain name):
```shell
RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-12-block-7107980-x86_64.tgz
```

The S3 bucket is setup to serve as the domain `update-cardano-mainnet.iohk.io`
```
$ curl --head -v https://update-cardano-mainnet.iohk.io                             
*   Trying 172.66.40.236:443...
* Connected to update-cardano-mainnet.iohk.io (172.66.40.236) port 443 (#0)
... snip ...
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=iohk.io
*  start date: Jun 10 00:00:00 2021 GMT
*  expire date: Jun  9 23:59:59 2022 GMT
*  subjectAltName: host "update-cardano-mainnet.iohk.io" matched cert's "*.iohk.io"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
```

Running the same using the S3 domain name + bucket name gives an expected certificate mis-match:
```
 curl --head -v https://update-cardano-mainnet.iohk.io.s3-ap-southeast-1.amazonaws.com
*   Trying 52.219.132.123:443...
* Connected to update-cardano-mainnet.iohk.io.s3-ap-southeast-1.amazonaws.com (52.219.132.123) port 443 (#0)
... snip ...
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.s3-ap-southeast-1.amazonaws.com
*  start date: Dec  9 00:00:00 2021 GMT
*  expire date: Dec  8 23:59:59 2022 GMT
*  subjectAltName does not match update-cardano-mainnet.iohk.io.s3-ap-southeast-1.amazonaws.com
* SSL: no alternative certificate subject name matches target host name 'update-cardano-mainnet.iohk.io.s3-ap-southeast-1.amazonaws.com'
```

Could you share where in the docs you found the url `update-cardano-mainnet.iohk.io.s3-ap-southeast-1.amazonaws.com` ? That documentation needs to be updated. If you haven't already seen there are docs [for running with docker](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/docker.md ).

**Comment by tmcgilchrist** [comment]
Fixed, the url used to download the snapshot was incorrect.
