### ISSUE TITLE
missing max block size proposal

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#1103]
latest dbsync

![obrazek](https://user-images.githubusercontent.com/58650764/165235782-f57a7bd4-96dd-4e77-b839-122346c000e3.png)

**Comment by erikd** [comment]
More information needed.

**Comment by cardanians** [comment]
Before the weekend, an update proposal was made to increase [#Cardano](https://twitter.com/hashtag/Cardano?src=hashtag_click) mainnet block size by 8K. This change will take effect later today at the boundary of epoch 335, Monday 25th April @ UTC 20:20:00.

https://twitter.com/InputOutputHK/status/1518596128056520707

SELECT * FROM param_proposal WHERE max_block_size IS NOT NULL

0 results

**Comment by kderme** [comment]
Maybe related to this https://github.com/input-output-hk/cardano-db-sync/pull/967

**Comment by erikd** [comment]
Ok, this is something I can look into.

**Comment by kderme** [comment]
I believe this is fixed in https://github.com/input-output-hk/cardano-db-sync/pull/967 and released with https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.0.0
