### ISSUE TITLE
Cardano node full sync but postgres got stuck

### ISSUE THREAD

**Issue by bruno-nirello** [input-output-hk/cardano-db-sync#1111]
**OS**
Docker Compose version v2.4.1

Docker version 20.10.14, build a224086

Description:	Ubuntu 20.04.4 LTS
ryzen 3600
32GB ram

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):
PostgreSQL version:  same 12.0.2 branch
cardano-node 1.33.0

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):

```
git clone cardano-db-sync
cd cardano-db-sync
git checkout 12.0.2
# change docker-compose.yml to node 1.33.0 from 1.31.0
docker compose up -d

```

**Problem Report**
After full sync with 60 million slots on cardano node (epoch 336), I connected to postgres to make some queries, and the MAX epoch was 267.
this query here:
```
select
   100 * (extract (epoch from (max (time) at time zone 'UTC')) - extract (epoch from (min (time) at time zone 'UTC')))
      / (extract (epoch from (now () at time zone 'UTC')) - extract (epoch from (min (time) at time zone 'UTC')))
  as sync_percent
  from block ;
``` 
the sync was 79.81%

i though that in some point they stop inserting data to postgres.

after that i did
docker system prune -all --volumes

and after sync the node to 55 million slots, the postgres stoped at the same sync percent.
I have all the screenshots but the msg says no images.

**Comment by erikd** [comment]
Is the `node` still running?

**Comment by bruno-nirello** [comment]
No, i turned off.
your suggestion is to keep it on?

**Comment by erikd** [comment]
Where do you think `db-sync` is getting blocks from if the node is not running?

**Comment by bruno-nirello** [comment]
i misunderstanding, everything as the `node`

all 3 containers are running fine

this is my last logs

```
[d154bfe5:cardano.node.ChainDB:Notice:1900] [2022-05-05 22:56:10.31 UTC] Chain extended, new tip: e835db23ae34ddd92c2eb2c7c48b73fbfa62b861412e88f65999306470dce5df at slot 60225077
[d154bfe5:cardano.node.ChainDB:Notice:1900] [2022-05-05 22:56:41.22 UTC] Chain extended, new tip: 33054fe3eb791298f7ce9a8eb4efbabf5cadb9ba410ac2b6c95e04f61bd53b67 at slot 60225108
[d154bfe5:cardano.node.ChainDB:Notice:1900] [2022-05-05 22:57:10.23 UTC] Chain extended, new tip: 068f028f4969a12be9a8e8439b361b779c5f9a22be6c55282ba5e60840a826a6 at slot 60225137
[d154bfe5:cardano.node.ChainDB:Notice:1900] [2022-05-05 22:57:23.12 UTC] Chain extended, new tip: 49c87fc3fec791638a85de0d806bbde30939aa2bed975e51681f1b0429d4d454 at slot 60225151
[d154bfe5:cardano.node.ChainDB:Notice:1900] [2022-05-05 22:57:51.68 UTC] Chain extended, new tip: 789036d2605de76912ddb7db155fa0f878b1a9f7401da3b4ea69270b58112d8c at slot 60225178
```

sync percent from query 82.01696969139286

**Comment by erikd** [comment]
In the original comment:

> the sync was 79.81%

Now:

> sync percent from query 82.01696969139286

From what I can tell, that is syncing.

**Comment by bruno-nirello** [comment]
those 3% come from letting running for 12 hours today, is this normal? the `node` was on last slot 60225178

**Comment by erikd** [comment]
The percentage given by the above query is calculated from the time stamps. However, the first two years plus of the chain history was almost empty and the recent chain in almost fully populated. Thus the early part of the chain can be incredibly quick to sync (something like 2 hours for 200 epochs) whereas later epochs take 3 to 4 hours.

 Login in the database and run the query ` select * from epoch_sync_time ;`. You will see that early epochs (ie less than epoch 200) sync in an average of under 60 seconds. Also note that later epochs require 10000-16000 seconds. If any of these epoch sync times is much more than a 20000 seconds, then something is wrong with your setup.

**Comment by bruno-nirello** [comment]
it really clear my mind now, thank you for that.
i will close the issue and wait for the full sync, i'm now in 89%
