### ISSUE TITLE
Document schema better

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1118]
Schema docs are quite important to downstream componets. We should fix existing documentation, extend it, add warnings or even add links where content values are further explained. We could also add the version where each new field/table has been added and its previous name if it's renamed.

A small list of ideas
- `epoch_reward_total_received` needs fixing, since its content have changed.
- `epoch_stake` should mention that it affect the elections for the specified epoch and that it may be inserted delayed.

**Comment by erikd** [comment]
i think that table needs to be dropped.

**Comment by kderme** [comment]
I believe this has been sufficiently improved.
