### ISSUE TITLE
Memory usage regression in `pulsing-rewards` tag

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-db-sync#1119]
**OS**
Linux

**Versions**
```
cardano-db-sync 12.0.1 - linux-x86_64 - ghc-8.10
git revision 30c0afb11bf7e4114487339a9341208ac5388205
```

**Run method**
- full Mainnet sync from a clean state

**Additional context**

**Problem Report**
RAM usage regression for the same epochs in the new tag:
- `mainnet_1` = last released version (`12.0.2`)
- `mainnet_1` = `pulsing-rewards` tag

![image](https://user-images.githubusercontent.com/29144964/168556799-22f1ee15-31f4-42f5-b77c-c76f9665b736.png)

**Comment by erikd** [comment]
While `db-sync` needs to maintain its own copy of ledger state, there is no solution to this.

**Comment by kderme** [comment]
Closing this as newer tags have fixed the issue
