### ISSUE TITLE
Db-sync fails to start due to changes in PlutusV1 cost model

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-db-sync#1121]
**OS**
Linux

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): `6af53927161a3914598491de6c650da96f3c8c09`
PostgreSQL version: 13.6

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: nix-build

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): none

**Problem Report**
Db-sync fails to start when running with cardano-node master (any commit after `41afffd647fd92b731ebe96aaadf1dadfaaceba8`), because some key names in Alonzo genesis PlutusV1 cost model changed:

```
$ diff genesis.alonzo.json genesis.alonzo.new.json
19,21c19,21
<       "blake2b-cpu-arguments-intercept": 2477736,
<       "blake2b-cpu-arguments-slope": 29175,
<       "blake2b-memory-arguments": 4,
---
>       "blake2b_256-cpu-arguments-intercept": 2477736,
>       "blake2b_256-cpu-arguments-slope": 29175,
>       "blake2b_256-memory-arguments": 4,
168,170c168,170
<       "verifySignature-cpu-arguments-intercept": 3345831,
<       "verifySignature-cpu-arguments-slope": 1,
<       "verifySignature-memory-arguments": 1
---
>       "verifyEd25519Signature-cpu-arguments-intercept": 3345831,
>       "verifyEd25519Signature-cpu-arguments-slope": 1,
>       "verifyEd25519Signature-memory-arguments": 1
```

The failure:

> Failed reading Alonzo genesis file "./state-cluster0/shelley/genesis.alonzo.json": There was an error parsing the genesis file: ./state-cluster0/shelley/genesis.alonzo.json Error: Error in $.costModels: Invalid PlutusV1 cost model: fromList [("addInteger-cpu-arguments-intercept",197209),("addInteger-cpu-arguments-slope",0),("addInteger-memory-arguments-intercept",1),("addInteger-memory-arguments-slope",1),("appendByteString-cpu-arguments-intercept",396231),("appendByteString-cpu-arguments-slope",621),("appendByteString-memory-arguments-intercept",0),("appendByteString-memory-arguments-slope",1),("appendString-cpu-arguments-intercept",150000),("appendString-cpu-arguments-slope",1000),("appendString-memory-arguments-intercept",0),("appendString-memory-arguments-slope",1),("bData-cpu-arguments",150000),("bData-memory-arguments",32),("blake2b_256-cpu-arguments-intercept",2477736),("blake2b_256-cpu-arguments-slope",29175),("blake2b_256-memory-arguments",4),("cekApplyCost-exBudgetCPU",29773),("cekApplyCost-exBudgetMemory",100),("cekBuiltinCost-exBudgetCPU",29773),("cekBuiltinCost-exBudgetMemory",100),("cekConstCost-exBudgetCPU",29773),("cekConstCost-exBudgetMemory",100),("cekDelayCost-exBudgetCPU",29773),("cekDelayCost-exBudgetMemory",100),("cekForceCost-exBudgetCPU",29773),("cekForceCost-exBudgetMemory",100),("cekLamCost-exBudgetCPU",29773),("cekLamCost-exBudgetMemory",100),("cekStartupCost-exBudgetCPU",100),("cekStartupCost-exBudgetMemory",100),("cekVarCost-exBudgetCPU",29773),("cekVarCost-exBudgetMemory",100),("chooseData-cpu-arguments",150000),("chooseData-memory-arguments",32),("chooseList-cpu-arguments",150000),("chooseList-memory-arguments",32),("chooseUnit-cpu-arguments",150000),("chooseUnit-memory-arguments",32),("consByteString-cpu-arguments-intercept",150000),("consByteString-cpu-arguments-slope",1000),("consByteString-memory-arguments-intercept",0),("consByteString-memory-arguments-slope",1),("constrData-cpu-arguments",150000),("constrData-memory-arguments",32),("decodeUtf8-cpu-arguments-intercept",150000),("decodeUtf8-cpu-arguments-slope",1000),("decodeUtf8-memory-arguments-intercept",0),("decodeUtf8-memory-arguments-slope",8),("divideInteger-cpu-arguments-constant",148000),("divideInteger-cpu-arguments-model-arguments-intercept",425507),("divideInteger-cpu-arguments-model-arguments-slope",118),("divideInteger-memory-arguments-intercept",0),("divideInteger-memory-arguments-minimum",1),("divideInteger-memory-arguments-slope",1),("encodeUtf8-cpu-arguments-intercept",150000),("encodeUtf8-cpu-arguments-slope",1000),("encodeUtf8-memory-arguments-intercept",0),("encodeUtf8-memory-arguments-slope",8),("equalsByteString-cpu-arguments-constant",150000),("equalsByteString-cpu-arguments-intercept",112536),("equalsByteString-cpu-arguments-slope",247),("equalsByteString-memory-arguments",1),("equalsData-cpu-arguments-intercept",150000),("equalsData-cpu-arguments-slope",10000),("equalsData-memory-arguments",1),("equalsInteger-cpu-arguments-intercept",136542),("equalsInteger-cpu-arguments-slope",1326),("equalsInteger-memory-arguments",1),("equalsString-cpu-arguments-constant",1000),("equalsString-cpu-arguments-intercept",150000),("equalsString-cpu-arguments-slope",1000),("equalsString-memory-arguments",1),("fstPair-cpu-arguments",150000),("fstPair-memory-arguments",32),("headList-cpu-arguments",150000),("headList-memory-arguments",32),("iData-cpu-arguments",150000),("iData-memory-arguments",32),("ifThenElse-cpu-arguments",1),("ifThenElse-memory-arguments",1),("indexByteString-cpu-arguments",150000),("indexByteString-memory-arguments",1),("lengthOfByteString-cpu-arguments",150000),("lengthOfByteString-memory-arguments",4),("lessThanByteString-cpu-arguments-intercept",103599),("lessThanByteString-cpu-arguments-slope",248),("lessThanByteString-memory-arguments",1),("lessThanEqualsByteString-cpu-arguments-intercept",103599),("lessThanEqualsByteString-cpu-arguments-slope",248),("lessThanEqualsByteString-memory-arguments",1),("lessThanEqualsInteger-cpu-arguments-intercept",145276),("lessThanEqualsInteger-cpu-arguments-slope",1366),("lessThanEqualsInteger-memory-arguments",1),("lessThanInteger-cpu-arguments-intercept",179690),("lessThanInteger-cpu-arguments-slope",497),("lessThanInteger-memory-arguments",1),("listData-cpu-arguments",150000),("listData-memory-arguments",32),("mapData-cpu-arguments",150000),("mapData-memory-arguments",32),("mkCons-cpu-arguments",150000),("mkCons-memory-arguments",32),("mkNilData-cpu-arguments",150000),("mkNilData-memory-arguments",32),("mkNilPairData-cpu-arguments",150000),("mkNilPairData-memory-arguments",32),("mkPairData-cpu-arguments",150000),("mkPairData-memory-arguments",32),("modInteger-cpu-arguments-constant",148000),("modInteger-cpu-arguments-model-arguments-intercept",425507),("modInteger-cpu-arguments-model-arguments-slope",118),("modInteger-memory-arguments-intercept",0),("modInteger-memory-arguments-minimum",1),("modInteger-memory-arguments-slope",1),("multiplyInteger-cpu-arguments-intercept",61516),("multiplyInteger-cpu-arguments-slope",11218),("multiplyInteger-memory-arguments-intercept",0),("multiplyInteger-memory-arguments-slope",1),("nullList-cpu-arguments",150000),("nullList-memory-arguments",32),("quotientInteger-cpu-arguments-constant",148000),("quotientInteger-cpu-arguments-model-arguments-intercept",425507),("quotientInteger-cpu-arguments-model-arguments-slope",118),("quotientInteger-memory-arguments-intercept",0),("quotientInteger-memory-arguments-minimum",1),("quotientInteger-memory-arguments-slope",1),("remainderInteger-cpu-arguments-constant",148000),("remainderInteger-cpu-arguments-model-arguments-intercept",425507),("remainderInteger-cpu-arguments-model-arguments-slope",118),("remainderInteger-memory-arguments-intercept",0),("remainderInteger-memory-arguments-minimum",1),("remainderInteger-memory-arguments-slope",1),("sha2_256-cpu-arguments-intercept",2477736),("sha2_256-cpu-arguments-slope",29175),("sha2_256-memory-arguments",4),("sha3_256-cpu-arguments-intercept",0),("sha3_256-cpu-arguments-slope",82363),("sha3_256-memory-arguments",4),("sliceByteString-cpu-arguments-intercept",150000),("sliceByteString-cpu-arguments-slope",5000),("sliceByteString-memory-arguments-intercept",0),("sliceByteString-memory-arguments-slope",1),("sndPair-cpu-arguments",150000),("sndPair-memory-arguments",32),("subtractInteger-cpu-arguments-intercept",197209),("subtractInteger-cpu-arguments-slope",0),("subtractInteger-memory-arguments-intercept",1),("subtractInteger-memory-arguments-slope",1),("tailList-cpu-arguments",150000),("tailList-memory-arguments",32),("trace-cpu-arguments",150000),("trace-memory-arguments",32),("unBData-cpu-arguments",150000),("unBData-memory-arguments",32),("unConstrData-cpu-arguments",150000),("unConstrData-memory-arguments",32),("unIData-cpu-arguments",150000),("unIData-memory-arguments",32),("unListData-cpu-arguments",150000),("unListData-memory-arguments",32),("unMapData-cpu-arguments",150000),("unMapData-memory-arguments",32),("verifyEd25519Signature-cpu-arguments-intercept",3345831),("verifyEd25519Signature-cpu-arguments-slope",1),("verifyEd25519Signature-memory-arguments",1)]

**Comment by JaredCorduan** [comment]
@kderme - it might be that you need to use this:

https://github.com/input-output-hk/cardano-ledger/blob/ac1c074393074c00c854aa8827aca5bde0f07a23/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Genesis.hs#L224-L230

**Comment by kderme** [comment]
db-sync master is not supposed to be always compatible with node master. Integration of the hf is in progress https://github.com/input-output-hk/cardano-db-sync/pull/1112. In this pr we fetch the new json instance for cost models, which includes the fix that Jared sent above.
