### ISSUE TITLE
cardano-db-sync crashes & enters restart death-loop while starting at a certain epoch

### ISSUE THREAD

**Issue by thatsbrandon** [input-output-hk/cardano-db-sync#1146]
**OS**
Your OS: Windows (WSL Ubuntu)

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 12.0.2
PostgreSQL version: postgres:11.5-alpine (Docker Image)

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: inputoutput/cardano-node:1.34.1 docker image running inside a Kubernetes Pod

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
Db-Sync container restarts many times during it's lifecycle, the `cardano-node` & `cardano-db-sync` are on the same server while `cardano-db-sync` connects to a remote `Postgresql` pod.

**Problem Report**
My `cardano-db-sync` docker container running in a Kubernetes Stateful deployment hangs while trying to `insertShellyBlockl(Alonzo)` after acouple seconds the container crashes and restarts only to crash again. My Postgres container logs the following line once `db-sync` crashes --> `unexpected EOF on client connection with an open transaction`

**LOGS [ Before Crash ]**
```
[db-sync-node:Info:57] [2022-06-08 02:13:50.90 UTC] Starting at epoch 178
[db-sync-node:Info:57] [2022-06-08 02:13:51.04 UTC] Handling 83242 stakes for epoch 178 slot 46632114, hash bd30a5f7391cc770c7c56531aaae66f1c628f28b5f9a08553669b1e105a813db
[db-sync-node:Info:57] [2022-06-08 02:14:05.88 UTC] insertShelleyBlock(Alonzo): epoch 178, slot 46632114, block 3200000, hash bd30a5f7391cc770c7c56531aaae66f1c628f28b5f9a08553669b1e105a813db
[db-sync-node:Info:57] [2022-06-08 02:14:12.18 UTC] insertEpochInterleaved: Epoch 178, 83242 stake addresses
/nix/store/4afrd31xx9iljzn2hd8i6b03h7v5gh1g-cardano-db-sync-testnet/bin/cardano-db-sync-testnet: line 3:    17 Killed                  /nix/store/51xj9nf405brglw1p42jwnx27n3z8sak-cardano-db-sync $@
```

**Comment by rdlrt** [comment]
Might be good to add docker tag to these, unfortunately lot of issues that are often related to resource/sizing/connectivity get mixed up here.

**Comment by kderme** [comment]
The `Killed` message usually indicates a problem with recourses. Maybe the out of memory killer killed db-sync? This should be apparent in kernel logs.

**Comment by thatsbrandon** [comment]
@kderme Could restricting container resources cause a crash like this?

**Comment by thatsbrandon** [comment]
It ended up being that docker wasn't giving enough resources to the container so at a certain point the cardano-db-sync would just crash. I got a new Linux Workstation and it's working really well with 64GB of ram on the host machine
