### ISSUE TITLE
Error: insertShelleyBlock(Alonzo)The block hash 43617264616e6f2e... is missing from the DB 

### ISSUE THREAD

**Issue by 0xtrossets** [input-output-hk/cardano-db-sync#1147]
**OS**
Your OS: Mac

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 12.0.0
PostgreSQL version:

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Cardano-rosetta

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): cardano-rosetta

**Additional context**
Same issue as https://github.com/input-output-hk/cardano-db-sync/issues/953
Fix has been reverted in 12.0.x releases.

**Problem Report**
Same as https://github.com/input-output-hk/cardano-db-sync/issues/953

Note that fix by @kderme has been reverted for some reason in 12.0.x
Just need to reapply that fix and release a new patch.

**Comment by erikd** [comment]
It is incredibly unlikely for there to be new `12,0.x` release. We are very close to a `13.0.0` release (required for the Vasil hard fork) which already has this fix.

**Comment by kderme** [comment]
Yes this is fixed in 13.x tags, soon to be released.
