### ISSUE TITLE
17 Addresses exceed b-tree index max char limit of 2704

### ISSUE THREAD

**Issue by alekswithakayy** [input-output-hk/cardano-db-sync#1157]
I am trying to use the address column in the `tx_out` table as a primary key in a new table. Unfortunately I was met with the following error:

`index row size 7464 exceeds btree version 4 maximum 2704 for index "address_utxos_checkpoint_pkey"`

Upon investigation using the following query, I discovered 17 addresses with abnormally long lengths:

```sql
select length(address) as address_length, * 
from tx_out 
where length(address) > 2704
```
![Screenshot from 2022-06-16 12-44-00](https://user-images.githubusercontent.com/31933454/174123343-04821a0f-ae81-4ac5-9c0d-85feedcf9c8d.png)

Just wondering how this is possible and whether it is a bug of some sort. I can get around it by ignoring those addresses but thought it was worth pointing out in case it is unexpected behaviour.

**Comment by erikd** [comment]
These addresses are all (unfortunately) correct and valid. In the Byron era there was a missing length validation that allowed extra data to be added to an address (often an image file). This has long since been fixed (only addresses shorter than a certain length are allowed).

If you modify your query as follows:
```!sql
select length (tx_out.address) as address_length, tx.id as tx_id, block.epoch_no, tx_out.value
    from tx_out inner join tx on tx_out.tx_id = tx.id inner join block on block.id = tx.block_id
    where length(tx_out.address) > 2704 ;
 address_length | tx_id  | epoch_no | value 
----------------+--------+----------+-------
          24127 | 849991 |       82 |     1
           5285 | 845137 |       82 | 77083
           5344 | 845147 |       82 | 77083
          26956 | 849983 |       82 |     1
           6762 | 846097 |       82 |     1
          27983 | 849968 |       82 |     1
           7446 | 889273 |       89 |     1
          30864 | 849976 |       82 |     1
           4428 | 857116 |       84 |     1
          28167 | 849120 |       82 |     1
           6510 | 889370 |       89 |     1
          10501 | 843514 |       81 | 77083
          29438 | 849970 |       82 |     1
          16454 | 849959 |       82 |     1
          24243 | 849966 |       82 |     1
           5292 | 845172 |       82 | 77083
           8996 | 857178 |       84 |     1
(17 rows)
```
you will see that all these transactions (with really long addresses) all occurred before epoch 90 (Byron ended on epoch 207) and all of these transactions transfer less than a full ADA (`value` is in Lovelace and 1 ADA == 1000000 Lovelace).

**Comment by alekswithakayy** [comment]
@erikd @kderme How does dbsync manage to create an index on the `tx_out.address` column even though there are addresses that exceed the index byte limit?

**Comment by erikd** [comment]
Sorry, no idea. Postgres devs should know the answer.

**Comment by alekswithakayy** [comment]
@erikd Who would be a good person to reach out to?

**Comment by kderme** [comment]
It is a `hash` index which doesn't have the limit of `btree` indexes
```
CREATE INDEX IF NOT EXISTS idx_tx_out_address ON tx_out USING hash (address);
```

**Comment by alekswithakayy** [comment]
Ah I tried that but now I realize I also had a unique index on the address column which can only be a b-tree. Thanks @kderme
