### ISSUE TITLE
Vasil hardfork compatibility

### ISSUE THREAD

**Issue by xdzurman** [input-output-hk/cardano-db-sync#1168]
Hello, will db sync 13.0.0 official release be out anytime soon? Or will 12.0.2 be able to handle a connection to 1.35.0 node? The hardfork is scheduled for this sunday.

Thanks

**Comment by kderme** [comment]
No 12.0.2 cannot handle the hardfork. Tags 13.x.x can handle it and will be released soon.

**Comment by kderme** [comment]
Released now https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.0.0, sorry for the noise
