### ISSUE TITLE
Getting very very slow sync speeds

### ISSUE THREAD

**Issue by Fluid-team** [input-output-hk/cardano-db-sync#1173]
**OS**
Your OS: Ubuntu 20.04.3 LTS  

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): cardano-db-sync-extended
PostgreSQL version: 14

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: built from src (cabal)

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): none

**Additional context**
node running slower by the second has now been online for 7 days and still not fully synced

**Problem Report**

Todays Log:-

Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-121-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sun  3 Jul 11:56:53 BST 2022

  System load:  0.49                Temperature:               8.3 C
  Usage of /:   25.6% of 670.79GB   Processes:                 368
  Memory usage: 1%                  Users logged in:           0
  Swap usage:   0%                  IPv4 address for enp3s0f0: 192.*.*.*

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

67 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

Last login: Tue Jun 28 07:21:45 2022 from 192.*.*.*
user@c-explorer:~$ tmux

[db-sync-node:Info:6] [2022-07-03 11:23:29.59 UTC] Using byron genesis file from: "config/../../cardano-node/configuration/cardano/mainnet-byron-genesis.json"
[db-sync-node:Info:6] [2022-07-03 11:23:29.59 UTC] Using shelley genesis file from: "config/../../cardano-node/configuration/cardano/mainnet-shelley-genesis.json"
[db-sync-node:Info:6] [2022-07-03 11:23:29.59 UTC] Using alonzo genesis file from: "config/../../cardano-node/configuration/cardano/mainnet-alonzo-genesis.json"
[db-sync-node:Info:6] [2022-07-03 11:23:30.32 UTC] NetworkMagic: 764824073
[db-sync-node:Info:6] [2022-07-03 11:23:31.22 UTC] Initial genesis distribution present and correct
[db-sync-node:Info:6] [2022-07-03 11:23:31.22 UTC] Total genesis supply of Ada: 31112484745.000000
[db-sync-node:Info:6] [2022-07-03 11:23:31.22 UTC] Inserting Shelley Genesis distribution
[db-sync-node:Info:6] [2022-07-03 11:23:31.22 UTC] epochPluginOnStartup: Checking
[db-sync-node:Info:6] [2022-07-03 11:23:31.22 UTC] localInitiatorNetworkApplication: connecting to node via "/opt/cardano/cnode/sockets/node0.socket"
[db-sync-node.Subscription:Notice:50] [2022-07-03 11:23:31.22 UTC] Identity Starting Subscription Worker, valency 1
[db-sync-node.Subscription:Notice:51] [2022-07-03 11:23:31.22 UTC] Identity Connection Attempt Start, destination LocalAddress "/opt/cardano/cnode/sockets/node0.socket"
[db-sync-node.Subscription:Notice:51] [2022-07-03 11:23:31.22 UTC] Identity Connection Attempt End, destination LocalAddress "/opt/cardano/cnode/sockets/node0.socket" outcome: ConnectSuccessLast
[db-sync-node.Handshake:Info:51] [2022-07-03 11:23:31.22 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/opt/cardano/cnode/sockets/node0.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 764824073),(NodeToClientV_2,TInt 764824073),(NodeToClientV_3,TInt 764824073),(NodeToClientV_4,TInt 764824073),(NodeToClientV_5,TInt 764824073),(NodeToClientV_6,TInt 764824073),(NodeToClientV_7,TInt 764824073),(NodeToClientV_8,TInt 764824073),(NodeToClientV_9,TInt 764824073),(NodeToClientV_10,TInt 764824073)]))
[db-sync-node.Handshake:Info:51] [2022-07-03 11:23:31.22 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/opt/cardano/cnode/sockets/node0.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_10 (TInt 764824073))
[db-sync-node.Mux:Info:51] [2022-07-03 11:23:31.22 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/opt/cardano/cnode/sockets/node0.socket"} event: Handshake Client end, duration 0.000589645s
[db-sync-node.Mux:Info:52] [2022-07-03 11:23:31.22 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/opt/cardano/cnode/sockets/node0.socket"} event: State: Mature
[db-sync-node:Info:55] [2022-07-03 11:23:31.22 UTC] Starting chainSyncClient
[db-sync-node:Info:55] [2022-07-03 11:23:31.24 UTC] Cardano.Db tip is at slot 48193738, block 6639999
[db-sync-node:Info:60] [2022-07-03 11:23:31.24 UTC] Running DB thread
[db-sync-node.Subscription:Notice:50] [2022-07-03 11:23:31.25 UTC] Identity Required subscriptions started
[db-sync-node:Info:60] [2022-07-03 11:23:31.25 UTC] Rolling back to slot 48193738, hash ecd8b5b457b541b3a8af5d161e3625564776b46114807ecd3017ca655fa03874
[db-sync-node:Info:60] [2022-07-03 11:23:31.25 UTC] No blocks need to be deleted
[db-sync-node:Info:60] [2022-07-03 11:24:28.61 UTC] Found snapshot file for slot 48193738, hash ecd8b5b457b541b3a8af5d161e3625564776b46114807ecd3017ca655fa03874
[db-sync-node:Info:63] [2022-07-03 11:24:42.94 UTC] getHistoryInterpreter: acquired
[db-sync-node:Info:74] [2022-07-03 11:24:42.94 UTC] Running Offline fetch thread
[db-sync-node:Info:60] [2022-07-03 11:24:42.94 UTC] thisIsAnUglyHack: Main thead
[db-sync-node:Info:60] [2022-07-03 11:24:44.15 UTC] File ledger-state/mainnet/48193738-ecd8b5b457.lstate exists
[db-sync-node:Info:60] [2022-07-03 11:24:44.15 UTC] Starting at epoch 309
[db-sync-node:Info:60] [2022-07-03 11:24:48.91 UTC] Handling 1010063 stakes for epoch 309 slot 48193750, hash 8741de9a344a5c8e2b397ec1e1bc9c5aa8fc8970c7dcc5710106d36d63a28286
[db-sync-node:Info:60] [2022-07-03 11:31:18.88 UTC] insertShelleyBlock(Alonzo): epoch 309, slot 48193750, block 6640000, hash 8741de9a344a5c8e2b397ec1e1bc9c5aa8fc8970c7dcc5710106d36d63a28286
[db-sync-node:Info:60] [2022-07-03 12:14:01.83 UTC] insertEpochInterleaved: Epoch 309, 1010063 stake addresses
[db-sync-node:Info:60] [2022-07-03 12:44:19.53 UTC] Offline pool metadata fetch: 51 results, 30 fetch errors
[db-sync-node:Info:60] [2022-07-03 13:17:32.32 UTC] Offline pool metadata fetch: 50 results, 28 fetch errors
[db-sync-node:Info:60] [2022-07-03 13:40:31.14 UTC] insertShelleyBlock(Alonzo): epoch 309, slot 48294720, block 6645000, hash 7d6dd0a2946ba06806fb7b1751c00583fb4f2d48e4fd7ad41fe282ecbe20dbb0
[db-sync-node:Info:60] [2022-07-03 14:04:20.70 UTC] Offline pool metadata fetch: 49 results, 35 fetch errors
[db-sync-node:Info:60] [2022-07-03 14:45:27.16 UTC] Offline pool metadata fetch: 50 results, 33 fetch errors
[db-sync-node:Info:60] [2022-07-03 14:52:25.02 UTC] Handling 944673 rewards for epoch 308 slot 48367269, hash 75d33908df09955b623e8a6c504a2b1fd9308bf4e026dd1afd79e66e0c65c893
[db-sync-node:Info:60] [2022-07-03 16:07:05.27 UTC] insertEpochInterleaved: Epoch 308, 944673 rewards
[db-sync-node:Info:60] [2022-07-03 16:18:28.31 UTC] Took a ledger snapshot at ledger-state/mainnet/48404483-78b722da39.lstate
[db-sync-node:Info:60] [2022-07-03 16:18:28.31 UTC] Removing valid files ["ledger-state/mainnet/47991743-f6062d3281.lstate"]
[db-sync-node:Info:60] [2022-07-03 16:18:28.64 UTC] insertShelleyBlock(Alonzo): epoch 309, slot 48404487, block 6650000, hash 6e8e3095670e8790b3f062a2ae0b26292c0abd8f3d691dfcb266d88799e6adc2
[db-sync-node:Info:60] [2022-07-03 16:18:28.64 UTC] Offline pool metadata fetch: 53 results, 29 fetch errors
[db-sync-node:Info:60] [2022-07-03 16:39:26.10 UTC] Offline pool metadata fetch: 55 results, 35 fetch errors
[db-sync-node:Info:60] [2022-07-03 17:21:37.70 UTC] Offline pool metadata fetch: 52 results, 33 fetch errors
[db-sync-node:Info:60] [2022-07-03 17:33:24.95 UTC] insertShelleyBlock(Alonzo): epoch 309, slot 48506751, block 6655000, hash 63fc21a8deda659524d82f78053c2d6873273aa5a832f8490bcfd956614a5a53
[db-sync-node:Info:60] [2022-07-03 17:44:07.54 UTC] Offline pool metadata fetch: 53 results, 31 fetch errors
[db-sync-node:Info:60] [2022-07-03 18:21:29.07 UTC] Took a ledger snapshot at ledger-state/mainnet/48556794-b0336f5eee-309.lstate
[db-sync-node:Info:60] [2022-07-03 18:21:29.07 UTC] Removing epoch boundary files ["ledger-state/mainnet/46396728-0b4e199430-304.lstate"]
[db-sync-node:Info:60] [2022-07-03 18:22:09.80 UTC] adjustEpochRewards: starting epoch 310, 864 orphaned rewards removed (1670.952042 ADA)
[db-sync-node:Info:60] [2022-07-03 18:22:09.90 UTC] Starting epoch 310
[db-sync-node:Info:60] [2022-07-03 18:22:13.28 UTC] Handling 1017022 stakes for epoch 310 slot 48556875, hash a5c9f0a35d0a9c94fd92b33796da284fd11935ac2a1d783db7efe43691791192
[db-sync-node:Info:60] [2022-07-03 18:22:50.74 UTC] validateEpochRewards: total rewards that become spendable in epoch 310 is 14350297.414804 ADA
[db-sync-node:Info:60] [2022-07-03 18:34:00.00 UTC] insertShelleyBlock(Alonzo): epoch 310, slot 48556875, block 6657401, hash a5c9f0a35d0a9c94fd92b33796da284fd11935ac2a1d783db7efe43691791192
[db-sync-node:Info:60] [2022-07-03 18:58:28.83 UTC] Offline pool metadata fetch: 52 results, 30 fetch errors
[db-sync-node:Info:60] [2022-07-03 19:10:39.75 UTC] insertEpochInterleaved: Epoch 310, 1017022 stake addresses
[db-sync-node:Info:60] [2022-07-03 19:19:12.79 UTC] epochPluginInsertBlock: epoch 309
[db-sync-node:Info:60] [2022-07-03 19:33:03.76 UTC] Took a ledger snapshot at ledger-state/mainnet/48609499-9416c16a02.lstate
[db-sync-node:Info:60] [2022-07-03 19:33:03.76 UTC] Removing valid files ["ledger-state/mainnet/48193738-ecd8b5b457.lstate"]
[db-sync-node:Info:60] [2022-07-03 19:33:05.27 UTC] insertShelleyBlock(Alonzo): epoch 310, slot 48609551, block 6660000, hash 4be6be533fd271cfd51b646b90c32e6bfd8ddeaece2b7714a650c13970ed975c
[db-sync-node:Info:60] [2022-07-03 19:33:05.27 UTC] Offline pool metadata fetch: 55 results, 30 fetch errors

**Comment by kderme** [comment]
You didn't mention your db-sync version, but I guess it's 12.0.x. There will be soon be a new release https://github.com/input-output-hk/cardano-db-sync/releases/tag/untagged-59bbb8471ddf6892e55f with improvements in syncing speed.

**Comment by Fluid-team** [comment]
> You didn't mention your db-sync version, but I guess it's 12.0.x. There will be soon be a new release https://github.com/input-output-hk/cardano-db-sync/releases/tag/untagged-59bbb8471ddf6892e55f with improvements in syncing speed.

yes 12.0.2 sorry

**Comment by erikd** [comment]
@Fluid-team Yes, ~6 to sync epoch 309 is more than I would expect.

Are you meeting the [minimum system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements), specifically with regards to IOops? Are you running `db-sync` on the same machine as the `PostgreSQL` instance?

**Comment by Fluid-team** [comment]
> @Fluid-team Yes, ~6 hours to sync epoch 309 is more than double what I would expect.
> 
> Are you meeting the [minimum system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements), specifically with regards to SSD disks and IOops? Are you running `db-sync` on the same machine as the `PostgreSQL` instance?

yes using bare metal server 2 x X5670 12 core processors 48GB ram 2TB ssd with 670mb of sas drives,
CNODE
PSQL
DB_SYNC 
only things running on this box.

**Comment by Fluid-team** [comment]
Closing as going to re-install everything
