### ISSUE TITLE
Block producer's node version

### ISSUE THREAD

**Issue by jiagengliu** [input-output-hk/cardano-db-sync#1174]
Hello, 

I am doing some research on Cardano's network performance, like connection, software updates, etc. I am wondering if the node version of a block producer can be found in DB-Sync? [PoolTool's Network Health page](https://pooltool.io/networkhealth) reports the node versions used by current validators. If other things on the NetworkHealth page can be found in DB-Sync I'd also appreciate them.

Thanks,
Jiageng

**Comment by rdlrt** [comment]
You cannot predict node versions from db-sync, as `cardano-node` version is not saved in block headers. You can still query `protocol_major`, `protocol_minor` in block headers which would indicate (only relevant to the present state) the state of nodes that have upgraded to 1.35 (protocol_major = 7, for nodes that have upgraded), you can find more details on those [here](https://github.com/cardano-foundation/CIPs/blob/14e3aa40677c1eae081fdc000201c8d6373eb001/CIP-namesSurroundingFeatures/feature-table.md).

As regards the page you refer, PoolTool can aggregate this information based on participating SPOs who can run cncli/sendTip utility to report their own status to Pooltool

**Comment by jiagengliu** [comment]
Thank you! I'll close the issue.
