### ISSUE TITLE
Running migrations fails

### ISSUE THREAD

**Issue by dansentivany** [input-output-hk/cardano-db-sync#1175]
**OS**
Your OS: inputoutput/cardano-db-sync:13.0.0

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): inputoutput/cardano-db-sync:13.0.0
PostgreSQL version: 13

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: inputoutput/cardano-db-sync:13.0.0

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): inputoutput/cardano-db-sync:13.0.0

**Additional context**

**Problem Report**
Hi, im trying to upgrade db-sync from 12.0.2 to 13.0.0 and the following happens on all instances:
```
2022-07-04 07:51:04.197 UTC [77] ERROR:  failed to re-find parent key in index "job_singletonon" for deletion target page 17291
2022-07-04 07:51:04.197 UTC [77] CONTEXT:  while vacuuming index "job_singletonon" of relation "pgboss.job"
	automatic vacuum of table "cexplorer.pgboss.job"
2022-07-04 07:51:17.829 UTC [173] ERROR:  could not create unique index "unique_treasury"
2022-07-04 07:51:17.829 UTC [173] DETAIL:  Key (tx_id, cert_index)=(37343, 0) is duplicated.
2022-07-04 07:51:17.829 UTC [173] CONTEXT:  SQL statement "ALTER TABLE "treasury" ADD CONSTRAINT "unique_treasury" UNIQUE("tx_id","cert_index")"
	PL/pgSQL function migrate() line 18 at EXECUTE
2022-07-04 07:51:17.829 UTC [173] STATEMENT:  SELECT migrate() ;
```
db-sync fails with
```
localhost:5440 - accepting connections
/run/secrets
Generating PGPASS file
Connecting to network: testnet
[db-sync-node:Warning:6] [2022-07-04 07:51:17.43 UTC] Version number: 13.0.0
[db-sync-node:Warning:6] [2022-07-04 07:51:17.43 UTC] Git hash: 67367b5ae317b2915de94dc3be43c29d796d876e
[db-sync-node:Warning:6] [2022-07-04 07:51:17.43 UTC] Option disable-ledger: False
[db-sync-node:Warning:6] [2022-07-04 07:51:17.43 UTC] Option disable-cache: False
[db-sync-node:Warning:6] [2022-07-04 07:51:17.43 UTC] Option disable-epoch: False
[db-sync-node:Warning:6] [2022-07-04 07:51:17.43 UTC] Enviroment variable DbSyncAbortOnPanic: False
[db-sync-node:Info:6] [2022-07-04 07:51:17.44 UTC] Schema migration files validated
[db-sync-node:Info:6] [2022-07-04 07:51:17.44 UTC] Running database migrations
ExitFailure 3

Errors in file: /tmp/migrate-2022-07-04T075117.log
```

**Comment by rdlrt** [comment]
Did you drop your existing DB before upgrade?

**Comment by dansentivany** [comment]
No, I didnt find any release notes for the version, but the version 12 stopped working for testnet.

**Comment by kderme** [comment]
Sorry, didn't know the link was private. You need to drop the db and resync everything from genesis for this release. The Changelog is https://github.com/input-output-hk/cardano-db-sync/blob/67367b5ae317b2915de94dc3be43c29d796d876e/cardano-db-sync/CHANGELOG.md#1300 and the db schema is documented https://github.com/input-output-hk/cardano-db-sync/blob/67367b5ae317b2915de94dc3be43c29d796d876e/doc/schema.md

**Comment by dansentivany** [comment]
Oh, there are actually quite a few changes. The hard one to spot was change of state dir to /var/lib/cexplorer . Since we are running containers, this would be a catastrophe on mainnet . Would it be possible to pass those as env vars to the container? Right now we are unable to pass --disable-ledger or state dir path, we have only network, snapshot etc.

**Comment by kderme** [comment]
Yes we will probably try to improve the docker configuration. I thought there was a workaround: you can pass the flags as extra options to the docker image and they pass to the executable.

**Comment by dansentivany** [comment]
That depends on how youre running the containers. We have to be actually already doing some workarounds around the entrypoint (dirs handling, pg init, snapshot handling). I was asking about the flags mainly because we are struggling with rollbacks on mainnet (can take even 2 days in our case) so I was keen on testing the new flag. Anyway, the initial error is solved by dropping the DB. Thank you a lot for the work on the new release, you are moving this tool in the much needed direction. Feel free to reach out if you want to talk about the docker config!

**Comment by kderme** [comment]
Feel free to open a new ticket for docker config. Looks like you have some good feedback.
> can take even 2 days

Slow rollbacks usually mean there are some missing indexes. This may be relevant https://github.com/input-output-hk/cardano-db-sync/issues/1109
