### ISSUE TITLE
Provide different db-sync flavours

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1195]
DB-sync uses many recourses because it populates a a big number of tables. Different set of flags are introduced which filter out specific set of data, like https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/configuration.md#--disable-ledger. Each of these flags duplicates the testing scenarios that db-sync needs.

To mitigate this we should only formally support specific cominations of these configuraions, called flavours. For example we could have the flavour with the full set of data, the reduced memory flavour without the ledger, the flavour for smash, dapps, light wallet, explorer etc.

To create targeted flavours we need feedback from downstream components.

**Comment by marshada** [comment]
Let's Identify additional flavors, and flush out the ones suggested above. Happy to discuss together if that helps.

Existing config flags:
—disable-ledger (reduce RAM from 12GB to 1GB)
—disable-cache
—disable-epoch
