### ISSUE TITLE
Rollback to genesis when restoring from any v13 snapshot

### ISSUE THREAD

**Issue by 1000101** [input-output-hk/cardano-db-sync#1196]
**OS**
Your OS: NixOS

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.0.1 (070a856)
PostgreSQL version: 14.1

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: nix

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): nix

**Problem Report**
Restoring the snapshot finishes fine, following [this](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/state-snapshot.md#restoring-from-a-snapshot) tutorial (it always worked flawlessly up to this point).

```
...
All good!
```

But then when I start cardano-db-sync service:

```
 Starting chainSyncClient
 Cardano.Db tip is at slot 66269743, block 7498999
 Running DB thread
 Running Offline fetch thread
 Identity Required subscriptions started
 Rolling back to genesis
 Deleting 7498999 blocks up to slot 66269743
```

It wants to roll back to genesis. This happens with both snapshots published here https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#13/

**Comment by erikd** [comment]
This happens because the `node` is not fully synced. When `db-sync` connects to the `node` they negotiate the tip and if `db-sync` is ahead of the `node` `db-sync` will roll back.

**Comment by 1000101** [comment]
> This happens because the `node` is not fully synced. When `db-sync` connects to the `node` they negotiate the tip and if `db-sync` is ahead of the `node` `db-sync` will roll back.

Thanks for the reply but it seems that the node (`v1.35.1`) is fully synced.

**Comment by erikd** [comment]
There are two possibilties that I ca think of for the `Rolling back to genesis` message:

* The `node` is not synced.
* The `node` and `db-sync` are running on different networks.

**Comment by KorayBarkin** [comment]
> There are two possibilties that I can think of for the `Rolling back to genesis` message:
> 
> * The `node` is not synced.
> * The `node` and `db-sync` are running on different networks.

I have the same issue, db-sync is running at port 3100 by default and my node is running at 1900. Should I pass 3100 as a port while starting the node? When I delete the restore snapshot parameter this error disappeared its getting from the genesis but takes TOO MUCH time to get db sync. After Byron era finishes it took 7 days to get 45 epoch in Shelley era...

**Comment by erikd** [comment]
@KorayBarkin I assume `db-sync` and `node` are running on the same machine (they should be).If that is the case, they should not connect via a regular socket but via a local domain socket. You need to read the docs.

**Comment by 1000101** [comment]
> There are two possibilties that I can think of for the `Rolling back to genesis` message:
> 
>     * The `node` is not synced.
> 
>     * The `node` and `db-sync` are running on different networks.

Thanks for the reply - I have experienced both scenarios before, but it really seems this is not the case now (node is running on mainnet). I'm not sure where I'm making an error, more logs:

```

Loading custom cardano-db-sync schemas.
[db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Version number: 13.0.1
[db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Git hash: 0000000000000000000000000000000000000000
[db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Option disable-ledger: False
[db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Option disable-cache: False
[db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Option disable-epoch: False
[db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Enviroment variable DbSyncAbortOnPanic: False
[db-sync-node:Info:6] [2022-07-18 00:40:06.16 UTC] Schema migration files validated
[db-sync-node:Info:6] [2022-07-18 00:40:06.16 UTC] Running database migrations
[db-sync-node:Info:6] [2022-07-18 00:40:06.75 UTC] Using byron genesis file from: "/nix/store/iwq90igv72ihdr9z9nl3m0dsiv0bfh7y-byron-genesis.json"
[db-sync-node:Info:6] [2022-07-18 00:40:06.75 UTC] Using shelley genesis file from: "/nix/store/sr1r1fsqij2bcr3jc1xz7hdgih2w6gp7-shelley-genesis.json"
[db-sync-node:Info:6] [2022-07-18 00:40:06.75 UTC] Using alonzo genesis file from: "/nix/store/8qnphq6yvcjspiy3z0aijfd6cv64l3hl-alonzo-genesis.json"
[db-sync-node:Info:6] [2022-07-18 00:40:07.53 UTC] NetworkMagic: 764824073
[db-sync-node:Info:6] [2022-07-18 00:40:08.08 UTC] Initial genesis distribution present and correct
[db-sync-node:Info:6] [2022-07-18 00:40:08.08 UTC] Total genesis supply of Ada: 31112484745.000000
[db-sync-node:Info:6] [2022-07-18 00:40:08.08 UTC] Inserting Shelley Genesis distribution
[db-sync-node:Info:6] [2022-07-18 00:40:08.09 UTC] epochStartup: Checking
[db-sync-node:Info:6] [2022-07-18 00:40:08.09 UTC] localInitiatorNetworkApplication: connecting to node via "/run/cardano-node/node.socket"
[db-sync-node.Subscription:Notice:56] [2022-07-18 00:40:08.09 UTC] Identity Starting Subscription Worker, valency 1
[db-sync-node.Subscription:Notice:57] [2022-07-18 00:40:08.09 UTC] Identity Connection Attempt Start, destination LocalAddress "/run/cardano-node/node.socket"
[db-sync-node.Subscription:Notice:57] [2022-07-18 00:40:08.09 UTC] Identity Connection Attempt End, destination LocalAddress "/run/cardano-node/node.socket" outcome: ConnectSuccessLast
[db-sync-node.Handshake:Info:57] [2022-07-18 00:40:08.09 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_9,TInt 764824073),(NodeToClientV_10,TInt 764824073),(NodeToClientV_11,TInt 764824073),(NodeToClientV_12,TInt 764824073),(NodeToClientV_13,TInt 764824073)]))
[db-sync-node.Handshake:Info:57] [2022-07-18 00:40:08.09 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_13 (TInt 764824073))
[db-sync-node.Mux:Info:57] [2022-07-18 00:40:08.09 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: Handshake Client end, duration 0.00151989s
[db-sync-node.Mux:Info:58] [2022-07-18 00:40:08.09 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: State: Mature
[db-sync-node.Mux:Info:58] [2022-07-18 00:40:08.09 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: Eagerly started (MiniProtocolNum 5) in InitiatorDir
[db-sync-node.Mux:Info:58] [2022-07-18 00:40:08.09 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: Eagerly started (MiniProtocolNum 6) in InitiatorDir
[db-sync-node.Mux:Info:58] [2022-07-18 00:40:08.09 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: Eagerly started (MiniProtocolNum 7) in InitiatorDir
[db-sync-node.Mux:Info:58] [2022-07-18 00:40:08.09 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/run/cardano-node/node.socket"} event: Eagerly started (MiniProtocolNum 9) in InitiatorDir
[db-sync-node:Info:61] [2022-07-18 00:40:08.10 UTC] Starting chainSyncClient
[db-sync-node:Info:61] [2022-07-18 00:40:08.10 UTC] Cardano.Db tip is at slot 65837130, block 7477999
[db-sync-node:Info:69] [2022-07-18 00:40:08.10 UTC] Running DB thread
[db-sync-node:Info:70] [2022-07-18 00:40:08.10 UTC] Running Offline fetch thread
[db-sync-node.Subscription:Notice:56] [2022-07-18 00:40:08.12 UTC] Identity Required subscriptions started
[db-sync-node:Info:69] [2022-07-18 00:40:08.19 UTC] Rolling back to genesis
```

**Comment by kderme** [comment]
It looks like db-sync doesn't find the ledger-state directory. Is this configured properly? Did this happen on docker

I'm trying to replicate this.

**Comment by 1000101** [comment]
> It looks like db-sync doesn't find the ledger-state directory. Is this configured properly? 

Oh, wow, you were right! The [statedir and workdir seems to have changed](https://github.com/input-output-hk/cardano-db-sync/commit/0f49e06cf440c1749ab6064b81bf55a587f3dccd#diff-a61e263fd6edf6a1ef73c12898675627a0dcac614808951bc049b8fc93d57eacR127) to:
```
StateDirectory=cexplorer
WorkingDirectory=/var/lib/cexplorer
```

> Did this happen on docker
> 
> I'm trying to replicate this.

Hey, it's on Nix(OS).

**Comment by kderme** [comment]
So I guess this has a workaround. Can it be closed?

> [db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Git hash: 0000000000000000000000000000000000000000

This is also strange.

**Comment by 1000101** [comment]
> So I guess this has a workaround. Can it be closed?
> 
> > [db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Git hash: 0000000000000000000000000000000000000000
> 
> This is also strange.

Yeah, sure. It would be nice if the changelog did mention this change though. I think more people may stumble over this. It can be solved in either start using the new structure or adjust the systemd service.

**Comment by erikd** [comment]
> [db-sync-node:Warning:6] [2022-07-18 00:40:06.15 UTC] Git hash: 0000000000000000000000000000000000000000

I am pretty sure that is an artifact of the Nix build.

**Comment by erikd** [comment]
See also https://github.com/input-output-hk/cardano-db-sync/pull/1200 which will be merged after it has been tested and known to work.

**Comment by GiorgosStou** [comment]
The [statedir and workdir seem to have changed](https://github.com/input-output-hk/cardano-db-sync/commit/0f49e06cf440c1749ab6064b81bf55a587f3dccd#diff-a61e263fd6edf6a1ef73c12898675627a0dcac614808951bc049b8fc93d57eacR127) to:
> 
> StateDirectory=cexplorer
> WorkingDirectory=/var/lib/cexplorer

Hello, I am facing the same issue, but DB-sync has been running for months (13.0.0). I had restored from snapshot as well, no problem so far. Suddenly, it started throwing errors and trying to roll back bit by bit and now rolling back to genesis. My node is fully synced (epoch 372). 

May I ask details about this solution? I do not understand exactly what needs to be done.

**Comment by erikd** [comment]
@GiorgosStou Please do not post screenshots. They are incredibly difficult to read on high DPI monitors. Instead, cut and paste the text.

> I had restored from snapshot as well, no problem so far.  Suddenly, it started throwing errors and trying to roll back bit by bit and now rolling back to genesis. 

I have seen this on machine where the machines ran out of disk space and when this happens there is no available disk space to write the ledger state file and with the ledger state file,  `db-sync` will try to roll back to genesis.

**Comment by kderme** [comment]
> Suddenly, it started throwing errors and trying to roll back bit by bit

Probably related to bugs previous releases had, like https://github.com/input-output-hk/cardano-db-sync/issues/1181 https://github.com/input-output-hk/cardano-db-sync/issues/1222

> 13.0.0

You're advised to use the latest release which fixes these bugs https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.0.5

**Comment by GiorgosStou** [comment]
Thank you both very much for the replies. 
@erikd I have ~200GB of disk space left, so that should not be a problem.

@kderme Can I update db-sync from 13.0.0 to 13.0.5 without dropping the database? I cannot find instructions for that. I look at https://github.com/input-output-hk/cardano-db-sync/releases .

I also see that it mentions compatibility with node 1.35.3. I use 1.35.0.
Would that be needed to be updated as well? So these bug will require a whole new installation of node & db-sync?

On another point, if I let the rolling back to genesis happen, will it continue from where it left as normal?
If yes, is there an estimate on how long I need to wait (I have it rolling back for 2 days now) ?

**Comment by erikd** [comment]
> Can I update db-sync from 13.0.0 to 13.0.5 without dropping the database? 

Yes.

> I cannot find instructions for that.

Just stop the old version, install the new version and restart. 

> I also see that it mentions compatibility with node 1.35.3. I use 1.35.0.

There was an important bug fix after `1.35.0`. You should install that.

> On another point, if I let the rolling back to genesis happen, will it continue from where it left as normal?

No, roll back to genesis means exactly that, rolling back to an empty database.

> is there an estimate on how long I need to wait (I have it rolling back for 2 days now) ?

Rolling back to genesis takes far far longer than just dropping the database. Whether you roll back to genesis or drop the database you will still need a full sync which takes about 5 days.

**Comment by GiorgosStou** [comment]
OK, I will update to the db-sync 13.0.5. 
I assume the node update works in the same way.

thank you very much for the help, much appreciated!

**Comment by erikd** [comment]
Node update should be even simpler.
