### ISSUE TITLE
Ogmios Health Check: HealthFailedToConnect

### ISSUE THREAD

**Issue by KorayBarkin** [input-output-hk/cardano-db-sync#1197]
When I start the node as followed:

```
DOCKER_BUILDKIT=1 \
COMPOSE_DOCKER_CLI_BUILD=1 \
RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/13/db-sync-snapshot-schema-13-block-7498999-x86_64.tgz \
docker-compose up -d --build &&\
docker-compose logs -f

```
Ogmios giving me this error:

`cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-07-18T08:40:27.311928204Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}`

**Comment by erikd** [comment]
This is not a `db-sync` error.

**Comment by erikd** [comment]
Closing this. Its in the wrong repo and I cannot seem to move it to the correct one.
