### ISSUE TITLE
[SOLVED] System crash/freeze due to full RAM/swap when restoring from snapshot

### ISSUE THREAD

**Issue by TypicalHog** [input-output-hk/cardano-db-sync#1207]
**SOLVED: Inserting TMPDIR=/var/tmp as the first thing in the restore.sh file seems to resolve the issue. This forces the application to use the hard drive for storing temporary files instead of RAM and swap.**

**OS**
openSUSE Tumbleweed x86_64

**Versions**
cardano-db-sync 13.0.0 - linux-x86_64 - ghc-8.10 git revision 67367b5ae317b2915de94dc3be43c29d796d876e
postgres (PostgreSQL) 14.4

**Build/Install Method**
nix (following building-running.md)

**Run method**
run.sh and restore.sh in attachments (running *seems* fine)

**Additional context**
When restoring the snapshot, my /tmp would fill up and my system would either crash or the process would give me an error saying there's not enough space left on device. (I fixed this by increasing the size of my /tmp)
Now, however, when I try to restore using the snapshot, my swap slowly fills up, my system grinds to a halt and eventually freezes (I have to reboot).
It can chug along for quite a while (1h+?) with swap hovering around 60+GB, growing and shrinking slightly, but filling up eventually.
Perhaps it's possible I have messed something up when I was trying to resize /tmp, but I find it unlikely.
It's possible the swap filling issue was present even before I have resized /tmp.
RAM/swap usage reported by htop doesn't seem to change after I terminate the execution. (They are not freed up)
htop reports RAM usage that's typical for my system (in this case it's 14GB since I'm also running a cardano-node, but the desktop widget reports usage of 30.4GB)
I have 32GB RAM, 64GB swap, over 1TB free space on the drive, filesystem is btrfs.
Below are some files that might come in handy, I can provide more on demand.

**Problem Report**
![htop](https://user-images.githubusercontent.com/11476902/180650448-79fcb67f-6a3a-4a0e-976d-4b83eb17cb9e.png)
-
![neofetch](https://user-images.githubusercontent.com/11476902/180650449-50759c51-cb67-43ef-8063-e84b46b4e9ae.png)
-
[df.txt](https://github.com/input-output-hk/cardano-db-sync/files/9175932/df.txt) (output from ´df -a´, potentially relevant)
[restoring.txt](https://github.com/input-output-hk/cardano-db-sync/files/9175933/restoring.txt) (all seems good here, AFAICT)
[restore.sh.txt](https://github.com/input-output-hk/cardano-db-sync/files/9175935/restore.sh.txt)
[run.sh.txt](https://github.com/input-output-hk/cardano-db-sync/files/9175936/run.sh.txt) (should not be relevant to the issue)
EDIT: [top.txt](https://github.com/input-output-hk/cardano-db-sync/files/9175983/top.txt) (output from ´top -o SHR -n 1´)

**Comment by rdlrt** [comment]
That screenshot shows that your issue is with Xorg using up most of your RAM - which , as you'd see on searching stackoverflow is a common trouble when associated with storage device. Unrelated to dbsync itself

**Comment by TypicalHog** [comment]
> That screenshot shows that your issue is with Xorg using up most of your RAM - which , as you'd see on searching stackoverflow is a common trouble when associated with storage device. Unrelated to dbsync itself

The issue I have ONLY happens when I run ´restore.sh´ tho. (As soon as I run it, RAM/swap start filling up at a decently worrying rate)
It's certainly possible the issue is not with db-sync itself, but I find it hard to believe.

**Comment by rdlrt** [comment]
> It's certainly possible the issue is not with db-sync itself, but I find it hard to believe.

The more you use storage R/W , higher memory being used, it is exactly as some of the other posts (besides, you're simply doing a restore (uses psql against postgres db, has not even reached dbsync yet 🙂 )

**Comment by TypicalHog** [comment]
Dang, OK, I'm just completely guessing with my quite limited Linux knowledge, but is there any chance this is related to btrfs?

**Comment by TypicalHog** [comment]
@rdlrt I added top.txt which might be useful, I guess.

**Comment by rdlrt** [comment]
Prolly best handled on stackoverflow instead dbsync github, but for starters you might want to use system without X11

**Comment by TypicalHog** [comment]
Alright, thank you! Should I close this issue then?

**Comment by TypicalHog** [comment]
**SOLVED: Inserting TMPDIR=/var/tmp as the first thing in the restore.sh file seems to resolve the issue. This forces the application to use the hard drive for storing temporary files instead of RAM and swap.**
