### ISSUE TITLE
column epoch_param.coins_per_utxo_word does not exist

### ISSUE THREAD

**Issue by airstring** [input-output-hk/cardano-db-sync#1211]
**OS**
Your OS:  ubuntu20

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.0.0
PostgreSQL version: 13.7

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: install

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): docker

**Problem Report**
postgress report:
ERROR:  column epoch_param.coins_per_utxo_word does not exist at character 2981

**Comment by airstring** [comment]
> Not really a bug. The column was renamed to `coins_per_utxo_size` in v13.

I'm sure my cardano-db-sync is v13.0.0, so what else caused me to make this mistake?

**Comment by kderme** [comment]
Did you upgrade from a previous release or tag? If so, you may need to drop the db and resync

**Comment by airstring** [comment]
> Did you upgrade from a previous release or tag? If so, you may need to drop the db and resync

I have dropped postgres and db-sync，version of each component:
cardano-db-sync:13.0.0
inputoutput/cardano-graphql-hasura:6.2.0
inputoutput/cardano-graphql:6.2.0
cardanosolutions/cardano-node-ogmios:v5.5.1-mainnet  
postgres:13.6-alpine

**Comment by erikd** [comment]
@airstring Is this resolved? Can the ticket be closed?

**Comment by airstring** [comment]
Wait a moment, I updated the version of inputoutput/cardano-graphql-hasura and inputoutput/cardano-graphql, the service can be started, but ada service is not back to normal yet.
![image](https://user-images.githubusercontent.com/26688391/182342367-4e1d813a-f3c3-4144-8ba4-e4a6cea6596b.png)

**Comment by erikd** [comment]
That is not a `db-sync` issue. This issue should be moved to the `graph-ql` repo.

**Comment by airstring** [comment]
ok
