### ISSUE TITLE
Is there a reason why the `public.tx_out` table is not fully normalized?

### ISSUE THREAD

**Issue by aleks-djuric** [input-output-hk/cardano-db-sync#1225]
The address and address_raw columns in `public.tx_out` are fairly long strings. In some cases (i.e. heavily used smart contract addresses), this string is replicated hundreds of thousands of times across rows in the `public.tx_out` table.

It seems to me that we could be more efficient with storage if the address and address_raw columns were pulled into a separate `public.address` table similar to how we have a `public.stake_address` table.

I assume there is probably a reason why it was not implemented this way and curious to know what it is. 

My best guess is that the computational overhead of joining these tables frequently for certain applications outweighs the extra storage costs. Would like to hear what you guys think though!

**Comment by kderme** [comment]
Last time I checked each address appears on average around 1.7 times in `tx_out`. So there are not enough repetitions to justify a separate table.

I haven't checked recently though and it's very possible that script addresses have way more repetetions than the average and may skew this average.

Having nornalised schema is not really a top priority. A good balance of performance between insertions and queries is.

**Comment by rdlrt** [comment]
> Last time I checked each address appears on average around 1.7 times in tx_out. 

Just for stat, current ratio is ~3.42
