### ISSUE TITLE
Total collateral field in Babbage transactions

### ISSUE THREAD

**Issue by Scitz0** [input-output-hk/cardano-db-sync#1229]
**OS**
Your OS: Ubuntu 22.04

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.0.4
PostgreSQL version: 14.1

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: cabal

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): systemd

**Additional context**

**Problem Report**
While looking into adding support for Babbage transactions I noticed that db-sync doesn't include total collateral field from [Babbage spec](https://hydra.iohk.io/build/17586760/download/1/babbage-changes.pdf). 
While I'm not sure it's needed, it would be good to get some clarity on the subject.

**Comment by johnnuy** [comment]
Is it possible to calculate this as the sum of the collateral inputs minus the sum of the collateral outputs?

**Comment by Scitz0** [comment]
> Is it possible to calculate this as the sum of the collateral inputs minus the sum of the collateral outputs?

To my understanding, even if CIP mention collateral outputs in plural, there can only be a single collateral output. But yes, the result should be the sum of collateral inputs (lovelace) - lovelace in collateral output. Though, this specific field is part of the tx to my understanding. I'm not entirely sure of its use case, it also doesn't take tokens in collateral into consideration to my knowledge. But just calculating the difference between input and output collateral could any end system system/user do, so not sure I see the value adding it to dbsync to be honest. I raised the issue just because I saw that it was missing, but also unsure if it's actually needed.

**Comment by kderme** [comment]
Indeed the total colateral is a reduntant and optional field in the transaction. It doesn't add any new information as its values can be computed by the difference coll inputs - coll output. I think it exists for hardware wallets that don't have access to UTxO and can't resolve inputs, but I don't know much about its usability.

In db-sync the field is reflected in the `tx.fee` of a Tx with a phase 2 failure. If the field is not there, as it's optional, db-sync will compute it. I think this can close?

**Comment by Scitz0** [comment]
I'm ok closing this one.
