### ISSUE TITLE
Evaluate Risks for UTxO-HD

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1233]
UTxO-HD will change the way the utxo is stored. It's expected that there will still be a in memory version, that db-sync can use. The kind of this type is expected to change. We should try to evaluate the risk of this integration. When there is a prototype in node, we should also try to integrate to db-sync to see what breaks and if it's a big task.

This is not about integration, but about evaluate the risks of it.

**Comment by erikd** [comment]
`db-sync` does not use the UTxO set itself, but the UTxO set is by far the largest part of the ledger state that `db-sync` currently maintains. The best solution is for `db-sync` to not maintain its own copy of ledger state but to extract what it needs from the `node`.

**Comment by kderme** [comment]
The first integration of UTxO-HD branches (still using in memory ledger state), even though it works properly and tests pass, has significant performance issues. A single block takes 17s to reapply and memory clibes to 30GB where it should be ~12GB. 

Possibly there are issues to the initial way we use the new apply utilities, however this creates an integration risk

**Comment by kderme** [comment]
An initial UTxO-DH integration using in memory ledger is completed now, without any performance regression. Closing this.
