### ISSUE TITLE
[FR] Separate Leader and Member rewards for the reward address of the pool

### ISSUE THREAD

**Issue by dmitrystas** [input-output-hk/cardano-db-sync#1244]
**DB-Sync version**
cardano-db-sync 13.0.2 - linux-x86_64 - ghc-8.10
git revision 8733b71af3ada773755c5cb08d9c061eda11fb96

**PostgreSQL version**
14.4

**Problem Report**
At the moment usually a pool's reward address has only `leader` type in the `reward` table, even if it's delegated to this pool. This `leader` reward contains both leader and member parts of rewards, i.e. equal to the sum of pool margin/fee + delegation rewards. But there are some addresses (234 at the moment in mainnet) which have both types `leader` and `member` at the same time, for the same epoch. They have right amounts of pool margin/fee in row with `leader` type, and delegation rewards in row with `member` type. This happened only in case when pool's reward address is not simultaneously the owner of this pool.

It will probably be more clear in the following example for`stake1uyt0rrp60jn8qnvnzlcj6up9q0r3mxyvnmxtlm0y4r3vltgf05u87`

```
SELECT *
FROM reward
WHERE addr_id = (SELECT id FROM stake_address WHERE view = 'stake1uyt0rrp60jn8qnvnzlcj6up9q0r3mxyvnmxtlm0y4r3vltgf05u87')
ORDER BY id;

    id    | addr_id |  type  |  amount   | earned_epoch | spendable_epoch | pool_id
----------+---------+--------+-----------+--------------+-----------------+---------
 22123937 | 1286599 | leader | 601547401 |          286 |             288 |    2252
 30092783 | 1286599 | member |   2407545 |          297 |             299 |    2252
 30829684 | 1286599 | leader | 667983420 |          297 |             299 |    2252
 31830284 | 1286599 | member |   2238730 |          299 |             301 |    2252
 32588487 | 1286599 | leader | 644985517 |          299 |             301 |    2252
 35364094 | 1286599 | member |   3758819 |          303 |             305 |    2252
 36147626 | 1286599 | leader | 644101159 |          303 |             305 |    2252
 39928735 | 1286599 | member |   4635321 |          308 |             310 |    2252
 40726881 | 1286599 | leader | 631304175 |          308 |             310 |    2252
 57495779 | 1286599 | leader | 659485102 |          324 |             326 |    2252
 68558739 | 1286599 | leader | 496559296 |          334 |             336 |    2252
 75285178 | 1286599 | leader | 492516169 |          340 |             342 |    2252
 81950560 | 1286599 | leader | 469693483 |          346 |             348 |    2252
 90464187 | 1286599 | leader | 462095941 |          353 |             355 |    2252
 91639614 | 1286599 | leader | 461872884 |          354 |             356 |    2252
(15 rows)
```

As can we see here, addr id 1286599 has both leader/member types, but from epoch 324 it has only leader type. Now, let's check the changes of pool_owners for this pool id 2252

```
SELECT pool_update.id, pool_update.active_epoch_no, STRING_AGG(pool_owner.addr_id::varchar, ','), pool_update.reward_addr_id
FROM pool_update
LEFT JOIN pool_owner ON pool_owner.pool_update_id = pool_update.id
WHERE pool_update.hash_id = 2252
GROUP BY pool_update.id, pool_update.active_epoch_no, pool_update.reward_addr_id
ORDER BY pool_update.id DESC;

  id   | active_epoch_no |          string_agg           | reward_addr_id
-------+-----------------+-------------------------------+----------------
 25985 |             323 | 638268,4461974,576317,1286599 |        1286599
 19074 |             276 | 576317,638268                 |        1286599
 19073 |             276 | 638268,576317                 |        1286599
 17438 |             269 | 638268,576317                 |        1286599
 16091 |             264 | 576317,638268                 |        1286599
 15851 |             263 | 576317,638268                 |         638268
 15330 |             261 | 638268,576317                 |         638268
 15329 |             261 | 576317,638268                 |         638268
 14941 |             260 | 638268                        |         638268
 14858 |             260 | 638268                        |         638268
 13741 |             257 | 638268                        |         638268
 11165 |             251 | 638268                        |         638268
 10813 |             250 | 638268                        |         638268
(13 rows)

```
We can see that addr_id 1286599 was added in the (active) Epoch 323 as pool owner, and there are no rewards with `member` type for this address in the reward table from this epoch.

So, the question is can we separate member and leader rewards for pools reward addresses in case when this address is simultaneously the owner of the pool?

Sorry if my explanation wasn't completely clear. I tried to explain in as much detail as possible, but it still looks a bit confusion :) If you need more details I am at your disposal

**Comment by kderme** [comment]
I think owners of a pool never get member rewards from that pool. It doesn't matter if they delegate to the pool or if they are the pool reward accounts.

> So, the question is can we separate member and leader rewards for pools reward addresses in case when this address is simultaneously the owner of the pool?

I'm not sure if there is something to separate, since there are no member rewards in that case. db-sync gets from the ledger layer only leader rewards and this is what it stores in the db.

**Comment by dmitrystas** [comment]
Thanks [kderme](https://github.com/kderme), I completely forgot that pool owners do not receive any rewards, their rewards are distributed to the pool reward address only. You're right, there's no way to separate them.
