### ISSUE TITLE
slot_leader table error  (erikd/shelley-32byte-address-hash)

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#125]
I mean there is error with slot leader table (bad slot leader hashes, there are block hashes instead leader id); this is reason why 

1 slot_leader hash = 1 row blocks table instead of 1 slot_leader = N rows blocks table 

the current solution doesn't make sense to me and is somewhat different from actual byron mainnet solution

**Comment by erikd** [comment]
The whole things is still very much a work in progress. I only just got this working on Thursday and it has only have minimal testing.

**Comment by erikd** [comment]
Can't really fix and validate this until the lower level libraries are fixed.

**Comment by rhyslbw** [comment]
https://github.com/input-output-hk/cardano-ledger-specs/issues/1529

**Comment by cardanians** [comment]
works great, good job @erikd thanks

**Comment by erikd** [comment]
This should now be fixed on `master`.
