### ISSUE TITLE
Docker - env vars missing a default

### ISSUE THREAD

**Issue by dansentivany** [input-output-hk/cardano-db-sync#1257]
getting

/nix/store/05cj1fqh8iakhmyk7ahs0di6wlz80afq-cardano-db-sync: line 34: DISABLE_LEDGER: unbound variable
/nix/store/05cj1fqh8iakhmyk7ahs0di6wlz80afq-cardano-db-sync: line 34: DISABLE_CACHE: unbound variable

after starting v13.0.5. we should have some default or add the var to docs. i suspect even the current compose wont run

**Comment by kderme** [comment]
What did you run to get this error?

**Comment by kderme** [comment]
Possible it will work if you `git checkout release/13.0.x` or after this is merged to master https://github.com/input-output-hk/cardano-db-sync/pull/1236

**Comment by jbgi** [comment]
this should be fixed with https://github.com/input-output-hk/cardano-db-sync/pull/1236/commits/df0ad0681eaa3861cc912a04b67b7d36aace06db
Maybe worth a `13.0.6`?

**Comment by kderme** [comment]
This should be fixed for image `13.0.5-extra-args`

**Comment by ArturWieczorek** [comment]
Closing this as it should be fixed now. Feel free to reopen if the problem still exists.
