### ISSUE TITLE
EBBs are not cleaned up properly

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1264]
If there is a restart during Byron syncing, which forces a rollback to the latest on disk snapshot, blocks are deleted based on their `BlockNo`. However EBBs have BlockNo = 0, so they are not properly cleaned up. The result is that syncing fails when the EBBS are tried to be reinserted. We need a better way to clean up EBBs on rollbacks.

This doesn't affect releases, as they do rollbacks using foreign keys.

**Comment by erikd** [comment]
The whole of the Byron can be synced in under an hour. Most Byron epochs sync in under 10 minutes. Is this even and issue?

**Comment by kderme** [comment]
This can cause syncing failure which may force users to delete everything and resync. Even if it is possible for a small initial part of syncing, I think it's worth fixing and having clear semantics about how rollbacks work.

I believe it's possible with a single delete query, for EBBs based on their EpochNo.

**Comment by kderme** [comment]
This is fixed since rollbacks have been reworked
