### ISSUE TITLE
GHC 9.2 compatibility

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1265]

**Comment by erikd** [comment]
This will be worked on when all the dependencies also compile. This does not require an issue IMO, because this **must** be done and there is zero chance this will be forgotten.

**Comment by kderme** [comment]
Even if you and me know about it, I think it's better for visibility to have an issue. I added it to this board https://github.com/orgs/input-output-hk/projects/52/views/1 which gives a clear view about what we're working on.

**Comment by kderme** [comment]
Fixed at https://github.com/input-output-hk/cardano-db-sync/pull/1403
