### ISSUE TITLE
Block/proto version interpretation - preprod HF

### ISSUE THREAD

**Issue by cexplorer** [input-output-hk/cardano-db-sync#1267]
We have one interresting issue with db-sync on preprod (babbage) after HF.

For better understanding visit please this url: https://preprod.cexplorer.io/pool/pool1hl6re0nwp9rmq2a7gcs6j8je64jgfd22l5cdq4vlj6fezp2ed9s/blocks#data

and look on block versions: 

block before HF: https://preprod.cexplorer.io/block/03e18ee7627b48aa016d8105332556df99dbd20a36f26853a3dc9f0f7cbaa5d4
Protocol: 7.2

block after HF: https://preprod.cexplorer.io/block/5e35dc57f3d8d71a2dc0bdc5aaf2dbbfc1ffb74be36e31bc7a0d064532b0e246
Protocol: 7.0

All nodes are running on latest cardano-node, db-sync too.

Is this expected or issue?

![image](https://user-images.githubusercontent.com/109023887/191025153-d3c936b3-6757-4505-852b-6ab3967b71e1.png)

**Comment by kderme** [comment]
That's indeed a bit strange, I don't know the reason behind it.
```
cexplorer=# select proto_major, proto_minor, count(*) from block where epoch_no = 21 group by proto_major, proto_minor;
 proto_major | proto_minor | count 
-------------+-------------+-------
           7 |           2 | 14821
           7 |           1 |    79
           6 |           0 |  5579
(3 rows)

cexplorer=# select proto_major, proto_minor, count(*) from block where epoch_no = 22 group by proto_major, proto_minor;
 proto_major | proto_minor | count 
-------------+-------------+-------
           7 |           0 |  1681
           7 |           1 |     5
(2 rows)

```

**Comment by kderme** [comment]
After asking the node team, it seems that the same software version reports different protocol versions in different eras. So I think this is expected.

**Comment by btbf** [comment]
https://github.com/input-output-hk/cardano-node/pull/4258

**Comment by kderme** [comment]
As described in the comment https://github.com/input-output-hk/cardano-node/pull/4260/files#diff-8c649864fe4b96d142cfd4c2bb9e32a9510fe737c6ad4e13e04b585ee15a6b74, using 7.2 was a hack to check the software version. After the HF the correct value 7.0 is restored.

Also in https://preprod.cexplorer.io/block/5e35dc57f3d8d71a2dc0bdc5aaf2dbbfc1ffb74be36e31bc7a0d064532b0e246 it's assumed that the node is 1.35.1. I belive this is a wrong assumption if it's based on the PV.

Can we close this?
