### ISSUE TITLE
Epoch_End < NOW

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#127]
Im not sure if is this okay (last epoch end time < actual time)

![obrazek](https://user-images.githubusercontent.com/58650764/84196401-6c7f6900-aaa0-11ea-9f58-663e222a505d.png)

Solution:
extend end_time in epochs table, when is minted block in same epoch and epoch.end_time < block.time ?

**Comment by erikd** [comment]
Its rather unclear what this issue is all about.

After reading this about a dozen times, I think that its about the fact that for the the current epoch, the `end_time` for the is less the the actual time. The `end_time` here is less than the actual time because the `end_time` is the time stamp on the most recent block. Is that a correct interpretation?

**Comment by erikd** [comment]
Can this be closed?

**Comment by cardanians** [comment]
end_time (time stamp on the most recent block) > end_time (last row in epoch table) 

(not always, just sometimes)

**Comment by erikd** [comment]
By how much? Is the block count > 0 ?

**Comment by cardanians** [comment]
Block count is > 0. I see into db and now looks like this "problem" is here:

![obrazek](https://user-images.githubusercontent.com/58650764/84496020-7e355c00-acac-11ea-92ea-93583a5fe421.png)
![obrazek](https://user-images.githubusercontent.com/58650764/84496131-ad4bcd80-acac-11ea-9c34-df21efbba5ef.png)

**Comment by cardanians** [comment]
maybe LAST epoch.end_time is not updated, when are/is last block(s) empty (txs=0)

**Comment by erikd** [comment]
I have a high res screen which makes the text in these images really difficult to read.

On top of that you need to be explicit about the actual problem instead of hoping I will infer it from images I can hardly read.
