### ISSUE TITLE
Speedup Reward and EpochStake insertions

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1292]
Syncing with `disable-leger` provides a considerable speedup. This is because ledger rules are not applied and because `Reward` and `EpochStake` tables are not populated. This provides the motivation to investigate why these tables take so long to populate.

The reward table has a unique key which is checked every time a new entry is inserted. It exists because the reward table is never deleted. After a rollback the same values will be reattempted and the unique key guards against it. Since https://github.com/input-output-hk/cardano-db-sync/issues/1190 is done, there are no rollbacks when db-sync syncs, they only happen when db-sync reaches the tip of the chain. So for the most part, the unique constaint checks provides delays without any benefit. We should try and find a way to delay the migration which creates this unique key untill db-sync reaches the tip of the chain.

Also rewards are added in bug chunks. We should consider limit the size of the insertions. Persistant cache is also affected by it

Similar things apply to EpochStake.

Depends on https://github.com/input-output-hk/cardano-db-sync/issues/1087 https://github.com/input-output-hk/cardano-db-sync/issues/1293

**Comment by marshada** [comment]
DBSync sync time is 40% faster when disable-ledger is enabled, chiefly because the Reward and EpochStake tables aren't populated.

**Comment by marshada** [comment]
@kderme can you clarify whether this performance hit is due to processing for the epoch boundary?

**Comment by kderme** [comment]
No this operation is spread acrosss most of the epoch and not done during the epoch boundary

**Comment by Cmdv** [comment]
So I’ve been trying to research postgresql constraint system and how it’s slowing down our inserts for rewards before db-sync reaches the tips of the chain. From what I gather even if we delay adding the constraint once the tip is reached/after a migration. The db would have to recalculate all the existing rows to check if adding constraints is valid. From what I gather there is another option of using COPY but that tends to use CSV/files.

So we could translate the bulk insert into a copy but I’m unsure of performance benefits or if it’s something that could even happen?

**Comment by kderme** [comment]
I belive `COPY` is mostly used to copy data from files/stin. So instead we use insert with a big list of entries. An additional optimization, which is proposed in this ticket, is to remove unecessary constraints, which trigger checks from Postgres and delay insertions.

**Comment by Cmdv** [comment]
would these constraints be permanently removed as from my understanding 
>  The db would have to recalculate all the existing rows to check if adding constraints is valid
So even though we'd think by delaying adding them after the insertion would be more performant it might actually not be the case 🤔

**Comment by kderme** [comment]
To overcome the limitations of persistent it may be wise to completely remove the unique key from these 2 tables from TH. That way we can have a user defined Unique Key which lives outside Persistent and TH. To make this safer we can validate it against the `entityFields` of the TH generated `EntityDef`.

Also before creating the Unique Key it's necessary to first check if it has already been created before. Postgres queries usually have a `IF NOT EXISTS` clause for this. Alternatively a separate query needs to check it.

**Comment by Cmdv** [comment]
Currently blocked as unable to test locally as there seems to be an issue with `cardano-node` when building with MacOs Ventura / M1 https://github.com/input-output-hk/cardano-node/issues/5122
