### ISSUE TITLE
Missing  index on multi_asset.fingerprint

### ISSUE THREAD

**Issue by wout** [input-output-hk/cardano-db-sync#1327]
**OS**
Your OS: Ubuntu 20.04 LTS

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): cardano-db-sync 13.0.5 - linux-x86_64 - ghc-8.10
PostgreSQL version: 14.5

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Docker image

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker (Caprover server)

**Additional context**
I'm not sure if it's intentional or not, but the `multi_asset.fingerprint` column is missing an index. I've now added it manually because I'm making a lot of queries there, but is there a reason why it's missing? If not, would you consider adding it, or accept a PR?

**Comment by kderme** [comment]
I think it shouldn't be a responsibility of db-sync to add indexes other that the indexes that it uses itself. Users and clients should add them based on their needs and the queries they make.

The coming release `13.1.0.0`, has some better documentation on this.
