### ISSUE TITLE
Config for FF-testnet

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-db-sync#133]
does db-sync supports ff-testnet?

**Comment by erikd** [comment]
Support for the F&F is a WIP.

**Comment by zenithpool** [comment]
I noticed the recent version of `inputoutput/cardano-db-sync:master` has a ff config. I got the following errors messages though:

```
/run/secrets
Generating PGPASS file
Connecting to network: ff
[db-sync-node:Info:4] [2020-06-22 03:56:45.63 UTC] NetworkMagic: RequiresMagic 42
cardano-db-sync: DbInsertException "SlotLeader" (SqlError {sqlState = "23514", sqlExecStatus = FatalError, sqlErrorMsg = "value for domain hash28type violates check constraint \"hash28type_check\"", sqlErrorDetail = "", sqlErrorHint = ""})

```

**Comment by erikd** [comment]
> has a ff config.

It does? Where?

The code on `master` does not currently support the F&F testnet. the branch `erikd/shelley-ff-network` has work-in-progress support.

**Comment by zenithpool** [comment]
If you pull the recent docker image from `https://hub.docker.com/r/inputoutput/cardano-db-sync/tags` and pull the `master` tag. Then you run the docker image and you can check the configs at `cat /bin/entry-point`. You will notice `ff` is an option

**Comment by rhyslbw** [comment]
@zenithpool The presence of ff config in the master image does not indicate compatibility in this case, only reinstates what @erikd has advised. You can however build an image locally in the compatible branch, and use this config by passing env `NETWORK=ff`. It's a [single line command](https://github.com/input-output-hk/cardano-db-sync/blob/master/nix/docker.nix#L6) but requires the nix toolchain
