### ISSUE TITLE
Hi, I logged into my adalite wallet and I can not see any of my ada there, all I can see that the exact amount is on a adress which I can not get it from. I do not understand how this could have happened, as every time i log in through my trezor. Here are all my funds: https://cardanoscan.io/address/addr1qyq4v3sgkh9r8gc75gd6ltnz5ty74nra3s4m2ndt8ddw4ysp2erq3dw2xw33agsm47hx9gkfatx8mrptk4x6kw66a2fq87v2t0 if someone can help me I would be very thankfull.

### ISSUE THREAD

**Issue by HHubi** [input-output-hk/cardano-db-sync#1330]
**OS**
Your OS:

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):
PostgreSQL version:

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):

**Additional context**

**Problem Report**
Please do not include screenshots or images, but instead cut and paste any relevant log messages
or errors.

**Comment by erikd** [comment]
This is an adalite wallet issue. If cardano scan says your funds are still there then they are still there.

Remember, your funds are stored on the blockchain not in your wallet. All you wallet does is hold your private keys so you can prove to the blockchain that the funds are yours.

I know nearly nothing of Adalite, but I suggest you find out how to contact their support services and ask them. Please be careful with people trying to contact you and scam you out of your ADA.

**Comment by HHubi** [comment]
Thank you very much. Yes will do so.
