### ISSUE TITLE
Redeemer for cert and reward purpose

### ISSUE THREAD

**Issue by infnada** [input-output-hk/cardano-db-sync#1356]
**OS**
Your OS: wsl docker

**Versions**
cardano-db-sync 13.1.0.0 - linux-x86_64 - ghc-8.10
git revision 1040fa9ec85fd75ce9f02dae2006170136793d02

PostgreSQL version: 11.18-apline

**Build/Install Method**
docker compose build

**Run method**
Docker

**Additional context**

Based on `redeemer` table schema. Column `purpose` -> What kind pf validation this redeemer is used for. It can be one of 'spend', 'mint', 'cert', 'reward'.

**Problem Report**
```
select count(*) from redeemer where purpose = 'cert'; -> 16
select count(*) from redeemer where purpose = 'reward'; -> 0
```

Shouldn't the redeemer table be populated with all `certs` of transactions? If i check for example the `stake_deregistration` schema we have two columns:
- cert_index
- redeemer_id

All redeemer_id's are NULL

Shouldn't this `redeemer` table be populated with the certs of:
- pool_update
- pool_retire
- stake_registration
- stake_deregistration
- delegation
- treasury
- reserve
- pot_transfer

Also I don't understand the purpose of the `cert_index` column on all those tables if we can't get all certs of a specific transaction.

Is this a bug and the `redeemer` table is not properly populated or i completely misunderstood it?

Thanks

**Comment by kderme** [comment]
I don't think this is a bug. 'cert' redeemers may come from different certificates. In this case I think they all 16 come from delegations:
```
select count(*) from delegation  where redeemer_id is not null;
 count 
-------
    16
(1 row)
```

**Comment by infnada** [comment]
But why only 16 redeemers, or said in different order, why only 16 delegations have certs? Shouldn't all delegations have a cert?

Not only delegations, but:
- pool_update
- pool_retire
- stake_registration
- stake_deregistration
- delegation
- treasury
- reserve
- pot_transfer

**Comment by kderme** [comment]
The list that you posted are all different kind of certificates. Only 16 certificates (it happens that they are all delegations) are associated with a plutus script execution.

**Comment by kderme** [comment]
Only two kind of certificates can be associated with a script execution `stake_deregistration` and `delegation`. Their redeemer has purpose = `cert`.

**Comment by kderme** [comment]
@infnada does the above answer your question? Should this be closed?

**Comment by infnada** [comment]
I thought (based on schema) every in:

- pool_update
- pool_retire
- stake_registration
- stake_deregistration
- delegation
- treasury
- reserve
- pot_transfer

should have a `cert`/`reward` redeemer which populates the `cert_index` in their respective tables.

But i guess only plutus script executions interacting with `certs` are inserted as redeemers type `cert`, i'm a bit confused (lack of knowledge from my side).

But if you believe everything is OK and we're not missing any data this issue should be closed. Thanks!

**Comment by kderme** [comment]
> But i guess only plutus script executions interacting with certs are inserted as redeemers type cert

Yes this is the case. `Redeemers` is a plutus script related notion and plutus script executions interacting with certs is something quite uncommon atm.
