### ISSUE TITLE
Missing script entry for addresses with address_has_script

### ISSUE THREAD

**Issue by infnada** [input-output-hk/cardano-db-sync#1357]
OS
Your OS: wsl docker

Versions
cardano-db-sync 13.1.0.0 - linux-x86_64 - ghc-8.10
git revision https://github.com/input-output-hk/cardano-db-sync/commit/1040fa9ec85fd75ce9f02dae2006170136793d02

PostgreSQL version: 11.18-apline

Build/Install Method
docker compose build

Run method
Docker

Additional context

Based on tx_out table schema. 

```
address_has_script | boolean | Flag which shows if this address is locked by a script.
payment_cred | hash28type | The payment credential part of the Shelley address. (NULL for Byron addresses). For a script-locked address, this is the script hash.
```

Understanding that as; if `address_has_script ` = true then `payment_cred` = script.hash

Problem Report

```
select count(*) from (
  select
    distinct on (address) address
  from tx_out
  left join script on tx_out.payment_cred = script.hash
  where tx_out.address_has_script = true and script.id is null
) as addresses_with_no_populated_script

count: 7671
```

It seems that 7671 addresses which are marked with `address_has_script` have no script on the `scripts` table

**Comment by kderme** [comment]
Indeed something doesn't add up. I'll investigate further.

**Comment by kderme** [comment]
Actually I think this is not a bug. 
```
Understanding that as; if address_has_script  = true then payment_cred = script.hash
```
This is correct. But when an output locked by a script appears the script may not have appeared in the blockchain yet. The script must appear when the output is **consumed**. The `address_has_script` part is just the declaration of the user that this output is locked by a script. This is not verified until the time the script is actually published.

**Comment by infnada** [comment]
Makes sense :+1: . Feel free to close the issue if there is nothing else to investigate from your side.
