### ISSUE TITLE
blk_count values on epoch table doesn't match with block table itself

### ISSUE THREAD

**Issue by saratomaz** [input-output-hk/cardano-db-sync#1363]
**OS**
Your OS: Ubuntu

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.0.0
PostgreSQL version: 13.6

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: nix

**Additional context**
Testing with cardano-node-tests local cluster

**Problem Report**
The `blk_count` on `epoch` table always returns one block less than the blocks for that epoch found in the `block` table.

`SELECT * FROM block WHERE epoch_no = 35;`
^^ returns 108 rows
**first_block** 2023-02-23 14:57:39.400000
**last_block** 2023-02-23 15:00:57.800000

`SELECT * FROM epoch WHERE no = 35;`
^^ returns a blk_count of 107
**epoch_start_time** 2023-02-23 14:57:39.400000
**epoch_end_time** 2023-02-23 15:00:56

Also, there is a gap between the end and the start time of the next epoch, and the last block is in that gap

`SELECT * FROM epoch WHERE no = 36;`
**Start time of the next epoch** 2023-02-23 15:00:58.400000

**Comment by kderme** [comment]
For some epochs this also happens to mainnet. It could be the result of https://github.com/input-output-hk/cardano-db-sync/issues/1304

**Comment by rdlrt** [comment]
> For some epochs

I think at some point on each network (doesn't seem to be consistent between instances, which suggests the issue could be at specific node or dbsync version updates), the behaviour starts to show up.. and once it does, it continues to stay as such, can be seen on all networks.

The network-wise occurance on few nodesavailable on my end:

|Instance #|Preview|Preprod|Guild|Mainnet|
|:--------:|:--:|:--:|:--:|:--:|
|1|118|47|4842|358|
|2|104|-|4894|348|

SQL query to check when occurance starts (below example is from preprod):

``` sql
SELECT e.no, e.start_time, e.end_time as epoch_end_time, b.end_time as block_end_time FROM epoch e left join (select epoch_no,max(time) as end_time from block group by epoch_no) b ON e.no = b.epoch_no where e.end_time != b.end_time ORDER BY e.no;
#  no |     start_time      |   epoch_end_time    |   block_end_time
# ----+---------------------+---------------------+---------------------
#  47 | 2023-01-22 00:00:10 | 2023-01-26 23:59:29 | 2023-01-26 23:59:34
#  48 | 2023-01-27 00:01:07 | 2023-01-31 23:59:45 | 2023-01-31 23:59:53
#  49 | 2023-02-01 00:00:58 | 2023-02-05 23:59:30 | 2023-02-05 23:59:33
#  50 | 2023-02-06 00:00:07 | 2023-02-10 23:59:52 | 2023-02-10 23:59:57
#  51 | 2023-02-11 00:00:04 | 2023-02-15 23:59:19 | 2023-02-15 23:59:29
#  52 | 2023-02-16 00:00:42 | 2023-02-20 23:57:50 | 2023-02-20 23:58:51
#  53 | 2023-02-21 00:00:29 | 2023-02-25 23:58:57 | 2023-02-25 23:59:15
#  54 | 2023-02-26 00:00:46 | 2023-02-27 23:12:32 | 2023-02-27 23:13:17
# (8 rows)

SELECT e.no, e.blk_count as epoch_blk_count, b.blk_count as block_blk_count FROM epoch e LEFT JOIN (SELECT epoch_no, count(1) as blk_count FROM block GROUP BY epoch_no) b ON b.epoch_no = e.no where e.blk_count != b.blk_count ORDER BY e.no;
#  no | epoch_blk_count | block_blk_count
# ----+-----------------+-----------------
#  47 |           16801 |           16802
#  48 |           17938 |           17939
#  49 |           17921 |           17922
#  50 |           18006 |           18007
#  51 |           17791 |           17792
#  52 |           17312 |           17313
#  53 |           17107 |           17108
#  54 |            6583 |            6584
# (8 rows)
```

**Comment by erikd** [comment]
On my machine:
```
 SELECT e.no, e.blk_count as epoch_blk_count, b.blk_count as block_blk_count FROM epoch e LEFT JOIN (SELECT epoch_no, count(1) as blk_count FROM block GROUP BY epoch_no) b ON b.epoch_no = e.no where e.blk_count != b.blk_count ORDER BY e.no;
cexplorer=# SELECT e.no, e.blk_count as epoch_blk_count, b.blk_count as block_blk_count FROM epoch e LEFT JOIN (SELECT epoch_no, count(1) as blk_count FROM block GROUP BY epoch_no) b ON b.epoch_no = e.no where e.blk_count != b.blk_count ORDER BY e.no;
 no  | epoch_blk_count | block_blk_count 
-----+-----------------+-----------------
 348 |           19977 |           19978
 349 |           20971 |           20972
 350 |           20957 |           20958
 351 |           20892 |           20893
 352 |           20574 |           20575
...
 392 |           20578 |           20579
 393 |           20820 |           20821
 394 |           20235 |           20553
 395 |           21033 |           21034
 396 |           13481 |           13482
(45 rows)
```
Basically every epoch after epoch `347` was wrong.

Deleting all the wrong entries:
```
delete from epoch where no >= 348 ;
```
Running the query above again resulted in zero incorrect entries.

`cardano-db-sync` was started again and when as part of the startup/initialization sequence, it fills in the missing `epoch` table entries. eg
```
[db-sync-node:Info:67] [2023-02-28 02:53:01.40 UTC] epochPluginInsertBlockDetails: epoch 348
[db-sync-node:Info:67] [2023-02-28 02:53:04.18 UTC] epochPluginInsertBlockDetails: epoch 349
[db-sync-node:Info:67] [2023-02-28 02:53:04.96 UTC] epochPluginInsertBlockDetails: epoch 350
[db-sync-node:Info:67] [2023-02-28 02:53:06.80 UTC] epochPluginInsertBlockDetails: epoch 351
```
Running the initial query again and there are zero incorrect entries.

The only caveat with the above is that the first and **all** subsequent incorrect entries but be deleted. The login that check the presence of `epoch` table rows finds the latest epoch and then fills in any missing ones.

So what is going wrong here? Pretty sure its due to #1304 as @kderme suggested. Due the normal network upheaval around epoch boundaries its not unusual for at least one block to be rolled back. This would be why different instances (geographically separated) will see different views of the network due to normal block propagation delays,

Investigating further.

**Comment by erikd** [comment]
From a top level point of view, the solution to this issue is to detect when a rollback is goes back to a the start of an epoch and when it does, delete the `epoch` table row for the previous epoch.

**Comment by erikd** [comment]
I have a relatively neat PR  (above) that should fix this. The epoch roll over is in less than 24 hours so I we will see if it works.

**Comment by erikd** [comment]
Seemed to work over the epoch transition that just happened. Will merge this.

@saratomaz Please keep an eye on this over the next couple of epoch transitions (I will try to do the same) and reopen this ticket its its not fixed.

**Comment by saratomaz** [comment]
@erikd seems solved :+1:
