### ISSUE TITLE
How to find CardanoDBSync snapshots?

### ISSUE THREAD

**Issue by mgajda** [input-output-hk/cardano-db-sync#1369]
**OS**
Your OS: Linux AMD64

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.0
PostgreSQL version: 11.5

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:
IOHK docker images

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker image on Kubernetes

**Additional context**

**Problem Report**

We do not see documentation for where get the CardanoDBSync snapshots from.
IOHK repository seems to have `mainnet` snapshots: https://update-cardano-mainnet.iohk.io/
as described on `cardano-world` patches:
https://github.com/input-output-hk/cardano-world/commit/27af1257f2ce5ca6f80283fe6a63daf9b53dcbf8

Due to slow syncing, it may be recommended to also consider `testnet` snapshots.

`cardano-node` snapshots are much better described on [cSnapshots.io](https://csnapshots.io/about)

If the above source is authoritative, I can make an MR describing it.

May there be a better way?

**Comment by erikd** [comment]
Mainnet snapshots are linked from the releases page: https://github.com/input-output-hk/cardano-db-sync/releases

There are no snapshots for testnet because syncing testnest from genesis is so fast.

**Comment by kamzar1** [comment]
Wrong place.
Took me also a while to find it there.
It belongs to:
https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/state-snapshot.md
Or at least a mention there too.
