### ISSUE TITLE
dbsync stuck at level of last snapshot, not syncing

### ISSUE THREAD

**Issue by kamzar1** [input-output-hk/cardano-db-sync#1372]
OS: Ubuntu 22.04
cardano-db-sync:  13.1.0.0.
PostgreSQL: 14
Same machine as cardano relay node 1.35.5
`cardano@Cardano-R1:~$ cardano-cli query tip --mainnet`

> {
>     "block": 8473896,
>     "epoch": 397,
>     "era": "Babbage",
>     "hash": "5044db6e918766496bedb4f06f0384c87fccfd1afea90d3836d77e6846ba91bc",
>     "slot": 86365089,
>     "syncProgress": "100.00"
> }

**Build/Install Method**

```
apt install postgresql
echo "CREATE USER cardano WITH PASSWORD '****'; ALTER USER cardano with superuser; ALTER USER cardano CREATEDB  \
  CREATEROLE; \q" | psql -U postgres 2> /dev/null || true
echo "CREATE DATABASE csexplorer; \q" | psql -U postgres 2> /dev/null || true
```
***release binaries
```
        url="https://api.github.com/repos/input-output-hk/cardano-db-sync/releases/latest"
        latest="$(wget -q -O - $url | grep tag_name | sed 's/.*: "\(.*\)".*/\1/' | head -n 1)"
        fileName="https://update-cardano-mainnet.iohk.io/cardano-db-sync/cardano-db-sync-"$latest"-linux.tar.gz"
        wget -q -O /tmp/$DIST.tar.gz $fileName
        tar -xzf /tmp/$DIST.tar.gz -C $NODEHOME/.local/bin
```
***config / schema
```
        wget -q -O /tmp/cardano-db-sync.tar.gz https://api.github.com/repos/input-output-hk/cardano-db-sync/tarball
        mkdir -p /tmp/cardano-db-sync
        tar -xzf /tmp/cardano-db-sync.tar.gz  --strip-components=1 -C /tmp/cardano-db-sync
        mv /tmp/cardano-db-sync/config /home/cardano/cardano-db-sync/
        mv /tmp/cardano-db-sync/schema /home/cardano/cardano-db-sync/
        echo "/var/run/postgresql:5432:cexplorer:cardano:*****" > $DBSYNCHOME/config/pgpass-mainnet
        chmod 600 $DBSYNCHOME/config/pgpass-mainnet  
        sed -i 's|^NodeConfigFile.*|NodeConfigFile: ../../config/mainnet/config.json|g' $DBSYNCHOME/config/mainnet-config.yaml
```
**Run method**
systemd, executes:
```
#!/bin/bash
USERNAME="cardano"
NODEHOME=/home/$USERNAME
DBSYNCHOME="$NODEHOME/cardano-db-sync"
export PGPASSFILE="$DBSYNCHOME/config/pgpass-mainnet"
$NODEHOME/.local/bin/cardano-db-sync \
    --config $DBSYNCHOME/config/mainnet-config.yaml \
    --socket-path $NODEHOME/db/socket \
    --state-dir /st1/cardano/db/ledger-state/mainnet \
    --schema-dir $DBSYNCHOME/schema/
```

Applied snapshot:
```
export PGPASSFILE="$DBSYNCHOME/config/pgpass-mainnet"
sh $DBSYNCHOME/scripts/postgresql-setup.sh --dropdb
sh $DBSYNCHOME/scripts/postgresql-setup.sh --createdb
snapshot="/st1/cardano/db/db-sync-snapshot-schema-13.1-block-8462999-x86_64.tgz"
ledger_state="/st1/cardano/db/ledger-state/mainnet/"
sh $DBSYNCHOME/scripts/postgresql-setup.sh --restore-snapshot $snapshot $ledger_state & >/db.log
```

`journalctl -u cardanodbsync.service -f`

> Mar 04 10:46:30 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:6943] [2023-03-04 10:46:30.82 UTC] Running DB thread
> Mar 04 10:46:56 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:6943] [2023-03-04 10:46:56.91 UTC] Delaying delete of 1642                              999 blocks after Just 6820000 while rolling back to (slot 51973406, hash d6b9cc05a15395d7ef08db005263c2b30282a9dfbf12ed0d1cd                              e005b9a835b40). Applying blocks until a new block is found. The node is currently at Tip (SlotNo 86360469) d25eb38b0443fac67                              76ccc9626fd54f80393abfa3be5572ed431f8e12bea9b94 (BlockNo 8473672)
> Mar 04 10:46:56 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:6943] [2023-03-04 10:46:56.92 UTC] Found in memory ledger                               snapshot at slot 51973406, hash d6b9cc05a15395d7ef08db005263c2b30282a9dfbf12ed0d1cde005b9a835b40
> Mar 04 10:46:56 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:6943] [2023-03-04 10:46:56.92 UTC] Setting ConsistencyLeve                              l to DBAheadOfLedger
> Mar 04 11:50:15 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:6943] [2023-03-04 11:50:15.57 UTC] Took a ledger snapshot                               at /st1/cardano/db/ledger-state/mainnet/52012780-1cef8acffe-317.lstate. It took 2792.95597617s.
> Mar 04 11:50:15 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:6943] [2023-03-04 11:50:15.57 UTC] Removing old epoch boun                              dary file /st1/cardano/db/ledger-state/mainnet/49420795-196bf5e4c5-311.lstate

`cardano@Cardano-R1:~$ ls -lh /st1/cardano/db/ledger-state/mainnet/`
total 12G
-rw-r--r-- 1 cardano cardano 1.1G Mar  4 07:25 49852789-237bb60b1a-312.lstate
-rw-r--r-- 1 cardano cardano 1.1G Mar  4 07:51 50284782-7a996976d6-313.lstate
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 08:28 50716752-77290c3664-314.lstate
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 08:45 50907994-ec9d8fa7ab.lstate
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 09:02 51122488-e123fc3871.lstate
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 09:12 51148787-dfe06e13b7-315.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 09:29 51336321-3cf35492b3.lstate
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 09:45 51552201-d823c0a62b.lstate
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 09:56 51580799-51cb6846b5-316.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 10:17 51764400-3b3925b713.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 10:45 51973399-5655321095.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 11:50 52012780-1cef8acffe-317.lstate

```
cexplorer=# select slot_no from block where block_no is not null
    order by block_no desc limit 1 ;
 slot_no
----------
 86141621
(1 row)

cexplorer=# select
   100 * (extract (epoch from (max (time) at time zone 'UTC')) - extract (epoch from (min (time) at time zone 'UTC')))
      / (extract (epoch from (now () at time zone 'UTC')) - extract (epoch from (min (time) at time zone 'UTC')))
  as sync_percent
  from block ;
    sync_percent
---------------------
 99.8708901250154514
(1 row)

cexplorer=# select now () - max (time) as behind_by from block ;
       behind_by
-----------------------
 2 days 13:35:34.13563
(1 row)

cexplorer=# select * from meta ;
 id |     start_time      | network_name |                       version
----+---------------------+--------------+------------------------------------------------------
  1 | 2017-09-23 21:44:51 | mainnet      | Version {versionBranch = [13,0,0], versionTags = []}
(1 row)

cexplorer=# select * from schema_version;
 id | stage_one | stage_two | stage_three
----+-----------+-----------+-------------
  1 |         9 |        25 |           6
(1 row)
```

**Comment by kderme** [comment]
Does it just stop there without any errors? How long is it stopped?

**Comment by kderme** [comment]
Also something seems off. You download a recent snapshot, slot 8462999, but db-sync starts on 51973406.
The snapshot is downloaded to ledger_state="/st2/cardano/db/ledger-state/mainnet/", but you use --state-dir /st1/cardano/db/ledger-state/mainnet \

Possibly a configuration issue

**Comment by kamzar1** [comment]
Indeed, typo with st1/st2. Just fixed that.

I attached two external nvme storages st1 & st2, because instance root not large enough to handle all, cardano relay db, snapshots, unpacking snapshots and postgresql neither by size nor by speed.
So either the config is pointing to that storage or is mounted under /var/lib/postgresql etc.
CPU: 8, Ram: 32G
A syncing from scratch has started and was working.

Only issue is, after applying a snapshot, it is not moving any further from that level, now since almost 3 days.

After importing the snapshot statement and starting db-sync service, it logs, it drops new files in ledger-state/ , and deletes from there, but a queries show, its not adding any new blocks.
`cardano@Cardano-R1:~$ ls -lh /st1/cardano/db/ledger-state/mainnet/`
total 12G
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 09:12 51148787-dfe06e13b7-315.lstate
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 09:56 51580799-51cb6846b5-316.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 11:50 52012780-1cef8acffe-317.lstate
-rw-r--r-- 1 cardano cardano 1.4G Mar  4 13:51 52186579-692d0b12c2.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 15:50 52401756-53f2360950.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 17:00 52444775-f041cf4833-318.lstate
-rw-r--r-- 1 cardano cardano 1.2G Mar  4 18:29 52613171-79e0ce53e6.lstate
-rw-r--r-- 1 cardano cardano 973K Mar  4 18:59 52823074-07f01c5bd4.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 20:06 52876752-af192981f4-319.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 21:54 53035846-c882f7285c.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 23:21 53250070-898729c0b2.lstate
-rw-r--r-- 1 cardano cardano 1.3G Mar  4 23:39 53308780-8ea9407d84-320.lstate
-rw-r--r-- 1 cardano cardano 144M Mar  4 23:51 53462265-5b72830946.lstate


```
cexplorer=# select slot_no from block where block_no is not null
    order by block_no desc limit 1 ;
 slot_no
----------
 86141621
(1 row)

cexplorer=# select now () - max (time) as behind_by from block ;
       behind_by
------------------------
 3 days 01:45:59.917313
(1 row)
```

> Mar 04 23:39:41 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8653] [2023-03-04 23:39:41.72 UTC] Setting ConsistencyLevel to Unchecked
> Mar 04 23:39:41 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8653] [2023-03-04 23:39:41.72 UTC] Starting chainSyncClient
> Mar 04 23:39:41 Cardano-R1 cardanodbsync[181]: [db-sync-node.Subscription:Notice:55] [2023-03-04 23:39:41.81 UTC] Identity Required subscriptions started
> Mar 04 23:39:41 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8653] [2023-03-04 23:39:41.83 UTC] Suggesting intersection points from memory: [At (Block {blockPointSlot = SlotNo 53308809, blockPointHash = 455be5399ed1e48bb3598a0a8a9be2f4eebb74120b3bf8cf6326e347aedf63eb})] and from disk: [At (Block {blockPointSlot = SlotNo 53308780, blockPointHash = 8ea9407d84e0dad7eb281d41a84a292d538575583548e1237db29af677bc9b23}),At (Block {blockPointSlot = SlotNo 53308686, blockPointHash = 6b41d746aa50555d33f77c8d702569f0b1ca4fe9d2422ee5b15c6c18c74b0f4a}),At (Block {blockPointSlot = SlotNo 53250070, blockPointHash = 898729c0b2aee96f01f314468e5cac38f34e9241cf97428658c6565c0c04e82f}),At (Block {blockPointSlot = SlotNo 53035846, blockPointHash = c882f7285c17b46372389e50519afca61c3c34cd859d01457bdb0a162f663710}),At (Block {blockPointSlot = SlotNo 52876752, blockPointHash = af192981f47a4150b4d4f96e2184050699febbbc31de18c3815bb5f338578ff6}),At (Block {blockPointSlot = SlotNo 52823074, blockPointHash = 07f01c5bd41a8f5987d7b697857832d7645878f7632d9d96f1efca731f4977a8}),At (Block {blockPointSlot = SlotNo 52613171, blockPointHash = 79e0ce53e6de6e903f154b7fbf97f98e8fbfe2fd630f8859cb577a6bf4230c4f}),At (Block {blockPointSlot = SlotNo 52444775, blockPointHash = f041cf4833a057855654977df9fbe4f90f65b38c5403cad3d8b61d6015aa40db}),At (Block {blockPointSlot = SlotNo 52401756, blockPointHash = 53f2360950344344863412f36f0984a5d99c32f457d538b043ad719bc23d4365}),At (Block {blockPointSlot = SlotNo 52186579, blockPointHash = 692d0b12c2f60724a7b55c130a723c462b9455b456b6bb99b05f77c3b43635d0}),At (Block {blockPointSlot = SlotNo 52012780, blockPointHash = 1cef8acffe72da132b404da7d3e207e93fbbc6cb21f190bffe0969022e18dd98}),At (Block {blockPointSlot = SlotNo 51580799, blockPointHash = 51cb6846b524e2ace75af09146dec574c9733d84f0f4c582289f9b22bca01d6b}),At (Block {blockPointSlot = SlotNo 51148787, blockPointHash = dfe06e13b7132e91e682903d71a553bca0815bbdf6fb865b0c7a37699f03926d})]
> Mar 04 23:39:41 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8653] [2023-03-04 23:39:41.92 UTC] Cardano.Db tip is at slot 86141621, block 8462999
> Mar 04 23:39:41 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8662] [2023-03-04 23:39:41.92 UTC] Running Offline fetch thread
> Mar 04 23:39:41 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8661] [2023-03-04 23:39:41.92 UTC] Running DB thread
> Mar 04 23:40:05 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8661] [2023-03-04 23:40:05.51 UTC] Delaying delete of 1580202 blocks after Just 6882797 while rolling back to (slot 53308809, hash 455be5399ed1e48bb3598a0a8a9be2f4eebb74120b3bf8cf6326e347aedf63eb). Applying blocks until a new block is found. The node is currently at Tip (SlotNo 86406883) ab0327b11bc1b33b64ddef5f0ae4eb16b84e6f09a22f8f95ac2e92c58486681b (BlockNo 8475857)
> Mar 04 23:40:05 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8661] [2023-03-04 23:40:05.52 UTC] Found in memory ledger snapshot at slot 53308809, hash 455be5399ed1e48bb3598a0a8a9be2f4eebb74120b3bf8cf6326e347aedf63eb
> Mar 04 23:40:05 Cardano-R1 cardanodbsync[181]: [db-sync-node:Info:8661] [2023-03-04 23:40:05.52 UTC] Setting ConsistencyLevel to DBAheadOfLedger

Also I tried a parallel syncing with flag  --disable-ledger in same environment, with pg db. It syncs from scratch and going well, so the overall environment seems intact.

**Comment by kamzar1** [comment]
I have reviewd the procedure, it was somewhere in communities mentioned to clear the folder ../ledger-state/mainnet/ which i did, as assumed, db-sync would produce new files from it's status.

This time I put back the original .lstate from snapshot and started the service again.
No it seems, it is going even farther back in block history:

`ls -lh /st1/cardano/db/ledger-state/mainnet/`
total 323M
-rw-r--r-- 1 cardano cardano 33M Mar  5 02:20 561599-0f7a47cea9-25.lstate
-rw-r--r-- 1 cardano cardano 35M Mar  5 02:22 583199-254851a6b3-26.lstate
-rw-r--r-- 1 cardano cardano 29M Mar  5 02:23 604799-1c26656e73-27.lstate
-rw-r--r-- 1 cardano cardano 31M Mar  5 02:24 626399-535496ca4b-28.lstate
-rw-r--r-- 1 cardano cardano 31M Mar  5 02:24 630074-363bc4f622.lstate
-rw-r--r-- 1 cardano cardano 32M Mar  5 02:25 640074-3393d317d0.lstate
-rw-r--r-- 1 cardano cardano 32M Mar  5 02:25 647999-6a644bf448-29.lstate
-rw-r--r-- 1 cardano cardano 32M Mar  5 02:25 650075-256f806dec.lstate
-rw-r--r-- 1 cardano cardano 33M Mar  5 02:26 660076-94af6ee082.lstate
-rw-r--r-- 1 cardano cardano 33M Mar  5 02:26 669599-b6b7971aad-30.lstate
-rw-r--r-- 1 cardano cardano 33M Mar  5 02:26 670076-20d6a94e1c.lstate
-rw-r--r-- 1 cardano cardano 34M Mar  5 02:27 680076-0bfaf0f855.lstate

`journalctl -u cardanodbsync.service -f`

> Mar 05 02:29:08 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:29:08.02 UTC] Took a ledger snapshot at /st1/cardano/db/ledger-state/mainnet/710079-32c428a448.lstate. It took 1.997888493s.
> Mar 05 02:29:08 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:29:08.02 UTC] Removing old file /st1/cardano/db/ledger-state/mainnet/650075-256f806dec.lstate
> Mar 05 02:29:19 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:29:19.63 UTC] Took a ledger snapshot at /st1/cardano/db/ledger-state/mainnet/712799-7984bc3c8b-32.lstate. It took 2.506424938s.
> Mar 05 02:29:19 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:29:19.63 UTC] Removing old epoch boundary file /st1/cardano/db/ledger-state/mainnet/583199-254851a6b3-26.lstate
> Mar 05 02:29:44 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:29:44.94 UTC] Took a ledger snapshot at /st1/cardano/db/ledger-state/mainnet/720083-c99bc4c75e.lstate. It took 2.120456736s.
> Mar 05 02:29:44 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:29:44.94 UTC] Removing old file /st1/cardano/db/ledger-state/mainnet/660076-94af6ee082.lstate
> Mar 05 02:30:19 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:30:19.03 UTC] Took a ledger snapshot at /st1/cardano/db/ledger-state/mainnet/730084-d09748d6c7.lstate. It took 2.498340383s.
> Mar 05 02:30:19 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:30:19.03 UTC] Removing old file /st1/cardano/db/ledger-state/mainnet/670076-20d6a94e1c.lstate
> Mar 05 02:30:34 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:30:34.13 UTC] Took a ledger snapshot at /st1/cardano/db/ledger-state/mainnet/734399-5fd0c2cc69-33.lstate. It took 2.009320578s.
> Mar 05 02:30:34 Cardano-R1 cardanodbsync[9599]: [db-sync-node:Info:66] [2023-03-05 02:30:34.13 UTC] Removing old epoch boundary file /st1/cardano/db/ledger-state/mainnet/604799-1c26656e73-27.lstate

**Comment by kderme** [comment]
There's probably a configuration issue. DBSync doesn't see the downloaded snapshot so it starts from genesis. Please follow the release notes https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.1.0.0

**Comment by kamzar1** [comment]
cardano-db-sync: 13.1.0.0: "This release is compatible with Cardano Node 1.35.4"
I am running 1.35.5. Could that be an issue?


> There's probably a configuration issue. DBSync doesn't see the downloaded snapshot ..

How it sees a downloaded snapshot? A reference in database?
Or is it the snapshot  .lstate dropped in ../ledger-state/mainnet/ ?

**Comment by kderme** [comment]
The `--state-dir` needs to contain the ledger snapshot that you restored

**Comment by kamzar1** [comment]
> Mar 05 18:30:45 Cardano-R1 cardanodbsync[15189]: [db-sync-node:Info:63] [2023-03-05 18:30:45.82 UTC] Starting chainSyncClient
> Mar 05 18:30:45 Cardano-R1 cardanodbsync[15189]: [db-sync-node:Info:63] [2023-03-05 18:30:45.82 UTC] Suggesting intersection points from memory: [] and from disk: [At (Block {blockPointSlot = SlotNo 86141621, blockPointHash = ba86368c058dd79b2697c4ef9cc4a3b748079ad038040262b85b8ae533c89b33})]
> Mar 05 18:30:45 Cardano-R1 cardanodbsync[15189]: [db-sync-node:Info:63] [2023-03-05 18:30:45.83 UTC] Cardano.Db tip is at slot 86141621, block 8462999

...

> Mar 05 18:30:46 Cardano-R1 cardanodbsync[15189]: [db-sync-node:Info:71] [2023-03-05 18:30:46.01 UTC] Delaying delete of 0 blocks after Just 8462999 while rolling back to (slot 86141621, hash ba86368c058dd79b2697c4ef9cc4a3b748079ad038040262b85b8ae533c89b33).
> Applying blocks until a new block is found. The node is currently at Tip (SlotNo 86474754) 668e6d2d549bd1fb8b73040dd64d59ba798c239e76c59ef1bc29165e97da9e76 (BlockNo 8479172)

...

> Mar 05 18:45:26 Cardano-R1 cardanodbsync[15189]: [db-sync-node:Warning:71] [2023-03-05 18:45:26.32 UTC] Failed to parse ledger state file **/st1/cardano/db/ledger-state/mainnet/86141621-ba86368c05.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 1217855894 "end of input")'. Deleting it.**
> Mar 05 18:45:26 Cardano-R1 cardanodbsync[15189]: [db-sync-node:Warning:71] [2023-03-05 18:45:26.32 UTC] Rollback failed. No more ledger state files.
> Mar 05 18:45:26 Cardano-R1 cardanodbsync[15189]: [db-sync-node:Info:71] [2023-03-05 18:45:26.32 UTC] Setting ConsistencyLevel to DBAheadOfLedger

**Comment by erikd** [comment]
@kamzar1 The message:

> /st1/cardano/db/ledger-state/mainnet/86141621-ba86368c05.lstate with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 1217855894 "end of input")'. Deleting it.

Is part of the normal behavior of `db-sync`. If it fails to open a ledger state file it will delete it an try to open the previous one.
