### ISSUE TITLE
Static binary download still missing for version 13.1.0.2

### ISSUE THREAD

**Issue by liv-io** [input-output-hk/cardano-db-sync#1391]
Dear cardano-db-sync team,

Apologies for creating an issue for this, but I didn't know how to get in touch otherwise.
The title basically says it all. The [download link in the latest release](https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.1.0.2) is still saying `TODO`.

```
Static binaries download
TODO
```

It would be great if someone could update and provide the latest build for this release.

Many thanks!

**Comment by kderme** [comment]
The link has been added in the release page https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.1.0.2

**Comment by liv-io** [comment]
Thank you
