### ISSUE TITLE
Add support for new cost models representation in Alonzo genesis file

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-db-sync#1392]
**OS**
Your OS: Fedora 37

**Versions**
The `db-sync` version: d06207415358e2efd713e4d24b0f096413c80329, 13.1.0.2
PostgreSQL version: 14.6

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: `nix build`

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): none

**Problem Report**
In PR https://github.com/input-output-hk/cardano-node/pull/5013, the cost model format changed to list, like
```
{
  "costModels": {
    "PlutusV1": [
      205665,
      812,
      1,
      1,
      1000,
      ...
```
db-sync currently don't support this new format, and fails to start with:

> Failed reading Alonzo genesis file "./state-cluster0/shelley/genesis.alonzo.json": There was an error parsing the genesis file: ./state-cluster0/shelley/genesis.alonzo.json Error: Error in $.costModels.PlutusV1: parsing Map ~Text failed, expected Object, but encountered Array

**Comment by kderme** [comment]
Fixed with https://github.com/input-output-hk/cardano-db-sync/pull/1403
