### ISSUE TITLE
cardano-db-sync-extended fails to sync past first epoch

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-db-sync#14]
```
[db-sync-node:Info:37] [2020-03-05 17:40:12.20 UTC] Total supply at start of epoch 0 is 41999999999.999903 Ada
[db-sync-node:Info:37] [2020-03-05 17:41:14.62 UTC] Total supply at start of epoch 1 is 41999999999.999903 Ada
[db-sync-node:Info:37] [2020-03-05 17:41:14.62 UTC] insertABOBBoundary: epoch 1 hash 73e68ae83ee19defc2bfc21c14cbc5e7c83868f21883a218753324453ae07777
[db-sync-node:Info:37] [2020-03-05 17:41:14.62 UTC] epochPluginInsertBlock: Epoch table updated for epoch 0
[db-sync-node:Error:37] [2020-03-05 17:41:14.63 UTC] Unable to query epoch number 0
[db-sync-node:Info:37] [2020-03-05 17:41:14.63 UTC] Shutting down DB thread
[db-sync-node:Error:41] [2020-03-05 17:41:14.68 UTC] recvMsgRollForward: AsyncCancelled
```

the process is still running, but the logs say it has given up and halted?
it fails the same way upon wiping everything and restarting (edited) 
switching to the non-extended db-sync appears to have fixed syncing

**Comment by erikd** [comment]
Only the `extended` version of `db-sync` uses `epochPluginInsertBlock` and that is where the error is.

I suspect that a change in the network data types has messed with the logic of the `extended` functionality.

**Comment by erikd** [comment]
Having troible reproducing this. I am on commit `6c574eab01` and ran:

```
./scripts/postgresql-setup.sh --recreatedb
PGPASSFILE=config/pgpass ./cardano-db-sync-extended.exe --config config/explorer-mainnet-config.yaml --genesis-file ../cardano-node/mainnet-genesis.json --socket-path ../cardano-node/state-node-mainnet/node.socket --schema-dir schema/
```

and it synced the first three epoch without a problem.

**Comment by erikd** [comment]
The query that builds an row for the `Epoch` table incorrectly assumes that each epoch has at least one transaction. That assumption holds for mainnet but does not hold in general.
