### ISSUE TITLE
db-sync stale snapshots

### ISSUE THREAD

**Issue by Ilia-TheNetworkFirm** [input-output-hk/cardano-db-sync#1405]
On https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#13.1 page there are only stale snapshots (11 days ago) but according the docs the snapshots should be published every epoch ~ every 5 days

I would expect 2 more snapshots during that period of time

**Comment by ArturWieczorek** [comment]
@jbgi Can you please look into that ?

**Comment by jbgi** [comment]
snapshots are back now. Thank you for reporting the issue.
