### ISSUE TITLE
[Docker]  Issue with `--disable-ledger` option for release `13.1.1.0`

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-db-sync#1409]
### Context:

In previous releases `cardano-db-sync` always required to use `--state-dir` with option `disable-ledger` and now with new release `13.1.1.0` it is fixed and when using `--disable-ledger` option `state-dir` should NOT be specified anymore otherwise it will result in error and service shut down.

### Problem description:

This change is causing an issue with docker.

When starting docker with:

`NETWORK=preprod EXTRA_DB_SYNC_ARGS="--disable-ledger" docker compose up && docker compose logs -f
`

It will result in:

> docker compose logs cardano-db-sync
> cardano-db-sync-cardano-db-sync-1  | /run/secrets
> cardano-db-sync-cardano-db-sync-1  | Generating PGPASS file
> cardano-db-sync-cardano-db-sync-1  | Connecting to network: preprod
> cardano-db-sync-cardano-db-sync-1  | cardano-db-sync: Error: Using `--disable-ledger` doesn't require having a --state-dir. For more details view https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/configuration.md#--disable-ledger
> cardano-db-sync-cardano-db-sync-1  | CallStack (from HasCallStack):
> cardano-db-sync-cardano-db-sync-1  |   error, called at app/cardano-db-sync.hs:30:28 in main:Main
> cardano-db-sync-cardano-db-sync-1  | Connecting to network: preprod
> cardano-db-sync-cardano-db-sync-1  | cardano-db-sync: Error: Using `--disable-ledger` doesn't require having a --state-dir. For more details view https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/configuration.md#--disable-ledger

because option `--state-dir` is always used inside docker.

One of the proposed solution is to change error in favor of ignoring it with a warning.

**Comment by ArturWieczorek** [comment]
CC: @kderme @Cmdv

**Comment by Cmdv** [comment]
Thanks @ArturWieczorek will look into this, I'm not 100% sure of the docker expectations for this project but it will certainly error out if it always requires `--state-dir`.

Ideally it should also be an option rather than hard coded which I can see here: https://github.com/input-output-hk/cardano-db-sync/blob/aed18d1be192bd58d054cdba23758b579dae9f4e/nix/docker.nix#L141 

Will report with proposed solution 👍

**Comment by Cmdv** [comment]
From internal discussions it was agreed this is now going to become a warning rather than an error. 😄
