### ISSUE TITLE
Ledger state is replayed from genesis of ledger state file cannot be decoded.

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#1425]
**OS**
Your OS: Debian Linux

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.1.1
PostgreSQL version: 15.3-0

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: cabal build

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): none

**Problem Report**
If the `db-sync` is started and the ledger-state decode fails eg:
```
[2023-05-31 21:35:04.27 UTC] Failed to parse ledger state file ledger-state/mainnet/93916791-b08a0e3447-414.lstate
  with error 'DecoderErrorDeserialiseFailure "Ledger state file" (DeserialiseFailure 3 "Size mismatch when decoding 
  decodePast.\nExpected 2, but found 3.")'. Deleting it.
```
the ledger state file is deleted. If all the ledger state files are deleted, then ledger state is replayed from genesis.

Replaying ledger state from genesis is initially really fast, but by the time the replay gets to about epoch 350, each epoch is taking an hour or more. Since we are currently at epoch 415, this is at least 2.5 days just to replay the ledger. This is sub optimal.

I suspect this is due to a change in the CBOR serialization in `ledger` or `consensus`.

**Comment by erikd** [comment]
@kderme informs me that this is mentioned in the release notes. However that still does not prevent it being a huge pain in the neck.

I wonder it it would be possible to version the CBOR serialization and then have it always support two versions; the current and the previous.

**Comment by erikd** [comment]
Yeah, this machine (a VM) was memory constrained. however with my async ledger state write commit the problem went away. I suspect that was because the time to write the file was removed, meaning local chain sync was less likely to disconnect and then reconnect.

**Comment by kderme** [comment]
Cool then, thanks for checking this out. Closing.
