### ISSUE TITLE
Allow to run docker without `--state-dir`

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1430]
db-sync can be executed with `--disable-ledger` which disables the ledger state. When it is on the `state-dir` option shouldn't be provided, since the directory is not needed to store snapshots. Release 13.1.1.0 initially crashed correctly if both options were enabled, but due to an issue with docker https://github.com/input-output-hk/cardano-db-sync/issues/1409 the crash was replaced by a warning in 13.1.1.2 and master

It would be great to have a way to run db-sync from docker with `--disable-ledger`, but without the `state-dir` option set.

**Comment by sgillespie** [comment]
The usual way to do this in docker would be to define an environment variable, say `DISABLE_LEDGER`, and then interpret this in the entrypoint, eg:
```
if [[ "${DISABLE_LEDGER:+}" ]]; then
    EXTRA_ARGS="--disable-ledger"
else
    EXTRA_ARGS="--state-dir stateDir"
fi
```
