### ISSUE TITLE
error in tag of docker 

### ISSUE THREAD

**Issue by manupadillaph** [input-output-hk/cardano-db-sync#1434]
I just download latest release 13.1.1.2-docker, and try to do compose the docker, with `docker-compose up -d && docker-compose logs -f`

I got this error:
```
[+] Running 1/1
 ✘ cardano-db-sync Error                                                                                                                1.5s 
Error response from daemon: manifest for inputoutput/cardano-db-sync:13.1.1.2 not found: manifest unknown: manifest unknown
```

I went in the hub of input output: https://hub.docker.com/r/inputoutput/cardano-db-sync/tags

And the tag for the image needed in the docker compose file: `inputoutput/cardano-db-sync:13.1.1.2`  does not exist.

Exist instead: `inputoutput/cardano-db-sync:13.1.1.2-docker`

I just replace it in `docker-compose.yml` file and I was able to compose the Docker

**Comment by kderme** [comment]
I think this is fixed, as docker compose now mentions, 13.1.1.3
