### ISSUE TITLE
Remove cardano-api dependency

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1453]
db-sync mainly uses directly the ledger and the ledger-api. However it still depends on cardano-api on some parts. Cardano-api has recently moved to a separate repository https://github.com/input-output-hk/cardano-api and it's questionable how fast it will be upgraded after node is released. We should try to completely drop our dependency to it, so that it doesn't block future node integrations.

**Comment by rdlrt** [comment]
Interesting, I thought node & CLI had strong dependency on cardano-api, so the work on cardano-api would be locked prior to node being tagged
