### ISSUE TITLE
DB Sync keeps choking on migration-4-0001-20200702.sql

### ISSUE THREAD

**Issue by wout** [input-output-hk/cardano-db-sync#1454]
**OS**
Your OS: Ubuntu 20.04

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.1.2
PostgreSQL version: 14.5

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Dockerfile

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
Postgres config:
- `shared_buffers = 8GB`
- `work_mem = 2GB`
- `maintenance_work_mem = 4GB`
- `max_wal_size = 16GB`
- `min_wal_size = 4GB`
- `wal_level = minimal`
- `max_wal_senders = 0`
- `wal_buffers = 16GB`

Server:
- AMD Ryzen 9 5950X (32) @ 3.400GHz
- 128GB RAM
- 2x 1.92TB Gen 4 NMVe datacenter edition (RAID1)

**Problem Report**
I'm setting up a new db-sync instance. It's fully synced, but now it keeps on crashing on the same migration (index for address in tx_out):

```
Running : migration-1-0000-20190730.sql
 init 
------
 
(1 row)

Running : migration-4-0001-20200702.sql
psql:/nix/store/8karnsk27jxnp00r94zkzvjsrx34s0b9-schema/migration-4-0001-20200702.sql:3: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
psql:/nix/store/8karnsk27jxnp00r94zkzvjsrx34s0b9-schema/migration-4-0001-20200702.sql:3: connection to server was lost
ExitFailure 2
```

I'm using the same Postgres config modifications as with previous instances and never had this issue.  Should I adjust the settings?

**Comment by kderme** [comment]
Is you postgres server running? Also are you running db-sync with `--force-indexes`?
This index creation takes normally quite some time
`CREATE INDEX IF NOT EXISTS idx_tx_out_address ON tx_out USING hash (address);`

You could try to stop db-sync, delete this line from the schema file in question `migration-4-0001-20200702.sql` and start again.

**Comment by wout** [comment]
> Is you postgres server running?

Yes, it's managed by Docker Swarm, and it's running as it should. It exists on that migration after a bit under 3 hours of execution.

> Also are you running db-sync with --force-indexes?

No. db-sync just is just continuing its default procedure. No special flags.

> This index creation takes normally quite some time

Yeah, I remember from previous syncs. Hashing ~196 million records is a lot. 🙂️

> You could try to stop db-sync, delete this line from the schema file in question migration-4-0001-20200702.sql and start again.

I'll try that next time it fails. I've pushed `maintenance_work_mem` and `shared_buffers` to 16GB now, and it just crossed 3h of execution time, which I haven't seen before.

I was thinking. Would it be a good idea to create this index at the start of the sync? I mean, for the next instance I set up of course.

**Comment by wout** [comment]
Just crashed again. I'm going to try without that particular index. But I'll need it eventually because I use it a lot.

**Comment by kderme** [comment]
> I was thinking. Would it be a good idea to create this index at the start of the sync? I mean, for the next instance I set up of course.

Yes this is possible, you can add it to a new phase 3 file.
Have you monitored the thread doing the work? What is you `max_parallel_maintenance_workers`?

**Comment by wout** [comment]
Executing it in the container worked. It's up and running now. So it should have been something in the internal connection between containers. But it worked before on the same machine with the same setup. So something is different. Maybe it's good to move this particular migration to stage 3 anyway?

> What is you max_parallel_maintenance_workers?

That's at the default value now (`2`, I believe).

Now that it's running, what do you advise for the postgres config?

- `shared_buffers = 8GB`
- `work_mem = 2GB`
- `maintenance_work_mem = 4GB`
- `max_wal_size = 16GB`
- `min_wal_size = 4GB`
- `wal_level = minimal`
- `max_wal_senders = 0`
- `wal_buffers = 16GB`
