### ISSUE TITLE
Wrong tx_count and blk_count numbers in the epoch table

### ISSUE THREAD

**Issue by dmitrystas** [input-output-hk/cardano-db-sync#1457]
**OS**
Your OS: Debian 11

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.0.2
PostgreSQL version: 15
 
**Build/Install Method**
The method you use to build or install `cardano-db-sync`: binaries download

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): systemd

**Additional context**
A snapshot (https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#13.1/) was used

**Problem Report**
Almost all rows in the table `epoch` have wrong tx_count and blk_count. Usually they differ by 1 block

 ```
SELECT COUNT(*) AS tx_count, COUNT(distinct block.id) AS blk_count
FROM block
LEFT JOIN tx ON tx.block_id = block.id
WHERE block.epoch_no = 386;

  tx_count | blk_count
----------+-----------
    429066 |     20893
(1 row)


SELECT tx_count, blk_count
FROM epoch
WHERE no = 386;

  tx_count | blk_count
----------+-----------
    428477 |     20892
(1 row)
```

but for some epochs it looks even more strange

```
SELECT COUNT(*) AS tx_count, COUNT(distinct block.id) AS blk_count
FROM block
LEFT JOIN tx ON tx.block_id = block.id
WHERE block.epoch_no = 387;

 tx_count | blk_count
----------+-----------
   389880 |     21065
(1 row)


SELECT tx_count, blk_count
FROM epoch
WHERE no = 387;

 tx_count | blk_count
----------+-----------
    1303  |       43
(1 row)

```

**Comment by Fell-x27** [comment]
I have the same problem.

**Comment by Fell-x27** [comment]
Here is a table showing inconsistent data. Everything is accurate up until entry 348, but after that, the data is almost always incorrect.

| no | count in blocks table | count in epochs table | deviation |
| :--- | :--- | :--- | :--- |
| 0 | 21587 | 21587 | 0 |
| 1 | 21590 | 21590 | 0 |
| 2 | 21599 | 21599 | 0 |
| 3 | 21598 | 21598 | 0 |
| 4 | 21601 | 21601 | 0 |
| 5 | 21599 | 21599 | 0 |
| 6 | 21601 | 21601 | 0 |
| 7 | 21600 | 21600 | 0 |
| 8 | 21601 | 21601 | 0 |
| 9 | 21601 | 21601 | 0 |
| 10 | 21601 | 21601 | 0 |
| 11 | 21594 | 21594 | 0 |
| 12 | 21600 | 21600 | 0 |
| 13 | 21599 | 21599 | 0 |
| 14 | 21600 | 21600 | 0 |
| 15 | 21597 | 21597 | 0 |
| 16 | 21599 | 21599 | 0 |
| 17 | 21598 | 21598 | 0 |
| 18 | 21601 | 21601 | 0 |
| 19 | 21597 | 21597 | 0 |
| 20 | 21601 | 21601 | 0 |
| 21 | 21599 | 21599 | 0 |
| 22 | 21596 | 21596 | 0 |
| 23 | 21599 | 21599 | 0 |
| 24 | 21600 | 21600 | 0 |
| 25 | 21594 | 21594 | 0 |
| 26 | 21600 | 21600 | 0 |
| 27 | 21600 | 21600 | 0 |
| 28 | 21601 | 21601 | 0 |
| 29 | 21600 | 21600 | 0 |
| 30 | 21600 | 21600 | 0 |
| 31 | 21601 | 21601 | 0 |
| 32 | 21598 | 21598 | 0 |
| 33 | 21596 | 21596 | 0 |
| 34 | 21594 | 21594 | 0 |
| 35 | 21600 | 21600 | 0 |
| 36 | 21601 | 21601 | 0 |
| 37 | 21600 | 21600 | 0 |
| 38 | 21601 | 21601 | 0 |
| 39 | 21599 | 21599 | 0 |
| 40 | 21599 | 21599 | 0 |
| 41 | 21597 | 21597 | 0 |
| 42 | 21599 | 21599 | 0 |
| 43 | 21599 | 21599 | 0 |
| 44 | 21601 | 21601 | 0 |
| 45 | 21599 | 21599 | 0 |
| 46 | 21598 | 21598 | 0 |
| 47 | 21600 | 21600 | 0 |
| 48 | 21601 | 21601 | 0 |
| 49 | 21583 | 21583 | 0 |
| 50 | 21563 | 21563 | 0 |
| 51 | 21599 | 21599 | 0 |
| 52 | 21599 | 21599 | 0 |
| 53 | 21599 | 21599 | 0 |
| 54 | 21597 | 21597 | 0 |
| 55 | 21599 | 21599 | 0 |
| 56 | 21600 | 21600 | 0 |
| 57 | 21601 | 21601 | 0 |
| 58 | 21600 | 21600 | 0 |
| 59 | 21589 | 21589 | 0 |
| 60 | 21600 | 21600 | 0 |
| 61 | 21598 | 21598 | 0 |
| 62 | 21595 | 21595 | 0 |
| 63 | 21591 | 21591 | 0 |
| 64 | 21591 | 21591 | 0 |
| 65 | 21588 | 21588 | 0 |
| 66 | 21587 | 21587 | 0 |
| 67 | 21590 | 21590 | 0 |
| 68 | 21569 | 21569 | 0 |
| 69 | 21591 | 21591 | 0 |
| 70 | 21588 | 21588 | 0 |
| 71 | 21589 | 21589 | 0 |
| 72 | 21590 | 21590 | 0 |
| 73 | 21587 | 21587 | 0 |
| 74 | 21558 | 21558 | 0 |
| 75 | 21590 | 21590 | 0 |
| 76 | 21594 | 21594 | 0 |
| 77 | 21585 | 21585 | 0 |
| 78 | 21582 | 21582 | 0 |
| 79 | 21589 | 21589 | 0 |
| 80 | 21587 | 21587 | 0 |
| 81 | 21586 | 21586 | 0 |
| 82 | 21588 | 21588 | 0 |
| 83 | 21593 | 21593 | 0 |
| 84 | 20686 | 20686 | 0 |
| 85 | 21584 | 21584 | 0 |
| 86 | 21588 | 21588 | 0 |
| 87 | 21586 | 21586 | 0 |
| 88 | 21597 | 21597 | 0 |
| 89 | 21595 | 21595 | 0 |
| 90 | 21601 | 21601 | 0 |
| 91 | 21601 | 21601 | 0 |
| 92 | 21601 | 21601 | 0 |
| 93 | 21601 | 21601 | 0 |
| 94 | 21600 | 21600 | 0 |
| 95 | 21601 | 21601 | 0 |
| 96 | 21600 | 21600 | 0 |
| 97 | 21599 | 21599 | 0 |
| 98 | 21601 | 21601 | 0 |
| 99 | 21600 | 21600 | 0 |
| 100 | 21601 | 21601 | 0 |
| 101 | 21599 | 21599 | 0 |
| 102 | 21601 | 21601 | 0 |
| 103 | 21601 | 21601 | 0 |
| 104 | 21600 | 21600 | 0 |
| 105 | 21600 | 21600 | 0 |
| 106 | 21601 | 21601 | 0 |
| 107 | 21601 | 21601 | 0 |
| 108 | 21594 | 21594 | 0 |
| 109 | 21601 | 21601 | 0 |
| 110 | 21599 | 21599 | 0 |
| 111 | 21601 | 21601 | 0 |
| 112 | 21598 | 21598 | 0 |
| 113 | 21601 | 21601 | 0 |
| 114 | 21601 | 21601 | 0 |
| 115 | 21599 | 21599 | 0 |
| 116 | 21601 | 21601 | 0 |
| 117 | 21597 | 21597 | 0 |
| 118 | 21601 | 21601 | 0 |
| 119 | 21600 | 21600 | 0 |
| 120 | 21597 | 21597 | 0 |
| 121 | 21601 | 21601 | 0 |
| 122 | 21600 | 21600 | 0 |
| 123 | 21600 | 21600 | 0 |
| 124 | 21590 | 21590 | 0 |
| 125 | 21600 | 21600 | 0 |
| 126 | 21601 | 21601 | 0 |
| 127 | 21601 | 21601 | 0 |
| 128 | 21601 | 21601 | 0 |
| 129 | 21601 | 21601 | 0 |
| 130 | 21599 | 21599 | 0 |
| 131 | 21601 | 21601 | 0 |
| 132 | 21601 | 21601 | 0 |
| 133 | 21600 | 21600 | 0 |
| 134 | 21599 | 21599 | 0 |
| 135 | 21601 | 21601 | 0 |
| 136 | 21601 | 21601 | 0 |
| 137 | 21601 | 21601 | 0 |
| 138 | 21601 | 21601 | 0 |
| 139 | 21601 | 21601 | 0 |
| 140 | 21601 | 21601 | 0 |
| 141 | 21599 | 21599 | 0 |
| 142 | 21601 | 21601 | 0 |
| 143 | 21600 | 21600 | 0 |
| 144 | 21601 | 21601 | 0 |
| 145 | 21601 | 21601 | 0 |
| 146 | 21600 | 21600 | 0 |
| 147 | 21601 | 21601 | 0 |
| 148 | 21601 | 21601 | 0 |
| 149 | 21599 | 21599 | 0 |
| 150 | 21601 | 21601 | 0 |
| 151 | 21601 | 21601 | 0 |
| 152 | 21601 | 21601 | 0 |
| 153 | 21600 | 21600 | 0 |
| 154 | 21601 | 21601 | 0 |
| 155 | 21601 | 21601 | 0 |
| 156 | 21601 | 21601 | 0 |
| 157 | 21600 | 21600 | 0 |
| 158 | 21601 | 21601 | 0 |
| 159 | 21601 | 21601 | 0 |
| 160 | 21085 | 21085 | 0 |
| 161 | 21601 | 21601 | 0 |
| 162 | 21601 | 21601 | 0 |
| 163 | 21601 | 21601 | 0 |
| 164 | 21601 | 21601 | 0 |
| 165 | 21601 | 21601 | 0 |
| 166 | 21601 | 21601 | 0 |
| 167 | 21601 | 21601 | 0 |
| 168 | 21601 | 21601 | 0 |
| 169 | 21601 | 21601 | 0 |
| 170 | 21601 | 21601 | 0 |
| 171 | 21601 | 21601 | 0 |
| 172 | 21601 | 21601 | 0 |
| 173 | 21601 | 21601 | 0 |
| 174 | 21577 | 21577 | 0 |
| 175 | 21600 | 21600 | 0 |
| 176 | 21600 | 21600 | 0 |
| 177 | 21600 | 21600 | 0 |
| 178 | 21600 | 21600 | 0 |
| 179 | 21597 | 21597 | 0 |
| 180 | 21600 | 21600 | 0 |
| 181 | 21600 | 21600 | 0 |
| 182 | 21600 | 21600 | 0 |
| 183 | 21600 | 21600 | 0 |
| 184 | 21600 | 21600 | 0 |
| 185 | 21587 | 21587 | 0 |
| 186 | 21600 | 21600 | 0 |
| 187 | 21596 | 21596 | 0 |
| 188 | 21600 | 21600 | 0 |
| 189 | 21597 | 21597 | 0 |
| 190 | 21600 | 21600 | 0 |
| 191 | 21600 | 21600 | 0 |
| 192 | 21599 | 21599 | 0 |
| 193 | 21600 | 21600 | 0 |
| 194 | 21598 | 21598 | 0 |
| 195 | 21559 | 21559 | 0 |
| 196 | 21600 | 21600 | 0 |
| 197 | 21597 | 21597 | 0 |
| 198 | 21600 | 21600 | 0 |
| 199 | 21589 | 21589 | 0 |
| 200 | 21600 | 21600 | 0 |
| 201 | 21543 | 21543 | 0 |
| 202 | 21596 | 21596 | 0 |
| 203 | 21600 | 21600 | 0 |
| 204 | 21600 | 21600 | 0 |
| 205 | 21600 | 21600 | 0 |
| 206 | 21591 | 21591 | 0 |
| 207 | 21544 | 21544 | 0 |
| 208 | 21556 | 21556 | 0 |
| 209 | 21570 | 21570 | 0 |
| 210 | 21547 | 21547 | 0 |
| 211 | 21315 | 21315 | 0 |
| 212 | 21280 | 21280 | 0 |
| 213 | 21442 | 21442 | 0 |
| 214 | 21452 | 21452 | 0 |
| 215 | 21572 | 21572 | 0 |
| 216 | 21217 | 21217 | 0 |
| 217 | 20728 | 20728 | 0 |
| 218 | 20511 | 20511 | 0 |
| 219 | 21427 | 21427 | 0 |
| 220 | 21627 | 21627 | 0 |
| 221 | 21547 | 21547 | 0 |
| 222 | 21466 | 21466 | 0 |
| 223 | 21374 | 21374 | 0 |
| 224 | 21324 | 21324 | 0 |
| 225 | 21298 | 21298 | 0 |
| 226 | 21439 | 21439 | 0 |
| 227 | 21125 | 21125 | 0 |
| 228 | 21171 | 21171 | 0 |
| 229 | 21229 | 21229 | 0 |
| 230 | 21244 | 21244 | 0 |
| 231 | 21089 | 21089 | 0 |
| 232 | 21149 | 21149 | 0 |
| 233 | 21065 | 21065 | 0 |
| 234 | 21046 | 21046 | 0 |
| 235 | 21203 | 21203 | 0 |
| 236 | 20915 | 20915 | 0 |
| 237 | 21440 | 21440 | 0 |
| 238 | 21245 | 21245 | 0 |
| 239 | 21258 | 21258 | 0 |
| 240 | 21428 | 21428 | 0 |
| 241 | 21399 | 21399 | 0 |
| 242 | 21418 | 21418 | 0 |
| 243 | 21586 | 21586 | 0 |
| 244 | 21491 | 21491 | 0 |
| 245 | 21485 | 21485 | 0 |
| 246 | 21327 | 21327 | 0 |
| 247 | 21508 | 21508 | 0 |
| 248 | 21356 | 21356 | 0 |
| 249 | 21376 | 21376 | 0 |
| 250 | 20991 | 20991 | 0 |
| 251 | 21324 | 21324 | 0 |
| 252 | 21085 | 21085 | 0 |
| 253 | 20922 | 20922 | 0 |
| 254 | 20713 | 20713 | 0 |
| 255 | 21268 | 21268 | 0 |
| 256 | 21059 | 21059 | 0 |
| 257 | 20836 | 20836 | 0 |
| 258 | 21021 | 21021 | 0 |
| 259 | 20796 | 20796 | 0 |
| 260 | 21047 | 21047 | 0 |
| 261 | 21087 | 21087 | 0 |
| 262 | 21194 | 21194 | 0 |
| 263 | 21111 | 21111 | 0 |
| 264 | 21127 | 21127 | 0 |
| 265 | 21427 | 21427 | 0 |
| 266 | 21404 | 21404 | 0 |
| 267 | 21702 | 21702 | 0 |
| 268 | 21413 | 21413 | 0 |
| 269 | 21509 | 21509 | 0 |
| 270 | 21395 | 21395 | 0 |
| 271 | 21410 | 21410 | 0 |
| 272 | 21499 | 21499 | 0 |
| 273 | 21464 | 21464 | 0 |
| 274 | 21521 | 21521 | 0 |
| 275 | 21505 | 21505 | 0 |
| 276 | 21298 | 21298 | 0 |
| 277 | 21323 | 21323 | 0 |
| 278 | 21352 | 21352 | 0 |
| 279 | 21404 | 21404 | 0 |
| 280 | 21204 | 21204 | 0 |
| 281 | 21411 | 21411 | 0 |
| 282 | 21452 | 21452 | 0 |
| 283 | 21412 | 21412 | 0 |
| 284 | 21517 | 21517 | 0 |
| 285 | 21201 | 21201 | 0 |
| 286 | 21504 | 21504 | 0 |
| 287 | 21065 | 21065 | 0 |
| 288 | 21136 | 21136 | 0 |
| 289 | 21195 | 21195 | 0 |
| 290 | 21320 | 21320 | 0 |
| 291 | 21261 | 21261 | 0 |
| 292 | 21264 | 21264 | 0 |
| 293 | 21243 | 21243 | 0 |
| 294 | 20960 | 20960 | 0 |
| 295 | 21081 | 21081 | 0 |
| 296 | 20849 | 20849 | 0 |
| 297 | 21168 | 21168 | 0 |
| 298 | 20840 | 20840 | 0 |
| 299 | 20982 | 20982 | 0 |
| 300 | 21225 | 21225 | 0 |
| 301 | 20989 | 20989 | 0 |
| 302 | 21203 | 21203 | 0 |
| 303 | 20948 | 20948 | 0 |
| 304 | 21095 | 21095 | 0 |
| 305 | 21025 | 21025 | 0 |
| 306 | 21141 | 21141 | 0 |
| 307 | 20910 | 20910 | 0 |
| 308 | 21033 | 21033 | 0 |
| 309 | 20804 | 20804 | 0 |
| 310 | 21045 | 21045 | 0 |
| 311 | 21090 | 21090 | 0 |
| 312 | 20821 | 20821 | 0 |
| 313 | 20267 | 20267 | 0 |
| 314 | 20390 | 20390 | 0 |
| 315 | 20182 | 20182 | 0 |
| 316 | 20141 | 20141 | 0 |
| 317 | 20478 | 20478 | 0 |
| 318 | 20284 | 20284 | 0 |
| 319 | 20414 | 20414 | 0 |
| 320 | 20284 | 20284 | 0 |
| 321 | 20096 | 20096 | 0 |
| 322 | 20393 | 20393 | 0 |
| 323 | 20573 | 20573 | 0 |
| 324 | 20380 | 20380 | 0 |
| 325 | 20541 | 20541 | 0 |
| 326 | 20534 | 20534 | 0 |
| 327 | 20346 | 20346 | 0 |
| 328 | 20579 | 20579 | 0 |
| 329 | 20353 | 20353 | 0 |
| 330 | 20685 | 20685 | 0 |
| 331 | 20704 | 20704 | 0 |
| 332 | 20391 | 20391 | 0 |
| 333 | 20290 | 20290 | 0 |
| 334 | 20232 | 20232 | 0 |
| 335 | 20446 | 20446 | 0 |
| 336 | 20500 | 20500 | 0 |
| 337 | 20794 | 20794 | 0 |
| 338 | 20640 | 20640 | 0 |
| 339 | 20678 | 20678 | 0 |
| 340 | 20670 | 20670 | 0 |
| 341 | 20708 | 20708 | 0 |
| 342 | 20990 | 20990 | 0 |
| 343 | 20994 | 20994 | 0 |
| 344 | 20776 | 20776 | 0 |
| 345 | 21030 | 21030 | 0 |
| 346 | 20578 | 20578 | 0 |
| 347 | 19345 | 19345 | 0 |
| 348 | 19978 | 19977 | 1 |
| 350 | 20958 | 20957 | 1 |
| 349 | 20972 | 20971 | 1 |
| 352 | 20575 | 20574 | 1 |
| 351 | 20893 | 20892 | 1 |
| 353 | 20232 | 20231 | 1 |
| 355 | 20825 | 20824 | 1 |
| 354 | 20498 | 20497 | 1 |
| 356 | 20782 | 20781 | 1 |
| 357 | 20692 | 20691 | 1 |
| 361 | 21242 | 21241 | 1 |
| 370 | 21170 | 21169 | 1 |
| 358 | 21169 | 21168 | 1 |
| 386 | 20893 | 20892 | 1 |
| 393 | 20821 | 20820 | 1 |
| 363 | 21361 | 21360 | 1 |
| 391 | 21084 | 36 | 21048 |
| 367 | 20902 | 20901 | 1 |
| 376 | 20525 | 20524 | 1 |
| 379 | 20948 | 20947 | 1 |
| 403 | 20893 | 20892 | 1 |
| 378 | 21006 | 21005 | 1 |
| 401 | 20869 | 20868 | 1 |
| 394 | 20553 | 20552 | 1 |
| 383 | 20917 | 46 | 20871 |
| 384 | 20998 | 20998 | 0 |
| 385 | 21174 | 21174 | 0 |
| 400 | 21062 | 21061 | 1 |
| 372 | 21095 | 21094 | 1 |
| 366 | 21098 | 21097 | 1 |
| 365 | 21027 | 21026 | 1 |
| 359 | 21023 | 21022 | 1 |
| 395 | 21034 | 21033 | 1 |
| 368 | 21103 | 21102 | 1 |
| 364 | 20964 | 20963 | 1 |
| 380 | 21270 | 21269 | 1 |
| 377 | 21014 | 21013 | 1 |
| 362 | 21266 | 21265 | 1 |
| 375 | 20731 | 20730 | 1 |
| 387 | 21065 | 43 | 21022 |
| 374 | 20881 | 20880 | 1 |
| 369 | 21048 | 21047 | 1 |
| 371 | 20982 | 20981 | 1 |
| 360 | 21226 | 21225 | 1 |
| 382 | 21186 | 21185 | 1 |
| 373 | 21095 | 21094 | 1 |
| 399 | 20970 | 20969 | 1 |
| 388 | 21194 | 21193 | 1 |
| 390 | 20916 | 20915 | 1 |
| 381 | 20976 | 20975 | 1 |
| 392 | 20579 | 20578 | 1 |
| 397 | 21003 | 21002 | 1 |
| 396 | 21174 | 21173 | 1 |
| 389 | 20811 | 20811 | 0 |
| 398 | 21190 | 21189 | 1 |
| 402 | 21128 | 21127 | 1 |
| 404 | 20828 | 20827 | 1 |
| 425 | 5735 | 5734 | 1 |
| 424 | 21035 | 21034 | 1 |
| 423 | 20898 | 20897 | 1 |
| 409 | 21000 | 20999 | 1 |
| 406 | 20954 | 20953 | 1 |
| 407 | 21107 | 21106 | 1 |
| 408 | 21176 | 21175 | 1 |
| 405 | 20811 | 20810 | 1 |
| 418 | 21066 | 20996 | 70 |
| 416 | 21143 | 21142 | 1 |
| 410 | 20933 | 20932 | 1 |
| 417 | 20947 | 20946 | 1 |
| 415 | 20820 | 20819 | 1 |
| 412 | 20966 | 20965 | 1 |
| 420 | 20649 | 20648 | 1 |
| 413 | 21252 | 21251 | 1 |
| 411 | 21418 | 21417 | 1 |
| 414 | 21215 | 21214 | 1 |
| 419 | 20685 | 20684 | 1 |
| 421 | 20907 | 20906 | 1 |
| 422 | 21026 | 21025 | 1 |

**Comment by Fell-x27** [comment]
@kderme , please, look at this. There is something wrong.

**Comment by kderme** [comment]
This table had many issues, especially on previous releases. It didn't handle rollbacks well. 

Good news is that this table has no genuine data, it's the result of querying other data. It's correct values can be created through other queries which for example count the txs, the number of blocks etc from all blocks of an epoch.

**Comment by Fell-x27** [comment]
>This table had many issues, especially on previous releases.

Well, I'm using 13.1.0.2, the latest version, and I'm experiencing this problem. Also, there wasn't a problem before the 348th epoch, but it didn't go away afterward...

**Comment by erikd** [comment]
@Fell-x27 wrote:
> But is this the only problematic table?

Well the `epoch` table is a derived table. It does not take data from the block chain or from ledger state. The `epoch` table is populated by queries that aggregate data from other tables. Therefore it could easily be possible for this table to be incorrect and all other tables be correct.

However, it any other tables are incorrect, it should be possible to write queries that show inconsistencies like you did for this table. If you can find any inconsistencies I am sure the maintainers would be every interested to see them.

@kderme wrote:
> This table had many issues, especially on previous releases.

In comparison to the current release?

@kderme wrote:
> It didn't handle rollbacks well.

That may well be true, but was it really worse that what we have now?

**Comment by erikd** [comment]
Ok, I have come up with a query that prints out the block count and tx count for each epoch and adds a column that specifies if they match.
```
select b.epoch_no, e.epoch_blk_count, e.epoch_tx_count, b.block_block_count, b.block_tx_count,
    e.epoch_blk_count = b.block_block_count and e.epoch_tx_count = b.block_tx_count as bad_row
  from
    (select no, blk_count as epoch_blk_count, tx_count as epoch_tx_count from epoch) as e,
    (select epoch_no, count (block_no) as block_block_count, sum (tx_count) as block_tx_count
      from block group by epoch_no) as b
    where e.no = b.epoch_no ;
```
On my system this show that:
* The block count in the epoch table is to high by `1` for all epochs up until epoch `176` (the Byron epoch boundary block is incorrectly being counted as a block).
* From epoch `348` to `363` the block count and tx count in the `epoch` table is low.
* The entry for epoch `349` is totally missing.
* Epoch `391`, `383`, `387` are all way out.
* Epoch `417` to `421` are all correct.

Since this table only contains derived data, it should be possible to write an update query to fix this.

**Comment by dmitrystas** [comment]
> Epoch 417 to 421 are all correct.
Does this mean that it's no longer the issue for the latest DB-Sync?

**Comment by erikd** [comment]
@dmitrystas Sorry, not sure. Wait and see I suppose.

I am working to put together a update query to fix the current entries (but that probably will not happen until tomorrow).

**Comment by erikd** [comment]
To fine rows that are incorrect:
```sql
select b.epoch_no, e.epoch_blk_count, e.epoch_tx_count, b.block_block_count, b.block_tx_count
  from
    (select no, blk_count as epoch_blk_count, tx_count as epoch_tx_count from epoch) as e,
    (select epoch_no, count (block_no) as block_block_count, sum (tx_count) as block_tx_count
      from block group by epoch_no) as b
    where e.no = b.epoch_no
      and (e.epoch_blk_count != b.block_block_count or e.epoch_tx_count != b.block_tx_count)
    order by b.epoch_no ;
```
The row for epoch `405` can be fixed using:
```sql
with agg_table as
  ( select
      min (block.epoch_no) as epoch_no,
      sum (tx.out_sum) as out_sum,
      sum (tx.fee) as fee_sum,
      min (block.time) as start_time,
      max (block.time) as end_time,
      count (tx.id) as tx_count,
      count (distinct block.block_no) as blk_count
    from
      block left join tx
    on
      block.id = tx.block_id
    where
      block.epoch_no = 405
  )
update epoch
  set
    out_sum = agg_table.out_sum,
    fees = agg_table.fee_sum,
    tx_count = agg_table.tx_count,
    blk_count = agg_table.blk_count,
    start_time = agg_table.start_time,
    end_time = agg_table.end_time
  from
    agg_table
  where
    no = agg_table.epoch_no ;
 ```

**Comment by erikd** [comment]
A rough and ready shell script to find and fix all entries (assumes the `pgpass-mainnet` is local
```bash
#!/bin/bash -eu

export PGDATABASE=cexplorer
export PGPASSFILE=cardano-db-sync/config/pgpass-mainnet

raw_epochs=$(
  psql << EOF
select b.epoch_no
  from
    (select no, blk_count as epoch_blk_count, tx_count as epoch_tx_count from epoch) as e,
    (select epoch_no, count (block_no) as block_block_count, sum (tx_count) as block_tx_count
      from block group by epoch_no) as b
    where e.no = b.epoch_no
      and (e.epoch_blk_count != b.block_block_count or e.epoch_tx_count != b.block_tx_count)
    order by b.epoch_no ;
EOF
  )

epochs=$(echo ${raw_epochs} | sed 's/epoch_no ---------- //;s/(.* rows)//')

for epoch in ${epochs[@]} ; do
  echo "Fixing ${epoch}"
  # psql --command=
  psql << EOF
      with agg_table as
        ( select
            min (block.epoch_no) as epoch_no,
            sum (tx.out_sum) as out_sum,
            sum (tx.fee) as fee_sum,
            min (block.time) as start_time,
            max (block.time) as end_time,
            count (tx.id) as tx_count,
            count (distinct block.block_no) as blk_count
          from
            block left join tx
          on
            block.id = tx.block_id
          where
            block.epoch_no = ${epoch}
        )
      update epoch
        set
          out_sum = agg_table.out_sum,
          fees = agg_table.fee_sum,
          tx_count = agg_table.tx_count,
          blk_count = agg_table.blk_count,
          start_time = agg_table.start_time,
          end_time = agg_table.end_time
        from
          agg_table
        where
          no = agg_table.epoch_no ;
EOF
  done
```

**Comment by Cmdv** [comment]
I'm pretty sure I hit the exact same scenario when adding cache capabilities to epochs in https://github.com/input-output-hk/cardano-db-sync/pull/1433 with epochs pre `176` being miscounted and fixed it [here](https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync/Epoch.hs#L180 )
Though this hasn't been released yet and will only work when starting fresh.

**Comment by erikd** [comment]
@dmitrystas Can this issue be closed now?
