### ISSUE TITLE
Release 13.1.1.3 is missing Static binaries

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1469]
We also want to automate the procedure of creating these binaries.

**Comment by kderme** [comment]
This seems fixed https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.1.1.3?

**Comment by sgillespie** [comment]
> This seems fixed https://github.com/input-output-hk/cardano-db-sync/releases/tag/13.1.1.3?

I manually added them, but I'm still working on the automation
