### ISSUE TITLE
Asset table missing data

### ISSUE THREAD

**Issue by YuXiaoCoder** [input-output-hk/cardano-db-sync#1495]
**OS**
Your OS: Ubuntu 20.04 Docker

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.1.3
PostgreSQL version: 12.16

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: docker

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): docker

**Additional context**
I recovered the data using the latest snapshot, and when the recovery was complete, the "public"." Asset" table has no data.
Snapshot link:
https://update-cardano-mainnet.iohk.io/cardano-db-sync/13.1/db-sync-snapshot-schema-13.1-block-9218537-x86_64.tgz

**Problem Report**
```bash
explorer=# SELECT count(*) FROM "public"."Asset";
 count
-------
     0
(1 row)
```

**Comment by kderme** [comment]
There is no "Asset" table created by db-sync. I believe this is created by cardano-graphql

**Comment by YuXiaoCoder** [comment]
I'm using cardano-graphql version 8.0.0, but the cardano-graphql-background logs keep getting stuck here, what is the reason for this?
```log
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"Db","msg":"Initializing...","time":"2023-08-31T17:37:26.731Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"HasuraBackgroundClient","msg":"Initializing","time":"2023-08-31T17:37:26.740Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"HasuraBackgroundClient","msg":"Initialized","time":"2023-08-31T17:44:03.337Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"MetadataFetchClient","msg":"Initializing","time":"2023-08-31T17:44:03.338Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"MetadataFetchClient","msg":"Initialized","time":"2023-08-31T17:44:03.733Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"ChainFollower","msg":"Initializing","time":"2023-08-31T17:44:03.733Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"ChainFollower","msg":"Initialized","time":"2023-08-31T17:44:03.741Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"Worker","msg":"Starting","time":"2023-08-31T17:44:03.742Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"Worker","msg":"Started","time":"2023-08-31T17:44:03.790Z","v":0}
{"name":"background","hostname":"ada-0-0","pid":2400,"level":30,"module":"ChainFollower","msg":"Starting","time":"2023-08-31T17:44:03.801Z","v":0}
```

**Comment by kderme** [comment]
This looks like a cardano-graphql issue which can be raised at https://github.com/cardano-foundation/cardano-graphql

**Comment by YuXiaoCoder** [comment]
thanks, https://github.com/cardano-foundation/cardano-graphql/issues/850
