### ISSUE TITLE
sancho-1-1-0 is not building

### ISSUE THREAD

**Issue by crypto-titan** [input-output-hk/cardano-db-sync#1503]
![image](https://github.com/input-output-hk/cardano-db-sync/assets/17948972/8f39d088-1988-4486-bfd8-1a492464b5c1)

**Comment by kderme** [comment]
There is an issue with building the tests, which has is fixed https://github.com/input-output-hk/cardano-db-sync/pull/1498/commits/0cd10d7c5cacb5aaaf59b045d368465eae61533d. This shouldn't be needed to build the actual executable. eg
```
cabal build cardano-db-sync
nix build -v .#cardano-db-sync -o db-sync-node
```

**Comment by crypto-titan** [comment]
ty!
