### ISSUE TITLE
Can't be from other era

### ISSUE THREAD

**Issue by stefiix92** [input-output-hk/cardano-db-sync#1505]
**OS**
Your OS: Amazon Linux 2 - docker container

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.1.3
PostgreSQL version: 14.5

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: -

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
db-sync container throws an error on the 83rd epoch (sync until then was fine) on `sanchonet`. I use cardano-node 8.3.1-pre docker container

**Problem Report**
```
ChainSyncWithBlocksPtcl: reapplyBlockLedgerResult: can't be from other era
CallStack (from HasCallStack):
  error, called at src/ouroboros-consensus/Ouroboros/Consensus/HardFork/Combinator/Ledger.hs:201:11 in ouroboros-consensus-0.6.0.0-GWbWF5pAqFDFUWzuziqkyk:Ouroboros.Consensus.HardFork.Combinator.Ledger
  reapplyBlockLedgerResult, called at src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Extended.hs:163:9 in ouroboros-consensus-0.6.0.0-GWbWF5pAqFDFUWzuziqkyk:Ouroboros.Consensus.Ledger.Extended
  reapplyBlockLedgerResult, called at src/ouroboros-consensus/Ouroboros/Consensus/Ledger/Abstract.hs:154:17 in ouroboros-consensus-0.6.0.0-GWbWF5pAqFDFUWzuziqkyk:Ouroboros.Consensus.Ledger.Abstract
```

**Comment by kderme** [comment]
13.1.1.3 doesn't support sanchonet and neither does any official release. You can check latest tag `sancho-1-1-0` for this.

**Comment by stefiix92** [comment]
I can't see this tag in the docker hub: https://hub.docker.com/r/inputoutput/cardano-db-sync/tags
that's why I picked the closest one.

**Comment by kderme** [comment]
You can try https://github.com/input-output-hk/cardano-db-sync/pkgs/container/cardano-db-sync/127245093?tag=sancho-1-1-0

**Comment by stefiix92** [comment]
Works with the mentioned docker image 👍
