### ISSUE TITLE
Speed up the prune migration

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1511]
Let's say we run the `prune` migration on a db which is close to being fully synced. The prune migration initially runs the consumed migrations, which marks all consumed `tx_out` and then it deletes all the old enough `tx_out`. It could become faster by directly deleting the old enough consumed `tx_out`, instead of doint it in 2 steps.
So instead of running in `runExtraMigrations`
```
migrateTxOut
deleteConsumedTxOut
```

These can be run as
```
deleteConsumedTxOut' -- different from the above
migrateTxOut
```

**Comment by Cmdv** [comment]
@kderme just a couple of question for clarification:

`runExtraMigrations` happens [here](https://github.com/input-output-hk/cardano-db-sync/blob/164f43f506928156e7336a34a47b0b177623468c/cardano-db-sync/src/Cardano/DbSync.hs#L187) inside of `runSyncNode` which happens once. `deleteConsumedTxOut` happens at an interval of every epoch [here](https://github.com/input-output-hk/cardano-db-sync/blob/164f43f506928156e7336a34a47b0b177623468c/cardano-db-sync/src/Cardano/DbSync/Default.hs#L182).

1. Is the idea to `deleteConsumedTxOut` just before `runExtraMigrations`?

2. If so you mention the function [deleteConsumedTxOut](https://github.com/input-output-hk/cardano-db-sync/blob/164f43f506928156e7336a34a47b0b177623468c/cardano-db/src/Cardano/Db/Migration/Extra/CosnumedTxOut/Queries.hs#L205) should be different how so?

**Comment by kderme** [comment]
Other usages of `deleteConsumedTxOut` shouldn't be affected by this. Only 1 of the 2 usages of `deleteConsumedTxOut` in `runExtraMigrations` should change its behaviour. Basically it should work without the need of running `migrateTxOut` and creating the extra column before it.
