### ISSUE TITLE
Analyzing Performance Differences: Cardano-DB-Sync 13.0.5 vs. 13.1.1.3 - What's Causing the 10-Minute Delay?

### ISSUE THREAD

**Issue by erikmaide** [input-output-hk/cardano-db-sync#1537]
<img width="1090" alt="Screen Shot 2023-10-19 at 11 17 07" src="https://github.com/input-output-hk/cardano-db-sync/assets/49160389/898b948f-b546-45db-941a-62d357877f94">
**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 13.1.1.3
PostgreSQL version: 11.18-alpine

**Additional context**
I have this query in sql
`SELECT 
  "txOut"."value" , 
  "maTxOut"."quantity"
FROM  "block" "blocks" 
  INNER JOIN "tx" "tx" ON "tx"."block_id" = "blocks"."id" 
  INNER JOIN "tx_out" "txOut" ON "txOut"."tx_id" = "tx"."id" 
  INNER JOIN "ma_tx_out" "maTxOut" ON "maTxOut"."tx_out_id" = "txOut"."id" 
  LEFT JOIN "tx_metadata" "txMetadata" ON "txMetadata"."tx_id" = "tx"."id" 
WHERE   "maTxOut"."ident" = 8043843 
  AND tx.script_size = '8842' 
  AND "txOut"."stake_address_id" IS NOT NULL 
  AND "txOut"."value" > 10000000 
  AND "txOut"."address_has_script" = TRUE 
  ORDER BY 
  "blocks"."time" DESC 
LIMIT 
  1`
 

**Problem Report**

With cardano-db-sync 13.0.5 it took 600ms, to get the result which should be none( empty fields), but with the version 13.1.1.3  it takes over 10 minutes, what  changes are causing this issue

The analyze screenshot is done with version 13.0.5, with version 13.1.1.3 it will time out in PSequel

**Comment by kderme** [comment]
I haven't been through all the details, but it's usually missing indexes. We have a policy to keep only necessary indexes and users can add their own.

**Comment by erikmaide** [comment]
Yes that was the issue
