### ISSUE TITLE
Failed reading Conway genesis file: key "poolVotingThresholds" not found"

### ISSUE THREAD

**Issue by MattJE9601** [input-output-hk/cardano-db-sync#1538]
**OS**
Your OS: Ubuntu 22.04 (Proxmox container)

**Versions**
The `db-sync` version: 13.1.1.3
PostgreSQL version: 14.9
Cardano node version: 8.1.1

**Build/Install Method**
Nix

**Run method**
None

**Additional context**
I'm getting an error 'failed reading conway genesis file'.  The file exists but there's almost nothing in it for mainnet.  Not an expert here so forgive me if this is something simple.  Internet searches have been no help.

Got config files from here: https://book.world.dev.cardano.org/environments.html

**Problem Report**
cardano-db-sync: Error SNErrConwayConfig: Failed reading Conway genesis file "/root/cardano-db-sync/config/../../cardano-mainnet/conway-genesis.json": "There was an error parsing the genesis file: /root/cardano-db-sync/config/../../cardano-mainnet/conway-genesis.json Error: Error in $: key \"poolVotingThresholds\" not found"

**Comment by sgillespie** [comment]
@MattJE9601 Are you using the released version, or do you have it checked out from master?

**Comment by MattJE9601** [comment]
Using latest 13.1.1.3.

**Comment by MattJE9601** [comment]
Tried removing the lines in the config but then the node won't start.  I'll start over, maybe I just did something wrong.  Appreciate the help!

**Comment by MattJE9601** [comment]
Checked out from master instead of using release and it's working now.  Not sure if that made the difference or if I did something wrong but it's working so that's what matters.  Thanks again!
