### ISSUE TITLE
Epoch table showing ID that does not match epoch entry

### ISSUE THREAD

**Issue by Willburn** [input-output-hk/cardano-db-sync#1545]
**OS**
Your OS:
Linux

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):
2.0.1

PostgreSQL version:
14.9

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:
Nix build.

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):
systemd.

**Additional context**

**Problem Report**
Please do not include screenshots or images, but instead cut and paste any relevant log messages
or errors.
in table epoch the id of entry 130 and 131 are 133 and 143 while the rest of the epoch id tables all follow by the entry number. Is this correct?

**Comment by kderme** [comment]
ids are autoincremental and created by Postgres. Postgres ensures their uniqueness but it's possible to find gaps. It can happen for many reasons, rollbacks, inserts that didn't materialise due to unique keys etc

**Comment by Willburn** [comment]
Gotcha thanks. Feel free to close.
