### ISSUE TITLE
[sancho] Store Governance Proposals in json format

### ISSUE THREAD

**Issue by mesudip** [input-output-hk/cardano-db-sync#1553]
**Versions**
[sancho-2-2-0](https://github.com/input-output-hk/cardano-db-sync/releases/tag/sancho-2-2-0)

**Problem Report**

Governance Proposal details are currently saved as string in following format using `Show`.

```
NewConstitution SNothing (Constitution {constitutionAnchor = Anchor {anchorUrl = Url {urlToText = "https://bit.ly/3zCH2HL"}, anchorData
Hash = SafeHash "1111111111111111111111111111111111111111111111111111111111111113"}, constitutionScript = SNothing})
```

This data cannot be easily parsed by frontend. Using json format will help.

**Comment by kderme** [comment]
Thanks, indeed it's a good idea to use the json format. Many of these fields are currently used as placeholders and are not very useful.

**Comment by cardanians** [comment]
this is very important and I join this request.

**Comment by kderme** [comment]
What kind of json format would be useful? I could use the existing json instances from the ledger team for the GovAction type https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs#L550. Some examples

```
{"contents":[null,{"major":10,"minor":11}],"tag":"HardForkInitiation"}
```
```
{"contents":[null,[{"keyHash":"db1bc3c3f99ce68977ceaf27ab4dd917123ef9e73f85c304236eeab3"}],{"keyHash-db1bc3c3f
99ce68977ceaf27af4dd917123ef9e73f85c304236eeab2":400,"scriptHash-db1bc3c3f99ce68977ceaf27ab4dd917123ef9e73f85c304236eeab3":300},0.4],"tag":"UpdateCommittee"
```
```
{"contents":null,"tag":"NoConfidence"}
```
```
{"tag":"InfoAction"}
```
```
{"contents":[null,{"anchor":{"dataHash":"1111111111111111111111111111111111111111111111111111111111111111","url":"1111111111111111111111111111111111111111111111111111111111111111"}}],"tag":"NewConstitution"}
```

Note that  "tag" matches the type of the action and contents the other metadata.

**Comment by iccicci** [comment]
+1 on @mesudip's proposal

**Comment by kderme** [comment]
@mesudip fair points we'll do most of these, thank you.

> prevGovActionId is missing in the governance_action. Is it deliberately leaved? It might be quieried by joining governance_action with the tx and block but I am not sure. We may also have nullable column prev_gov_action in the governance_action that will be set to null for info and treasuryWithdraw proposal types.

prevGovActionId is not added because I'm not sure it's needed. It helps the ledger apply the rules correctly, but does it add anything else?

**Comment by cexplorer** [comment]
@kderme prevGovActionId would be nice to have

**Comment by kderme** [comment]
I think most issues in this issue are resolved in https://github.com/input-output-hk/cardano-db-sync/pull/1573
- governance_action is renamed to gov_action_proposal
- a new gov_action_proposal.prev_gov_action_proposal is added
- gov_action_proposal.description now uses a json format, using the FromJSON format from the leedger repository.
- new_committee.quorum is replaced by new_committee.quorum_nominator and new_committee.quorum_denominator

Please reopen or open a new issue if something should be added
