### ISSUE TITLE
sancho column naming mess

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#1554]
sancho [2.0.0]

1) m x mm:

tables: co**mm**ittee_
column: voting_procedure.co**m**ittee_

2) doublecheck cold x hot key hashes:

committee_de_registration.**hot_key** column is probably "**cold_key**" value instead **hot_key**

**Comment by kderme** [comment]
1. is fixed in sancho 2.2.0
2. this is indeed a bug

Please use 2.2.0 as it fixes bugs found in 2.0.0 https://github.com/input-output-hk/cardano-db-sync/blob/ffde876ad45ffacf644b985c8843a46596a28e77/cardano-db-sync/CHANGELOG.md#sancho-220

**Comment by cardanians** [comment]
@kderme perfect thanks for fast response

**Comment by cardanians** [comment]
@kderme FYI

build with cabal and tag 2-2-0 is stuck on "[db-sync-node:Info:59] [2023-11-07 09:22:58.55 UTC] Reached EpochNo 130"  

cardano-node: cardano-node 8.6.0

**Comment by kderme** [comment]
Any chance your is also stuck?

**Comment by cardanians** [comment]
> Any chance your node is also stuck?

unfortunately not

**Comment by cardanians** [comment]
> Any chance your node is also stuck?

aah, sorry, true! db-sync works
