### ISSUE TITLE
[sancho] `drep_always_no_confidence` and `drep_always_abstain` have the same hash

### ISSUE THREAD

**Issue by gabrielKerekes** [input-output-hk/cardano-db-sync#1560]
**Versions**
The `db-sync` version: `sancho-2-2-0`

**Problem Report**
As the title mentions - `drep_always_no_confidence` and `drep_always_abstain` have the same hash (`\x00000000000000000000000000000000000000000000000000000000`) in the `drep_hash` database table. This means that to properly distinguish the DRep the address has delegated to we need to also `SELECT` the `view` column of the `drep_hash` table. Or is there some other way to get the DRep the address has delegated to?

Are there plans to change these two dRep hashes or will they stay the same on mainnet as well?

**Comment by kderme** [comment]
I think this will stay as is. `drep_always_no_confidence` and `drep_always_abstain` dont' have a hash and this is just a placeholder.

**Comment by Cmdv** [comment]
They seem to be hardcoded [here](https://github.com/input-output-hk/cardano-db-sync/blob/sancho-2-2-0/cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Insert.hs#L1580) right now. My assumption this is just a place holder for now but @kderme should be able to clarify

**Comment by gabrielKerekes** [comment]
Ok, so the only way to distinguish the two DReps is via the `view` column, right? Or maybe we could hardcode the `drep_hash_id`s on our end, but that seems a bit fragile.

**Comment by kderme** [comment]
Note that the behaviour has slightly changes with https://github.com/input-output-hk/cardano-db-sync/pull/1573. There are no hardcoded placeholder values any more. drep_hash.raw is now null for always abstan/no confidence. The way to tell these apart is still the view field, which is hardcoded `drep_always_abstain` and `drep_always_no_confidence`.
