### ISSUE TITLE
governance_action.description content format change request

### ISSUE THREAD

**Issue by iccicci** [input-output-hk/cardano-db-sync#1568]
**OS**
Your OS: Linux

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 2.2.0

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: Docker image

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
In [governance_action schema documentation](https://github.com/input-output-hk/cardano-db-sync/blob/sancho-2-2-0/doc/schema.md#governance_action) is stated that the content of the column in subject is in a readable format.

**Problem Report**
Looking at some some example records it seems the content of the column is concatenation of a string describing the Governance Action with the serialization of a complex data.

Speaking with @Cmdv I learned that a new specific table for Governance Action description may be added in the future, in that case this could probably be ignored.

Otherwise I would suggest to change the content of the given column in a single JSON somethin like:
```
{
  "governane_action_description": ${complex_data},
  "any_other_interesting_attribute_1": ${value_1},
  "any_other_interesting_attribute_2": ${value_2},
  ...
}
```

Thank you

**Comment by Cmdv** [comment]
going to close this issue as there seems to already be a discussion on this matter here -> https://github.com/input-output-hk/cardano-db-sync/issues/1553
