### ISSUE TITLE
Unable to Build cardano-db-sync and cardano-db-sync-extended

### ISSUE THREAD

**Issue by djalillounis** [input-output-hk/cardano-db-sync#161]
Hello Team,

I am  having some error to build thecardano-db-sync and cardano-db-sync-extended  v 2.0.0
When I run cabal install cardano-db-sync-extended
I have this error:
Building library for cborg-0.2.3.0..
[ 1 of 14] Compiling Codec.CBOR.ByteArray.Internal ( src/Codec/CBOR/ByteArray/Internal.hs, dist/build/Codec/CBOR/ByteArray/Internal.o )
[ 2 of 14] Compiling Codec.CBOR.ByteArray.Sliced ( src/Codec/CBOR/ByteArray/Sliced.hs, dist/build/Codec/CBOR/ByteArray/Sliced.o )
[ 3 of 14] Compiling Codec.CBOR.ByteArray ( src/Codec/CBOR/ByteArray.hs, dist/build/Codec/CBOR/ByteArray.o )
[ 4 of 14] Compiling Codec.CBOR.Decoding ( src/Codec/CBOR/Decoding.hs, dist/build/Codec/CBOR/Decoding.o )
[ 5 of 14] Compiling Codec.CBOR.Encoding[boot] ( src/Codec/CBOR/Encoding.hs-boot, dist/build/Codec/CBOR/Encoding.o-boot )
[ 6 of 14] Compiling Codec.CBOR.FlatTerm[boot] ( src/Codec/CBOR/FlatTerm.hs-boot, dist/build/Codec/CBOR/FlatTerm.o-boot )
[ 7 of 14] Compiling Codec.CBOR.Encoding ( src/Codec/CBOR/Encoding.hs, dist/build/Codec/CBOR/Encoding.o )
[ 8 of 14] Compiling Codec.CBOR.Magic ( src/Codec/CBOR/Magic.hs, dist/build/Codec/CBOR/Magic.o )

src/Codec/CBOR/Magic.hs:569:9: error:
    Ambiguous occurrence ‘copyByteArrayToPtr’
    It could refer to either ‘Prim.copyByteArrayToPtr’,
                             imported from ‘Data.Primitive.ByteArray’ at src/Codec/CBOR/Magic.hs:103:1-49
                          or ‘Codec.CBOR.Magic.copyByteArrayToPtr’,
                             defined at src/Codec/CBOR/Magic.hs:597:1
    |
569 |         copyByteArrayToPtr ba off ptr len
    |         ^^^^^^^^^^^^^^^^^^
cabal: Failed to build cborg-0.2.3.0 (which is required by exe:cardano-db-sync
from cardano-db-sync-2.0.0). See the build log above for details.

**Comment by mnaboka** [comment]
i am observing similar issue, according to previous build logs, `cborg` was not built before, but now for some reason it was added.

**Comment by erikd** [comment]
My understanding is that this problem only occurs when building the `2.0.0` tag.

The fix is to add `index-state: 2020-04-01T00:00:00Z` as the first line of `cabal.project` (this line has already been added on `master`).

**Comment by mnaboka** [comment]
@erikd i was able to fix this by running `cabal v2-update`, 2.0.0 tag works 🤷
