### ISSUE TITLE
Can't find rewards of my delegators

### ISSUE THREAD

**Issue by Proxiweb** [input-output-hk/cardano-db-sync#168]
In the database, I've found my pool, delegators of my pool but not rewards of delegators ( by addr_id found in the delegation table for my pool )

**Comment by erikd** [comment]
Please provide the SQL queries you are using.

**Comment by Proxiweb** [comment]
select * from pool where hash='\xf784138ce22b62919022ca3439bef0b0d25518da4427bc5beabf4334';
=> 3 pools with the same hash, only the first has delegations
select * from delegation where pool_id = 124;

select * from stake_address left join delegation on stake_address.id=delegation.addr_id where pool_id=124;

=> 5 results
the first one is pool's owner addr_id = 22878;
"581de00115d7c23fd22a60d4306fe148752b41a71256c103465cd2e631c10a"

cardano-cli shelley query stake-address-gives  
 
    "581de00115d7c23fd22a60d4306fe148752b41a71256c103465cd2e631c10a": {
        "delegation": "f784138ce22b62919022ca3439bef0b0d25518da4427bc5beabf4334",
        "rewardAccountBalance": 1539770088234
    }

but "select * from reward where addr_id = 22878;" gives nothing

**Comment by erikd** [comment]
I have a work-in-progress branch at `erikd/pool-fix` . This splits the `pool` table into two separate tables `pool_hash` and `pool_update` and all other foreign references point to the `pool_hash`. 

Hopefully this makes more sense. Comments welcome.

**Comment by erikd** [comment]
```
shelley-test=# select * from pool_hash where hash='\xf784138ce22b62919022ca3439bef0b0d25518da4427bc5beabf4334';
 id  |                            hash                            
-----+------------------------------------------------------------
 105 | \xf784138ce22b62919022ca3439bef0b0d25518da4427bc5beabf4334
(1 row)

shelley-test=# select * from pool_update ;
shelley-test=# select * from pool_update where hash_id = 105 ;
 id  | hash_id |   pledge    | reward_addr_id | meta | margin | fixed_cost | registered_tx_id 
-----+---------+-------------+----------------+------+--------+------------+------------------
 124 |     105 | 90000000000 |          22878 |   82 |   0.05 |  100000000 |             2799
 277 |     105 | 90000000000 |          23200 |   82 |   0.05 |   10000000 |            19285
 298 |     105 | 90000000000 |          23200 |   82 |   0.05 |   10000000 |            27823
(3 rows)
```

**Comment by Proxiweb** [comment]
Its seems good for me, pool updates are easier to understand. Rewards not inserted were related to a wrong pool_id due to pools updates ?

**Comment by erikd** [comment]
Yes, it seems that was the case.
