### ISSUE TITLE
Rewards not listed

### ISSUE THREAD

**Issue by Proxiweb** [input-output-hk/cardano-db-sync#175]
It is not fixed : 

`select * from pool_hash where hash = '\xf784138ce22b62919022ca3439bef0b0d25518da4427bc5beabf4334'`

`select * from pool_update where hash_id=105;`

the reward_addr_id corresponding to my owner is 22878.

`select * from reward where addr_id=22878;`

=> nothing, idem for an other staking address with addr_id=23200

Values I should have received : 
23200 -> 712912434664
22878 -> 1539770088234

Note.

I don't know if it's related... When I registered my pool, I tried to set a different --pool-reward-account-verification-key-file than the --pool-owner-stake-verification-key-file. I did not received rewards on the reward account until I delegate to the pool. I always received rewards on the owner account... I think db-sync should show these rewards. I'm going to resubmit the certificate with the same reward & owner verification key to see if it helps.

**Comment by Proxiweb** [comment]
It's not related to my pool : pool_hash.id **264**  / lots of blocks / only one reward_addr_id **33536** in updates, no rewards for this addr_id

**Comment by erikd** [comment]
Confirmed. Will figure out what is going wrong.

**Comment by erikd** [comment]
`select * from pool_hash where hash = '\xf784138ce22b62919022ca3439bef0b0d25518da4427bc5beabf4334' ;` gives an `id` of `105`.

`select * from pool_update where hash_id = 105 ;` give 4 entries, two with `reward_addr_id`s `22878` and two with `23200`.

And then `select * from reward where addr_id = 22878 ;` and `select * from reward where addr_id = 23200 ;` both return zero results.

**Comment by erikd** [comment]
@Proxiweb The rewards you see are part of the ledger state and are not currently communicated to `db-sync` over the `node-to-client` protocol. That is why you do not see them.

If you want to see them, you need to "withdraw" the rewards so they will end up in the `withdarwal` table. The `rewards` table you are querying above is for "instantaneous rewards" which is the mechanism by which ITN rewards are brought back onto mainnet.

Does that make sense?

**Comment by Proxiweb** [comment]
Ok. Maybe the reward table could be renamed reward_itn. 
Will not withdraw-ed funds be communicate to db-sync in a near future ? If not, how can I list rewards of my pool's delegators.
( I ask this because I would like to give rewards history graph to my delegators ).

**Comment by erikd** [comment]
> Ok thanks. Maybe the reward table could be renamed reward_itn.

There are other uses of the reward table.

> Will not withdraw-ed funds be communicate to db-sync in a near future 

Yes, that is the plan.

**Comment by Proxiweb** [comment]
Ok. Thanks !
