### ISSUE TITLE
Upgrade from 2.0.0 to 2.1.0 failes on migrations step

### ISSUE THREAD

**Issue by ksemaev** [input-output-hk/cardano-db-sync#177]
The error after upgrade is:

```
Running : migration-2-0002-20200615.sql
psql:/nix/store/7rbfljczglgd45gjv06gg978mf1xgb8r-schema/migration-2-0002-20200615.sql:17: ERROR:  column "slots_per_epoch" contains null values
CONTEXT:  SQL statement "ALTER TABLE "meta" ADD COLUMN "slots_per_epoch" INT8 NOT NULL"
PL/pgSQL function migrate() line 7 at EXECUTE
ExitFailure 3
```

**Comment by erikd** [comment]
From the release notes https://github.com/input-output-hk/cardano-db-sync/releases/tag/2.1.0

> This release requires the database to be dropped and recreated.

Yes I know this is suboptimal, but the changes required for Shelley are large and invasive and not even complete yet.

Once Shelley support is finalized we will attempt to make migrations work correctly.
