### ISSUE TITLE
cardano-node 15.1 incompatible with latest master of db-sync

### ISSUE THREAD

**Issue by papacarp** [input-output-hk/cardano-db-sync#183]
I know erik hasn't worked insuring db-sync works with 15.1 yet.  I already tried updating the dependencies and it didn't work so dropping this in here for now.  

db-sync-extended exits with the following error code on startup:
```
cardano-db-sync-extended: DecoderFailure ChainSync ServerAgency TokNext TokCanAwait DeserialiseFailure 90 "Size mismatch when decoding Block.\nExpected 4, but found 2."
```

**Comment by erikd** [comment]
Working on this now. Hopefully today or tomorrow.

**Comment by erikd** [comment]
And of course it has turned out to be more complicated than anticipated.
