### ISSUE TITLE
Relate rewards and withdrawal back to pool

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#198]
Other tables needing the same relationship:
- https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Schema.hs#L205
- https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Schema.hs#L212

_Originally posted by @rhyslbw in https://github.com/input-output-hk/cardano-db-sync/issues/195#issuecomment-660814051_

Basically a way to relate `Reward` and `Withdrawal` values back to the pool they originated from.

**Comment by erikd** [comment]
Now that I have looked at it, the `Reward` table contains `MirRewards` which may bot be the rewards @rhyslbw is thinking about.

**Comment by dcoutts** [comment]
Would need more details on what's being asked for to be totally sure, but this sounds like stuff for phase 2 when we can depend on info from the ledger state.

Note that we cannot relate withdrawals or MIR values to stake pools. They are related to specific reward accounts, but not related to stake pools.

**Comment by Proxiweb** [comment]
AFAIK actually rewards are listed only if they have been withdrawn. (see [#175](https://github.com/input-output-hk/cardano-db-sync/issues/175#issuecomment-655976069)). Is there a chance to have a simple way to query pool's delegators rewards implemented soon ?

**Comment by erikd** [comment]
The `reward` table already references the `pool_id` . Need to add this to the `Withdrawal` table.
