### ISSUE TITLE
Add payment credentials for addresses

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/cardano-db-sync#207]
In Shelley, light wallets need to query for payments keys instead of full addresses (for example, to deal with the malleability of base addresses)

More concretely,

currently we query the transaction history from our server using
```
{
  addresses: [
    bootstrap_address_1,
    bootstrap_address_2,
    ...,
  ]
}
```
However, we want to (as an end result), do
```
{
  addresses: [
    payment_key_hash_1,
    payment_key_hash_2,
    ...,
  ]
}
```

There are a few ways this can be done. Two main ways:
1) Create a lookup table that contains two columns: `full address`  and `payment key`. Whenever a tx input / output gets added, an entry in the lookup table is created (if needed)
2) Explicitly store a new column inside transaction input & output columns that store the payment key (if one exists for that address type)

At its core though, this request is mostly for some way to access components of an address from an SQL query, so although this specific ticket is about accessing the payment key field of an address, somebody else may have a requirement of accessing other information like
1) Address type (header payload)
2) Script key hash

**Comment by erikd** [comment]
Sorry, I am not able to relate this report back to what `db-sync` actually does. My first impression was that this question actually belongs to the https://github.com/input-output-hk/cardano-rest repository. That may still be the case. This repository does not have **any** components that serve JSON over HTTP.

If this actually is against this repository, you need to relate this to the database schema and maybe an SQL query.

**Comment by SebastienGllmt** [comment]
Yoroi doesn't use Cardano-Rest. Our queries are REST queries that go
Our backend -> Cardano-GraphQL -> cardano-db-sync

The problem is we can't create this kind of endpoint in our backend because the information about address types isn't stored in db-sync so there is no way to write a graphql / sql query for this that allows us to create this endpoint

**Comment by SebastienGllmt** [comment]
If you want a specific SQL query, you can see our current transaction history SQL query [here](https://github.com/Emurgo/yoroi-graphql-migration-backend/blob/master/src/services/transactionHistory.ts#L23).

Notably, we check for addresses that contain a transaction by doing 
```
where "address" = ANY(($1)::varchar array)
```
However, this doesn't work for Shelley where we need to be able to query that the payment key hash matches

**Comment by erikd** [comment]
After a quick char with @dcoutts I understand what needs to be done.
