### ISSUE TITLE
Feature request: block.slotInEpoch

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#210]
In a single-era chain this is a simple calculation that can be performed by the client, however once the parameters are changed during a hard fork, storing this as a separate column when syncing the chain is the most practical approach. [Cardano Wallet](https://github.com/input-output-hk/cardano-wallet/search?q=slotInEpoch&unscoped_q=slotInEpoch) could serve as a reference

`block.slotInEpoch`

**Comment by papacarp** [comment]
similar issue for cardano-node:  https://github.com/input-output-hk/cardano-node/issues/1463

**Comment by erikd** [comment]
Yep, totally appropriate and relatively trivial.
