### ISSUE TITLE
Feature request: time-to-live

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/cardano-db-sync#212]
Time-to-live is currently missing from cardano-db-sync DB. It's part of each Shelley tx

**Comment by erikd** [comment]
Not saying no, but I am wondering how this is useful. TTL is the maximum time from a tx being submitted to when it **must** be included on the chain or be rejected. That means that once its on the chain, the above condition was satisfied and hence not really valuable.

If you have a good reason to add it sure, but I can't currently see one.

**Comment by SebastienGllmt** [comment]
The idea is that we will eventually have pending & failed transactions in our backend where the ttl differentiates between pending & failed.
If you don't want this to be present when the tx is successful (which is every tx in db-sync current), that's okay and we can add this field only in a plugin of some kind or a wrapper for db-sync

**Comment by erikd** [comment]
Ah ok, currently db-sync only contains on-chain data. There are plans to include ledger state and mempool data. Transactions in the  mempool will be stored in a seprate `pending_tx` table and for that it would be totally appropriate to include the TTL value.

**Comment by erikd** [comment]
@SebastienGllmt I wonder if this can be closed. We do have an plan to implement a `pending_tx` table and `TTL` would obviously be included.

**Comment by SebastienGllmt** [comment]
Okay, if that's the way you want to do it, we can live with that
