### ISSUE TITLE
Duplicate Delegation records

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/cardano-db-sync#231]
During re-delegation to a different pool, a new row in Delegation table is created and the old one remains at the same time. So one StakeAddress now have 2 Delegation objects for 2 different pools, but only later Delegation is valid and active. Maybe filed "active" should be added to a Delegation table. Because if pool 1 and pool 2 query their delegators they both will see delegation from the same stake address.

**Comment by erikd** [comment]
This is the intended design. The database (with the only exception being the optional `epoch` table) is designed to only contain immutable data, ie it is append only.

Getting the current valid pool delegation information can be done using:
```
select * from pool_update where not exists (select update_id from pool_retire where update_id = pool_update.id) ;
```

**Comment by adascanBovich** [comment]
PoolUpdate with PoolHash - 153806dbcd134ddee69a8c5204e38ac80448f62342f8c23cfe4b7edf has StakeAddress "e15ed4a0f3e25416845b16bbde8f5bcc8f7125172d972ebcfd7f0f6e76" in its delegation set.

**Comment by erikd** [comment]
A couple of joins:
```
cexplorer=# select stake_address.*, block.slot_no from 
    stake_address inner join delegation inner join tx inner join block
    on tx.block = block.id on delegation.tx_id = tx.id
    on delegation.addr_id = stake_address.id
    where stake_address.hash = '\xe15ed4a0f3e25416845b16bbde8f5bcc8f7125172d972ebcfd7f0f6e76' ;
 id |                             hash                             | slot_no 
----+--------------------------------------------------------------+---------
  7 | \xe15ed4a0f3e25416845b16bbde8f5bcc8f7125172d972ebcfd7f0f6e76 | 4493860
  7 | \xe15ed4a0f3e25416845b16bbde8f5bcc8f7125172d972ebcfd7f0f6e76 | 4493820
(2 rows)
```
so you can see that the first delegation happened on `slot_no = 4493820` and the second happened on `slot_no = 4493860`.

The second overrides the first.
