### ISSUE TITLE
`--rollback-to- slot` does not clear stake addresses

### ISSUE THREAD

**Issue by mebassett** [input-output-hk/cardano-db-sync#239]
See #238 for background.

The rollback function and delete functions in Delete.hs (https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Delete.hs) do not clear stake addresses as they do not have any dependencies to the `block` table that would be caught by a cascade.  

Probably a minor issue.

**Comment by erikd** [comment]
> Probably a minor issue.

I think this is a little more important, especially for debugging and reproducing issues.
