### ISSUE TITLE
can not launch cardano-db-sync due to the wrong sql

### ISSUE THREAD

**Issue by anysoft** [input-output-hk/cardano-db-sync#244]
I have build the db-sync from matser branch.
the log:

/coins/ada/bin/cardano-db-sync --config /coins/ada/datas/cardano-db-sync/config/mainnet-config.yaml --socket-path /coins/ada/datas/state-node-mainnet/node.socket --schema-dir /coins/ada/datas/cardano-db-sync/schema

[db-sync-node:Info:4] [2020-08-12 03:38:06.28 UTC] NetworkMagic: 764824073
[db-sync-node:Info:4] [2020-08-12 03:38:06.29 UTC] Inserting Byron Genesis distribution
cardano-db-sync: DbInsertException "Meta" (SqlError {sqlState = "23502", sqlExecStatus = FatalError, sqlErrorMsg = "null value in column \"protocol_const\" violates not-null constraint", sqlErrorDetail = "Failing row contains (2, null, null, 2017-09-23 21:44:51, mainnet, null).", sqlErrorHint = ""})

mainnet-config.yaml from master config dir
schema from  master  schema  dir

**Comment by anysoft** [comment]
from byron to shelley version we need update the database structs.

see : https://github.com/input-output-hk/cardano-db-sync/tree/shelley-schema
SQL DB Schema: The current PostgreSQL DB schema, as generated by the code.
https://hydra.iohk.io/job/Cardano/cardano-db-sync/native.haskellPackages.cardano-db.checks.test-db.x86_64-linux/latest/download/1

in my way. just to delete old db then recovery it from SQL DB Schema.(this operation need rescan all blocks.it may take a long time )

sudo -u postgres psql
\c cexpolrer
drop table block,delegation,epoch,meta,param_update,pool_hash,pool_meta_data,pool_owner,pool_relay,pool_retire,pool_update,reserve,reward,schema_version,slot_leader,stake,stake_address,stake_deregistration,stake_registration,treasury,tx,tx_in,tx_metadata,tx_out,withdrawal CASCADE ;

psql -d cexplorer -U root -f /coins/ada/datas/cardano-db-sync/db_schema.sql

then we can launch cardano-db-sync .

**Comment by erikd** [comment]
`db-sync` is still under **heavy** development, with schema changes for nearly every release.

The [release notes](https://github.com/input-output-hk/cardano-db-sync/releases/tag/3.1.0) state:
> This release requires the database to be dropped and recreated.

**Comment by anysoft** [comment]
> `db-sync` is still under **heavy** development, with schema changes for nearly every release.
> 
> The [release notes](https://github.com/input-output-hk/cardano-db-sync/releases/tag/3.1.0) state:
> 
> > This release requires the database to be dropped and recreated.

but the scripts of  scripts/postgresql-setup.sh  is out of date.
i had recreate the db use this script. 


so .i delete all tables then import db structs from db-schema.

**Comment by erikd** [comment]
> but the scripts of scripts/postgresql-setup.sh is out of date.

How is it out of date? I still use that script. I used it less than an hour ago?

**Comment by anysoft** [comment]
1.I build cardano-db-sync from sourcecode
2. install postgresql 
3. scripts/postgresql-setup.sh --createdb
4.launch cardano-db-sync

the  program of  cardano-db-sync stops automatically.error logs is this issue.


from byron to shelley
cardano-node to 1.18 
cardano-db-sync 3.1.0
use scripts/postgresql-setup.sh --createdb to init db  can't run cardano-db-sync

the table of meta's struct is diff

3.1.0
 id |     start_time      | network_name
----+---------------------+--------------
  1 | 2017-09-23 21:44:51 | mainnet


old
 id | protocol_const | slot_duration |     start_time      | network_name
----+----------------+---------------+---------------------+--------------
  1 |           2160 |         20000 | 2017-09-23 21:44:51 | mainnet

**Comment by anysoft** [comment]
@erikd

**Comment by erikd** [comment]
Yes, the `meta` table in the new schema is different. The entries `protocol_const` and `slot_duration` made sense during the Byron era but make *zero* sense for the Shelley era. Hence they have been dropped.

**Comment by Mercurial** [comment]
does cardano-db-sync suppose to create the tables when its run the first time? cause mine is not creating it

**Comment by erikd** [comment]
Yes, the tables are created when it is first run. When run you must supply the --`schema-dir` option which should point to the `schema/` directory of the git checkout.

**Comment by Mercurial** [comment]
> Yes, the tables are created when it is first run. When run you must supply the --`schema-dir` option which should point to the `schema/` directory of the git checkout. This is documented in https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/building-running.md .

yep, thats what I understood in your other answer in another issue, thank you!
