### ISSUE TITLE
epoch table not being updated in testnet explorer

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/cardano-db-sync#250]
Using cardano-db-sync extended, tag `3.1.0`, the db-sync on testnet explorer (https://explorer.cardano-testnet.iohkdev.io/en) does not have the epoch table updated with every block.  Compare this to mainnet explorer (https://explorer.cardano.org/en) which does have the epoch table updated with every block.  The tag and extended mode is the same for both explorers.

One impact of this is that both explorers on the frontend show the "Latest Blocks" section accurately (the lower half of the page), but the "Latest Epochs" section of explorer (the top half of the page) is accurate for mainnet but not testnet explorer.

This can also been seen when comparing the timestamps of the latest record in each of the block and epoch tables in the postgres db:

```
Mainnet (most recent block time and epoch_time match because the epoch table is being updated):

cexplorer=# select time from block order by time desc limit 1;
        time         
---------------------
 2020-08-14 15:34:28

cexplorer=# select end_time from epoch order by no desc limit 1;
      end_time       
---------------------
 2020-08-14 15:34:28


---------------------------------------------------------------------------------------------------------


Testnet (most recent block time and epoch_time DON'T match because the epoch table is NOT being updated):

cexplorer=# select time from block order by time desc limit 1;
        time         
---------------------
 2020-08-14 15:34:36

cexplorer=# select end_time from epoch order by no desc limit 1;
      end_time       
---------------------
 2020-08-14 15:01:56
```

Possibly related to: https://github.com/input-output-hk/cardano-db-sync/issues/242 and perhaps already resolved in `4.0.0`

**Comment by erikd** [comment]
Yeah, probably fixed by #242.

**Comment by erikd** [comment]
> does not have the epoch table updated with every block.

It only updates the epoch table on every block when following the chain, not while syncing. When syncing, it only updates the epoch table at the end of the epoch.

There definitely was something odd with the epoch start and end times but that was fixed in #242 .

**Comment by erikd** [comment]
Just found an instance where blocks in epoch 213 are being reported as having a time stamp of `2025-05-09 *` which is just wrong, but I think may be related to this issue.

**Comment by johnalotoski** [comment]
For the `3.1.0` tag, the issue was seen after sync was complete and it was following the chain.
Just checked locally against the `4.0.0` tag with extended and the problem is not observed.

**Comment by johnalotoski** [comment]
Problem not observed with `5.0.0` either.  Closing ticket.
