### ISSUE TITLE
Missing PoolOwner for some pools

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/cardano-db-sync#251]
Pools with hashes:

- 215622e669c0f0c09828ec4100a4c689b1f9c148f542b0192b6ed00d

- cfd262b1ab70425788ffd7bfdd1a2fa63b66f85057cc637365edce16

- 28e31e89ea8a27199c2a3469703df2534d83b1df9be7d98709e3307f

- a79511ed32291c73925164af7aa4ea37dd600dcbbed0ef144bd33dcb

- a7a2ffbb7cf30694dbf57b9721cf0b825a7abd3fa4b7c72a2f1bdbaa

- 7a3ff427e2fc66843d3251bb02dd2e72a8234d496b9787a1b5af7655

have no PoolOwner relations but in `cardano-cli shelley query ledger-state` output file you can see that they actually have owners. See screenshots with some examples.
<img width="699" alt="Screenshot 2020-08-16 at 23 39 33" src="https://user-images.githubusercontent.com/58727428/90343528-de80ab00-e019-11ea-8e2d-010e2872c44b.png">
<img width="699" alt="Screenshot 2020-08-16 at 23 39 57" src="https://user-images.githubusercontent.com/58727428/90343529-dfb1d800-e019-11ea-81df-0ba964dfd738.png">

**Comment by erikd** [comment]
Confirmed!
```
cexplorer=# select * from pool_hash where hash = '\x215622e669c0f0c09828ec4100a4c689b1f9c148f542b0192b6ed00d' ;
 id  |                            hash                            
-----+------------------------------------------------------------
 219 | \x215622e669c0f0c09828ec4100a4c689b1f9c148f542b0192b6ed00d
(1 row)
cexplorer=# select * from pool_owner where pool_id = 219 ;
 id | hash | pool_id 
----+------+---------
(0 rows)
```
Something not right here.

**Comment by erikd** [comment]
I wonder if the pool registration certificate has an empty pool owners list. That would explain this.

**Comment by SebastienGllmt** [comment]
Probably related: https://github.com/Emurgo/yoroi-graphql-migration-backend/issues/36

**Comment by erikd** [comment]
This is subtle. The `pool_owner` table had a unique constraint on the `hash` column where. This means that the schema correctly allowed a pool owner to own a single pool but incorrectly did not allow a pool owner to own a second or subsequent pool.

The fix for this is to have the unique constraint cover both the `hash` and the `pool_hash_id` column. Currently re-syncing the database with this schema fix to test this.

**Comment by erikd** [comment]
Much better:
```
cexplorer=# select * from pool_hash
    where hash = '\x215622e669c0f0c09828ec4100a4c689b1f9c148f542b0192b6ed00d' ;
 id  |                            hash                            
-----+------------------------------------------------------------
 219 | \x215622e669c0f0c09828ec4100a4c689b1f9c148f542b0192b6ed00d
(1 row)

cexplorer=# select * from pool_owner where pool_hash_id = 219 ; 
 id  |                            hash                            | pool_hash_id 
-----+------------------------------------------------------------+--------------
 407 | \xd33cabe9bc7a7646243c03f062881d06744b3d53983823178973b9b0 |          219
(1 row)
```
and after my fix:
```
cexplorer=# select * from pool_hash
       where not exists (select * from pool_owner where pool_owner.pool_hash_id = pool_hash.id) ;
 id | hash 
----+------
(0 rows)
```
