### ISSUE TITLE
Delete/Cascade is slow

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#256]
The delete/cascade operation is slow. Its main purpose is testing and debugging, but deleting 1 million rows can take 30 minutes or more.

Persistent issue: https://github.com/yesodweb/persistent/issues/1113

**Comment by erikd** [comment]
Progress is being made: https://github.com/yesodweb/persistent/pull/1121#issuecomment-684107454 .

**Comment by erikd** [comment]
The Persistent PR has been merged, but last time I checked, Esqueleto did not yet work with the new Persistent.

**Comment by PapaSwer** [comment]
How can I implement it in the cardano-db-sync ?

**Comment by erikd** [comment]
This is a library (Persistent/Esqueleto) issue, rather than a db-sync issue.

**Comment by PapaSwer** [comment]
Is there anyway to import the fixed library to work with cardano-db-sync?

**Comment by erikd** [comment]
I need to investigate that, but it is not at the top of my list if priorities.
