### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by xdzurman** [input-output-hk/cardano-db-sync#263]
Hello, will 4.0.0 be compatible with 1.19.0 node or will we have to wait for another version of db-sync?

**Comment by erikd** [comment]
Sorry, I have not tested it yet.

**Comment by erikd** [comment]
Just tested it. `db-sync` version `4.0.0` is 100% compatible with `node` version `1.19.0`.

**Comment by Mercurial** [comment]
I can't seem to get mien running 1.18.0 or 1.19.0
