### ISSUE TITLE
Error starting using native static binary

### ISSUE THREAD

**Issue by Mercurial** [input-output-hk/cardano-db-sync#280]
Hi Guys I've been trying to run db-sync like this

```
PGPASSFILE=config cardano-db-sync-extended --config config.yaml --socket-path ../pool/node.socket --schema-dir schema/
```

but no matter how I fidle with it It always gives me this error:

```
cardano-db-sync-extended: SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"block\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}
```

I can confirm its connected to a postgresql12 instance in docker that I have setup

is there anything I'm missing here?

P.S I compiled it via ```cabal build all```

Thanks!

**Comment by SebastienGllmt** [comment]
Often times updates are not backwards compatible, so to upgrade you will have to dump your existing database and re-sync from scratch. Most likely that's the issue in your case.

**Comment by Mercurial** [comment]
> Often times updates are not backwards compatible, so to upgrade you will have to dump your existing database and re-sync from scratch. Most likely that's the issue in your case.

Thanks for the answer Seb, but I haven't successfully ran it even once. I wonder what did I miss on my end?

**Comment by Mercurial** [comment]
Hi guys, I got it to work!

I had to import the latest .sql dump file in postgres and it ran!

**Comment by Mercurial** [comment]
actually I'm gonna re-open and just wait for response if this was suppose to be the steps taken for it to run? because it wasn't started anywhere in the docs.

**Comment by erikd** [comment]
> I had to import the latest .sql dump file in postgres and it ran!

That is a potential fix, but probably not the right fix. The `db-sync` program relies on an external schema definition, which is in the `schema/` directory of the git repo. That`schema/` directory is needed for the correct operation of `db-sync`.

**Comment by Mercurial** [comment]
> > I had to import the latest .sql dump file in postgres and it ran!
> 
> That is a potential fix, but probably not the right fix. The `db-sync` program relies on an external schema definition, which is in the `schema/` directory of the git repo. That`schema/` directory is needed for the correct operation of `db-sync`.

oh so I should've pointed the schema parameter to that folder when it ran the first time? doh! so its my big mistake then if thats the case!

**Comment by erikd** [comment]
Yes, I think it is :D . Closing this.

**Comment by Mercurial** [comment]
> Yes, I think it is :D . Closing this.

Thank you 👍
