### ISSUE TITLE
Deleting blocks numbered Info:37

### ISSUE THREAD

**Issue by AskBid** [input-output-hk/cardano-db-sync#285]
my cardano-db-sync seems stuck to this type of messages:

```
[db-sync-node:Info:37] [2020-09-06 20:47:33.81 UTC] Deleting blocks numbered: [4657783]
[db-sync-node:Info:37] [2020-09-06 21:07:40.51 UTC] Rolling back to slot 7860151, hash 8d28a0a373cd619446a7c58be11e89643f7fbadf05a3aba9b2262489ca1da5aa
[db-sync-node:Info:37] [2020-09-06 21:07:40.51 UTC] Deleting blocks numbered: [4657843]
```

What is the meaning of it?

**Comment by erikd** [comment]
This is normal operation of the Cardano blockchain. It happens when the consensus algorithm chose one chain fork over another. All blockchains that use distributed consensus will occasionally fork like this.

This is a reasonable explanation https://en.wikipedia.org/wiki/Fork_(blockchain) .
