### ISSUE TITLE
epoch table not populated

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-db-sync#291]
On shelley-qa using db-sync-extended after a full sync the epoch table is empty:

```
cexplorer=> SELECT * FROM epoch;
 id | out_sum | tx_count | blk_count | no | start_time | end_time | fees 
----+---------+----------+-----------+----+------------+----------+------
(0 rows)
```

This is aftera  fresh sync on deployed master version.

**Comment by disassembler** [comment]
Ignore, someone changed the globals file to not use extended.

**Comment by aleincsharp** [comment]
Hello, i've the same problem. How to solve this?

**Comment by erikd** [comment]
@aleincsharp As per the [architecture](https://github.com/input-output-hk/cardano-db-sync#architecture) section of the README, the table will be empty if you run the `cardano-db-sync` executable. It is only populated if you run the `cardano-db-sync-extended` executable.
