### ISSUE TITLE
Not able to get the correct total stake form Postgres

### ISSUE THREAD

**Issue by djalillounis** [input-output-hk/cardano-db-sync#292]
Hello,

This is more like a question and not an issue,
I am trying to get some stats from the Postgres DB so I made this query that returns the number of delegators per pool:
```
select pool_hash_id,count(*) from public.delegation as d
    join public.tx_out as tx on tx.tx_id = d.tx_id
    where pool_hash_id = 1218 and  d.tx_id in (select max (tx_id) from public.delegation group by addr_id)
    group by pool_hash_id;
```
The query seem to return the correct number of delegators after cross checking with 3rd party tools.

Now to get the amount of stake delegated per delegator  I use this one :
```
select pool_hash_id, d.tx_id,tx.address,ballance from public.delegation as d
    join public.tx_out as tx on tx.tx_id = d.tx_id
    join (select address,sum (value) as ballance  from public.utxo_view  group by  address)
    as v on v.address =tx.address
    where pool_hash_id = 1218 and  d.tx_id
    in (select max (tx_id) from public.delegation group by addr_id) ;
```
I can see that the value  are not correct for some Addresses.

Can you please help me to  fix this query

**Comment by erikd** [comment]
Sorry, I do not have a working/running db-sync instance at the moment because I am working on functionality to add ledger state information to the DB. 

When I get my db-sync instance fixed and synced to mainnet I will look at this query. It should be later this week.

**Comment by djalillounis** [comment]
Hello Erikd,

I think that I am missing the delegators that did delegate from an HW wallet.

**Comment by erikd** [comment]
> I think that I am missing the delegators that did delegate from an HW wallet.

Why do you think that?

**Comment by djalillounis** [comment]
It was because the balance is showing wrong for them.
Even the vew UTXO is not showing the right balance for some addresses.
But on the other hand tools like graphql are accurate.
I can query the adress and get the right balance in graphql console.

**Comment by erikd** [comment]
Without providing me with the exact query you are running, the block height, what you got and what you expect, there is little I can do to help (even I get my db-sync instance working).

**Comment by djalillounis** [comment]
Hello Eric,

sorry for the delay ,I switched to graphql as it is easier for me to get the data that I need.
Thank you for your help

**Comment by djalillounis** [comment]
Hello @erikd  ,

I am Back,  So here is what I want to do Let take an example of this adress staking address: 

stake1uy6p6z6nad8n46vhw6r7gvw4rvgxt2y4f2xgmeq3u4cvj2cm4tztt.

when query the registered stake using the query : 
select *  from  public.stake_address as d where d.view ='stake1uy6p6z6nad8n46vhw6r7gvw4rvgxt2y4f2xgmeq3u4cvj2cm4tztt'
I get the reg id = 2681471

If I query the tx table : 
 select * from public.tx where id = 2681471
I can see the transaction with out_sum : 19,996.825567 ADA

Now I query the tx_out with the same id:
select * from public.tx_out where tx_id =2681471
id : 6507111
Index = 0
address = 'addr1qxmpe8yrr3f3a8ygp2vutrtajsfesyer805gm83pyf580dp5r59486608t5ewa58usca2xcsvk5f2j5v3hjpretsey4s99c6l7'

what I need to get is the sum of all UTXO for the stake1uy6p6z6nad8n46vhw6r7gvw4rvgxt2y4f2xgmeq3u4cvj2cm4tztt.

Abd it seems that it is not possible Because I checked in 3rdparty tools like https://adapools.org/ and https://cardanoscan.io/

And I know this adress  control a stake of : 112K and not 19K

it seems that I cant find the other UTXO linked to that staking key

I hope that it a bit more clear now.

**Comment by erikd** [comment]
It probably is possible to get this from the database as it is now, but it is difficult and complicated. I am working on something right now that will make it relatively easy.

**Comment by erikd** [comment]
@djalillounis I have just reread this ticket and I am now less sure of what you are trying to do than I was previously. It would help if you could describe what you are trying to do, and then I can come up with the query or figure out what is missing from the current schema.

**Comment by djalillounis** [comment]
Hello Eric,

I have solved the  issue,  I wanted to get all the stake addresses with the
correspondent balances.

To solve the issue I had to convert the stake address to hex and then query
the tx table with the condition that the last 54  chars of the
address UTXO are the same as the stake address.

**Comment by erikd** [comment]
> To solve the issue I had to convert the stake address to hex and then query the tx table with the condition that the last 54  chars of the address UTXO are the same as the stake address.

Still need to come up with an easier solution to this.

**Comment by rhyslbw** [comment]
> Still need to come up with an easier/better solution for this.

Can easily achieve this with a simple aggregate query of the rewards table. It's just the sum by address

**Comment by erikd** [comment]
Its the pulling aprt of the address that needs to be made un-necessary.

**Comment by djalillounis** [comment]
I havent upgrade my db-sync to the latest version yet.
I dont I will upgrade and check what can be done from the reward table.

**Comment by erikd** [comment]
Seems like a stale ticket for something that has been fixed some time ago.

**Comment by djalillounis** [comment]
Just the previous epoch everything was working fine and no updates were pushed recently.
I could try to restart my core but the problem I dont know when I will he slotleader again and risk missing blocks

**Comment by erikd** [comment]
@djalillounis This sounds like it should be a new issue. You will need to specify what version of `db-sync` you are running. You wll also need to specify what as working fine and why you think what you see now is wrong.
