### ISSUE TITLE
The db does not contain a second pool retire certificate

### ISSUE THREAD

**Issue by dmitrystas** [input-output-hk/cardano-db-sync#306]
The 2-nd retire certificate was sent (tx 4a6fc5625c0b0378bc94f382a86ebab071bc16cf582ed3644d2438be947ac5ff) for the pool 0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0, but there is no info about this in the db

DB-Sync version: 5.0.1
Node version: 1.20.0

P.S. During the tests, we found out that the old DB-Sync version (3.1.0) works correctly, and contains info about 2-nd retire cert.

**Comment by erikd** [comment]
So why are there two de-registration certs for the same pool? Is that not something the ledger should reject?

**Comment by dmitrystas** [comment]
Another one registration certificate was sent after 1st retire certificate

**Comment by erikd** [comment]
Sorry what? Please tell me the exact sequence of events, because I seem to be missing an important piece of the puzzle.

**Comment by dmitrystas** [comment]
Ok, I'll try to explain in more detail

1. The pool 0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 was registered in the epoch 208 (2020-07-29 22:16:51, tx id a450e752e19cb464eb619b42acc84892730c85910229326cfbf9e3ce45c0ba9e)
2. After this in the epoch 210 the first retire certificate was sent (2020-08-10 21:27:51, tx id da4824527d6a29fead26ebaeaac35a642748a41f9c436c83b0f81c85cd8dc8a9, the retire epoch was specified as 214)
3. After this in the epoch 212 (2020-08-23 21:10:16, tx id 6350185af0452a49e90a0af9df3728995ce555f57ddddd6fe7fad87eb7738549) the new register certificate was sent. This new registration certificate overwrites the previous retire certificate, because it was sent before epoch 214 (according to the [documentation](https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/retire_stakepool.html#:~:text=The%20pool%20will%20retire%20at,then%20overrule%20the%20deregistration%20certificate.)
4. And after this in the epoch 213 (2020-08-24 08:07:04, tx id 4a6fc5625c0b0378bc94f382a86ebab071bc16cf582ed3644d2438be947ac5ff) the 2nd retire certificate was sent

**Comment by erikd** [comment]
Looking at the pool registrations:
```
cexplorer=# select pool_update.id, pool_hash.hash as pool_hash, tx.hash as tx_hash, block.time
    from pool_update
        inner join pool_hash on pool_update.hash_id = pool_hash.id
        inner join tx on pool_update.registered_tx_id = tx.id
        inner join block on tx.block = block.id
        where pool_hash.hash = '\x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0'
    order by block.time asc ;
  id  |                         pool_hash                          |                              tx_hash                               |        time         
------+------------------------------------------------------------+--------------------------------------------------------------------+---------------------
   18 | \x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 | \xa450e752e19cb464eb619b42acc84892730c85910229326cfbf9e3ce45c0ba9e | 2020-07-29 22:16:51
 1500 | \x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 | \x3c390a6a7c3bce3e56ea2789b851bff53ea2611d09d3b2c82211823253e724b4 | 2020-08-03 23:32:51
 2545 | \x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 | \x566c78db0a254483794ac9a9d10570ddb76992c2d1596976c1d6601c19f5d00a | 2020-08-10 21:18:11
 2548 | \x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 | \x4a5ea05c8136b231e85992a7db450ee39e7d6b13f507cb85af104bdc368846e3 | 2020-08-10 21:22:11
 2550 | \x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 | \xfb1a4b5d96719f06df920426f7b647bad0525244cebceeda89701818a4a8eef9 | 2020-08-10 21:23:51
 3684 | \x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 | \x6350185af0452a49e90a0af9df3728995ce555f57ddddd6fe7fad87eb7738549 | 2020-08-23 21:10:16
(6 rows)
```

**Comment by dmitrystas** [comment]
right, the latest registration certificate (latest row, id 3684) was sent after 1st retire certificate

**Comment by erikd** [comment]
Found the problem! The pool retire table is defined in Haskell/Persistent as:
```
  PoolRetire
    hashId              PoolHashId
    certIndex           Word16
    announcedTxId       TxId                                    -- Slot number in which the pool announced it was retiring.
    retiringEpoch       Word64              sqltype=uinteger    -- Epoch number in which the pool will retire.
    UniquePoolRetiring  hashId
```
The uniqueness constraint is only on the `hashId` which prevents more than one retirement for each `hashId`. 

The fix is to add `announcedTxId` to the uniqueness constraint.

**Comment by erikd** [comment]
To pick up the missing pool retirement cert, the database will need to be resynced.

**Comment by erikd** [comment]
After the fix, the `pool_update` table is mostly the same (some autogenerated `id` fields are different).

However the `pool_retire` table now has:
```
cexplorer=# select pool_retire.id, pool_hash.hash as pool_hash, tx.hash as tx_hash, block.time
    from pool_retire inner join pool_hash on pool_retire.hash_id = pool_hash.id
        inner join tx on pool_retire.announced_tx_id = tx.id
        inner join block on tx.block = block.id
    where pool_hash.hash = '\x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0'
    order by block.time asc ;
 id |                         pool_hash                          |                              tx_hash                               |        time         
----+------------------------------------------------------------+--------------------------------------------------------------------+---------------------
 44 | \x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 | \xda4824527d6a29fead26ebaeaac35a642748a41f9c436c83b0f81c85cd8dc8a9 | 2020-08-10 21:27:51
 84 | \x0001a00910e9e6ae309e0f216aa6669b9a711bc627c98cb66e8f11b0 | \x4a6fc5625c0b0378bc94f382a86ebab071bc16cf582ed3644d2438be947ac5ff | 2020-08-24 08:07:04
(2 rows)
```
which I think is what is expected.
