### ISSUE TITLE
Node config file path inconsistent with context used by cardano-node

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#321]
[`NodeConfigFile`](https://github.com/input-output-hk/cardano-db-sync/blob/master/config/mainnet-config.yaml#L11) uses the executable context when interpreting a relative path, which is inconsistent with `cardano-node` since https://github.com/input-output-hk/cardano-node/pull/750. The current context should be the config file, which remains static based on the file system structure

Using 1c51743a6cf1fffe46936290334ebd98fca1e246

**Comment by erikd** [comment]
The provided config is an example. It works when running in the git checkout. If you are not running in a git checkout, you should change this. I can't see a way to fix this for your use case that won't break it for my use case.

**Comment by rhyslbw** [comment]
I'm not using the provided config, but still expect the path to be resolved relative to the config file. Resolving it based on the executable context is quite brittle.

> I can't see a way to fix this for your use case that won't break it for my use case.

Given you have:
```
./cardano-node
./cardano-db-sync
```
this should work:
``` yaml
NodeConfigFile: ../../cardano-node/configuration/cardano/mainnet-config.json
```

**Comment by erikd** [comment]
I am confused. What I have now works. I am 100% sure what you suggest will not work because `../../cardano-node/` does not exist.

**Comment by rhyslbw** [comment]
`../../cardano-node/` is a valid path relative to the **config file** right?. Parent is `config`, grandparent is the directory where I suspect you have both repositories checked out. Right now it only works if you execute `cardano-db-sync` in the root of the source repo, but will fail if the working directory differs. The current behaviour is how `cardano-node` used to resolve paths, however, it was hardened to what I'm proposing here

**Comment by erikd** [comment]
Ah, I get it. Yes, I could probably fix that.
