### ISSUE TITLE
FR - eta0 (epoch nonce) added to epoch_param table

### ISSUE THREAD

**Issue by papacarp** [input-output-hk/cardano-db-sync#322]
Epoch nonce is a system wide hash that is used in the leader log calculations.  It is the only item that we are unable to pull out of the node gracefully without hacking the node.  

We currently hack it out of the node with the following edits:

in the following file:
`dist-newstyle/src/ouroboros_-e7dffa0d85e2839/ouroboros-consensus-shelley/src/Ouroboros/Consensus/Shelley/Protocol.hs`

line 45: add
`import Debug.Trace`

line 425: replace with
`      y'         = SL.mkSeed SL.seedL   slot (trace("{\"epochNonce\": " ++ show eta0 ++ "}") $ eta0)`

It would be most convenient it was added to the new `epoch_param` table so we can access it and use it for our calculations

**Comment by kevinhammond** [comment]
Thanks, Mike.  We'll look at this.

**Comment by erikd** [comment]
Unfortunately this is somewhat non-trivial.

It is calculated as a temporary value inside the `TPraosCrypto era => ConsensusProtocol (TPraos era)` class method and does not seem to be part of the ledger state.

**Comment by erikd** [comment]
Its part of the `ExtLedgerState` struct so I can switch from maintaining `LedgerState` to maintaining `ExtLedgerState` and get it that way.

**Comment by erikd** [comment]
We now have:
```
cexplorer=# select epoch_no, nonce from epoch_param where epoch_no >= 221 ; 
 epoch_no |                               nonce                                
----------+--------------------------------------------------------------------
      221 | \x5ee77854fe91cc243b8d5589de3192e795f162097dba7501f8d1b0d5d7546bd5
      222 | \x171625aef5357dfccfeaeedecd5de49f71fb6e05953f2799d3ff84419dbef0ac
      223 | \xfa2cd68857d74b32d704c86ac94ad40c2d7b5d7143ace3ea4e1fa798794059c0
      224 | \xe329be6b095b4af25217a8af19a1ebbdd6bae3cb7a6a98fbe7529660498ed332
      225 | \xedb2d417956becb8ae5c6e29028459ab1230c1c8620778b9a801cd99feae8fb9
(5 rows)
```
which has been confirmed as being the expected values by @papacarp .
