### ISSUE TITLE
Wrong reward_addr_id in the pool_update table

### ISSUE THREAD

**Issue by dmitrystas** [input-output-hk/cardano-db-sync#326]
There is a some strange things in the stake_address table (after adding UNIQUE hash_raw, **registered_tx_id**). For example, the address stake1u86lar08slg8np2zh60898lrlp0vas40xl9xupyn2k43x3qrawyzr

```
cexplorer=# select id, view, registered_tx_id
from stake_address
where view = 'stake1u86lar08slg8np2zh60898lrlp0vas40xl9xupyn2k43x3qrawyzr';

  id   |                            view                             | registered_tx_id
-------+-------------------------------------------------------------+------------------
  4142 | stake1u86lar08slg8np2zh60898lrlp0vas40xl9xupyn2k43x3qrawyzr |          2429890
  4236 | stake1u86lar08slg8np2zh60898lrlp0vas40xl9xupyn2k43x3qrawyzr |          2430177
 16932 | stake1u86lar08slg8np2zh60898lrlp0vas40xl9xupyn2k43x3qrawyzr |          2436419
 39353 | stake1u86lar08slg8np2zh60898lrlp0vas40xl9xupyn2k43x3qrawyzr |          2465541
(4 rows)

```

was specified 4 times, but it was only 1 time registered (1st row, registered_tx_id = 2429890). The other rows are pool certifcate registration (pool id 77b0a93c26ac65be36e9a9f220f9a43cbc57d705fc5d8f1de5fdeea1) with this stake address as reward address. And if we look in the pool_update table

```
cexplorer=# select pool_update.id, pool_update.reward_addr_id, pool_update.registered_tx_id
from pool_update
left join pool_hash on pool_update.hash_id = pool_hash.id
where pool_hash.hash = '\x77b0a93c26ac65be36e9a9f220f9a43cbc57d705fc5d8f1de5fdeea1';

  id  | reward_addr_id | registered_tx_id
------+----------------+------------------
 1310 |          39353 |          2465541
  512 |          16932 |          2436419
  412 |           4236 |          2430177
(3 rows)
```
we can see each of rows has a new reward_addr_id, but this is not true, only first of them (id 4142) is available and present in the reward / withdrawal tables

**Comment by erikd** [comment]
Is this mainnet?

**Comment by dmitrystas** [comment]
yes

**Comment by erikd** [comment]
Pretty sure the fact that we now have multiple `stake_address.id` values for the same stake address means that `registered_tx_id` should **not** be part of the uniqueness constraint.

**Comment by dmitrystas** [comment]
Well, since a stake address can be registered multiple times (registration -> deregistration -> new registration) the decision to make UNIQUE hash_raw, registered_tx_id looks good. But the question is why are there not only address registration transactions in the stake_address table, but pool registration transactions also...

**Comment by erikd** [comment]
> But the question is why are there not only address registration transactions in the stake_address table, but pool registration transactions also.

There is a reason for that. When someone registers a pool they have to specify a reward address which actually is a stake address. Even without providing a delegation certificate, pool rewards will go to the stake/reward address. Therefore if a pool is registered and the reward address is not already in the stake address table, it is added.

**Comment by erikd** [comment]
After removing `registered_tx_id` from the uniqueness constraint and resyncing the database:
```
cexplorer=# select id, view, registered_tx_id from stake_address
    where view = 'stake1u86lar08slg8np2zh60898lrlp0vas40xl9xupyn2k43x3qrawyzr' ;
  id  |                            view                             | registered_tx_id 
------+-------------------------------------------------------------+------------------
 3751 | stake1u86lar08slg8np2zh60898lrlp0vas40xl9xupyn2k43x3qrawyzr |          2427822
(1 row)

```
which looks good.

Also:
```
cexplorer=# select pool_update.id, pool_update.reward_addr_id, pool_update.registered_tx_id
    from pool_update left join pool_hash on pool_update.hash_id = pool_hash.id
    where pool_hash.hash = '\x77b0a93c26ac65be36e9a9f220f9a43cbc57d705fc5d8f1de5fdeea1';
  id  | reward_addr_id | registered_tx_id 
------+----------------+------------------
 1310 |           3751 |          2463473
  512 |           3751 |          2434351
  412 |           3751 |          2428109
(3 rows)
```
Which also looks good. @dmitrystas please confirm.

**Comment by dmitrystas** [comment]
Looks good!
