### ISSUE TITLE
Document how to determine if the initial sync has completed

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#33]
As a _data consumer_ I need to know if the **initial sync** from genesis is **completed**, so I can avoid running queries that may produce invalid results.

## Proposed changes
~`meta.at_tip - boolean, default: false`~
Add documentation to explain where the incomplete data will be during the initial sync, then a SQL query to determine this client-side

**Comment by erikd** [comment]
What sort of inconsistent results are you concerned about? I am pretty sure that even when the DB is not yet following the chain tip, there cannot be any inconsistent results.

Furthermore no meta table entry is required for this, its simply a query and a simple calculation. Eg

* Get the `meta` row
* Get the latests block
* Return `(calcuate_current_time_from_meta - calculate_time_from_latest_block) < 20`

**Comment by rhyslbw** [comment]
There's an inconsistency when querying for epochs during the initial sync, due to the row being created at the boundary of the next. I'll determine the state client-side, thanks

**Comment by erikd** [comment]
When syncing, I could update the `Epoch` row on each new block, but that would drastically slow down sync times for zero real benefit.

**Comment by rhyslbw** [comment]
The design is good, but we do need to make it clear `cardano-db-sync-extended` must be fully synchronised to guarantee consistency. I'll re-scope this issue to specify this is a documentation issue

**Comment by erikd** [comment]
> must be fully synchronised to guarantee consistency.

When it is not fully synced, the data is incomplete, but is absolutely fully consistent.

**Comment by rhyslbw** [comment]
Ok, updated the description to summarise this

**Comment by erikd** [comment]
I have added a demo Esqueleto query `queryIsFullySynced`. Is that sufficient?

**Comment by rhyslbw** [comment]
I'll add some documentation to support this, so have assigned myself

**Comment by erikd** [comment]
Just a note than I have added an [interesting SQL queries](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md) document which has SQL queries for slot number of the modest recently received block and another that estimates the current slot number from chain metadata.

**Comment by rhyslbw** [comment]
Thanks @erikd
