### ISSUE TITLE
A table to keep a mapping from pool_id to stake

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#330]
In this case stake could be either a proportion of the total stake or a `Coin` value.

The obvious name for this is `EpochStake` but we already have a table by that name. Maybe that should be renamed `EpochAddrStake` and the new one called `EpochPoolStake`. Maybe even drop the "Epoch" part of the names.

**Comment by rhyslbw** [comment]
_Active_ stake? This could be defined as stake participating in the protocol for the associated epoch

**Comment by erikd** [comment]
> Active stake?

"Active" is a transitory characteristic and hence I think unsuitable. I am still leaning towards `EpochAddrStake` and `EpochPoolStake` .

**Comment by rhyslbw** [comment]
By _active_ I'm referring to it playing a role in the protocol during that epoch.

"The stake for the address x was active in epoch 220"

**Comment by erikd** [comment]
Sure, but "active" as part of a table name is just confusing.

**Comment by erikd** [comment]
I am wondering if this is even needed. The `EpochStake` table is defined as:
```
  EpochStake
    addrId              StakeAddressId
    poolId              PoolHashId
    amount              Word64              sqltype=lovelace
    epochNo             Word64
    blockId             BlockId             -- To make rollbacks work correctly.
    UniqueStake         addrId epochNo
```
A simple aggregation should be able to get a mapping from `poolId` to `Coin` which actually is the desired mapping.

**Comment by erikd** [comment]
Wow, this is even easier than I thought.
```
select pool_id, sum (amount) from epoch_stake where epoch_no = 216 group by pool_id ;
```
or, to get the Bech32 pool name rather than the Postgres generated `id` field:
```
select pool_hash.view, sum (amount) from epoch_stake
   inner join pool_hash on epoch_stake.pool_id = pool_hash.id
   where epoch_no = 216 group by pool_hash.id ;
```
