### ISSUE TITLE
Relate stake key registration to stake pool

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#331]
Right now we're missing the link between stake key registration and the stake pool. If the `pool_id` was stored with the registration, then it would be possible to find the pool's delegators.

**Comment by erikd** [comment]
What `pool_id` are you talking about here? The `pool_update` references `pool_hash` which is effectively the pool identifier.

But that does not seem to be what this is about. It seems like you want a list of the stake addresses that are delegating to a specific pool. Is that right?

**Comment by rhyslbw** [comment]
> It seems like you want a list of the stake addresses that are delegating to a specific pool.

Yes, ultimately the goal here is to present `StakePool.delegators`

`stake_address.pool_hash_id` ?

**Comment by erikd** [comment]
But `stake_address.pool_hash_id` is not a static value. A `stake_address` owner can redelegate to another pool.

The `delegation` table has `stake_address_id` and `pool_hash_id` columns.

**Comment by rhyslbw** [comment]
> The delegation table

I had somehow missed this table in the schema. :facepalm: 

> It might be worth adding an active_epoch_no column.

It's [already there](https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Schema.hs#L229)

**Comment by erikd** [comment]
Ans so it is!
