### ISSUE TITLE
Add build instructions using cabal

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-db-sync#339]
Many users are using `cabal` to build the `cardano-node`.

Considering that `db-sync` is connecting to `cardano-node`, it would make sense to provide the same build options for both projects.

**Comment by dorin100** [comment]
At this moment we are proving build instruction using `cabal` for the `cardano-node` and using `nix` for the `db-sync`

**Comment by erikd** [comment]
This is a subset of #342 . Closing.

**Comment by benjichat** [comment]
Need cabal instructions please
