### ISSUE TITLE
db-sync-node.Subscription:Error:56

### ISSUE THREAD

**Issue by WEALLOVESRAM** [input-output-hk/cardano-db-sync#341]
[db-sync-node.Subscription:Error:56] [2020-10-13 03:10:27.34 UTC] [String "Connection Attempt Exception, destination LocalAddress {getFilePath = \"/node-ipc/node.socket\"} exception: Network.Socket.connect: <socket: 12>: does not exist (No such file or directory)",String "SubscriptionTrace"]

in the cardano-rest， but cardano-db-sync can't running. thanks 
and my folder /node-ipc has nothing file

**Comment by rhyslbw** [comment]
This message is expected initially, as the socket is created by `cardano-node` after a validation routine. Is this a new instance, or are you upgrading `cardano-node` ?

**Comment by WEALLOVESRAM** [comment]
> This message is expected initially, as the socket is created by `cardano-node` after a validation routine. Is this a new instance, or are you upgrading `cardano-node` ?

upgrading cardano-node

**Comment by WEALLOVESRAM** [comment]
> This message is expected initially, as the socket is created by `cardano-node` after a validation routine. Is this a new instance, or are you upgrading `cardano-node` ?

and has this err
SqlError {sqlState = "42703", sqlExecStatus = FatalError, sqlErrorMsg = "column block.epoch_slot_no does not exist", sqlErrorDetail = "", sqlErrorHint = ""}

**Comment by erikd** [comment]
You existing database and the code you are running are incompatible. The solution is to drop and restart the database and then sync from scratch.

**Comment by WEALLOVESRAM** [comment]
postgres_1              | 2020-10-13 07:30:58.414 UTC [89] ERROR:  column block.epoch_slot_no does not exist at character 77

**Comment by WEALLOVESRAM** [comment]
curl http://localhost:8100/api/blocks/pages
Something went wrong

**Comment by WEALLOVESRAM** [comment]
> Your existing database and the code you are running are incompatible. The solution is to drop and recreate the database and then sync from scratch.

how to drop database, i have been delete container and images

**Comment by WEALLOVESRAM** [comment]
this is my command
NETWORK=mainnet docker-compose up

**Comment by WEALLOVESRAM** [comment]
this problem is issue.
docker container rm XXX
docker image rm XXX
docker volume rm xxx
NETWORK=mainnet docker-compose up
