### ISSUE TITLE
Need a way to relate a pool created block to the pool which created it

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#349]
I think that `block.vrf_key` should match up with `pool_update.vrf_key` but the former is `VerKeyVRF PraosVRF` and the latter is a `Hash Blake2b_256 (VerKeyVRF PraosVRF)`.

**Comment by erikd** [comment]
Turns out that the `hash` field of the `slot_leader` table as the verification key which it should have been the hash (`Blake_224`) of the verification key.

**Comment by rhyslbw** [comment]
Does `block.vrf_key` not correlate with `pool_update.vrf_key` though?

**Comment by erikd** [comment]
No, the first is a "verification key" and the second is a "hash of a verification key".

**Comment by erikd** [comment]
The first is a "verification key" and the second is a "verification key hash".

**Comment by rhyslbw** [comment]
Ok. Might be worth suffixing it with `_hash` before the next major version?
