### ISSUE TITLE
How to start cardano-db-sync-extended in docker?

### ISSUE THREAD

**Issue by lcgogo** [input-output-hk/cardano-db-sync#363]
I use cardano-graphql docker-compose.yml to start cardano 
https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml

However, in above docker-compose.yml file, @rhyslbw use his own docker hub image to start cardano-db-sync-extended which default version should be 5.0.1.
cardano-db-sync-extended:
    image: rhyslbw/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-09205d901ee86299cc68b3a0d0a8feb52489858f}

I do not find any clues to start cardano-db-sync-extended by  input-output-hk/cardano-db-sync:5.0.2

Does anyone give some help?

**Comment by lcgogo** [comment]
The reason why I want to use cardano-db-sync:5.0.2 because some guy metioned to use it in https://github.com/input-output-hk/cardano-graphql/issues/338

**Comment by rhyslbw** [comment]
Just bump the version in https://github.com/input-output-hk/cardano-graphql/blob/2.2.0/docker-compose.yml#L47

[This](https://github.com/input-output-hk/cardano-graphql/blob/2.2.0/docker-compose.yml#L53) sets the executable to `cardano-db-sync-extended`

**Comment by lcgogo** [comment]
> Just bump the version in https://github.com/input-output-hk/cardano-graphql/blob/2.2.0/docker-compose.yml#L47
> 
> [This](https://github.com/input-output-hk/cardano-graphql/blob/2.2.0/docker-compose.yml#L53) sets the executable to `cardano-db-sync-extended`

The tag 2.2.0 docker-compose file is default graphql version still using

    image: inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION:-2.1.0}

but not 2.2.0
