### ISSUE TITLE
epoch_params.protocol_version destructed, and column name variance 

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#368]
The protocol params in the genesis file are modelled as:

```
"protocolVersion": {
  "minor": 0,
  "major": 2
}
```
however, the values are concatenated into the db as a single string  `ProtVer 2 0`.

1. Why is there divergence here? Presumably there's a reason to have structure for the version, which could be represented with `jsonb` or just flattened into two columns 
2. The column names are more human-friendly, however the actual param names require a manual re-mapping should an implementation wish to use the names defined in the spec.

**Comment by erikd** [comment]
This field is contains close to zero information. The value can only change at epoch boundaries (as a result of a protocol parameter update) so storing it  for every block seems excessive. I would prefer to drop this column all together.

**Comment by rhyslbw** [comment]
> so storing it for every block seems excessive. I would prefer to drop this column all together.

I'm referring to the `epoch_params` table, but agree you could drop it from the block table with this in place

**Comment by erikd** [comment]
Ok, its gone from the block table. I can live with the full version in the `epoch_params` table
