### ISSUE TITLE
How to migrate from v5.0.3 to v6.0.0?

### ISSUE THREAD

**Issue by sjlee1125** [input-output-hk/cardano-db-sync#395]
I have full sync cardano-node and postgres.
I tried to migrate 5.0.3 to 6.00 but I got this error
```
postgres                | 2020-11-03 09:34:07.550 UTC [138] ERROR:  type "outsum" already exists
postgres                | 2020-11-03 09:34:07.550 UTC [138] CONTEXT:  SQL statement "CREATE DOMAIN outsum AS word128type;"
postgres                | 	PL/pgSQL function migrate() line 14 at EXECUTE
postgres                | 2020-11-03 09:34:07.550 UTC [138] STATEMENT:  SELECT migrate();
```
Is there any way to migrate?
Or Do I have to sync from the beginning?

I am using docker

**Comment by mmahut** [comment]
As per release notes:

`As this release has breaking changes, the database has to be dropped and recreated if upgrading.`

**Comment by sjlee1125** [comment]
@mmahut Thank you
