### ISSUE TITLE
Couldn't parse field `pledge` from table `pool_update`. Failed to parse Haskell type Word64: PersistRational

### ISSUE THREAD

**Issue by AdamZWinter** [input-output-hk/cardano-db-sync#399]
Got this error from old install.  Pulled update to existing install, got the same error.  Installed fresh to a different directory and got the same error.

{"at":"2020-11-09T16:11:03.52Z","env":"<unknown>:00000","ns":["db-sync-node"],"data":{"kind":"LogMessage","message":"runDBThread: PersistMarshalError \"Couldn't parse field `pledge` from table `pool_update`. Failed to parse Haskell type Word64: PersistRational (750000000000 % 1)\""},"app":[],"msg":"","pid":"4008","loc":null,"host":"","sev":"Error","thread":"181"}
{"at":"2020-11-09T16:11:03.52Z","env":"<unknown>:00000","ns":["db-sync-node"],"data":{"kind":"LogMessage","message":"ChainSyncWithBlocksPtcl: PersistMarshalError \"Couldn't parse field `pledge` from table `pool_update`. Failed to parse Haskell type Word64: PersistRational (750000000000 % 1)\""},"app":[],"msg":"","pid":"4008","loc":null,"host":"","sev":"Error","thread":"175"}
{"at":"2020-11-09T16:11:03.52Z","env":"<unknown>:00000","ns":["db-sync-node.Mux"],"data":{"event":"State: Dead","kind":"MuxTrace","bearer":"ConnectionId {localAddress = LocalAddress {getFilePath = \"\"}, remoteAddress = LocalAddress {getFilePath = \"/home/ec2-user/cnode/sockets/node0.socket\"}}"},"app":[],"msg":"","pid":"4008","loc":null,"host":"","sev":"Info","thread":"172"}
{"at":"2020-11-09T16:11:03.52Z","env":"<unknown>:00000","ns":["db-sync-node.Mux"],"data":{"event":"Miniprotocol MiniProtocolNum 5 InitiatorDir terminated with exception PersistMarshalError \"Couldn't parse field `pledge` from table `pool_update`. Failed to parse Haskell type Word64: PersistRational (750000000000 % 1)\"","kind":"MuxTrace","bearer":"ConnectionId {localAddress = LocalAddress {getFilePath = \"\"}, remoteAddress = LocalAddress {get$
{"at":"2020-11-09T16:11:03.52Z","env":"<unknown>:00000","ns":["db-sync-node.Subscription"],"data":{"event":"Application Exception: LocalAddress {getFilePath = \"/home/ec2-user/cnode/sockets/node0.socket\"} PersistMarshalError \"Couldn't parse field `pledge` from table `pool_update`. Failed to parse Haskell type Word64: PersistRational (750000000000 % 1)\"","kind":"SubscriptionTrace"},"app":[],"msg":"","pid":"4008","loc":null,"host":"","sev":"E$
{"at":"2020-11-09T16:11:03.52Z","env":"<unknown>:00000","ns":["db-sync-node.ErrorPolicy"],"data":{"event":"ErrorPolicyUnhandledApplicationException (PersistMarshalError \"Couldn't parse field `pledge` from table `pool_update`. Failed to parse Haskell type Word64: PersistRational (750000000000 % 1)\")","kind":"ErrorPolicyTrace","address":"LocalAddress {getFilePath = \"/home/ec2-user/cnode/sockets/node0.socket\"}"},"app":[],"msg":"","pid":"4008"$

**Comment by erikd** [comment]
Most of the changelog (eg [6.0.0](https://github.com/input-output-hk/cardano-db-sync/releases/tag/6.0.0) for the last number of releases have included the line:

> As this release has breaking changes, the database has to be dropped and recreated if upgrading.

**Comment by erikd** [comment]
Closing this.
