### ISSUE TITLE
different ids when db recreate

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#408]
is okay, when I recreate db, I dont have same transaction ids (auto increment) in tx table? same for relays ids for example, maybe its in more tables, not checked.

**Comment by erikd** [comment]
This is expected behavior. `id` columns generated by Postgres are not guaranteed or even expected to always be the same.

**Comment by cardanians** [comment]
auto increment is not always same in postgres?

**Comment by erikd** [comment]
It is not guaranteed to be the smae. Furthermore, if the chain has rollbacks, rows that have previously been inserted are deleted a new rows inserted. Postgres foes not re-use the `id`s of the delete rows.
