### ISSUE TITLE
Add blockCount to Epoch table

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#41]
Maintaining a count of blocks produced in the current epoch will remove the need for a common aggregation query that impacts performance and db load. In particular, the homepage of the new Cardano Explorer requires this information, and query caching only improves the UX, not load.

**Comment by erikd** [comment]
This is relatively trivial. The easiest solution that avoids a data migration would be to just drop the `epoch` table which can be rebuilt in a minute or two.

**Comment by erikd** [comment]
It needs more than just dropping the `epoch` table. Dropping the database works.

**Comment by erikd** [comment]
Dropping the database ans recreating it and now I have:
```
cexplorer=# select * from epoch ;
 id |      out_sum       | tx_count | blk_count | no |     start_time      |      end_time       
----+--------------------+----------+-----------+----+---------------------+---------------------
  1 |  10378568796482912 |       33 |     21587 |  0 | 2017-09-24 16:09:11 | 2017-09-28 21:26:11
  2 | 101402912214214219 |    12870 |     21590 |  1 | 2017-09-28 21:45:51 | 2017-10-03 21:43:51
  3 |  63479608908424764 |     4292 |     21599 |  2 | 2017-10-03 21:45:11 | 2017-10-08 21:38:51
  4 |  41495794265422302 |     3293 |     21598 |  3 | 2017-10-08 22:39:31 | 2017-10-13 21:38:11
  5 |  56099901221413934 |     3524 |     21601 |  4 | 2017-10-13 21:45:31 | 2017-10-18 21:24:51
  6 |  26501823739220193 |     2608 |     21599 |  5 | 2017-10-18 23:56:51 | 2017-10-23 21:43:51
  7 |  20047784722009723 |     2404 |     21601 |  6 | 2017-10-23 21:46:51 | 2017-10-28 21:40:51
  8 | 141738338747111456 |     2645 |     21600 |  7 | 2017-10-28 21:49:51 | 2017-11-02 21:40:51
```
How important is a proper data migration?

**Comment by erikd** [comment]
Since there is only a single DB schema, a schema migration will be needed.

**Comment by erikd** [comment]
Ok, i have written the migration. All is well.

**Comment by erikd** [comment]
Ok, have a working migration. All seems well.
