### ISSUE TITLE
Db-sync Error. Fails to index

### ISSUE THREAD

**Issue by alexqrid** [input-output-hk/cardano-db-sync#411]
Hi I am running `cardano-db 6.0.0` with `cardan-node1.21.1`. Suddenly it failed to sync new blocks with such error:

```
Nov 21 23:05:35 cardano-fork cardano-db6[1971]: [db-sync-node.ErrorPolicy:Error:4] [2020-11-21 23:05:35.51 UTC] [String "ErrorPolicyUnhandledApplicationException Panic! applyHeaderTransition failed: [[NewEpochFailure (EpochFailure (NewPpFailure (UnexpectedDepositPot (Coin 857622000000) (Coin 857626000000))))]]\nCallStack (from HasCallStack):\n  error, called at src/Shelley/Spec/Ledger/API/Validation.hs:92:15 in shelley-spec-ledger-0.1.0.0-inplace:Shelley.Spec.Ledger.API.Validation",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"state-node-mainnet/sock\"}"]
Nov 21 23:05:39 cardano-fork cardano-db6[1971]: [db-sync-node.Handshake:Info:81401] [2020-11-21 23:05:39.94 UTC] [String "Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 764824073),(NodeToClientV_2,TInt 764824073),(NodeToClientV_3,TInt 764824073)]))",String "LocalHandshakeTrace",String "ConnectionId {localAddress = LocalAddress {getFilePath = \"\"}, remoteAddress = LocalAddress {getFilePath = \"state-node-mainnet/sock\"}}"]
Nov 21 23:05:39 cardano-fork cardano-db6[1971]: [db-sync-node.Handshake:Info:81401] [2020-11-21 23:05:39.94 UTC] [String "Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_3 (TInt 764824073))",String "LocalHandshakeTrace",String "ConnectionId {localAddress = LocalAddress {getFilePath = \"\"}, remoteAddress = LocalAddress {getFilePath = \"state-node-mainnet/sock\"}}"]

```

**Comment by erikd** [comment]
This is a duplicate of #398 .

**Comment by alexqrid** [comment]
> This is a duplicate of #398 .

Applied your commit with tag `tmp-fix-6.0.x` but unfortunately it didn't help

**Comment by CyberCyclone** [comment]
> > This is a duplicate of #398 .
> 
> Applied your commit with tag `tmp-fix-6.0.x` but unfortunately it didn't help

That only helps with nodes that aren't already affected. Quote from the comment:

> However, running this version may detect an already corrupted ledger state (I am not even sure what that would look like) in which case a resync will be required.

**Comment by alexqrid** [comment]
Thanks for the information. 
So any choices to make an indexer work now?

**Comment by erikd** [comment]
> So any choices to make an indexer work now?

Sorry, what? I do not even understand what you are asking.

**Comment by alexqrid** [comment]
Can you give me a piece of advice how to make cardano-db-sync work now, after such failure,please?

**Comment by CyberCyclone** [comment]
> Thanks for the information.
> So any choices to make an indexer work now?

You'll need to do a re-sync.

**Comment by CyberCyclone** [comment]
Instructions here: https://github.com/input-output-hk/cardano-db-sync/wiki/Docker

**Comment by erikd** [comment]
And if you are not running it in Docker then
```
PGPASSFILE=config/pgpass-mainnet scripts/postgresql-setup.sh --recreatedb
```

**Comment by erikd** [comment]
@alexqrid If you have managed to get the fixed version running and re-synced your db, please close this.

**Comment by alexqrid** [comment]
Just downgraded to `cardano-db-sync 5.0.0.3` and synced from scratch. Everything seems to work fine.
