### ISSUE TITLE
Is correct to have balance in reward table lower than in a withdrawal table for stake addr?

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#419]
SELECT sum(amount) FROM reward WHERE addr_id=19074
> 1173597821

SELECT amount AS amount FROM withdrawal WHERE addr_id=19074
> 18684388149

**Comment by xdzurman** [comment]
ITN rewards are stored in 'reserve' table, also pending returned deposits (e.g. 500 ADA from pool creation) are nowhere explicitly in the database, but they can be withdrawn. So yes, ITN rewards and deposits can be withdrawn without first being in the reward table.

**Comment by cardanians** [comment]
@xdzurman oh, yes this is it! thanks :)
