### ISSUE TITLE
which version of cardano-node is db-sync 7.1.0 compatibie with?

### ISSUE THREAD

**Issue by bitnado-io** [input-output-hk/cardano-db-sync#437]
is the new [7.1.0 db-sync release](https://github.com/input-output-hk/cardano-db-sync/releases/tag/7.1.0) release compatible with the latest [1.24.2 cardano-node release](https://github.com/input-output-hk/cardano-node/releases/tag/1.24.2)?

i rely on the db-sync release notes to tell me which cardano-node release it's compatible with but i didn't see any mention of cardano-node compatibility in this db-sync release notes. is there another more reliable method i should use to determine cardano-node compatibility? this is blocking me upgrading my cardano-node

**Comment by mmahut** [comment]
Yes, it is. Given the token locking and native tokens eras are introduced to 1.24.2.

The compatibility is often mentioned in the release notes, however, this time it was skipped (cc @LaurenceIO).

**Comment by bitnado-io** [comment]
great thanks!

**Comment by LaurenceIO** [comment]
Sorry about that @bitnado-io have updated the release notes with the compatible version, and will ensure it's included when it's released in future.
Thanks very much for your assistance @mmahut
