### ISSUE TITLE
Example for catalyst voting registration

### ISSUE THREAD

**Issue by TrevorBenson** [input-output-hk/cardano-db-sync#439]
Would be great to have an example for reviewing catalyst voting registrations included in the `interesting-queries.md`.

Thanks

**Comment by erikd** [comment]
I have no idea about the catalyst stuff. Do you have a transaction hash for one of these?

**Comment by TrevorBenson** [comment]
I plan to work on it this evening. Once I get the logic figured out I'll
fork the repo and build/submit a PR.

**Comment by TrevorBenson** [comment]
@erikd Example query submitted in [Pull Request #447](https://github.com/input-output-hk/cardano-db-sync/pull/447)

**Comment by TrevorBenson** [comment]
I actually missed a commit in my fork. Redacting the Pull Request until I adjust the query.

**Comment by TrevorBenson** [comment]
Resubmitted as #448

**Comment by TrevorBenson** [comment]
Closing as PR merged into #451
