### ISSUE TITLE
After restart db sync rollback to slot 0 on testnet

### ISSUE THREAD

**Issue by APshenkin** [input-output-hk/cardano-db-sync#449]
Just updated to 7.1.0. DB was dropped before update. After syncing i did restart cardano-db-sync and After restart db sync rollback to slot 0 on testnet.

```
[db-sync-node:Info:48] [2020-12-16 11:51:24.59 UTC] Starting chainSyncClient
[db-sync-node:Info:48] [2020-12-16 11:51:24.61 UTC] Database tip is at slot 457022, block 455978
[db-sync-node:Info:53] [2020-12-16 11:51:24.61 UTC] Running DB thread
[db-sync-node.Subscription:Notice:31] [2020-12-16 11:51:24.62 UTC] [String "Required subscriptions started",String "SubscriptionTrace"]
[db-sync-node:Info:53] [2020-12-16 11:51:24.97 UTC] Rolling back to slot 0, hash genesis
[db-sync-node:Info:56] [2020-12-16 11:51:25.13 UTC] getHistoryInterpreter: acquired
[db-sync-node:Error:53] [2020-12-16 11:51:25.18 UTC] Rollback block count is high and therefore rollback is likely to be incredibly slow. Dropping the database and resyncing from scratch will be faster.
[db-sync-node:Info:53] [2020-12-16 11:51:25.79 UTC] Deleting slots numbered: [457022..1031]
```

**Comment by wkoder** [comment]
Atala PRISM is also being affected by this.

**Comment by wkoder** [comment]
To resolve the issue we (note we are using Docker):
  - Increased our machine capacity (I think from 4GB to 6GB).
  - Started to persist the internal data of `db-sync`, as in https://github.com/input-output-hk/cardano-rest/pull/104.
  - 
We have been told that from now on, when truncating the DB we need to wipe out that Docker volume as well.

Hope that helps to other affected users.

**Comment by krcz** [comment]
Memory thing was causing unrelated error (it was making the whole instance crash when db-sync started processing crash after slot 7000000; in previous versions memory usage of cardano-node + cardano-wallet + cardano-db-sync was 1.2GB, now 3.3GB with db-sync causing the difference).

**Comment by erikd** [comment]
Since version `6.0.0` `db-sync` also maintains ledger state (non-blockchain data) which is persisted on disk in the directory specified by the `--state-dir` command line argument. This looks like that state needs to be deleted at the same time as the database is dropped.

This will become un-neccessary when the new, faster rollbacks are merged (PR https://github.com/input-output-hk/cardano-db-sync/pull/414).

**Comment by APshenkin** [comment]
Thanks everyone for the answers!

Yes, my problem was that `/var/lib/cdbsync` folder wasn't persisted stored. After adding this folder to persisted volume problem was solved

**Comment by shelley-dev** [comment]
> Thanks everyone for the answers!
> 
> Yes, my problem was that `/var/lib/cdbsync` folder wasn't persisted stored. After adding this folder to persisted volume problem was solved

Great to see that there is a workaround for this issue. How did you deduce this to the folder /var/lib/cdbsync folder? Is this in some db-sync config file or documented somewhere how to achieve persistence? Cannot find /var/lib/cdbsync folder, so currently at a loss on how to work around this issue

**Comment by erikd** [comment]
The folder is what one is specified using `--state-dir` on the command line.

**Comment by shelley-dev** [comment]
Hm...the folder specified by --state-dir in inside my home directory. Aren't these directories persistent?

**Comment by erikd** [comment]
They are persistent when they are correct. When they are no longer correct, they need to be manually removed.
