### ISSUE TITLE
Tag docker image with sermver

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-db-sync#45]
db-sync has a semver [1.4.0](https://github.com/input-output-hk/cardano-db-sync/releases/tag/1.4.0)

but docker image only has a [master version](https://hub.docker.com/r/inputoutput/cardano-db-sync/tags)

Why not tag docker image with 1.4.0?

**Comment by rhyslbw** [comment]
Hi @islishude. It's [our intent](https://github.com/input-output-hk/cardano-db-sync/blob/master/.buildkite/docker-build-push.nix#L64-L69), but the webhook didn't send the tag event. Looking into this now, and will update you when it's available.

**Comment by islishude** [comment]
resolved.use commit hash.
