### ISSUE TITLE
System requirements?

### ISSUE THREAD

**Issue by rvl** [input-output-hk/cardano-db-sync#452]
Hi, what are the system requirements for running cardano-db-sync? I did a search around and didn't find answers. The reason is that I would like to run it myself and try it out.

- I imagine the cardano-node process needs the normal amount of system resources for a passive node.
- The cardano-db-sync process would do a small amount of work for every block to make DB insert queries, and possibly query the ledger for things.
- The graphql part would use very little resources in itself.
- PostgreSQL would definitely use the most resources. How much disk space is needed for a mainnet db? Do common queries use a lot of memory? What sort of CPU is needed to keep up with the chain?

And, does the Epoch table need more resources to maintain?

**Comment by rvl** [comment]
@disassembler - you might be able to give an estimate?

**Comment by erikd** [comment]
I run `db-sync` and its associated `node` in a 4 CPU VM with 16G of RAM (8G may be sufficient). I do not run `graphql` ..

**Comment by rvl** [comment]
Thanks @erikd - is the PostgreSQL server also running on that same VM?

**Comment by erikd** [comment]
Yes, postgresql server is running in the same VM.

**Comment by rvl** [comment]
Thanks :+1:
