### ISSUE TITLE
Database was dropped, but wasn't recreated successfully (updating from 6.0.x -> 7.1.0)

### ISSUE THREAD

**Issue by michdr** [input-output-hk/cardano-db-sync#453]
After following the above update (alongside with the other compatible components), the database schema remains empty:

```sql
SELECT * FROM pg_tables WHERE schemaname = 'public'
0 rows retrieved in 142 ms (execution: 63 ms, fetching: 79 ms)
```

As for the build process, I've noticed one difference referring to this [documentation](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/building-running.md): we do not use the `--state-dir`. Is this one a new requirement for the current version (7.1.0)?

Is there a way to force a DB recreation when starting up? We have deleted the schema dir content and dropped the DB, of course, but to no avail.

**Comment by erikd** [comment]
The `--state-dir` parameter was added in `6.0.0` and all subsequent releases.

> Is there a way to force a DB recreation when starting up?

No, the `db-sync` executable will create the required tables, but the database needs to be created externally.

> We have deleted the schema dir content

Why? The schema dir is **essential** to the operation of `db-sync`.

**Comment by michdr** [comment]
Thanks for clearing this up, @erikd !

The thought was to make the db-sync create the database from scratch. We had a major update, and it is stated there that DB drop is required. Thus, we assumed accordingly that allowing a new db-sync version to run on a "clean set" is better to avoid any inconsistencies.

Anyway, after adding `--state-dir`, all works as expected.
