### ISSUE TITLE
Need help to query an stake address's delegation amount

### ISSUE THREAD

**Issue by mesudip** [input-output-hk/cardano-db-sync#460]
I am trying to add two columns to the delegations table

- previous_pool_hash_id  --- The pool from which the delegator moved. Null, if this is first delegation transaction for a stake address.
- stake_amount        ---  total balance present in the stake address during the delegation transaction.

I've already made required change to include `previous_pool_hash_id`, It's ordered by Id instead of transaction order, but it still works.
```.hs,.diff
cardano-db-sync/src/Cardano/DbSync/Era/Shelly/Query.hs
+  queryLastDelegatedPoolHash :: MonadIO m => StakeAddressId -> ReaderT SqlBackend m (Either LookupFail (Maybe  PoolHashId))
+  queryLastDelegatedPoolHash addr = do
+    res <- select . from $ \ d -> do
+              where_ (d ^. DelegationAddrId ==. val addr)
+              orderBy [desc (d ^. DelegationId)]
+              limit 1
+              pure (d ^. DelegationPoolHashId)
+    case res of
+      [] -> do
+          pure $ Right Nothing
+      x -> do
+          pure $  Right $ Just $ unValue $ head  x

cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Insert.hs
    insertDelegation
        :: (MonadBaseControl IO m, MonadIO m)
        => Trace IO Text -> DbSyncEnv -> DB.TxId -> Word16 -> EpochNo
        -> ShelleyStakingCred -> ShelleyStakePoolKeyHash
        -> ExceptT DbSyncNodeError (ReaderT SqlBackend m) ()
    insertDelegation _tracer env txId idx (EpochNo epoch) cred poolkh = do
      addrId <- firstExceptT (NELookup "insertDelegation")
                    . newExceptT
                    $ queryStakeAddress (Shelley.stakingCredHash env cred)
+   
+     previousPoolHashId <-  firstExceptT (NELookup "insertDelegation")
+                                           . newExceptT
+                                           $ queryLastDelegatedPoolHash addrId
      poolHashId <- firstExceptT (NELookup "insertDelegation")
                      . newExceptT
                      $ queryStakePoolKeyHash poolkh
      void . lift . DB.insertDelegation $
        DB.Delegation
          { DB.delegationAddrId = addrId
          , DB.delegationCertIndex = idx
          , DB.delegationPoolHashId = poolHashId
+         , DB.delegationPreviousPoolHashId = previousPoolHashId
          , DB.delegationActiveEpochNo = epoch + 2 -- The first epoch where this delegation is valid.
          , DB.delegationTxId = txId
          }

```

How do I query the total balance in stake address at that instant?

**Comment by erikd** [comment]
> I am trying to add two columns to the delegations table

Why? You do realize that this would make you modified version incompatible with this version.

> `previous_pool_hash_id`

That can be obtained with an SQL query on the existing database.

> `stake_amount` 

That can also be obtained with an SQL query on the existing database.

**Comment by erikd** [comment]
@mesudip Is this issue resolved? If so, please close the ticket.

**Comment by mesudip** [comment]
I was aware of the `epoch_stake` table. I was just confused when actually does the insertion occur.

 So the value is updated every block and not at the end of epoch during reward calculation?

**Comment by erikd** [comment]
The `epoch_stake` table is updated at the start of each epoch. 

If we are in epoch `N` the values in the `epoch_stake` table for epoch `N` are the values from when the stake snapshot was taken at the start of epoch `N - 1`.

**Comment by mesudip** [comment]
That data should be available in the ledger state. How do query the value from  ledger state in haskell?

**Comment by erikd** [comment]
you can get a JSON dump of the ledger state from the `node` using a command something like `cardano-cli shelley query ledger-state` .

**Comment by erikd** [comment]
@mesudip Can this be closed?

**Comment by mesudip** [comment]
Let's say somebody registered a new stake address `stake1uxwt57g5k59805exsla94smwdhy8uy748fadeua77pdr5mglnft2u`
Where can I find the balance for that address? Do I have to wait until the end of epoch? 
`cardano-cli` provides only the stake distribution for active pools, and balance of reward address of the stakeAddress.

**Comment by erikd** [comment]
> Where can I find the balance for that address? 

The balance is not stored directly anywhere. Instead `db-sync` stores deposits and withdrawals from the rewards account.

> Do I have to wait until the end of epoch?

`db-sync` only adds rewards to the reward table when the rewards can actually be spent. Rewards for epoch `N` are calculated in the `cardano-node` 2 days after the start of epoch `N + 1` but those rewards cannot be spent until after the start of epoch `N + 2`. Its is at the start of epoch `N + 2` that the rewards are added the database.

To get the rewards for a specific stake address:
```
select * from reward inner join stake_address on reward.addr_id = stake_address.id
    where stake_address.view = 'stake1.....' ;
```
To get the withdrawals for the same address:
```
select * from withdrawal inner join stake_address on withdrawal.addr_id = stake_address.id
     where stake_address.view = 'stake1...' ;
```
To get the current balance of the reward account it is simply the first minus the second.

**Comment by erikd** [comment]
@mesudip Have you sorted this out yet?

**Comment by erikd** [comment]
Closing.

**Comment by erikd** [comment]
To get the amount delegated and which pool it was delegated to:
```sql
> select stake_address.view as stake_address, pool_hash.view as pool, amount as lovelace, epoch_no
      from epoch_stake inner join stake_address on epoch_stake.addr_id = stake_address.id
      inner join pool_hash on epoch_stake.pool_id = pool_hash.id
      where stake_address.view = 'stake1uxwt57g5k59805exsla94smwdhy8uy748fadeua77pdr5mglnft2u'
      order by epoch_no asc;
                        stake_address                        |                           pool                           | lovelace  | epoch_no 
-------------------------------------------------------------+----------------------------------------------------------+-----------+----------
 stake1uxwt57g5k59805exsla94smwdhy8uy748fadeua77pdr5mglnft2u | pool1calq8kjzrvp83l80rtvgmulausl99q4tjfkz2lp227vkymd5wgg | 142725567 |      250
 stake1uxwt57g5k59805exsla94smwdhy8uy748fadeua77pdr5mglnft2u | pool1calq8kjzrvp83l80rtvgmulausl99q4tjfkz2lp227vkymd5wgg | 142725567 |      251
 stake1uxwt57g5k59805exsla94smwdhy8uy748fadeua77pdr5mglnft2u | pool1calq8kjzrvp83l80rtvgmulausl99q4tjfkz2lp227vkymd5wgg | 142725567 |      252
 stake1uxwt57g5k59805exsla94smwdhy8uy748fadeua77pdr5mglnft2u | pool1calq8kjzrvp83l80rtvgmulausl99q4tjfkz2lp227vkymd5wgg | 142805683 |      253
 stake1uxwt57g5k59805exsla94smwdhy8uy748fadeua77pdr5mglnft2u | pool1calq8kjzrvp83l80rtvgmulausl99q4tjfkz2lp227vkymd5wgg | 142885847 |      254
 stake1uxwt57g5k59805exsla94smwdhy8uy748fadeua77pdr5mglnft2u | pool1calq8kjzrvp83l80rtvgmulausl99q4tjfkz2lp227vkymd5wgg | 143001638 |      255
(6 rows)

```
