### ISSUE TITLE
need help understanding delegations select

### ISSUE THREAD

**Issue by AskBid** [input-output-hk/cardano-db-sync#461]
trying to look for a pool delegations in a certain epoch I queried the following:
```pg
cexplorer=# select active_epoch_no, view, addr_id from delegation join pool_hash on delegation.pool_hash_id = pool_hash.id where pool_hash.view = 'pool1wxn9nsl8rvxa6r8e5eaak0ml6etfxnz2n9vqrmsw5nzgyexgkrn' and delegation.active_epoch_no = 237;
```
But this returns 36 rows for a [pool](https://pool.pm/c70d35ffc108348294aac06f8f2fc65eae8bef2c4723c535ebc0830a) that had none delegation in epoch 237.

What is the `delegation` table  actually about?

**Comment by erikd** [comment]
@AskBid If you are going to open an issue and then close it, please add a brief note as to why it was closed. 

For this one it seems like you had some misconception about how things worked, but adding a note about how you cleared up this misconception might help others.

**Comment by rdlrt** [comment]
Afaik - He had a mismatch of pool queried in dbsync vs the actual pool he was checking at other sites

**Comment by AskBid** [comment]
Sorry, new to the GitHub culture and processes.
But yes Priyank is right. No issues aside from me getting confused.
Thanks.
