### ISSUE TITLE
Document ma_tx_mint.name and ma_tx_out.name as (most likely) UTF8 encoded byte strings

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#470]
~~It would be useful to have a table that contains the decoded asset names of tokens, so the value can be joined for human consumption in `ma_txMint` and `ma_tx_out`~~
See https://github.com/input-output-hk/cardano-db-sync/issues/470#issuecomment-756295671

**Comment by erikd** [comment]
What do you mean by decoded?

**Comment by rhyslbw** [comment]
Decoded human-readable names, such as `couttscoin`

**Comment by mmahut** [comment]
> Decoded human-readable names, such as `couttscoin`, or is that value a hash? I was working from the understanding it was the on-chain encoded value
I think it is already available:

```
csyncdb=> SELECT policy, convert_from(name, 'UTF8'), quantity from ma_tx_mint limit 1;
                           policy                           | convert_from | quantity 
------------------------------------------------------------+--------------+----------
 \xb0d07d45fe9514f80213f4020e5a61241458be626841cde717cb38a7 | nutcoin      |        5
(1 row)
```

**Comment by erikd** [comment]
This is purely a presentation issue. The `name` field in the actual data structure is a Haskell `ByteString` and that is the type I have used for the dayabase. I supposedly could change that to Text, but then I would have to UTF-8 encode/decode, but I have no idea whether what is in the field can actually be decoded as UTF-8, but what if it isn't UTF-8 encoded?

**Comment by rhyslbw** [comment]
Thanks @mmahut, that's all we need. I'll update this issue to reflect

**Comment by kevinhammond** [comment]
Note that the coin is uniquely identified by the policy id hash and the token name.  Token names are not unique (so you cannot freely interchange coins with the same token name that are minted under different policies).

**Comment by kevinhammond** [comment]
The raw internal (ledger) format for token names is arbitrary byte string, rather than UTF-8.  I'm not sure whether there will be UTF-8 conversion somewhere on the pipeline?

**Comment by erikd** [comment]
The CIP [A user facing asset fingerprint](https://github.com/cardano-foundation/CIPs/pull/64) is related.

**Comment by kderme** [comment]
I believe this was done in the previous release. The name provides all the info available.
Also there is now a separate table `multi_asset` so that we don't replicate the (name, policy_id) for each output or each mint.
Finally the fingerprint has been added to the `multi_asset` table.
