### ISSUE TITLE
Validate the SQL schema files on start up

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#472]
The DB schema files are stored on disk, and it is possible (eg mixing and matching git checkouts) to have the disk schema out of sync with the schema the `db-sync` executable was actually built with. With many inconsistencies caused by this, it will only noticed when the database hits one of these inconsistencies which is only likely on the Shelley (or later) era.

It would be nice if the executable could contain a list of the migrations it expects to see, with their md5sums and check that against the local disk storage.

**Comment by dmitrystas** [comment]
I totally agree, this would be very useful. I've already had at least 2 cases where the inconsistencies was noticed only after the Byron era was fully synchronized

**Comment by erikd** [comment]
Basically this needs:

* A new subcommand for `scripts/postgres-setup.sh` that basically does `(cd schema ; md5dum *.sql > inventory.txt)`
* A haskell function that reads the inventory file and checks that:
  - Checks that the schema directory exists and is not empty.
  - No extra SQL migrartions exist
  - The md5sums of the files matches the inventory file

All of these should provided really good error messages. In the case when the md5sums do not match, it would be good to get expected and actual md5sums.

**Comment by erikd** [comment]
Actually the `inventory.txt` file is a bad idea, mainly because the file is on the file system and not compiled into the binary.

Instead, we should generate a Haskell with the inventory that gets compiled into the binary, so that the binary knows what it is expecting in terms of the schema files.
