### ISSUE TITLE
Explore how pool deposits can be tracked in the database

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#474]
From https://github.com/input-output-hk/cardano-db-sync/issues/406#issuecomment-755142757 @xdzurman says:
> To put the pool deposit (500 ADA) somewhere in the database, after a pool is retired. Currently it can't be explicitly linked to the reward address it belongs to.

**Comment by JaredCorduan** [comment]
The pool deposit is returned to the stake pool (via its registered reward account) on the epoch in which it is reaped (ie the epoch listed in the pool retirement certificate). This is shown in "Figure 40: Pool Reap Inference Rule" of the Shelley ledger spec. It is therefore implicit in the protocol.

Note that if the reward account is not registered, the deposit goes to the treasury.

Note also that a pool retirement certificate does not guarantee that a pool will be reaped, as the operator may issue a new registration certificate (rendering the retirement void) or a new retirement certificate (changing the epoch).

The deposit amount is according to the `poolDeposit` protocol parameter. Note that if a pool is reaped on the same epoch that this parameter is changed, the old value is used (see "Figure 44: Epoch Inference Rule" of the spec).

As an example, say Alice issues a retirement certificate for her pool for epoch 300. Provided she doesn't issue any pool certificates, then on the 299 to 300 epoch boundary, the reward address registered in her pool certificate will be credited by the deposit value as it is in epoch 299.

**Comment by erikd** [comment]
If a stake address receives staking rewards and a pool deposit refund at the same epoch boundary, there will just be a single entry for that epoch. There are plans afoot to improve this, but what we have now we will have to live with.

**Comment by xdzurman** [comment]
Any progress on this? 

> there will just be a single entry for that epoch. what we have now we will have to live with.

Does that mean it already work? I still can't find the pool deposits.

**Comment by erikd** [comment]
Pool deposits can be seen with
```
select * from tx where deposit > 0 ;
```
Deposits of `2000000` lovelace (2 ADA) are stake key registration deposits. The ones for `500000000` lovelace (500 ADA) are the stake poll registration deposits.

When a pool is de-registered, the deposit is refunded. At the epoch boundary where that pool is reaped. the pool deposit goes back to the stake address. If the stake address does not exist, the deposit goes back to the reserves.

**Comment by erikd** [comment]
@xdzurman Is there anyting left unresolved here? Can this ticket be closed?

**Comment by xdzurman** [comment]
You can close this.

**Comment by 1000101** [comment]
I might be a tad late to the party, but would you mind sharing how would one track a balance of an account, for example?

Calculating  `outputs + reward + reserve +  treasury - inputs - withdrawal` won't do the trick and there doesn't seem to be a nice and easy way around this.

A good candidate could be `stake1uyluup0rh6r2cc7kcw8nudqz990ezf5ltagxmw3u8deukvqwq7etq` (rewards account for an already retired pool). Different explorers show this in a different manner, but I think it's currently not possible without any kind of workaround / additional cumbersome computing. Things become even more blurry when taking edge cases into account. With all that in mind, wouldn't it be beneficial to explicitely track `reaped` info along with account and epoch in the dbsync?

**Comment by erikd** [comment]
@1000101 Please make that a separate ticket.
