### ISSUE TITLE
Rollback Time too long

### ISSUE THREAD

**Issue by asnakep** [input-output-hk/cardano-db-sync#491]
Hello Team,

I'm running db-sync-extended + cardano-node on a 4gb mem Nixos VM,
db-sync runs as systemd service, and is actually getting killed on epoch 232 loading due to mem exceeded.
I'll try a manual run to load postgres.

I open the issue to report a too long rollback action on service stop/start or when get killed.
For example 414112 rows delete didn't finish in more than 24 hours.
I've checked session statements and rollback process is performed,
(I can see new select/delete statements when I refresh the session).

A deletion of 414112 rows is typically get done in seconds, max a couple of minutes.

Should I run some schema objects optimization action when I stop the service or when get killed?

Can this be marked as bug?

Many thanks,
best regards,
Emanuele

**Comment by erikd** [comment]
> getting killed on epoch 232 loading due to mem exceeded.

System requirements for running db sync are {documented here)[https://github.com/input-output-hk/cardano-db-sync#system-requirements]. 4GB of memory is not enough.

> A deletion of 414112 rows is typically get done in seconds, max a couple of minutes.

In the version you are running the rollback is done in Haskell and that is why it is slow. The next release will off load that to PostgrSQL.

**Comment by asnakep** [comment]
Hello,

many thanks for your feedback on what I reported,

kind regards,
Emanuele
