### ISSUE TITLE
value for domain asset32type violates check constraint

### ISSUE THREAD

**Issue by shelley-dev** [input-output-hk/cardano-db-sync#501]
The following error occurred on launchpad network

**sqlErrorMsg = \"value for domain asset32type violates check constraint \\\"asset32type_check\\
\"\",**

More logging from sync, that did not manage to start
```
[db-sync-node:Error:746] [2021-01-19 15:10:37.52 UTC] runDBThread: DbInsertException "insertMaTxOut" (SqlError {sql
State = "23514", sqlExecStatus = FatalError, sqlErrorMsg = "value for domain asset32type violates check constraint 
\"asset32type_check\"", sqlErrorDetail = "", sqlErrorHint = ""})
[db-sync-node:Error:741] [2021-01-19 15:10:37.52 UTC] ChainSyncWithBlocksPtcl: DbInsertException "insertMaTxOut" (S
qlError {sqlState = "23514", sqlExecStatus = FatalError, sqlErrorMsg = "value for domain asset32type violates check
 constraint \"asset32type_check\"", sqlErrorDetail = "", sqlErrorHint = ""})
[db-sync-node.Mux:Info:738] [2021-01-19 15:10:37.52 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", re
moteAddress = LocalAddress "*****"} event: State: Dead
[db-sync-node.Mux:Notice:738] [2021-01-19 15:10:37.52 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", 
remoteAddress = LocalAddress "*****"} event: Miniprotocol MiniProtocolNum 5 Initiat
orDir terminated with exception DbInsertException "insertMaTxOut" (SqlError {sqlState = "23514", sqlExecStatus = Fa
talError, sqlErrorMsg = "value for domain asset32type violates check constraint \"asset32type_check\"", sqlErrorDet
ail = "", sqlErrorHint = ""})
[db-sync-node.Subscription:Error:737] [2021-01-19 15:10:37.52 UTC] [String "Application Exception: LocalAddress \"/
******" DbInsertException \"insertMaTxOut\" (SqlError {sqlState = \"23514\", sqlExec
Status = FatalError, sqlErrorMsg = \"value for domain asset32type violates check constraint \\\"asset32type_check\\
\"\", sqlErrorDetail = \"\", sqlErrorHint = \"\"})",String "SubscriptionTrace"]
[db-sync-node.ErrorPolicy:Error:4] [2021-01-19 15:10:37.52 UTC] [String "ErrorPolicyUnhandledApplicationException (
DbInsertException \"insertMaTxOut\" (SqlError {sqlState = \"23514\", sqlExecStatus = FatalError, sqlErrorMsg = \"va
lue for domain asset32type violates check constraint \\\"asset32type_check\\\"\", sqlErrorDetail = \"\", sqlErrorHi
nt = \"\"}))",String "ErrorPolicyTrace",String "LocalAddress \"*****""]
[db-sync-node.Subscription:Notice:28] [2021-01-19 15:10:38.52 UTC] [String "Restarting Subscription after 1.7808603
98s desired valency 1 current valency 0",String "SubscriptionTrace"]
```

**Workaround**
To get sync started again was to drop constraint asset32type_check

**The prime suspect**
A very loooooooong asset name
[link to the asset in our blockchainintelligence solution](https://bi-preprod.stakepoolcentral.com:8443/assethistory?policy_id=e1d821a95cf9f62ddc5e78bab1111bb8b453ace681dfe15693737605&asset_name=6c6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f6f303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303067)

cardano-node: 1.24.2
cardano-db-sync: 7.1.0

**Comment by erikd** [comment]
This is **not a bug** in db-sync. 

The problem is that version `1.24.2` of the `node` allows assets to be defined with names that are longer than 32 bytes. This is out of spec. Once its on the chain, db-sync correctly flags this as an error.

The required length check is present in the soon to be tagged version 1.25.0` of the node.

For now, on your testnet, dropping that constraint is reasonable, but it is not something that should done in the repo.

**Comment by shelley-dev** [comment]
Great stuff! Good to hear
