### ISSUE TITLE
support transition from byron -> another era in epoch 0

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-db-sync#507]
The node has a configuration parameter to transition all epochs at beginning of chain:

```
   TestShelleyHardForkAtEpoch = 0;
   TestAllegraHardForkAtEpoch = 0;
   TestMaryHardForkAtEpoch = 0;

```

But we were unable to get db-sync to synchronize against a environment that forked from byron -> mary in the 0th epoch.

**Comment by erikd** [comment]
From @disassembler on Slack:
> I think I'd like to tackle this with getting a local cluster integrated with db-sync rather than spinning up a remote cluster to test it. You can just put it in the backlog until we have a good way for you to test things like this.

**Comment by kderme** [comment]
> But we were unable to get db-sync to synchronize against a environment that forked from byron -> mary in the 0th epoch.

@disassembler did you try this recently, for alonzo testnets? By any chance is there a callstack how it failed?
