### ISSUE TITLE
Insert without checking unique constraints

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#529]
When we do any kind of insert on the sql level, we first do a query to check that the unique constraints are satisfied. We could probably omit this query in most cases and get some performance boosts.

**Comment by kderme** [comment]
I've seen some good results from the first epochs (I suspect speedup will be better when tables become bigger)
When we check (44 min):
```
[db-sync-node:Info:57] [2021-02-14 19:49:27.28 UTC] insertABOBBoundary: epoch 28 hash 6fd5e5f45485f36b9e70270865f3e8d3360ea38f25338a53725054e53b3b4908
[db-sync-node:Info:57] [2021-02-14 20:02:48.48 UTC] insertABOBBoundary: epoch 40 hash 31732323544f560dbeffa0258a0484302035ceb27f806f03a5127db303084900
[db-sync-node:Info:57] [2021-02-14 20:33:41.88 UTC] insertABOBBoundary: epoch 76 hash 13c26f05091afaf1d2f207f88764255442d861536b256fedf2ee4a4665b2309e
```

when we don't check (37 min)
```
[db-sync-node:Info:55] [2021-02-14 21:27:17.78 UTC] insertABOBBoundary: epoch 28 hash 6fd5e5f45485f36b9e70270865f3e8d3360ea38f25338a53725054e53b3b4908
[db-sync-node:Info:55] [2021-02-14 21:37:10.31 UTC] insertABOBBoundary: epoch 40 hash 31732323544f560dbeffa0258a0484302035ceb27f806f03a5127db303084900
[db-sync-node:Info:55] [2021-02-14 22:04:10.40 UTC] insertABOBBoundary: epoch 76 hash 13c26f05091afaf1d2f207f88764255442d861536b256fedf2ee4a4665b2309e
```

**Comment by erikd** [comment]
This behavior is due to [this code](https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db/src/Cardano/Db/Insert.hs#L147-L162). If we drop the `getByValue` part there will be no lookup, but we will get a failed constraint exception if it goes wrong.

**Comment by erikd** [comment]
The Postgres `upsert` might be the right way to fix this. Especially if we do it as `ON CONFLICT DO NOTHING RETURNING id`.
