### ISSUE TITLE
insertValidateGenesisDist: Genesis data mismatch.

### ISSUE THREAD

**Issue by chbfiv** [input-output-hk/cardano-db-sync#531]
root@5945b0965be1:/# cardano-db-sync     --config "/storage/config/testnet-db-sync-config.json"     --socket-path "/storage/testnet/node.socket"     --state-dir "/storage/testnet/db-sync-ledger-state"     --schema-dir "schema/"
[db-sync-node:Info:4] [2021-02-20 21:53:49.55 UTC] NetworkMagic: 1097911063
[db-sync-node:Info:4] [2021-02-20 21:53:49.57 UTC] Inserting Byron Genesis distribution
Error: insertValidateGenesisDist: Genesis data mismatch.

NOTE: testnet node runs fine with those configs. I think this is something specific to db-sync?

The config used in this repo is "https://github.com/input-output-hk/cardano-node/blob/master/configuration/cardano/shelley_qa-config.json" which is different than testnet, but why wouldn't testnet work?

**Comment by chbfiv** [comment]
you can see the configs being used here
https://github.com/floydcraft/cardano-node-k8s/tree/master/storage/config

**Comment by erikd** [comment]
Every different network (mainnet, testnet, shelley_qa etc) have different configurations. If they configs do not match you will get an error. The solution is make sure the config and the genesis config match and to make sure the database has been dropped before switching between networks.

**Comment by chbfiv** [comment]
ah that must be it. I need to drop the db (was using the qa config before)
