### ISSUE TITLE
[BUG] - pool_owner.hash cannot be joined with stake_address.hash_raw

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/cardano-db-sync#543]
Other than `pool_update.reward_addr` and `epoch_stake.addr_id`, `pool_owner.hash` cannot be joined with `stake_address.hash_raw`.

Is this intentionally? Perhaps there is another way to get at the BECH32 for a pool owner?

**Comment by erikd** [comment]
I have no idea what you are trying to do.

There is no `pool_owner.hash` field.

**Comment by erikd** [comment]
Ah so you think there should be a Bech32 view ot the `pool_owner`. If that is the case, then yes, you are probably right.

**Comment by erikd** [comment]
Please show me the actual SQL query you are trying to write.

**Comment by tdiesler** [comment]
Merci. Would it be safe for now to prepend the pool_owner.hash with '\xe1' for now?

**Comment by erikd** [comment]
Yes, that would help for now. Also, please post the working query here.

**Comment by tdiesler** [comment]
Here you go ...

```
# Pool Update
SELECT pu.id, pu.active_epoch_no epoch, pu.meta_id, pu.pledge, pu.margin, sar.view reward_addr, sao.view owner_addr
FROM pool_update pu
LEFT JOIN pool_owner po ON pu.registered_tx_id = po.registered_tx_id
INNER JOIN stake_address sar ON pu.reward_addr = sar.hash_raw
INNER JOIN stake_address sao ON substring(cast(po.hash as varchar), 3) = substring(cast(sao.hash_raw as varchar), 5)
WHERE hash_id = 1806
ORDER BY pu.id DESC
```

**Comment by tdiesler** [comment]
simplified, like this ...

```
SELECT pu.active_epoch_no epoch, pu.meta_id, pu.pledge, pu.margin, sar.view reward_addr, sao.view owner_addr
FROM pool_update pu
JOIN pool_owner po ON pu.registered_tx_id = po.registered_tx_id
JOIN stake_address sar ON pu.reward_addr = sar.hash_raw
JOIN stake_address sao ON substring(cast(po.hash as varchar), 3) = substring(cast(sao.hash_raw as varchar), 5)
WHERE pu.hash_id = 1806
ORDER BY pu.id DESC
```
