### ISSUE TITLE
Epoch boundary

### ISSUE THREAD

**Issue by xdzurman** [input-output-hk/cardano-db-sync#545]
Hey, I know you guys merged some epoch boundary optimizations into master, can we expect an official release with this soon? Or should we run master instead of the newest official release? Is it safe?

**Comment by erikd** [comment]
The only epoch boundary optimisation that has actually been implemented was in the `8.0.0` release. I have another in mind but want to see the effect of the fix for the `node`'s epoch boundary plus 48 hours issue first.

There is a `9.0.0` release in the works, but the main feature there is a new `AdaPots` table that gets updated on each epoch.

**Comment by xdzurman** [comment]
So this https://github.com/input-output-hk/cardano-db-sync/commit/142c762b3af3854e8ba81f0bfd8744a8a6ed83fc did not work? It's not in the 8.0.0 release afaik

**Comment by erikd** [comment]
Yeah that is not in `8.0.0`. It improved the problem but does not fix it. It will be in the `9.0.0` release which is in QA now.

**Comment by xdzurman** [comment]
Any update on this? The epoch boundary time increasing rapidly each epoch is very unsettling
```
[db-sync-node:Info:123] [2021-03-22 23:35:05.12 UTC] Finishing epoch 246: 148679 rewards, 257 orphaned_rewards, 176740 stakes.
[db-sync-node:Info:123] [2021-03-22 23:46:02.37 UTC] Starting epoch 247
--
[db-sync-node:Info:123] [2021-03-23 00:23:39.57 UTC] Finishing epoch 247: 154678 rewards, 260 orphaned_rewards, 197331 stakes.
[db-sync-node:Info:123] [2021-03-23 00:37:17.90 UTC] Starting epoch 248
--
[db-sync-node:Info:123] [2021-03-23 01:10:53.61 UTC] Finishing epoch 248: 166465 rewards, 234 orphaned_rewards, 220596 stakes.
[db-sync-node:Info:123] [2021-03-23 01:23:56.62 UTC] Starting epoch 249
--
[db-sync-node:Info:123] [2021-03-23 02:06:11.81 UTC] Finishing epoch 249: 184427 rewards, 272 orphaned_rewards, 243779 stakes.
[db-sync-node:Info:123] [2021-03-23 02:21:54.44 UTC] Starting epoch 250
--
[db-sync-node:Info:123] [2021-03-23 03:05:59.60 UTC] Finishing epoch 250: 206799 rewards, 422 orphaned_rewards, 269770 stakes.
[db-sync-node:Info:123] [2021-03-23 03:23:45.60 UTC] Starting epoch 251
--
[db-sync-node:Info:123] [2021-03-23 04:06:15.05 UTC] Finishing epoch 251: 228865 rewards, 259 orphaned_rewards, 295232 stakes.
[db-sync-node:Info:123] [2021-03-23 04:21:39.87 UTC] Starting epoch 252
--
[db-sync-node:Info:123] [2021-03-23 04:56:33.02 UTC] Finishing epoch 252: 250983 rewards, 305 orphaned_rewards, 320343 stakes.
[db-sync-node:Info:123] [2021-03-23 05:12:32.94 UTC] Starting epoch 253
--
[db-sync-node:Info:123] [2021-03-23 05:50:42.63 UTC] Finishing epoch 253: 271653 rewards, 329 orphaned_rewards, 338671 stakes.
[db-sync-node:Info:123] [2021-03-23 06:15:42.96 UTC] Starting epoch 254
--
[db-sync-node:Info:123] [2021-03-23 07:09:54.47 UTC] Finishing epoch 254: 286770 rewards, 310 orphaned_rewards, 354525 stakes.
[db-sync-node:Info:123] [2021-03-23 07:38:58.64 UTC] Starting epoch 255
```

You can see how it went from 9 minutes to almost 30 over just a few epochs. @erikd

**Comment by erikd** [comment]
What are you running that on. On this last epoch boundary, I saw an 11 minute delay (2 CPU VM on an 8 CPU box), but not a 30 minute one.

**Comment by xdzurman** [comment]
t3a.2xlarge - 8 vCPU (2.5 GHz AMD EPYC 7000 series)

**Comment by erikd** [comment]
New issue https://github.com/input-output-hk/cardano-db-sync/issues/560 .
