### ISSUE TITLE
9.0.0 not on dockerhub

### ISSUE THREAD

**Issue by xdzurman** [input-output-hk/cardano-db-sync#557]
Hello, releases 8.0.0 and 7.1.0 had dockerhub image within minutes, is it normal that 9.0.0 still does not have a pushed image on [dockerhub](https://hub.docker.com/r/inputoutput/cardano-db-sync)?

**Comment by erikd** [comment]
The CI build that uploads to Docker failed for some reason. We are investigating.

**Comment by erikd** [comment]
The build has now passed, but the artifact has not been uploaded. I have contacted people who know more about the CI/Nix installation.

**Comment by erikd** [comment]
Dockerhub should be good to go now.
