### ISSUE TITLE
stall when running node and db sync at the same time

### ISSUE THREAD

**Issue by jrafsantos** [input-output-hk/cardano-db-sync#571]
Hello,

when the node is running and after that I decide to execute the db sync I get the message "Killed" from the db sync output terminal and the following message in the node output terminal:

cardano.node.LocalErrorPolicy:Error:84] [2021-04-03 00:23:48.42 UTC] IP LocalAddress "" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 33> closed when reading data, waiting on next header True")

cardano.node.DnsSubscription:Error:90] [2021-04-03 00:26:58.55 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 18.158.233.100:3001 SubscriberError {seType = SubscriberWorkerCancelled, seMessage = "SubscriptionWorker exiting", seStack = []}

the node doesnt end and continues to execute.

Please, can you help.
Thanks and congrats for the amazing work

**Comment by erikd** [comment]
That is not the full error mesages. Pleas provide at least 10 linies of logs from before the "Killed" message.

**Comment by erikd** [comment]
Those `node` messages are nothing to do with `db-sync` and are almost certainly a consequence of `db-sync` being killed.

Please provide at 10-20 lines of the `db-sync` logging out from before the "Killed" message.

**Comment by jrafsantos** [comment]
> Those `node` messages are nothing to do with `db-sync` and are almost certainly a consequence of `db-sync` being killed.
> 
> Please provide at 10-20 lines of the `db-sync` logging out from before the "Killed" message.

yes thats exacly what i wanted to say. the node error happens most likely because the dbsync gets killed.

I successfully got to the 253 epoch but know it only shows me this:
[db-sync-node:Info:4] [2021-04-03 08:57:15.17 UTC] Using byron genesis file from: "config/../../cardano-node/configuration/cardano/mainnet-byron-genesis.json"
[db-sync-node:Info:4] [2021-04-03 08:57:15.17 UTC] Using shelley genesis file from: "config/../../cardano-node/configuration/cardano/mainnet-shelley-genesis.json"
[db-sync-node:Info:4] [2021-04-03 08:57:15.92 UTC] NetworkMagic: 764824073
[db-sync-node:Info:4] [2021-04-03 08:57:16.52 UTC] Initial genesis distribution present and correct
[db-sync-node:Info:4] [2021-04-03 08:57:16.52 UTC] Total genesis supply of Ada: 31112484745.000000
[db-sync-node:Info:4] [2021-04-03 08:57:16.52 UTC] Inserting Shelley Genesis distribution
[db-sync-node:Info:4] [2021-04-03 08:57:27.38 UTC] localInitiatorNetworkApplication: connecting to node via "../cardano-node/state-node-mainnet/node.socket"
[db-sync-node.Subscription:Notice:50] [2021-04-03 08:57:27.38 UTC] Identity Starting Subscription Worker, valency 1
[db-sync-node.Subscription:Notice:51] [2021-04-03 08:57:27.38 UTC] Identity Connection Attempt Start, destination LocalAddress "../cardano-node/state-node-mainnet/node.socket"
[db-sync-node.Subscription:Notice:51] [2021-04-03 08:57:27.38 UTC] Identity Connection Attempt End, destination LocalAddress "../cardano-node/state-node-mainnet/node.socket" outcome: ConnectSuccessLast
[db-sync-node.Handshake:Info:51] [2021-04-03 08:57:27.38 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 764824073),(NodeToClientV_2,TInt 764824073),(NodeToClientV_3,TInt 764824073),(NodeToClientV_4,TInt 764824073),(NodeToClientV_5,TInt 764824073),(NodeToClientV_6,TInt 764824073),(NodeToClientV_7,TInt 764824073),(NodeToClientV_8,TInt 764824073)]))
[db-sync-node.Handshake:Info:51] [2021-04-03 08:57:27.38 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_8 (TInt 764824073))
[db-sync-node.Mux:Info:51] [2021-04-03 08:57:27.38 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"} event: Handshake Client end, duration 0.000795006s
[db-sync-node.Mux:Info:52] [2021-04-03 08:57:27.38 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"} event: State: Mature
[db-sync-node:Info:55] [2021-04-03 08:57:27.38 UTC] Starting chainSyncClient
[db-sync-node:Info:55] [2021-04-03 08:57:27.41 UTC] Cardano.Db tip is at slot 24240103, block 5464000
[db-sync-node:Info:59] [2021-04-03 08:57:27.41 UTC] Running DB thread
[db-sync-node.Subscription:Notice:50] [2021-04-03 08:57:27.41 UTC] Identity Required subscriptions started
[db-sync-node:Info:59] [2021-04-03 08:57:29.38 UTC] Rolling back to SlotNo 24240103, hash fd76a5aad46f8d47176e8dcd0fd18bbf44dc4fa1c32c270a563bc134a07d5d75
[db-sync-node:Info:59] [2021-04-03 08:57:29.39 UTC] No Rollback is necessary
[db-sync-node:Info:62] [2021-04-03 08:57:29.79 UTC] getHistoryInterpreter: acquired
Killed

**Comment by erikd** [comment]
There is nothing in that log output that points to why it was killed. That makes me suspect it was killed by the operating system. If that was the case, there should be something in the machine's syslog.

Are you meeting the [minimum system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements)?

**Comment by jrafsantos** [comment]
> There is nothing in that log output that points to why it was killed. That makes me suspect it was killed by the operating system. If that was the case, there should be something in the machine's syslog.
> 
> Are you meeting the [minimum system requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements)?

You might be correct. I think it might be related with lack of storage space, despite having still a few GB left from a total of 70GB. I'm going to increase it and try again. I'll leave feedback. Thanks Erikd :)

**Comment by erikd** [comment]
70G of storage should be more than sufficient.

**Comment by jrafsantos** [comment]
> 70G of storage should be more than sufficient.

Ok, I solve the problem. I guess i didnt have enough memory RAM and swap space also was to short. I was able to load all epochs to postgres. Thank you Erikd for your support
