### ISSUE TITLE
Keeping the DB updated

### ISSUE THREAD

**Issue by kzka90** [input-output-hk/cardano-db-sync#572]
Hope this is the right place to ask this question, and maybe should be added to the Readme to clarify how does it work.

I've already set up everything, and I'm running this command to start populating the DB: 

`cardano-db-sync-extended --config $CNODE_HOME/files/dbsync.json --socket-path $CNODE_HOME/sockets/node0.socket --state-dir $CNODE_HOME/guild-db/ledger-state --schema-dir schema/`

(Which it is still running as I'm typing this, I believe it'll take some time to populate everything the first time)

But what will happen when it finishes populating?

- Do I need to keep running the command from above to always be up to date?
- Or does it automatically add new entries as my cardano-node receives new data? (If so, what should I had done to make it work like this)

**Comment by erikd** [comment]
If both the `node` and `db-sync` are left running, new block arriving at the `node` will be fowarded to `db-sync` and inserted into the database.

**Comment by kzka90** [comment]
> If both the `node` and `db-sync` are left running, new block arriving at the `node` will be fowarded to `db-sync` and inserted into the database.

Is there special/intended way to run `db-sync` as a service? Or is it intended to run just like the command from above?

**Comment by erikd** [comment]
Do you mean via systemd? Sure, that would be possible, but IOG does not currently supply one.
