### ISSUE TITLE
Allow for a new db-sync node to sync with a pre-existing database

### ISSUE THREAD

**Issue by failfectionist** [input-output-hk/cardano-db-sync#590]
**External**

**Existing Database Connections**

**Summary**
Hopefully this hasn't already been hashed, I tried to do some searching but haven't found much. I've deployed db-sync several times now and have noticed that I do not seem to have a way to re-use an existing sync'ed database. Would love to be able to clone a database and have a newly installed/configured db-sync connect to it and verify. 

For deployments and issues that may crop up with servers, requiring a total re-load / re-sync is extremely time-consuming. This will become a major issue in the future when the blockchain is getting even larger I can only assume.

**Steps to reproduce**
1. Install a db sync node
2. Fully sync a database
3. Clone the database
4. Install another db sync node and attempt to sync

**Expected behavior**
The node should ideally be able to quickly perform checks to verify the database is valid instead giving insertion errors or attempting to rollback the entire database. 

**System info:**
- OS: Debian Buster
- DB Sync Version 9.0
- Node version 1.26.1

**Additional context**
Finally amazing job and if there's something I can do to help, just let me know. As the size of the services grow having "modular" capabilities like this to improve deployments and separate the db-sync process from the node and from the database could be advantageous.

**Comment by erikd** [comment]
There are two bits of persistent state; the Postgres database and the ledger state directory (as specified by the `--state-dir` directory. As long as you clone **both** bits of state from one machine to another, and they are running the same version of software, this should work now.

**Comment by failfectionist** [comment]
Ahhh, ok that helps; I'm assuming if that state directory doesn't match perfectly with the database, the whole thing will get rolled back? For example if I have a database that is one day old, but a ledger state that is one week old; it won't just roll back to the ledger state, but the entire db?

**Comment by erikd** [comment]
As long as the database is not behind the ledger state directory, it will only roll back to the latest point specified by the ledger state.

In the example you give, it will roll back a week, not the whole db.

**Comment by failfectionist** [comment]
Sweeet, thanks!
