### ISSUE TITLE
cardano-db-sync does not log output after start about inserting data

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-db-sync#6]
I followed the steps from building and running document for db-sync and the last line of output is:

> [db-sync-node:Info:1] [2020-03-03 15:36:41.01 UTC] localInitiatorNetworkApplication: connecting to node via "../cardano-node/state-node-staging/state-node-staging/node.socket"

There is no information about inserting data blocks anymore as it used to be for explorer - it this an expected behavior now ? 

```
$ PGPASSFILE=config/pgpass db-sync-node/bin/cardano-db-sync --config config/explorer-staging-config.yaml --genesis-file ../cardano-node/configuration/mainnet-genesis-dryrun-with-stakeholders.json --socket-path ../cardano-node/state-node-staging/state-node-staging/node.socket --schema-dir schema/ 
[db-sync-node:Info:1] [2020-03-03 15:36:31.50 UTC] NetworkMagic: RequiresNoMagic 633343913
[db-sync-node:Info:1] [2020-03-03 15:36:41.00 UTC] Initial genesis distribution populated. Hash c6a004d3d178f600cd8caa10abbebe1549bef878f0665aea2903472d5abf7323
[db-sync-node:Info:1] [2020-03-03 15:36:41.01 UTC] Total genesis supply of Ada: 31112484651.000000
[db-sync-node:Info:1] [2020-03-03 15:36:41.01 UTC] localInitiatorNetworkApplication: connecting to node via "../cardano-node/state-node-staging/state-node-staging/node.socket"
```

**Comment by erikd** [comment]
This is not `db-sync`. I had just tried mine and it logs just fine.

I suspect either your node or your byron proxy is not syncing and therefore not supplying blocks for db-sync.
