### ISSUE TITLE
Is there a way to get the actual sync progress of the db?

### ISSUE THREAD

**Issue by ggcaponetto** [input-output-hk/cardano-db-sync#602]
Hello

I can't figure out a way to get the sync progress of the db with a sql query. Is this even possible?

I guess that the only way to achieve this would be to query the **cardano-node** component that runs alongside the **cardano-db-sync** component.

I also feel somehow bad to post those questions as "issues" and i apologize. Is there some other channel I might use for this kind of conversation?

Have a great day!

**Comment by erikd** [comment]
All blocks in the db are time stamped. Therefore if you do:
```
select max (time) from block ; 
```
If the timestamp returned by the query is the same (within say 20 seconds) as the current UTC time, the database is fully synced.

**Comment by ggcaponetto** [comment]
Thank you @erikd. I will use the timestamp difference to calculate the approximate number of missing blocks. The 20s block production is a variable parameter in ouroboros if I am not wrong. It would be nice to be able to perform a sync progress check dynamically in the future somehow.

**Comment by erikd** [comment]
To get the sync progress as a number between `0` and `1`
```
select
   (extract (epoch from (max (time) at time zone 'UTC')) - extract (epoch from (min (time) at time zone 'UTC')))
      / (extract (epoch from (now () at time zone 'UTC')) - extract (epoch from (min (time) at time zone 'UTC')))
  from block ;
```

**Comment by erikd** [comment]
I will assume that the above (or better yet the query in the [interesting queries](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md) document satisfies this ticket and hence I will close it.
