### ISSUE TITLE
Pass in PG Connection string for Container.

### ISSUE THREAD

**Issue by bruceharrison1984** [input-output-hk/cardano-db-sync#612]
Can an environment variable be exposed to allow passing in a fully hydrated PG connection string? The current method of using secret files and PGPASSFILE is fairly esoteric, and to be frank, bizarre. 

Passing in connection strings is an accepted practice for this type of thing rather than relying on a container to build a file out of multiple one line secret files, then read the resulting file. This is a particular headache in K8s scenarios.

Alternatively, check if a custom PGPASSFILE is passed in, and use that if it is fully formed. Right now it always attempts to construct the PGPASSFILE, even if a complete connection string file has already been passed in.

It feels very strange right now that the hostname/port can be passed in, but username/password must be secrets. Multiple methods of injecting values is great but only when it is consistent.

**Comment by rhyslbw** [comment]
> The current method of using secret files and PGPASSFILE is fairly esoteric, and to be frank, bizarre.

The Docker design stems from supporting both `cardano-db-sync` and the official postgres image requirements, in addition to supporting the [best-practice of not passing sensitive information via ENVs](https://stackoverflow.com/questions/44615837/why-is-docker-secrets-more-secure-than-environment-variables
). 

> This is a particular headache in K8s scenarios.

How so? The transformation is an internal operation, so you should just be using the standard Docker secretes interface.

**Comment by bruceharrison1984** [comment]
Sorry, I forgot about this one.

I suppose my chief complaint here stemmed from PGPASSFILE being generated via the executable despite being visible in the repository. This was fairly mysterious and I didn't understand why passing in a fully complete PGPASSFILE still resulted in connection failure. It wasn't until I read the source code that  I understood that the 3 separate secrets are required, and put together behind the scenes to create what is then used as the connection string.

My k8s/docker complaint stemmed from passing in what feels to be an unnecessary amount of secrets, when one would easily suffice. Using Env/Secrets with Docker is a different debate altogether, and not one we should get into here. 🍺

This may just be a matter of opinion in terms of what form connection strings should be passed in, but slightly better documentation on the nuances of how the connection string is constructed would be helpful.

**Comment by erikd** [comment]
Documentation PRs accepted. I do not use Docker, so its up to you and Rhys to sort this out.

**Comment by erikd** [comment]
Closing this.
