### ISSUE TITLE
Kubernetes Deployment

### ISSUE THREAD

**Issue by KazW** [input-output-hk/cardano-db-sync#614]
I've been trying to figure out how to run a passive relay node with cardano-db-sync on Kubernetes. Setting up the node using a stateful set is pretty straight forward. Setting up db-sync is not as straight forward since it needs to connect to the node via a Unix socket.

I could hack this using socat, but I'd rather have the node socket connect via TCP directly, if possible. Any suggestions on the best approach would be greatly appreciated.

Documenting how this can be achieved would also be quite useful for anyone wanting to build something using cardano-db-sync on Kubernetes.

**Comment by erikd** [comment]
The local connection between the `node` and `db-sync` is **designed** to use a local domain socket. Surely there much be a way to allow this in Kubernetes. If not, I would suggest switching to Docker.

**Comment by KazW** [comment]
I managed to get this working with the Unix socket by using an emptyDir volume shared by the 2 containers in a stateful set. https://gist.github.com/KazW/c7ef4cad7806089de509e4c0e62f161d

**Comment by erikd** [comment]
Cool, that sounds like a sensible solution.

**Comment by rcmorano** [comment]
> I managed to get this working with the Unix socket by using an emptyDir volume shared by the 2 containers in a stateful set. https://gist.github.com/KazW/c7ef4cad7806089de509e4c0e62f161d

If you plan to separate node from db-sync into different statefulsets, you might want to use `socat` to transport the socket using TCP like this [0][1].

[0] https://gitlab.com/gimbalabs/dandelion/kustomize-dandelion/-/blob/main/base/cardano-node/statefulset.yaml#L74
[1] https://gitlab.com/gimbalabs/dandelion/kustomize-dandelion/-/blob/main/base/cardano-db-sync/statefulset.yaml#L84
