### ISSUE TITLE
Couldn't parse field `state` from table `epoch_sync_time`. Cannot convert PersistLiteral to Text

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-db-sync#623]
`node`: 1.27.0
`db-sync`: commit 38769647f126b8c68083aaafe3bee1751789a055 on `release/10.0.x`
`network:` mainnet, shelley-qa, (this is related to new table `epoch_sync_time` so it is rather network "independent" issue)

Both components built with `nix`, as in instruction. Logs attached at the end of ticket.

After `db-sync` was successfully built and started for the first time on `release/10.0.x` branch I stopped it and then stopped node. After starting `node` again (no errors):

>[artur-li:cardano.node.ChainDB:Notice:56] [2021-05-31 16:29:57.66 UTC] Chain extended, new tip: 49cbe5b80894edeb86b6d69fe8098847de97c6e609b0731b2a06707b4f5e70dd at slot 30912306
[artur-li:cardano.node.ChainDB:Notice:56] [2021-05-31 16:30:21.78 UTC] Chain extended, new tip: 47621563a245febff8861ecbf5652f8cc30ee2d44fd6a3406dacb8c2d95de785 at slot 30912330

I started `db-sync` again and there are errors in the logs informing about parsing issues, this keeps repeating - subscription being restarted and then again parsing error showing up, in the loop:

> db-sync-node:Info:54] [2021-05-31 16:30:28.50 UTC] thisIsAnUglyHack: Main thead
[db-sync-node:Error:54] [2021-05-31 16:30:28.50 UTC] runDBThread: PersistMarshalError "Couldn't parse field `state` from table `epoch_sync_time`. Cannot convert PersistLiteral to Text"
[db-sync-node:Error:49] [2021-05-31 16:30:28.50 UTC] ChainSyncWithBlocksPtcl: PersistMarshalError "Couldn't parse field `state` from table `epoch_sync_time`. Cannot convert PersistLiteral to Text"
[db-sync-node.Mux:Info:46] [2021-05-31 16:30:28.50 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"} event: State: Dead
[db-sync-node.Mux:Notice:46] [2021-05-31 16:30:28.50 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-mainnet/node.socket"} event: Miniprotocol MiniProtocolNum 5 InitiatorDir terminated with exception PersistMarshalError "Couldn't parse field `state` from table `epoch_sync_time`. Cannot convert PersistLiteral to Text"
[db-sync-node.Subscription:Error:45] [2021-05-31 16:30:28.50 UTC] Identity Application Exception: LocalAddress "../cardano-node/state-node-mainnet/node.socket" PersistMarshalError "Couldn't parse field `state` from table `epoch_sync_time`. Cannot convert PersistLiteral to Text"
[db-sync-node.ErrorPolicy:Error:6] [2021-05-31 16:30:28.50 UTC] IP LocalAddress "../cardano-node/state-node-mainnet/node.socket" ErrorPolicyUnhandledApplicationException (PersistMarshalError "Couldn't parse field `state` from table `epoch_sync_time`. Cannot convert PersistLiteral to Text")
[db-sync-node.Subscription:Notice:44] [2021-05-31 16:30:29.51 UTC] Identity Restarting Subscription after 1.767893481s desired valency 1 current valency 0
[db-sync-node.Subscription:Notice:44] [2021-05-31 16:30:37.75 UTC] Identity Starting Subscription Worker, valency 1

and on the node side those errors appeared right after starting `db-sync`:

>[artur-li:cardano.node.ChainDB:Notice:56] [2021-05-31 16:30:21.78 UTC] Chain extended, new tip: 47621563a245febff8861ecbf5652f8cc30ee2d44fd6a3406dacb8c2d95de785 at slot 30912330
[artur-li:cardano.node.LocalErrorPolicy:Error:84] [2021-05-31 16:30:28.51 UTC] IP LocalAddress "" ErrorPolicyUnhandledApplicationException (MuxError (MuxIOException writev: resource vanished (Broken pipe)) "(sendAll errored)")
[artur-li:cardano.node.LocalErrorPolicy:Error:84] [2021-05-31 16:30:39.47 UTC] IP LocalAddress "" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 36> closed when reading data, waiting on next header True")

Stopping and starting services again did not help with that db-sync parsing error.

Logs:
[db_sync_errors_mainnet_logs.txt](https://github.com/input-output-hk/cardano-db-sync/files/6571502/db_sync_errors_mainnet_logs.txt)

[node_errors_mainnet_logs.txt](https://github.com/input-output-hk/cardano-db-sync/files/6571508/node_errors_mainnet_logs.txt)

**Comment by erikd** [comment]
I was able to replicate this, but after that error is reported, `db-sync` seems to continue to work correctly.

Yes, I will fix this, but this error seems to be pretty benign.
