### ISSUE TITLE
how to build the carrano-db-sync

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-db-sync#631]

**Comment by malingzhao** [comment]
how to use the cardano-db-sync

**Comment by erikd** [comment]
iAt the bottom of the repo README, there is a lint titled "Building and Running".

**Comment by malingzhao** [comment]
thank you, I have already compelete wallet and node&nbsp; using docker , So I want to know how to use docker to compelete the install



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Erik de Castro ***@***.***&gt;; 
发送时间: 2021年6月4日(星期五) 下午3:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [input-output-hk/cardano-db-sync] how to build the carrano-db-sync (#631)





 
At the bottom of the repo README, there is a lint titled "Building and Running".

**Comment by malingzhao** [comment]
-v $PWD/node-ipc:/node-ipc \ what's the node-ipc , I want to know about it

**Comment by erikd** [comment]
What does the wallet have to do with `db-sync` ?

> -v $PWD/node-ipc:/node-ipc \ what's the node-ipc , I want to know about it

@rhyslbw Docker related ^^ .

**Comment by rhyslbw** [comment]
This is the shared volume allowing `cardano-db-sync` to gain access to the `cardano-node` IPC socket. It's demonstrated in the [docker-compose.yml](https://github.com/input-output-hk/cardano-db-sync/blob/master/docker-compose.yml)
