### ISSUE TITLE
best practices for syncing

### ISSUE THREAD

**Issue by tokumine** [input-output-hk/cardano-db-sync#633]
hello there,

doing a full sync is painfully slow from epoch 265 onwards (10+hours per epoch). are there best practices for the setup during sync that can speed up there process? we have disabled vacuum and are looking at disabling indexes, but have a fairly vanilla postgres setup. is there a recommended postgres config?

love the recent commits that will support downloading a pre-existing dump - that's help next time we get ledger corruption! (did everyone need to re&sync recently?)

thank you!

**Comment by erikd** [comment]
First of all, make sure the machine you are running on is [proper speced](https://github.com/input-output-hk/cardano-db-sync#system-requirements).

Second, it you are running Postgres on a separate machine to `db-sync` , sync times will be 4 times or more slower than if the database and `db-sync` are on the same machine (this is also mentioned in the system requirements).

I always run Postgres and `db-sync` on the same machine and currently syncing the full chain (to epoch 270) takes about 20 hours.

**Comment by erikd** [comment]
@tokumine It would be extremely useful if you were able to report back on whether your machine is properly spec-ed and whether you are running Postgres and `db-sync` on the same machine.

**Comment by tokumine** [comment]
Thank you! Sorry for the delay. Yes, we ran db-sync and postgres on the same machine and clocked in at around 36hrs on a Digital Ocean 8Gb/4CPU Server (which I see is underspecced). We had also tried to run it on our 16Gb server that was also running other services on and it seemed to choke. If there are any other best practices in addition to better specs that'd be really great to learn about. 

Thanks!

**Comment by erikd** [comment]
I have run `db-sync` on a Digital Ocean instance and 36 hours to sync seems about right (about 1.5 time what I see on my VM). I suspect the Digital Ocean machines are about 50% a bit slower than my VM. This could be CPU/RAM speed or it could be disk throughput related.

I am working on a best practices document but that should include:

* Meet system requirements (including using solid state disks instead of electo-mechanical ones).
* Run PostgreSQL on the same machine.

**Comment by tokumine** [comment]
great. thanks Erik

**Comment by tokumine** [comment]
on thing that did occur to me is that the Digital Ocean machines may well be using some type of network attached storage (it's abstracted after all). thanks for corroborating our speeds though. appreciate it.

**Comment by nykfank** [comment]
Has anyone tried to disable WAL (write ahead log) in postgresql by running "ALTER TABLE table_name SET UNLOGGED" on all the tables in the cexplorer schema?
