### ISSUE TITLE
[FR] - Fetching Operational Certificate counter in block table

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-db-sync#641]
Currently `block` table includes op_cert column, but the value of op_cert is `KesVerificationKey_ed25519_kes_2^6` .
While this is useful to verify the block, it does not allow to get the counter (number of rotations of KES key).

![image](https://user-images.githubusercontent.com/3169068/121486400-740b8200-ca14-11eb-96a2-9d7e841ddcdb.png)

It would be nice to be able to fetch `ocertN` against block which will allow SPO to recreate the hot KES key with precision, simply using their cold keys and not worrying about surety of whether they rotated with newer counter.

Context:
If a SPO restores a backup cold.counter file accidentally overwriting their current operational certificate and cold-counter. This will allow us to add verification to CNTools to ensure that operators are deriving it to a newer counter (instead of single increment currently in place in all the guides/tools).

**Comment by erikd** [comment]
Currently we store the value `ocertVkHot` but @rdlrt is requesting that we also store `ocertN` .
