### ISSUE TITLE
Come up with a better way of storing Alonzo language cost models

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#652]
Currently these are just stored serialized as Text. which is rather suboptimal as can be seen in [this comment](https://github.com/input-output-hk/cardano-db-sync/pull/649#issuecomment-862597490).

We should come up with a better way.

**Comment by kderme** [comment]
I asked ledger and plutus teams and it seems these parameters like `if_then_else-cpu-arguments`, `eq_integer-memory-arguments` are not stable at all (not the values, but the fields themshelves). So probably we want to avoid creating tables with columns that will change all the time. 

Maybe we can store in a json format, that someone could parse if necessary?

**Comment by erikd** [comment]
Yes, converting to JSON makes sense. We should also put it in a separate table to make sure we are not storing multiple copies of exactly the same thing.

**Comment by erikd** [comment]
Currently there is a `cost_model` column which looks like:
```
fromList [(PlutusV1,"fromList [( ...
```
which is just the text serialized Haskell data structure.

Instead we should convert it to JSON and store it in its own table (to prevent any possible duplication)
