### ISSUE TITLE
How to use a remote postgres instance instead of locally

### ISSUE THREAD

**Issue by Josema** [input-output-hk/cardano-db-sync#653]
I've edited my `PGPASSFILE=config/pgpass-mainnet` using the same credentials that I'm using for my computer client to connect. And it looks like this:
```
my.whatever.ip:5432:postgres:MyPassWord
```

But when I run `PGPASSFILE=config/pgpass-mainnet scripts/postgresql-setup.sh --check` I get this error:
```
Error : User 'ubuntu' can't access postgres.

To fix this, log into the postgres account and run:
    createuser --createdb --superuser ubuntu
```

**Comment by erikd** [comment]
Running `db-sync` and PostgreSQL on separate machines is explicitly recommended against in the [System Requirements](https://github.com/input-output-hk/cardano-db-sync#system-requirements) section of the main Readme file in the repo. Running them separate machines leads to sync times that are 4 times or more slower than the recommended configuration.
