### ISSUE TITLE
Error parsing node config: AesonException AlonzoGenesisFile not found

### ISSUE THREAD

**Issue by leobel** [input-output-hk/cardano-db-sync#656]
I'm trying to run `cardano-db-sync` with a local-cluster from: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/shelley/exe/local-cluster.hs

```
PGPASSFILE=config/pgpass-mainnet db-sync-node/bin/cardano-db-sync  \ 
--config config/mainnet-config.yaml  \
--socket-path /tmp/test-cluster1314319/node/node.socket  \
--state-dir ledger-state/mainnet  \
--schema-dir schema/
```

but I got this message:

```
FatalError {fatalErrorMessage = "Error parsing node config: AesonException \"Error in $: key \\\"AlonzoGenesisFile\\\" not found\""}
```

**Comment by erikd** [comment]
if you are building from the `master` branch, you are building new code that has not been released.

Instead, you should be building from the `9.0.0` release tag or the soon to be released `release/10.0.x` branch.
