### ISSUE TITLE
Restarting db-sync can result in loss of volatilve data.

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#657]
Data that is in memory (like rewards and stake distribution) and not yet inserted in the database will be lost if `db-sync` is stopped and restarted.

~My mainnet instance is now in epoch `273` but the rewards table for epoch `271` have not been inserted yet.~

~This is probably due to a2fb225ac0fbc3c8ae4c5d1cf63eeabcfc74cbf0 .~

**Comment by erikd** [comment]
When the letdger state provides the set of rewards for an epoch, they are stuck in a queue so that insertion of the reward data can be interleaved with regular blockchain data. If `db-sync` is stopped and restarted, the data in the queue is lost and never gets inserted in the database.

**Comment by erikd** [comment]
There are a number of reasons `db-sync` might be stopped requiring a restart:

* User initiated `control-C`.
* OS initiated stop (eg killed by the OOM killer).
* Machine reboot (for whatever reason).

The easiest and most obvious solution would be the one provided by an improved ledger state API that would not require `db-sync` to maintain its own ledger state.

**Comment by erikd** [comment]
A possible (but somewhat rather fiddly) solution would be to get the original data from the ledger and then immediately store it on disk. When all this volatile data has been inserted into the database, the file can be deleted. On restart, `db-sync` could check if there is a data file and if there is load it and start or continuing inserting.

There are a bunch of problems with this solution. It add yet more complexity, it has a bunch of corner cases that must all be handled correctly and it is likely to be fragile.

**Comment by kderme** [comment]
What about the solution I propose here https://github.com/input-output-hk/cardano-db-sync/issues/665?
In that ticket I meant ledger file snapshots, not the full db snapshots that were recently introduced.
If we never take ledger snapshots when there are volatile data, after a restart, dbsync will rollback to a point that is old enough and the rewards/stake will become available and pushed to the queue again.

**Comment by erikd** [comment]
That will not help because this is a problem we can run into without snapshots. I have seen this when I just stop and restart `db-sync` at the right time.

**Comment by kderme** [comment]
> As an example, if a LedgerRewards even is received and we wait for at least one more block, and then stop/restart db-sync, then all of the rewards that were queued internally will be lost,

Won't dbsync rollback to a previous state and get this reward once again?

**Comment by erikd** [comment]
No it does not. If `db-sync` is shut down cleanly, there is unlikely to be any rollback at all. However if before the shutdown there is rewards data in queue, it will be lost, and cannot be recreated without a rollback to where the rewards are available, with may actually be more than 8 blocks (assuming chain following rather than syncing).

**Comment by kderme** [comment]
Ok I had in mind a chain syncing not following.
We need a different solution for a chain following. One idea is to switch to keeping latest k ledger states in memory, instead of storing every single ledger checkpoint on disk. This is also what the LedgerDB in the node does.

**Comment by kderme** [comment]
I think we have to make sure to flush all the volatile data in TBQueue's, handle them and commit them in db, before taking a ledger snapshot

**Comment by erikd** [comment]
> One idea is to switch to keeping latest k ledger states in memory, instead of storing every single ledger checkpoint on disk. This is also what the LedgerDB in the node does.

The fact that we have two instances of ledger state; one in `node` and one in `db-sync` really grinds my gears. We have two implementaion of what is basically the same thing.
