### ISSUE TITLE
Database Support for Shelley Era Blocks, Transactions and Ledger State Information [CD-6]

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-db-sync#66]
We need to adapt the existing database format and tools to support the needs of the new GraphQL dashboard/explorer and other internal or external tools.  In essence, this involves:

1. Agree on the data requirements with the explorer team

2. Adapt the existing PostgreSQL database schema for Byron to support the new Shelley era block, transaction and other data
         including address format and other changes

3.  Normalise the schema if necessary to optimise the data storage and database performance
         extend the existing schema

4.  Provide any necessary interfacing code
         to abstract over raw SQL code (e.g. db_add_new_block(...))
         (this may involve changing existing calls to deal with additional information or the new schema)

5.  Include calls in the node to record basic on-chain data
          block creation and embedded transactions

6.  Include calls to record off-chain data obtained from the ledger state
          rewards calculations
          treasury and reserves levels
          (may require code to be inserted at the epoch boundary transition - beware of data insertion cost
           - might need a separate thread to achieve this efficiently)

7.  Include basic abstractions over transactions
          pool registration/deregistration
          stake key registration/deregistration
          delegations
          ...
          (needs to be done during transaction insertion - make sure this is efficient - it will be on the critical performance path)

8.  Extend to include more complex transactions
          parameter protocol updates (may require replay of the voting mechanism)

Note that the database will need to be migrated to the new format.  We will not be able to use the existing database.

**Comment by erikd** [comment]
Closing this as it is basically done. Will track the remaining work in more fine grained tickets.
