### ISSUE TITLE
Take snapshots only when there are no volatile data in memory

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#665]
I was benchmarking dbsync, which included stopping and restarting it many times. I notices that rewards for epoch 250 were missing, while rewards for later epochs existed in db. I believe this happened because rewards stay in memory for some time. If a snapshot is taken before rewards are inserted and dbsync restarts, these rewards get lost.

A solution is to never take a snapshots while a reward/stake is still in memory. Another solution is to only take snapshots on epoch boundaries. Profiling already indicates that taking snapshots has an impact in sync times, so reducing the snapshots can help there.

**Comment by erikd** [comment]
Firstly, snapshots should only be taken when `db-sync` is stopped. Is there a way we can ensure this?

Also think this is related to issue https://github.com/input-output-hk/cardano-db-sync/issues/657
