### ISSUE TITLE
Connection to node.socket refused

### ISSUE THREAD

**Issue by mikaint** [input-output-hk/cardano-db-sync#673]
I'm trying to set up cardano in Kubernetes and cardano-db-sync fails.

`[db-sync-node.Subscription:Notice:1322] [2021-06-26 14:53:44.18 UTC] Identity Connection Attempt Start, destination LocalAddress "/ipc/node.socket"
[db-sync-node.Subscription:Error:1322] [2021-06-26 14:53:44.18 UTC] Identity Connection Attempt Exception, destination LocalAddress "/ipc/node.socket" exception: Network.Socket.connect: <socket: 14>: does not exist (Connection refused)
[db-sync-node.ErrorPolicy:Warning:4] [2021-06-26 14:53:44.18 UTC] IP LocalAddress "/ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 14>: does not exist (Connection refused))) 20s 20s
[db-sync-node.Subscription:Warning:45] [2021-06-26 14:53:44.21 UTC] Identity Failed to start all required subscriptions`

/ipc/node.socket exists in cardano-db-sync's pod. I also have transaction & relay nodes running in different pods and working fine.

**Comment by erikd** [comment]
Sorry, I know what Kubernetes is, but I have never used it and know close to nothing about it.

However `db-sync` **requires** a locally running `cardano-node` from which to get block chain data.

**Comment by vbonini** [comment]
I may be able to help here. It took us some time to think of a solution, but we created a PVC and gave cardano-node and cardano-db-sync (and also wallet) access to it. Mount them internally as `/ipc` and `/node-ipc` respectively. Then start cardano-node up first. After about ~10 mins or so, spin up cardano-db-sync which can then use `node.socket` on the volume. 

Also make sure these Cardano components are all running on the same worker via labels or NodeSelector or whichever your preference, so they all have access to the volume.

**Comment by erikd** [comment]
So this is a Kubernetes specific issue? Can I close it?

**Comment by erikd** [comment]
Closing this.
