### ISSUE TITLE
Project build fails

### ISSUE THREAD

**Issue by oskin1** [input-output-hk/cardano-db-sync#675]
Getting error when trying to build tag `10.0.0` with `stack build`:
`No cabal file found for Repo from https://github.com/input-output-hk/cardano-node, commit e730ea84310e19e036eca382855acc4e35af717c in subdir hedgehog-extras`

Am I doing something wrong?

**Comment by erikd** [comment]
Yeah, do not build with `stack`. Build with `cabal` instead, because all the current devs build with cabal.

I should delete the `stack.yaml` file.
