### ISSUE TITLE
Rewards that should be orphaned are not

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#681]
Getting stake addresses that have been de-registered and the epoch in which they were deregistered (on mainnet) and doing that for one specific recent epoch:

```sql
select stake_deregistration.*, block.epoch_no from stake_deregistration
    inner join tx on tx.id = stake_deregistration.tx_id
    inner join block on tx.block_id = block.id
    where block.epoch_no = 272 order by addr_id asc limit 10 ;
  id   | addr_id | cert_index |  tx_id  | epoch_no
-------+---------+------------+---------+----------
 65084 |   11559 |          0 | 8894495 |      272
 66190 |   14916 |          0 | 8996255 |      272
 65621 |   43137 |          0 | 8939941 |      272
 65240 |   61948 |          0 | 8907021 |      272
 65876 |   66661 |          0 | 8962414 |      272
 65002 |   66713 |          0 | 8888638 |      272
 65197 |   70235 |          0 | 8902308 |      272
 65618 |   71176 |          0 | 8939782 |      272
 65281 |   78388 |          0 | 8910427 |      272
 65589 |   80403 |          0 | 8937469 |      272
(10 rows)
```
The first four addresses above have no rewards, but the fifth:
```sql
select * from reward where addr_id = 66661 and epoch_no >= 272 ; 
    id    | addr_id |  type  | amount | epoch_no | pool_id 
----------+---------+--------+--------+----------+---------
 13620650 |   66661 | member | 586586 |      274 |   13175
 13010336 |   66661 | member | 476142 |      273 |    5607
 12410442 |   66661 | member | 888858 |      272 |    5607
(3 rows)
```
but has no `orphaned_reward` entries:
```sql
select * from orphaned_reward where addr_id = 66661 and epoch_no >= 272 ; 
 id | addr_id | type | amount | epoch_no | pool_id 
----+---------+------+--------+----------+---------
(0 rows)
```
I suspect that all the entries shown in the `reward` table above should be in the `orphaned_reward` table.

**Comment by erikd** [comment]
Had a chat with @JaredCorduan and he agrees that the three entries in the `reward` table above should instead be in the `orphaned_reward` table.

Studied the logic that splits `orphaned_reward` entries out from `reward` entries and I am just using what is provided by the `ledger-specs` library. I may be using the data provided by the `ledger-specs` library incorrectly but it seems like a bad idea for `db-sync` to be "emulating" an operation done internally in `ledger-specs` and then expecting the results of the "emulation" to be the same as the what it is emulating.

The obvious solution is for `ledger-specs` to provide some way of distinguishing orphaned from non-orphaned rewards.

**Comment by erikd** [comment]
Something incredibly odd going on here.

The code for extracting rewards from ledger state is [here](https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-sync/src/Cardano/Sync/Era/Shelley/Generic/Rewards.hs#L66-L101) and for inserting that data into the database is [here](https://github.com/input-output-hk/cardano-db-sync/blob/master/cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Insert/Epoch.hs)

Assuming that the above function is called in epoch `273` (with the reward rewards for epoch `272` and which become spendable after the start of epoch `274`), the address (which was de-registered in epoch `272`) should not be in the `rewardAccounts` map, so rewards for epoch `272` and later should all be orphaned. Why aren't they?

**Comment by erikd** [comment]
:sob: The address was deregistered and then re-registered all within epoch `272`:
```sql
select stake_registration.*, block.block_no, block.epoch_no from stake_registration
    inner join tx on tx.id = stake_registration.tx_id
    inner join block on tx.block_id = block.id
    where stake_registration.addr_id = 66661 order by epoch_no asc ;
   id   | addr_id | cert_index |  tx_id  | block_no | epoch_no 
--------+---------+------------+---------+----------+----------
  48318 |   66661 |          0 | 2524573 |  4540050 |      210
 117264 |   66661 |          0 | 3138246 |  5038648 |      233
 736504 |   66661 |          0 | 8962433 |  5862355 |      272
(3 rows)
```
The de-registractions are:
```sql
select stake_deregistration.*, block.block_no, block.epoch_no from stake_deregistration
    inner join tx on tx.id = stake_deregistration.tx_id
    inner join block on tx.block_id = block.id
    where stake_deregistration.addr_id = 66661 order by epoch_no asc ;
  id   | addr_id | cert_index |  tx_id  | block_no | epoch_no 
-------+---------+------------+---------+----------+----------
  2610 |   66661 |          0 | 3138112 |  5038582 |      233
 65876 |   66661 |          0 | 8962414 |  5862354 |      272
(2 rows)
```
Since the last operation (by block number, which is strictly monotonic increasing) is a registration, the stake address is valid when reward distribution for epochs `272` , `273` and `274` are done, so these rewards are correctly entered into the `reward` table and this stake address has no entries in the `orphaned_reward` table.

**Comment by erikd** [comment]
So while the above is **not** a bug, the fact that `db-sync` has any of this logic at all means there is potentially still room for one.

Having two implementations of what is supposed to be the same logic is just an incredibly bad idea.

**Comment by erikd** [comment]
Closing this.

**Comment by JaredCorduan** [comment]
I totally agree that having to re-implement this logic is asking for trouble!
