### ISSUE TITLE
Docker image startup issue

### ISSUE THREAD

**Issue by Daennes** [input-output-hk/cardano-db-sync#686]
Hello,
I have upgraded from version 9 to 10 which is causing a startup problem. Tested it with both my existing setup and a clean docker state setup.
Used unmodified Docker compose file to spin up the services.

Tested on Ubuntu 20.04 and MacOS 11.4

```
/run/secrets
Generating PGPASS file
Connecting to network: mainnet
/nix/store/xirfrf8q9kdj2hjcfrwbqwv7qhip0nnz-entry-point/bin/entry-point: line 26: /nix/store/3pvccdbrmaih10f6xf1csm1fjrsy72w2-cardano-db-sync-mainnet: Is a directory
/nix/store/xirfrf8q9kdj2hjcfrwbqwv7qhip0nnz-entry-point/bin/entry-point: line 26: exec: /nix/store/3pvccdbrmaih10f6xf1csm1fjrsy72w2-cardano-db-sync-mainnet: cannot execute: Is a directory
```

**Comment by tobg** [comment]
Same issue here

**Comment by erikd** [comment]
This was fixed in https://github.com/input-output-hk/cardano-db-sync/pull/690 . Unfortunately that did not make the `10.0.0` release, but the `docker-compose.yaml` file can be copied from `master`.

**Comment by vbonini** [comment]
Continuing the failing startup problem:

I had the same issue. I deployed the `master` image but get a new error.  For reference I'm trying to use non-extended service. 

Please let me know if you want me to open a new issue for this. 

```
/run/secrets
Generating PGPASS file
Connecting to network: mainnet
cardano-db-sync-extended: FatalError {fatalErrorMessage = "Error parsing node config: AesonException \"Error in $: key \\\"AlonzoGenesisFile\\\" not found\""}
```

**Comment by erikd** [comment]
@vbonini `master` is updated almost daily. Users should avoid `master` and should only use tagged releases.

**Comment by vbonini** [comment]
Thank you for the confirmation. 

So we are using K8s for our deployment, and pulled the `10.0.0` image when we saw the original issue. I can recreate and plug in the modified file in #690 if I need to. Where should that file go?

**Comment by erikd** [comment]
I have asked the release manager if we should do a release just to fix this docker issue.

**Comment by erikd** [comment]
There will be a `10.0.1` release.
