### ISSUE TITLE
hurdles restoring from snapshot via dockerized cardano-db-sync

### ISSUE THREAD

**Issue by edwmurph** [input-output-hk/cardano-db-sync#691]
- `cardano-db-tool` is not currently baked into the image but it's necessary for doing snapshot restores. can `cardano-db-tool` be baked into the docker image going forward?
- `postgresql-setup.sh` is required for restoring from the snapshot but i can't find it on the `cardano-db-sync` image. i could manually copy it over but it would be ideal if it was also baked into the image to facilitate setting up automation on my end for restoring from snapshots

**Comment by erikd** [comment]
`cardano-db-tool` is needed for snapshot creation, but not restoration.

**Comment by edwmurph** [comment]
@erikd oh great! it would still be helpful though if `cardano-db-tool` was baked into the docker image for creating custom snapshots going forward but for the near term, just baking the `postgresql-setup.sh` script into the docker image would help a lot

**Comment by erikd** [comment]
I know close to zero about Docker, so I would love to get a fix for this (and instructions on how to test it). PRs gladly accepted.

**Comment by edwmurph** [comment]
looks like you guys use nix so im not exactly sure how to implement this

**Comment by erikd** [comment]
OK, we have someone on it, but they may not get to it immediately.

**Comment by jbgi** [comment]
initial implementation in https://github.com/input-output-hk/cardano-db-sync/pull/712
(still need some testing)

**Comment by erikd** [comment]
#712  has been merged to `master` and cherry picked into the `release/10.0.x` branch which will be released as `10.0.2`.
