### ISSUE TITLE
rewards table should track rewards received from treasury/reserves by MIR process

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-db-sync#695]
There isn't a good authoritative source for this using just db-sync. I suggest rewards table should have a reward_type as an enum POOL|TREASURY|RESERVE and any rewards paid out from treasury/reserve at epoch boundary should be logged in this table.

**Comment by erikd** [comment]
This would need to be implemented in `ledger-specs` first.

**Comment by JaredCorduan** [comment]
What do you think needs to be implemented in ledger-specs? Rewards from pools come via the reward updates, the other rewards come via the MIR certs, marked as either `Treasury` or `Reserves`.

**Comment by erikd** [comment]
As far as `db-sync` and the actual accounting is concerned, there is no real difference whether rewards come from owning/delegating to a pool or from reserves/treasury.

Secondly pulling treasury and reserve rewards out of the transactions (where the `MIR` certs are) is **way** more complicated than pulling them out of the ledger state.

In my ideal API, staking rewards and reserves/treasury rewards would all be lumped together in one big map, with each reward being tagged with where it came from (eg `LeaderReward` , `MemberReward` , `TreasuryPayment` or `ReservesPayment`).

**Comment by vsubhuman** [comment]
> In my ideal API, staking rewards and reserves/treasury rewards would all be lumped together in one big map, with each reward being tagged with where it came from (eg LeaderReward , MemberReward , TreasuryPayment or ReservesPayment).

As I understand different kinds of rewards might have different "enabling" formula as a function of their "epoch" parameter. E.g. delegation rewards inserted during epoch `N` would have "epoch" value equal to `N-1` but would only be spendable starting with `N+1`. Meanwhile any MIR inserted durin epoch `N` would have "epoch" value equal to `N` but would be spendable also from `N+1`, is that correct?

@erikd, just confirming, do you plan to add the `spendable_epoch` column (as discussed here: https://github.com/input-output-hk/cardano-db-sync/pull/704#issuecomment-885326111) to encapsulate all this difference?

**Comment by erikd** [comment]
Yes, there will be two columns, `earned_epoch` and `spendable_epoch` .
