### ISSUE TITLE
incorrect handling of metadata url in some cases

### ISSUE THREAD

**Issue by cardanians** [input-output-hk/cardano-db-sync#697]
poolId: `pool1l92x52u37neuc2w38wrgeu3esu9qzddmzvkvyuf9vfk5gav8nxl`

```sql
SELECT * FROM public.pool_offline_fetch_error
    WHERE fetch_error LIKE '%pool1l92x52u37neuc2w38wrgeu3esu9qzddmzvkvyuf9vfk5gav8nxl%'
````

if the metadata fails to download several times, it will stop downloading again.

This is fine in a way (but it might be worth repeating once a day anyway, wouldn't it?). however, they will not start re-fetching if the pool updates its poolcert.

![obrazek](https://user-images.githubusercontent.com/58650764/126069818-5b72d72e-eab6-4fef-885e-5b3a4227769f.png)

Look on screen.

1) 13.7. some fetch tests with fail
2) 17.7. reregistered pool
3) then no other fetching...

![obrazek](https://user-images.githubusercontent.com/58650764/126069895-e75047c2-50fa-4c56-b507-c04d75b053ef.png)

Second thing is, why is this new meta url not saved in DB? He registered first url with typo "BLOOIR" (in db). Then re-registered with fix, but in db is no record about this.

latest version (v10)

**Comment by erikd** [comment]
Please do not post images in bug reports. Instead, please cut and paste the text.

**Comment by erikd** [comment]
There seem to be two issues here, and the do not seem to be well distinguished.

The first problem, is that if a `PoolMetadataRef` update for the same `PoolId` and same metadata `hash`, but a different `url` will not update the table. This is due to and incomplete uniqueness constraint.

The second issue seems to be a failure to parse some URLs.

**Comment by erikd** [comment]
It seems like the error with the uniqueness constraint is confounding and confusing the other problems, so I will fix that first.

**Comment by erikd** [comment]
Lets find the pool id:
```sql
select id, view from pool_hash where view = 'pool1l92x52u37neuc2w38wrgeu3esu9qzddmzvkvyuf9vfk5gav8nxl' ;
  id   |                           view                           
-------+----------------------------------------------------------
 18067 | pool1l92x52u37neuc2w38wrgeu3esu9qzddmzvkvyuf9vfk5gav8nxl
(1 row)
```
and the `pool_metadata_ref`:
```sql
select * from pool_metadata_ref where pool_id = 18067 ;
  id   | pool_id |             url             |                  hash                 | registered_tx_id 
-------+---------+-----------------------------+---------------------------------------+------------------
 18012 |   18067 | https://blooir.com/MTD.json | \x3f192a9740e983b...7028a25fcc99400dc |          8197291
 18015 |   18067 | https://booir.com/MTD.json  | \x3f192a9740e983b...7028a25fcc99400dc |          8198428
(2 rows)
```
Did not pick up any `pool_offline_fetch_error`s for this `pool_id`:
```sql
select * from pool_offline_fetch_error where pool_id = 18067 ;
 id | pool_id | fetch_time | pmr_id | fetch_error | retry_count 
----+---------+------------+--------+-------------+-------------
(0 rows)
```
Not sure if there is another error in here somewhere, but the main one is fixed.

**Comment by cardanians** [comment]
@erikd ok awesome! can you please push new resease into world? with this + rewards, thanks.

**Comment by erikd** [comment]
There is one ore thing that needs fixing, before a new release, but that should be done this week.
