### ISSUE TITLE
nullTracers

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-db-sync#7]
Checking the `cardano-explorer` code I found a few `nullTracers` which should not be in a production code.  This will not allow us to debug the application, and should not be in a production code.

* [ncSubscription_V1 traces](https://github.com/input-output-hk/cardano-explorer/blob/master/cardano-explorer-node/src/Explorer/Node.hs#L203)
* [handshake tracer](https://github.com/input-output-hk/cardano-explorer/blob/master/cardano-explorer-node/src/Explorer/Node.hs#L201)
* [mux tracer](https://github.com/input-output-hk/cardano-explorer/blob/master/cardano-explorer-node/src/Explorer/Node.hs#L200)
* [chain-sync tracer](https://github.com/input-output-hk/cardano-explorer/blob/master/cardano-explorer-node/src/Explorer/Node.hs#L254)

**Comment by erikd** [comment]
I have looked at the `ToObjectOrphans.hs` module in `cardano-node` (it has moved to https://github.com/input-output-hk/cardano-node/blob/master/cardano-config/src/Cardano/Tracing/ToObjectOrphans.hs ).

That is 1300 lines of code which I think is rather a lot. That gives me two options, copy/paste it from `node` which seems insane, or pull in `cardano-node` as a dependency (`db-sync`) does not otherwise depend on node (which also seem insane).

Even if I do one of the above, what do I replace the `nullTracer` with?

**Comment by coot** [comment]
Yes, copying all is not good, a long term solution, in my opinion, is to add  `cardano-monitoring-framework` library which has all the instantiations, and is easily reusable by other clients. 

> Even if I do one of the above, what do I replace the nullTracer with?
You must have a top level `tracer`.  It should be general enough to use its contravarince to transform it to the form required by the network tracers. `cardano-node` does this in `Cardano.Tracing.Tracers`. Again there's a lot of code, some more specific to the node (e.g. consensus tracers, network tracers for node to node protocols).

There's also work on `cli` tools, but it lives inside `cardano-node`.  They should pull it out and set a proper boundaries between clients and the node code.

**Comment by disassembler** [comment]
The current problem we don't know how to debug is:

**Comment by erikd** [comment]
Proper tracers are in https://github.com/input-output-hk/cardano-db-sync/pull/8 which has not yet been merged due to CI issues.

**Comment by coot** [comment]
Still with the proper tracers we couldn't see anything useful in the logs, even if enabled `Debug` severity (see my branch [coot/haskell-updates](https://github.com/input-output-hk/cardano-db-sync/commit/84b106d23e10132252c79820b76ccc376dceee34).  @karknu replaced the logging trace with `stdoutTracer` and was able to get the information that we needed to debug the connection issue.  This suggest that there's something wrong with the configuration of the loggers.

^ @CodiePP

**Comment by erikd** [comment]
The tracers fix has been merged to master. Closing this.
