### ISSUE TITLE
Improve epoch table calculation

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#708]
The `Epoch` table contains a row per epoch for like the following:

```sql
select * from epoch where no = 250 ;
 id  |      out_sum      |    fees     | tx_count | blk_count | no  |     start_time      |      end_time       
-----+-------------------+-------------+----------+-----------+-----+---------------------+---------------------
 251 | 48999055712564141 | 41831556274 |   192598 |     20991 | 250 | 2021-02-24 21:44:51 | 2021-03-01 21:44:44
(1 row)

```

When `db-sync` is syncing the row is updated once per epoch via an SQL query that aggregates the data for the epoch and then writes a row to the database.

When `db-sync` is following the chain tip, the row for the current epoch is updated after every block, also via an SQL query.

The syncing query (once per epoch) is of zero concern. However, when following the chain tip, running this query for every single new block is suboptimal.

When following the chain we would like to avoid doing an SQL query per block. It should be possible to grab the info out of each block to update a cache and the cached value is written to the database. At the end of an epoch the SQL query can be run again to validate that the epoch row from the query matches the value accumulated during the epoch.

**Probably need to get real numbers on how long it currently takes to get the epoch table entry via an SQL query,**

**Comment by kderme** [comment]
A `Cache` table was introduced in db-sync which can be extended to cache this value. Also since this is an updated value in memory, rollbacks require special treatment. IMO the best aproach is to just delete the cached version and recreated after the cache miss.

**Comment by kderme** [comment]
Additionally to this, I believe there is a related bug related to restarts for the epoch table. If a value is inserted because db-sync follows the chain and then db-sync restarts, this value may never be updated.

**Comment by Cmdv** [comment]
Currently blocked as unable to test locally as there seems to be an issue with cardano-node when building with MacOs Ventura / M1 https://github.com/input-output-hk/cardano-node/issues/5122
