### ISSUE TITLE
Active Stake slowly re-syncing after epoch

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-db-sync#709]
### Environment

`cardano-graphql@5.0.0` with `cardano-db-sync@10.0.1`, synced fulling from scratch on new machine (no restore).

#### Runtime

- [X] Docker

### Steps to reproduce the bug
Usually after an epoch change over the active stake is calculated immediately. After changing to epoch 280, I've noticed that the active stake is not accurate and is slowly being tallied up. 

```
{
  activeEpochStake: activeStake_aggregate(where: {
    _and:[
      {epochNo: {_eq: 280}}, 
      {registeredWith: {hash: {_eq: "5b9a5633289c52003d359bce18f77f571a701fd3942a52bde3262558"}}}
    ]
  }) {
    aggregate {
      sum {
        amount
      }
      count
    }
  }
}
```

### What is the expected behavior?
Running the above query, a few minutes after the node had finished changing to epoch 280 (via tip query), I ran the above query and it only return the count of 12. It should be at least 240. After leaving it for about an hour, it's at count 64. So it seems like it's now slowly counting the active stake, compared to `cardano-gaphql@4.0.0` (`cardano-db-sync@9.0.0`) that was doing it almost instantly at the epoch change over (usually took 5 minutes).

I have a feeling that it's a cardano-db-sync issue (or design change? Didn't see it in the change-logs), however I'm technically using cardano-graphql.

**Comment by erikd** [comment]
But `db-sync` does not have "active stake".

**Comment by rhyslbw** [comment]
@erikd `epoch_stake` is the area of interest
```sql
CREATE VIEW "ActiveStake" AS
SELECT
  stake_address.view AS "address",
  amount AS "amount",
  epoch_no as "epochNo",
  epoch_stake.id AS "id",
  pool_hash.hash_raw AS "stakePoolHash",
  pool_hash.view AS "stakePoolId"
FROM epoch_stake
JOIN pool_hash
  ON pool_hash.id = epoch_stake.pool_id
JOIN stake_address on epoch_stake.addr_id = stake_address.id;
```

**Comment by Elitestakepool** [comment]
@erikd, i have the same issue across 2 DBSync build 10.0.0.1. After epoch boundary the epoch_stake table seems to rebuild and querying epoch_stake seems to recalculate - building up slowly until the correct value is displayed

`SELECT
   sum(amount) 
 FROM epoch_stake 
 WHERE pool_id=47 
 AND 
 epoch_no=(select max(no) from epoch)) as activestake;`

**Comment by erikd** [comment]
@Elitestakepool `epoch_stake` has roughly the same number of entries as there are active stake addreses. This has grown (and is continuing to grow) to over 400,000  (actually 595,592 addresses for epoch 270). Inserting all of these at once was taking over 10 minutes during which time `db-sync` was not getting new blocks from the chain. To work around this problem, the epoch stake distribution was divided into chunks of about 1000, and placed in a queue. The insertion of these chunks was then interleaved with regular block inserts (so that `db-sync` would follow the chain after the epoch boundary and not halt).

That means that the `epoch_stake` table does not have a complete set of entries for a given epoch until some time after the epoch boundary. You say 3 hours which I do not find that surprising. I don't think there is anything to fix here. We are limited by the realities of how fast things can be inserted into PostgreSQL.

My advise is to avoid running you query for the first 3+ hours of each epoch.

**Comment by CyberCyclone** [comment]
I can definitely understand that the more the network grows the more work is required at each epoch, although I'm not really following the reason for the time difference.  With db-sync:9.0.0 it usually took 10 minutes to complete all the tasks, now it takes several hours with 10.0.0 (although I'd need to verify this time difference again in case it was a 1 off).

@erikd is it expected that between 9.0.0 and 10.0.0, the completed changeover time should be almost the same? Even with a queue based system, I'd expect it to be similar.

@rhyslbw is it possible to expose the 'queue' that @erikd is talking about so we can see it's progress as a percentage? E.g, `{cardanoDbMeta{initialized syncPercentage currentEpochInitializedPercentage}}`. For my application (adatools.io), the issue is that I don't know when the epoch_stake (activeStake for graphql) has finished calculating.

**Comment by erikd** [comment]
> With db-sync:9.0.0 it usually took 10 minutes to complete all the tasks, now it takes several hours with 10.0.0

In `db-sync:9.0.0` the epoch stakes were inserted in one go at the start of the epoch. However, inserting them in one go took 10 minutes (back in epoch `260`, it would be 50% more than that at epoch `280`) and while the epoch stake distribution was being inserted, no new blocks were being pulled from the chain. Now, epoch stake is inserted in chunks, which can take up to 3 hours.

> @erikd is it expected that between 9.0.0 and 10.0.0, the completed changeover time should be almost the same? Even with a queue based system, I'd expect it to be similar.

They are absolutely not expected to be the same. The start times are the same but the completion times are not the same. Back in epoch `260` all 400k epoch stakes were inserted at once, as quick as possible (but still takes 10+ minutes). Now those `400k` stakes for epoch `260` are split into chunks of `1000`, with each chunk being inserted when a new block arrives (ie about every 20 seconds). That means if there are `400k` stake addresses, there will be 4000 chunks of 1000, which will take `4000 * 20 seconds` which is approximately 3 hours.

**Comment by erikd** [comment]
This is related https://github.com/input-output-hk/cardano-db-sync/issues/688 .

**Comment by CyberCyclone** [comment]
Thanks for clarity. That makes a lot more sense, especially if in 5 years we hit 1 Billion stakes and trying to insert all that in one go wouldn't end well. 

I could be way off with this suggestion, but maybe write to a temp location like Redis and then bulk insert into Postgres with larger chunks? That would obviously have an impact on RAM.

**Comment by erikd** [comment]
> maybe write to a temp location like Redis and then bulk insert into Postgres with larger chunks?

I have not tried it, but I am pretty sure that would hit the same Postgres locking collisions I encountered when doing inserts from two separate threads.

**Comment by Elitestakepool** [comment]
> @Elitestakepool The `epoch_stake` table has roughly the same number of entries as there are active stake addreses. This has grown (and is continuing to grow) to over 400,000 (actually 595,592 addresses for epoch 270). Inserting all of these at once was taking over 10 minutes (when there were 400k of them) during which time `db-sync` was not getting new blocks from the chain. To work around this problem, the epoch stake distribution was divided into chunks of about 1000, and the chunks placed in a queue. The insertion of these chunks was then interleaved with regular block inserts (so that `db-sync` would follow the chain after the epoch boundary and not halt).
> 
> That means that the `epoch_stake` table does not have a complete set of entries for a given epoch until some time after the epoch boundary. You say 3 hours which I do not find that surprising. I don't think there is anything to fix here. We are limited by the realities of how fast things can be inserted into PostgreSQL.
> 
> My advise is to avoid running your query for the first 3+ hours of each epoch.

Thank you @erikd , i have implemented this into our poolstats.org site, calaculation now waits around 4 hours before re-calculating epoch_stake per pool.

**Comment by rhyslbw** [comment]
> is it possible to expose the 'queue' 

I think you have worked it out, but for clarity, the current design uses an internal in-memory queue @CyberCyclone, so we would have to determine a progress estimate based on the registered stake addresses count and chain length post epoch rollover. While we could do this it would be best to have `cardano-db-sync` record some metadata which we can then expose over an API

**Comment by CyberCyclone** [comment]
@erikd can you please let me know if it's a quick thing to add metadata for the epoch_stake sync progress so it can be exposed in cardano-graphq as @rhyslbw is suggesting?  For cardano-graphql the epochs active stake would be inaccurate until the sync has finished. So a usable solution would be to have a sync progress indicator until it's finished.

**Comment by erikd** [comment]
@CyberCyclone `db-sync` currently does not have anything like that, but I am open to suggestions.

**Comment by CyberCyclone** [comment]
> @CyberCyclone `db-sync` currently does not have anything like that, but I am open to suggestions.

My thinking was after db-sync has done a bulk insert, it writes to a "sync progress metadata" table how many it has inserted already and how much is left to do. From that we can work out the percentage left to complete. 

Unless what you're saying is that there is no way to determine how many are remaining?

**Comment by erikd** [comment]
> Unless what you're saying is that there is no way to determine how many are remaining?

Yeah, that is the main issue. Incomplete/complete is easier.

**Comment by CyberCyclone** [comment]
Ok, whatever is the easiest way. For me it's just a way to know from a script point of view that's it's safe to query the current epochs data so that's it's accurate. Otherwise it's guess work which is prone to being inaccurate.

If we're able to get the incomplete/complete stats to feed back to the users on the dashboard as a rough guide on its progress the better.

**Comment by erikd** [comment]
@CyberCyclone if you think the feature described in #797 is sufficient to address this issue, please close this one.

**Comment by CyberCyclone** [comment]
> @CyberCyclone if you think the feature described in #797 is sufficient to address this issue, please close this one.

Perfect.
