### ISSUE TITLE
Sum of ada_pots amounts does not lead anymore to 45B ADA

### ISSUE THREAD

**Issue by SmaugPool** [input-output-hk/cardano-db-sync#716]
With cardano-db-sync 9.0.0 (feel free to close if this has been fixed with 10.0.x), the sum of `ada_pots` amounts does not return anymore 45B since epoch 252:
```
cardano=> select epoch_no,treasury+reserves+rewards+utxo+deposits+fees from ada_pots;

 epoch_no |     ?column?      
----------+-------------------
      208 | 45000000000000000
      209 | 45000000000000000
      210 | 45000000000000000
      211 | 45000000000000000
      212 | 45000000000000000
      213 | 45000000000000000
      214 | 45000000000000000
      215 | 45000000000000000
      216 | 45000000000000000
      217 | 45000000000000000
      218 | 45000000000000000
      219 | 45000000000000000
      220 | 45000000000000000
      221 | 45000000000000000
      222 | 45000000000000000
      223 | 45000000000000000
      224 | 45000000000000000
      225 | 45000000000000000
      226 | 45000000000000000
      227 | 45000000000000000
      228 | 45000000000000000
      229 | 45000000000000000
      230 | 45000000000000000
      231 | 45000000000000000
      232 | 45000000000000000
      233 | 45000000000000000
      234 | 45000000000000000
      235 | 45000000000000000
      236 | 45000000000000000
      237 | 45000000000000000
      238 | 45000000000000000
      239 | 45000000000000000
      240 | 45000000000000000
      241 | 45000000000000000
      242 | 45000000000000000
      243 | 45000000000000000
      244 | 45000000000000000
      245 | 45000000000000000
      246 | 45000000000000000
      247 | 45000000000000000
      248 | 45000000000000000
      249 | 45000000000000000
      250 | 45000000000000000
      251 | 45000000000000000
      252 | 44999999999959626
      253 | 44999999999959626
      254 | 44999999999959626
      255 | 44999999999959626
      256 | 44999999998926034
      257 | 44999999998778092
      258 | 44999999998778092
      259 | 44999999997872763
      260 | 44999999997872763
      261 | 44999999997846173
      262 | 44999999997842316
      263 | 44999999997330302
      264 | 44999999997300978
      265 | 44999999997300978
      266 | 44999999997300978
      267 | 44999999997300978
      268 | 44999999996395370
      269 | 44999999996394025
      270 | 44999999980746186
      271 | 44999999980691185
      272 | 44999999980368105
      273 | 44999999980368105
      274 | 44999999980368105
      275 | 44999999980368105
      276 | 44999999980295866
      277 | 44999999980294528
      278 | 44999999980294528
      279 | 44999999980267691
      280 | 44999999980267691
(73 rows)

```

**Comment by kderme** [comment]
Thank you for the report. I'll sync to verify this and check if https://github.com/input-output-hk/cardano-db-sync/pull/717 is a fix and come back to this.

**Comment by erikd** [comment]
My instance (without #717)  is currently syncing (and is at epoch `264`) and I get 45B for all the epoch I have synced so far.

There was a problem that if `db-sync` was stopped and restarted some volatile data (data extracted from the ledger state and in a queue to be inserted into the database) is lost. @kderme has fixed this on `master` as part of #679 .

I will wait for my instance to fully sync and verify this again before closing this.

**Comment by erikd** [comment]
Raise an issue for added validation: https://github.com/input-output-hk/cardano-db-sync/issues/718 .

**Comment by erikd** [comment]
My instance (without #717) is still syncing (and is currently at epoch 270) and every row in the range [`208, 270]` is still showing `45B ADA`. 

I have also added this as a validation (#720) to the `cardano-db-tool` `validate` sub command.

**Comment by erikd** [comment]
Resynced my instance after merging #717 (currently at epoch 273) and with the SQL query above, every row sums to `45B ADA`.  After the sync has completed I will start and stop `db-sync` a number of times and make sure the sum is still correct.

**Comment by erikd** [comment]
After merging #717 I have tested this again, including stopping/restarting `db-sync` and I have not seen any problem. The mainnet balance is `45B ADA` for every row.

Closing this.
