### ISSUE TITLE
docker-compose does not work with alonzo-white-1.4

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-db-sync#730]
We do not have image for tag `11.0` [here](https://hub.docker.com/r/inputoutput/cardano-db-sync/tags?page=1&ordering=last_updated) , there is only image for:

`inputoutput/cardano-db-sync:alonzo-white-1.4`

```
sudo docker-compose up -d && docker-compose logs -f
[sudo] password for artur:           
Pulling cardano-db-sync (inputoutput/cardano-db-sync:11.0.0)...
ERROR: manifest for inputoutput/cardano-db-sync:11.0.0 not found: manifest unknown: manifest unknown
```
and in [docker-compose](https://github.com/input-output-hk/cardano-db-sync/blob/alonzo-white-1.4/docker-compose.yml#L41) file we are using:

```
 cardano-db-sync:
    image: inputoutput/cardano-db-sync:11.0.0
```

`db-sync` version:
```
git last
commit 7ac87cf0f91bd836715ac608d707811bc3dfecf3 (HEAD, tag: alonzo-white-1.4, origin/prerelease/11.0.x)
Author: Erik de Castro Lopo <erikd@mega-nerd.com>
Date:   Wed Aug 4 17:27:35 2021 +1000

    Version 11.0.0

```

**Comment by erikd** [comment]
Totally unsurprised.

**Comment by erikd** [comment]
Closing this. The `docker-compose,yaml` file should only bet tested on released branches.
