### ISSUE TITLE
Missing migrations error

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#741]
I build and run Cardano-db-sync-extended and I get this error:

```
cardano-db-sync-extended: FatalError {fatalErrorMessage = "Inconsistent migrations found: \nMigrations 
missing at runtime that were present at compilation time: []\nMigrations found at runtime that were missing 
at compilation time: []"}
```

I think the migrations parsed in Setup are not ordered properly so the list comparison fails, even though the migrations Set is the same.

**Comment by erikd** [comment]
That has been fixed on master in #738 .
