### ISSUE TITLE
`collateral_tx_in` documentation issue

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-db-sync#747]
The [docs](https://github.com/input-output-hk/cardano-db-sync/blob/alonzo-purple-1.0/doc/schema.md#collateral_tx_in) state: 
>  tx_in_id:  The Tx table index where this transaction is used as an input.

Should this not be "tx_in table index where this collateral was assigned" ?
> tx_out_id : The Tx table index where this transaction was created as an output.

"tx_out table index where this collateral was created" ?

**Comment by erikd** [comment]
Looking at this again, I actually do not think that is right.

The Haskell definition of this table is:
```
  CollateralTxIn
    txInId          TxId             OnDeleteCascade     -- The transaction where this is used as an input.
    txOutId         TxId             OnDeleteCascade     -- The transaction where this was created as an output.
    txOutIndex      Word16           sqltype=txindex
    UniqueColTxin   txInId
```
where `tx_in_Id` and `tx_out_id` are indices into the `Tx` table, not the `TxIn` or `TxOut` table.

The `CollateralTxIn` table is very similar to the `TxIn` table which is similarly defined as:
```
  TxIn
    txInId          TxId             OnDeleteCascade     -- The transaction where this is used as an input.
    txOutId         TxId             OnDeleteCascade     -- The transaction where this was created as an output.
    txOutIndex      Word16           sqltype=txindex
    redeemerId      RedeemerId Maybe OnDeleteCascade
    UniqueTxin      txOutId txOutIndex
```

**Comment by rhyslbw** [comment]
Ok I see. The descriptions in the docs for both [tx_in](https://github.com/input-output-hk/cardano-db-sync/blob/alonzo-purple-1.0/doc/schema.md#tx_in) and `collateral_tx_in` are not valid though: 

![image](https://user-images.githubusercontent.com/303881/128812472-75e5cdda-6ab7-4454-a725-d94af6c8cd0b.png)
