### ISSUE TITLE
validateEpochRewardsBefore failure

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#749]
On commit ab44c8cc4e3edb34156ce00bb78a7c281bd15347, after stopping and restarting `db-sync` I got:
```
validateEpochRewardsBefore: rewards earned in epoch 246 expected total of 16624936.26224 ADA
    but got 16626468.218414 ADA
```
Have stopped and restarted it numerous times and not seen another.

**Comment by cardanians** [comment]
because after restart are no rewards inserted into reward table.

**Comment by erikd** [comment]
@cardanians What evidence do you have of that?

**Comment by cardanians** [comment]
all is synced (txs, blocks, delegations, all) except new rewards (e282), they are just missing. and all I did was stop db-sync and start it again in e281.

**Comment by erikd** [comment]
@cardanians what version are you running? This issue is about the code on `master` not about any of the previous releases. The stopped and restarted `db-sync` numerous times and never saw another instance of this.

**Comment by cardanians** [comment]
10.0.0

**Comment by erikd** [comment]
Yes, after the release if `10.0.01` we discovered a problem with lost rewards. That has been fixed on `master` and is not the issue here.

**Comment by erikd** [comment]
Closing this as almost certainly stale.
