### ISSUE TITLE
Fix `insertCheckUnique` on conflict

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#759]
We should check if we're using `insertCheckUnique` in the correct way or if we should change its behaviour.
Currently `insertCheckUnique` checks if a unique contraint is violated and if it does, it updates a random field. The reason it does this, is because an update is necessary for PostgreSQL to return the Id. However, we should actually update a field which is part of the Unique Key.

**Comment by erikd** [comment]
`insertUnchecked` makes the assumption that there will be no conflict.

> Currently insertUnchecked checks if a unique constraint is violated and if it does, it updates a random field.

What? That is not intended. It should just abort.

**Comment by kderme** [comment]
umm sorry I meant `insertCheckUnique`

**Comment by erikd** [comment]
> Currently `insertCheckUnique` checks if a unique contraint is violated and if it does, it updates a random field.

If this is the case, then it should be possible to add a test to the test suite to show this, right?

**Comment by erikd** [comment]
Looking at the code, it updates the first field (`head`). This may be incorrect if the first field is not a field that is part of the uniqueness constraint.

**Comment by kderme** [comment]
Yes I think this hasn't caused issues by luck: basically because in most tables the first field happens to be part of the Unique Key.

I think I have found a simple solution https://github.com/input-output-hk/cardano-db-sync/pull/763. I'l work on a test

**Comment by erikd** [comment]
Yeah, would really like a test for this, even if it requires a custom database schema to trigger it.
