### ISSUE TITLE
Need help with querying latest pool of a stake address

### ISSUE THREAD

**Issue by ruppo-912116** [input-output-hk/cardano-db-sync#774]
I am starting out with cardano db sync and needed help to query latest pool of a stake address?

**Comment by neverMindMap** [comment]
This is what i could come up with:

```
select latest_pool.addr_id, latest_pool.pool_id, ph.view, stakes.stake_address, stakes.amount
from (
         select distinct on (addr_id) addr_id, pool_id
         from epoch_stake
         order by addr_id, epoch_no DESC
     ) latest_pool
         join (
    select saa.addr_id, saa.stake_address, sum(saa.amount) amount
    from stake_address_addresses saa
    group by saa.stake_address, saa.addr_id
) stakes on stakes.addr_id = latest_pool.addr_id
         join pool_hash ph on ph.id = latest_pool.pool_id;
```

**Comment by erikd** [comment]
Are you aware of the [interesting queries](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md) document? [This query](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md#get-the-delegation-history-for-a-specified-stake-address) is pretty close to what you want.

**Comment by ruppo-912116** [comment]
Yes, I did it though but I don't know if it's right.
select latest_pool.addr_id, latest_pool.pool_id, ph.view, stakes.stake_address, stakes.amount
from (
         select distinct on (addr_id) addr_id, pool_id
         from epoch_stake
         order by addr_id, epoch_no DESC
     ) latest_pool
         join (
    select saa.addr_id, saa.stake_address, sum(saa.amount) amount
    from stake_address_addresses saa
    group by saa.stake_address, saa.addr_id
) stakes on stakes.addr_id = latest_pool.addr_id
         join pool_hash ph on ph.id = latest_pool.pool_id;``
