### ISSUE TITLE
Missing testnet config file

### ISSUE THREAD

**Issue by javiertc** [input-output-hk/cardano-db-sync#785]
Hi, in order to run dbsync on the testnet we have to run this command, but the file `config/testnet-config.yaml` doesn't exist 

```
PGPASSFILE=config/pgpass-testnet scripts/postgresql-setup.sh --createdb
PGPASSFILE=config/pgpass-testnet ./cardano-db-sync-extended-exe \
    --config config/testnet-config.yaml \
    --socket-path ../cardano-node/state-node-testnet/node.socket \
    --state-dir ledger-state/testnet \
    --schema-dir schema/
```

Can I use a copy of mainnet-config.yaml with `NetworkName: testnet` and changing the path for `NodeConfigFile` ?

**Comment by MrMitch17** [comment]
Similar, when running..

`NETWORK=testnet docker-compose up`

This is the error that returns

`cardano-db-sync_1  | [db-sync-node:Info:6] [2021-09-03 20:56:46.39 UTC] Using byron genesis file from: "/nix/store/kax0css4lx3ywihvsgrqjym0jpi20f99-byron-genesis.json"
cardano-db-sync_1  | [db-sync-node:Info:6] [2021-09-03 20:56:46.39 UTC] Using shelley genesis file from: "/nix/store/2xhy92909anynqsvx1b1x153cxwnfmzx-shelley-genesis.json"
cardano-db-sync_1  | [db-sync-node:Info:6] [2021-09-03 20:56:46.39 UTC] Using alonzo genesis file from: "/nix/store/5qpskcxlvakm8d0qf4gg0mhs3ckr264l-alonzo-genesis.json"
cardano-db-sync_1  | [db-sync-node:Info:6] [2021-09-03 20:56:46.41 UTC] NetworkMagic: 1097911063
cardano-db-sync_1  | [db-sync-node:Info:6] [2021-09-03 20:56:46.41 UTC] Inserting Byron Genesis distribution
cardano-db-sync_1  | Error: insertValidateGenesisDist: Genesis data mismatch.
`

**Comment by MrMitch17** [comment]
I think the error I'm experiencing here is related to how the container brings up postgres and its databses.  Its only creating the DB on first start, so if you need to switch between mainnet and testnet, its using the same database and credentials.  So it fails because when you switch, it stays on the first network that you started with.
