### ISSUE TITLE
Query UTxO

### ISSUE THREAD

**Issue by zefexdeveloper** [input-output-hk/cardano-db-sync#787]
How can I query the last UTxO from an address on PostgreSQL (I used `cardano-db-sync`) like I would do using cardano-cli:

> cardano-cli query utxo --address addr_test1vpm4uhupwxc4jjea6c6s5p0t80znlfr03xj4ewygnjtxd3cyjdv8x --testnet-magic 1097911063

I also want to know more information regarding this transaction like who sent, etc.

Thank you very much.

**Comment by erikd** [comment]
> the last UTxO from an address

That does not make a lot of sense. Do you mean the current balance for a given address?

**Comment by wutzebaer** [comment]
You could take a look here

https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/interesting-queries.md

and here:

https://github.com/wutzebaer/cardano-tools/blob/main/src/main/java/de/peterspace/cardanotools/dbsync/CardanoDbSyncClient.java

**Comment by zefexdeveloper** [comment]
Thank you @wutzebaer, it helped a lot.
