### ISSUE TITLE
Build docker image for cardano-db-sync with a specific cardano-node release

### ISSUE THREAD

**Issue by tatyanavych** [input-output-hk/cardano-db-sync#79]
@KtorZ raised:
_There's no docker images tagged for corresponding node's releases for cardano-db-sync, for instance, if one wants to run cardano-db-sync with cardano-node@1.10.0_

DevOps provided instructions for this:
1. tag a commit
2. go to:
https://buildkite.com/input-output-hk/cardano-db-sync
3. put in the commit rev in commit field and BUILDKITE_TAG=<TAG NAME> in environment variables
4. hit create build 

Currently, the latest [cardano-node release](https://github.com/input-output-hk/cardano-node/releases/) is [1.10.1](https://github.com/input-output-hk/cardano-node/releases/tag/1.10.1).

**Comment by tatyanavych** [comment]
Should this be done for every cardano-node release, for every cardano-db-release, or both?

**Comment by kevinhammond** [comment]
For every `cardano-db `release.

**Comment by tatyanavych** [comment]
https://github.com/input-output-hk/cardano-db-sync/pull/86 - to automate process
https://hub.docker.com/r/inputoutput/cardano-db-sync
https://hub.docker.com/r/inputoutput/cardano-db-sync/tags
[https://hub.docker.com/layers/inputoutput/cardano-db-sync/1.5.0](https://hub.docker.com/layers/inputoutput/cardano-db-sync/1.5.0/images/sha256-5d3b0ce426fc30b35790bf7d4d03914b44d7918d867e4aa6a05f535f4dc75d07?context=explore)

**Comment by tatyanavych** [comment]
The automation is available from `master` (#86); it will be in the next release.
Before that DevOps will run manually the cardano-db-sync build docker commands similar to:
`https://buildkite.com/input-output-hk/cardano-db-sync/builds/322#e6fe8f26-d3e9-4264-ba86-ecb99f7acf2e` if needed.
