### ISSUE TITLE
Multiple instances started

### ISSUE THREAD

**Issue by psturm51** [input-output-hk/cardano-db-sync#812]
Hey guys. I'm having an issue. I have an instance running but it seems other instances are being started without my express knowledge of how or why. They are being started by /sbin/init and they are destroying performance. Not certain on the condition which causes this as it takes many hours for an instance to show. Any help would be appreciated. Maybe there is an autorun script being created? There is no documentation to explain my issue as far as I'm aware

**Comment by erikd** [comment]
What version is this? How did you obtain the `db-sync`? How do you run it?

**Comment by psturm51** [comment]
I run it in a custom daemon in node js. It will only ever be called if and only if it is not already running. It almost seems to be nightly that another instance will start. Can't pin point the issue. The issue with the problematic instances is that they are being executed by /sbin/init (start up context) instead of my service so I know it's not my code that's the issue. I've also expressly NOT added a startup script for this reason and it was fairly easy to search all start up scripts. But I also note that I'm the only one having this issue so it must be something I've missed.
