### ISSUE TITLE
List of negative reward balances

### ISSUE THREAD

**Issue by mmahut** [input-output-hk/cardano-db-sync#818]
Hello Erik,

As per our call last week, [here is the list of addresses](https://github.com/input-output-hk/cardano-db-sync/files/7153806/results.txt) we are seeing with negative balances. These appears to be shared across all the instances of cardano-db-sync we have, so they are probably not random. 

`cardano-db-sync 11.0.0`, mainnet restored from _db-sync-snapshot-schema-11-block-6214864-x86_64.tgz_
`cardano-node 1.29.0`

Interesting fact is that a huge majority of these addresses are not registered.

**Comment by erikd** [comment]
@mmahut ANy chance of getting the SQL query that got that list? Just to validate when I finally fix this.

**Comment by mmahut** [comment]
@erikd ah, sorry, should have thought of that.

```
SELECT * FROM
(
  SELECT sa.view AS "address",(
    (
      SELECT COALESCE(SUM(txo.value), 0) AS "outputAmount"
      FROM tx
        JOIN tx_out txo ON (txo.tx_id = tx.id AND sa.id = txo.stake_address_id)
    ) - (
      SELECT COALESCE(SUM(txo.value), 0) AS "inputAmount"
      FROM tx
        JOIN tx_in txi ON (txi.tx_in_id = tx.id)
        JOIN tx_out txo ON (
          txo.tx_id = txi.tx_out_id
          AND txo.index = txi.tx_out_index
          AND sa.id = txo.stake_address_id
        )
    ) + COALESCE(rewards_sum.amount, 0) - COALESCE(withdrawals_sum.amount, 0)
  ) AS "controlled_amount"
  FROM stake_address sa
  LEFT JOIN (
    SELECT addr_id,
      SUM(amount) AS "amount"
    FROM reward
    GROUP BY addr_id
  ) AS "rewards_sum" ON (rewards_sum.addr_id = sa.id)
  LEFT JOIN (
    SELECT addr_id,
      SUM(amount) AS "amount"
    FROM withdrawal
    GROUP BY addr_id
  ) AS "withdrawals_sum" ON (withdrawals_sum.addr_id = sa.id)
GROUP BY sa.id, sa.view, rewards_sum.amount, withdrawals_sum.amount
) AS "controlled_amounts" WHERE controlled_amount < 0;
```

**Comment by mmahut** [comment]
Eric, [here is output from the `1b3c60514011e184b6493b6297843c143cb870f7` release branch](https://github.com/input-output-hk/cardano-db-sync/files/7177808/resultssss.txt).

Also, adjusted query to pre-calcuated rewards as we're after the 48h mark.

```
WITH current_epoch AS (
  SELECT b.epoch_no
  FROM block b
  ORDER BY b.id DESC
  LIMIT 1
)
SELECT * FROM
(
  SELECT sa.view AS "address",(
    (
      SELECT COALESCE(SUM(txo.value), 0) AS "outputAmount"
      FROM tx
        JOIN tx_out txo ON (txo.tx_id = tx.id AND sa.id = txo.stake_address_id)
    ) - (
      SELECT COALESCE(SUM(txo.value), 0) AS "inputAmount"
      FROM tx
        JOIN tx_in txi ON (txi.tx_in_id = tx.id)
        JOIN tx_out txo ON (
          txo.tx_id = txi.tx_out_id
          AND txo.index = txi.tx_out_index
          AND sa.id = txo.stake_address_id
        )
    ) + COALESCE(rewards_sum.amount, 0) - COALESCE(withdrawals_sum.amount, 0)
  ) AS "controlled_amount"
  FROM stake_address sa
  LEFT JOIN (
    SELECT addr_id,
      SUM(amount) AS "amount"
    FROM reward
    WHERE spendable_epoch <= (SELECT * FROM current_epoch)
    GROUP BY addr_id
  ) AS "rewards_sum" ON (rewards_sum.addr_id = sa.id)
  LEFT JOIN (
    SELECT addr_id,
      SUM(amount) AS "amount"
    FROM withdrawal
    GROUP BY addr_id
  ) AS "withdrawals_sum" ON (withdrawals_sum.addr_id = sa.id)
GROUP BY sa.id, sa.view, rewards_sum.amount, withdrawals_sum.amount
) AS "controlled_amounts" WHERE controlled_amount < 0;

```

**Comment by erikd** [comment]
> Eric, here is output from the 1b3c60514011e184b6493b6297843c143cb870f7 release branch.

The rewards issue is not fixed on that release branch.

**Comment by mmahut** [comment]
> The rewards issue is not fixed on that release branch.

And which branch is it?

**Comment by erikd** [comment]
I have only just managed to get it working on a branch which is sill under heavy development. I now have a serious performance regression which needs to be fixed before I merge it to master.

**Comment by mmahut** [comment]
Oh sorry, nevermind - I misunderstood.

**Comment by mmahut** [comment]
This appears to be fixed on the current master.

**Comment by lordmalzahar** [comment]
How I can freely withdraw my correct amount of rewards? I dont know how and I have some rewards missed. Thank you

**Comment by erikd** [comment]
> How I can freely withdraw my correct amount of rewards? I dont know how and I have some rewards missed. Thank you

`db-sync` is now correct. Nest steps are:

* Official `db-sync` release with these fixes (should happen next week).
* Yoroi backend needs to upgrade to use the new `db-sync` release.
