### ISSUE TITLE
K.3

### ISSUE THREAD

**Issue by K3V3NROY** [input-output-hk/cardano-db-sync#821]
**OS**
Your OS:

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):
PostgreSQL version:

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):

**Additional context**

**Problem Report**
Please do not include screenshots or images, but instead cut and paste any relevant log messages
or errors.

**Comment by erikd** [comment]
There is zero information here.  Closing this.
