### ISSUE TITLE
Epoch table not updating

### ISSUE THREAD

**Issue by neverMindMap** [input-output-hk/cardano-db-sync#828]
**OS**
Your OS: ubuntu

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):
PostgreSQL version: 13.1

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

The epoch table only shows up to epoch 286 after updating to cardano dbsync 11.0.0. it is not updating but when querying the max block from block table, shows the latest block. I am not sure if its a bug.

**Comment by erikd** [comment]
Are you running the `cardano-db-sync` executable or the `cardano-db-sync-extended` executable?

**Comment by neverMindMap** [comment]
i am running cardano-db-sync executable.

**Comment by erikd** [comment]
@neverMindMap The `cardano-db-sync` executable **does not update the epoch table**. For the epoch table to be updated you need to run the `cardano-db-sync-extended` executable.
