### ISSUE TITLE
Missing tx input in script transaction

### ISSUE THREAD

**Issue by xdzurman** [input-output-hk/cardano-db-sync#833]
**OS**
Your OS: Ubuntu 20.04

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`): 11.0.0
PostgreSQL version: 12.3

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: docker

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Problem Report**

This testnet transaction https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=df388c44bf8de15e6080007ea190dc1b48f62c862389d68396641a15131fe4e1 is missing a transaction input. The only provided tx input is 150 ADA, whereas the transaction outputs sum to 151.8 ADA. If you check out the inputs to the transaction in db-sync with ... you will get:
```
select tx_out.* from tx_out
    inner join tx_in on tx_out.tx_id = tx_in.tx_out_id
    inner join tx on tx.id = tx_in.tx_in_id and tx_in.tx_out_index = tx_out.index
    where tx.hash = '\xdf388c44bf8de15e6080007ea190dc1b48f62c862389d68396641a15131fe4e1' ;
   id    | tx_id  | index |                             address                             |                         address_raw                          |                        payment_cred                        | stake_address_id |   value   | address_has_script | data_hash 
---------+--------+-------+-----------------------------------------------------------------+--------------------------------------------------------------+------------------------------------------------------------+------------------+-----------+--------------------+-----------
 2025776 | 738369 |     0 | addr_test1vrwnsw8q8pfuj8f8tk6thw07pz7zk5j4yg6kr289yxq7s3g5nf3r0 | \x60dd3838e03853c91d275db4bbb9fe08bc2b5255223561a8e52181e845 | \xdd3838e03853c91d275db4bbb9fe08bc2b5255223561a8e52181e845 |                  | 150000000 | f                  |
``` 
as the only transaction input. Shouldn't a transaction with outputs higher than inputs fail when sending and not get through to second validation (script)? I suppose the issue is in the db sync which somehow did not map this input. Cardanoscan does not use db-sync and on their page, you can see that they somehow got this 1.8 ADA tx input. https://testnet.cardanoscan.io/transaction/df388c44bf8de15e6080007ea190dc1b48f62c862389d68396641a15131fe4e1

**Comment by kderme** [comment]
I think both db-sync and cardanoscan got this wrong.
This tx contains a phase 2 script failure. Notice 'valid_contract' below:
```
select * from tx where tx.hash = '\xdf388c44bf8de15e6080007ea190dc1b48f62c862389d68396641a15131fe4e1';
   id   |                                hash                                | block_id | block_index |  out_sum  |  fee   | deposit  | size | invalid_before | invalid_hereafter | valid_contract | script_size 
--------+--------------------------------------------------------------------+----------+-------------+-----------+--------+----------+------+----------------+-------------------+----------------+-------------
 633996 | \xdf388c44bf8de15e6080007ea190dc1b48f62c862389d68396641a15131fe4e1 |  2893736 |           3 | 151302827 | 497173 | -1800000 | 7663 |                |                   | f              |        7088
(1 row)
```
In this case the inputs are not consumed, but instead the collateral inputs and the `tx_in` table is populated with the collateral. So db-sync has the correct inputs. However the outputs should remain empty. Luckily the fix for this is a one liner.

**Comment by ashisherc** [comment]
@kderme It is shown correctly on Cardanoscan. https://testnet.cardanoscan.io/transaction/df388c44bf8de15e6080007ea190dc1b48f62c862389d68396641a15131fe4e1

The transaction indeed provide 2 inputs and was expecting 4 outputs. As this transaction is a phase 2 script failure, the inputs are not consumed but instead the collaterals. You can see the collateral inputs in the collateral tab, which are consumed as fees and the fee is shown accordingly.

**Comment by kderme** [comment]
Right I didn't noticed there is an additional tab for collateral.
