### ISSUE TITLE
Remove all the coerce calls

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#838]
To work around the complete absence of anything that ever looks like an API for `ledger-specs` I have been using `coerce` to make things compile.

However @JaredCorduan has recommended against `coerce` so we should remove them all. This will no doubt be a horrific ordeal.

**Comment by erikd** [comment]
A correct solution to the most simple version of this problem is:
```
convertStakePoolkeyHash :: KeyHash 'StakePool (Crypto era) -> Maybe (KeyHash 'StakePool StandardCrypto)
convertStakePoolkeyHash (KeyHash h) = KeyHash <$> hashFromBytes (hashToBytes h)
```
The `Maybe` in the return type is needed because `hashFromBytes` can fail if its input has the incorrect number of bytes and to call that `Maybe` a minor inconvenience is a **HUGE** understatement.

We can remove the `Maybe` with something like:
```
convertStakePoolkeyHash :: KeyHash 'StakePool (Crypto era) -> KeyHash 'StakePool StandardCrypto
convertStakePoolkeyHash (KeyHash h) = maybe (error "this is fucked") KeyHash $ hashFromBytes (hashToBytes h)
```
but that is a pretty shabby solution.

Another solution would be to wrap the provided `ByteString` in a `newtype`:
```
newtype StakePoolKeyHash
  = StakePoolKeyHash { unStakePoolKeyHash :: ByteString }

convertStakePoolkeyHash :: KeyHash 'StakePool (Crypto era) -> StakePoolHash
convertStakePoolkeyHash (KeyHash h) = StakePoolHash $ hashToBytes h
```
This is total, but will silently accept whatever `hashToBytes` gives it. This is fine until it is inserted into the database where it may fail (to insert) if the length of the `ByteString` is not correct. However, this should be fine if proper testing and QA is done before any release where the `KeyHash 'StakePool (Crypto era)` changes (and I actually suspect that it can't change without a huge impact on the ecosystem).

**Comment by lehins** [comment]
@erikd according to Duncan we do not expect crypto types to change ever, so you can simply avoid polymorphic types and switch at every place where `Crypto era` is being used to `StandardCrypto`, in which case you don't even need functions like `convertStakePoolkeyHash`

**Comment by erikd** [comment]
@lehins While that may help with `convertStakePoolkeyHash` i can't see how iy would with a type signature like:
```
getShelleyBalance
    :: forall era. (Crypto era ~ StandardCrypto, Ledger.TxOut era ~ Shelley.TxOut era)
    => Compactible (Ledger.Value era) => Val (Ledger.Value era)
    => Text -> Shelley.UTxO era -> Either Text Word64
```

**Comment by lehins** [comment]
@erikd It doesn't work because your types aren't quite right. You need to make sure not to mix up `era` and `Crypto era`:

```haskell
getShelleyBalance
    :: forall era. (Crypto era ~ StandardCrypto, Ledger.TxOut era ~ Shelley.TxOut era)
    => Compactible (Ledger.Value StandardCrypto) => Val (Ledger.Value StandardCrypto)
    => Text -> Shelley.UTxO era -> Either Text Word64
```

**Comment by erikd** [comment]
@lehins That particular function was not written by me. From you comment I can now see that it was wrong and why, but GHC accepted the old version and was able to determine that it was no logically inconsistent, even if it was not optimal. From the point of view of the `db-sync` devs (@kderme and me), we do our best and if GHC accepts it then that is enough for us.

This points to the fact that someone who knows the ledger specs types should be reviewing how we are using those types in `db-sync` on say a monthly basis.
