### ISSUE TITLE
Hardcoded references for EpochSlots

### ISSUE THREAD

**Issue by rdlrt** [input-output-hk/cardano-db-sync#84]
While testing using a genesis with smaller values for k (EpochSlot effectively reduced to 2000), we found that slot_no was not being adhered to. Upon checking, it seems there are a few hard coded references that would be good to eliminate :

For Migration Schema ([here](https://github.com/input-output-hk/cardano-db-sync/blob/master/schema/migration-2-0002-20190918.sql#L13) and [here](https://github.com/input-output-hk/cardano-db-sync/blob/8fe44c55940470d061a279eaa3976f5b9d0be65e/schema/migration-2-0003-20191017.sql#L19)).

For grafana monitoring dashboard ([here](https://github.com/input-output-hk/cardano-db-sync/blob/master/monitoring/explorer-dashboard.json#L349) and [here](https://github.com/input-output-hk/cardano-db-sync/blob/master/monitoring/explorer-dashboard.json#L615)).

Would be good if these could be fetched from genesis.json in config file instead.

This issue also impacts input-output-hk/cardano-rest#19

**Comment by erikd** [comment]
Longer term the `k` constant can be changed via the update proposal mechanism, but for now it should just be the one in the `genesis.json` file.

**Comment by rdlrt** [comment]
This is partially (not completely) outdated, the newer references in #135 now
