### ISSUE TITLE
cardano-db-sync-extended version command gives the wrong git revision

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#844]
The version command output:
```
$ cardano-db-sync-extended --version
cardano-db-sync-extended 11.0.3 - linux-x86_64 - ghc-8.10
git revision 08d36075ca25b804b5b1b544d6eafe5c877e7049
```
gives the wrong git revision. The revision is for a temporary commit on a debug/development branch. The commit hash does not exist in the `cardano-node` repo nor does it occur on the `master` or `release/11.0.x` branches of `db-sync` .

I have run `cabal clean` and rebuilt it and it still gives the same commit hash.

The git commit hash should be correct regardless of whether we compile from `master`, a work-in-progress branch or a release branch.

**Comment by tmcgilchrist** [comment]
Weird, running this locally with a fresh version of master:

```shell
$ cabal exec cardano-db-sync-extended -- --version
cardano-db-sync-extended 11.0.0 - darwin-x86_64 - ghc-8.10
git revision 5bbac3eb8cfffda3b272878a7d454573f8a33026
```

Which should be getting this version:
```
$ git rev-parse --verify HEAD                      
dd23425869a91f74326a1fae0a2b7fc4d43e5558
```

Looking into this.
