### ISSUE TITLE
upgrade from 11.0.0 to 11.0.3-pre3 causes "DbInsertException EpochParam / cost_models" missing error

### ISSUE THREAD

**Issue by ggcaponetto** [input-output-hk/cardano-db-sync#846]
OS
Your OS: Ubuntu 20.04

Versions
The db-sync version (eg cardano-db-sync --version): 11.0.3-pre3
PostgreSQL version: 11.5

Build/Install Method
The method you use to build or install cardano-db-sync: docker

Run method
The method you used to run cardano-db-sync (eg Nix/Docker/systemd/none): docker

Additional context
upgraded from 11.0.0 to 11.0.3-pre3

Problem Report
**loops endlessly with this error**
``
[db-sync-node:Info:355] [2021-09-23 12:18:31.95 UTC] Cardano.Db tip is at slot 40348798, block 6257379
[db-sync-node:Info:360] [2021-09-23 12:18:31.95 UTC] Running DB thread
[db-sync-node:Info:360] [2021-09-23 12:18:31.97 UTC] Rolling back to slot 40348798, hash 907b0257659c817a5e3dcf2fff293dfbe30bc6c5e17955d66b3e3888afefc77d
[db-sync-node:Info:360] [2021-09-23 12:18:31.97 UTC] No blocks need to be deleted
[db-sync-node:Info:360] [2021-09-23 12:18:31.97 UTC] Found in memory ledger snapshot at slot 40348798, hash 907b0257659c817a5e3dcf2fff293dfbe30bc6c5e17955d66b3e3888afefc77d
[db-sync-node:Info:360] [2021-09-23 12:19:20.25 UTC] File /var/lib/cdbsync/40348798-907b025765-290.lstate exists
[db-sync-node:Error:360] [2021-09-23 12:19:21.27 UTC] runDBThread: DbInsertException "EpochParam" (SqlError {sqlState = "42703", sqlExecStatus = FatalError, sqlErrorMsg = "column \"cost_models\" of relation \"epoch_param\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""})
[db-sync-node:Error:363] [2021-09-23 12:19:21.27 UTC] recvMsgRollForward: AsyncCancelled
[db-sync-node:Error:355] [2021-09-23 12:19:21.27 UTC] ChainSyncWithBlocksPtcl: DbInsertException "EpochParam" (SqlError {sqlState = "42703", sqlExecStatus = FatalError, sqlErrorMsg = "column \"cost_models\" of relation \"epoch_param\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""})
``

Do i need to prune the db and start a fresh sync for this to work? It seems like a schema error in postgres. ~~A full resync is starting to be painful each time. What is the recommanded way of upgrading every time there are schema changes? Are there any snapshots/dumps available somewhere? Can I do this on my own with pg_dumpall?~~ --> [snapshot doc]()

**Comment by erikd** [comment]
I suspect you tried using `master` and then dropped back to the `11.0.x` release without resyncing.

If you go to the `release/11.0.x` branch:

* `git log schema/` will show you that the last change in that directory was on Aug 12 which was before the `11.0.0` release.
*  `git-logv cardano-db/src/Cardano/Db/Schema.hs` will show you that the only change to the schema definition that happened after the `11.0.0` release was a typo fix for schema docs in 13a16a5a41fbaaa750056d5272da6fd0a8e02660 .

Pretty sure the schema from `11.0.0` can be updated to the schema on `master`, but going the other way is not possible.
