### ISSUE TITLE
Deleting blocks takes too long and suddenly db sync stops

### ISSUE THREAD

**Issue by neverMindMap** [input-output-hk/cardano-db-sync#848]
**OS**
Your OS:

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):cardano db sync 11.0.0 extended
PostgreSQL version: 13.0

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): docker

Upon restarting the cardano db sync, the log shows "Deleting [number] blocks up to slot [number]". it takes too long and suddenly db sync stops. after a long time then, the log says "failed to start all subscriptions". " identity restarting after 1.0267s desired valency 1 current valency 0.

**Comment by erikd** [comment]
Whenever `db-sync` is restarted in needs to rollback to the start of the current epoch. If it does not do this it can lose data kept in an in-memory queue. Yes, I would love to fix this, but there are too many other issues with higher priority that need fixing

> the log says "failed to start all subscriptions". " identity restarting after 1.0267s desired valency 1 current valency 0.

That is a totally unrelated problem that suggests something is wrong with the `node` that `db-sync` is connecting to.
