### ISSUE TITLE
Rewards differ between ledger and db-sync at epoch 86

### ISSUE THREAD

**Issue by twilightrus** [input-output-hk/cardano-db-sync#849]
**OS**
Your OS: Ubuntu 18.04.5 LTS

**Versions**
PostgreSQL version: psql (PostgreSQL) 11.13 (Ubuntu 11.13-1.pgdg18.04+1)

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: source

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): none

When running cardano-db-sync it writes this logs and restarts:

`[db-sync-node:Info:77] [2021-09-23 10:26:11.42 UTC] Starting at epoch 86
[db-sync-node:Info:77] [2021-09-23 10:26:11.43 UTC] Handling 256 stakes for epoch 86 slot 6782400, hash 3fdfbd1bedo358d16778ae4dobd5e46212cf
f3d1a9a155a1fb8574fbb7f10497
[db-sync-node:Warning:77] [2021-09-23 10:26:11.68 UTC] validateEpochRewards: rewards earned in epoch 84 expected total of 158768. 12877 ADA b
ut got 158468. 12877 ADA
dbMap length: 27
ledger Map length: 27
diffMap Length: 3
203412de65e523666ef5df0a7c3db51eb99b0553b67f324f0ba215af82 (118244, 1): [(RwdMember,DbLovelace 118244)], Coin 100118244
e07821cc41d0 16e17e2f6e37a8c1ba8a3caaaf52d44b80a557b4cc4d98 ( 128667, 1): [(RwdMember, DbLovelace 128667)], Coin 100128667
e09cd7cdo7obbcc65f75b460a3f4462e3445f11a7f2f1a49825a10f88d (128667, 1): [(RwdMember,DbLovelace 128667)], Coin 100128667
Rewards differ between ledger and db-sync.
Please report at https://github.com/input-output-hk/cardano-db-sync/issues.`

**Comment by thavlik** [comment]
I was just about to open an issue about this! Curious, how did you get the verbose error log? Mine looks like this:

```
[db-sync-node:Info:80] [2021-09-24 07:55:26.05 UTC] Starting at epoch 86
[db-sync-node:Info:80] [2021-09-24 07:55:26.05 UTC] Handling 256 stakes for epoch 86 slot 6782400, hash 3fdfbd1bed0358d16778ae4d0bd5e46212cff3d1a9a155a1fb8574fbb7f10497
[db-sync-node:Warning:80] [2021-09-24 07:55:26.49 UTC] validateEpochRewards: rewards earned in epoch 84 expected total of 158768.12877 ADA but got 158468.12877 ADA
```

**Comment by twilightrus** [comment]
@erikd should the commit https://github.com/input-output-hk/cardano-db-sync/commit/778cb983a6c1609163059fbaa721afff09bc2253 fix this?

**Comment by erikd** [comment]
I **think** this is fixed on the `erikd/missing-itn-rewards` branch, but I am still testing (currently at epoch 257). Even when I have confirmed that it works, I still have some performance regressions to fix and some possibly related issues to fix.

**Comment by erikd** [comment]
@twilightrus Are you able to confirm that this is fixed on the `erikd/missing-itn-rewards` branch?

**Comment by twilightrus** [comment]
@erikd this branch is not built with error

`
root@btc-test:/home/blockchain/cardano-db-sync# nix-build -A cardano-db-sync -o db-sync-node --show-trace
trace: To make project.plan-nix for haskell-project a fixed-output derivation but not materialized, set `plan-sha256` to the output of the 'calculateMaterializedSha' script in 'passthru'.
trace: To materialize project.plan-nix for haskell-project entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
building '/nix/store/amrcjgnywwfj3y0ydkibhmwv0zxj3y2g-hackage-repo-hackage.haskell.org-at-2021-07-02T000000Z.drv'...
building '/nix/store/6d2i289kmr6n3lxrpsv5dfsyndz02hs6-cardano-ledger-specs-5ddef26.drv'...
exporting https://github.com/input-output-hk/cardano-ledger-specs (rev 5ddef26dac3638df72453e183a419f8f5193dd33) into /nix/store/n5i96g423l9jbrwal3i5rbg4w0icj968-cardano-ledger-specs-5ddef26
Initialized empty Git repository in /nix/store/n5i96g423l9jbrwal3i5rbg4w0icj968-cardano-ledger-specs-5ddef26/.git/
remote: Enumerating objects: 1215, done.
remote: Counting objects: 100% (1215/1215), done.
remote: Compressing objects: 100% (1029/1029), done.
remote: Total 1215 (delta 94), reused 551 (delta 32), pack-reused 0
Receiving objects: 100% (1215/1215), 15.54 MiB | 11.67 MiB/s, done.
Resolving deltas: 100% (94/94), done.
From https://github.com/input-output-hk/cardano-ledger-specs
 * branch            refs/pull/2495/head -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...
hash mismatch in fixed-output derivation '/nix/store/5pj4mjcpqxs074r9cvl21yhphr42gjwh-cardano-ledger-specs-5ddef26':
  wanted: sha256:05bwy7x1asyfshqsfsyv2c70qwrxp4680xlvhwdm1hz9bi0lpq41
  got:    sha256:0ryx1irqjggchdd6xz7abbpgnh1p8kwviv4zggmh61ynh12cdvim
cannot build derivation '/nix/store/fw4nmflkbzkjclsf9jkfk9vkajv42qgn-haskell-project-plan-to-nix-pkgs.drv': 1 dependencies couldn't be built
error: while evaluating the attribute 'hsPkgs' at /nix/store/i369k44ks1r4pwd7znr2pqvncx2nl06z-source/overlays/haskell.nix:549:15:
while evaluating the attribute 'hsPkgs' at /nix/store/i369k44ks1r4pwd7znr2pqvncx2nl06z-source/overlays/haskell.nix:526:43:
while evaluating anonymous function at /nix/store/i369k44ks1r4pwd7znr2pqvncx2nl06z-source/lib/import-and-filter-project.nix:5:1, called from /nix/store/i369k44ks1r4pwd7znr2pqvncx2nl06z-source/overlays/haskell.nix:504:27:
build of '/nix/store/fw4nmflkbzkjclsf9jkfk9vkajv42qgn-haskell-project-plan-to-nix-pkgs.drv' failed
`

**Comment by erikd** [comment]
@twilightrus Sorry (I don't use NIx), but I think I fixed it.

**Comment by sorki** [comment]
We deployed this on one node three days ago and there's only a single warning

```
# journalctl -u cardano-db-sync --since "2021-09-24 13:00" | grep Warning
Sep 25 13:24:33 dbsync1 gwcrqraar19kpdgnar3b1pml265vflvl-cardano-db-sync[2024230]: [db-sync-node:Warning:79] [2021-09-25 13:24:33.63 UTC] insertTxMetadata: dropped due to a Unicode NUL character.

# journalctl -u cardano-db-sync --since "2021-09-24 13:00" | grep "expected total"
<empty>
```

so the rewards issue looks resolved. I'm not observing performance regressions compared to (pre-)releases but this is only based on eyeballing memory/CPU utilization graphs.

**Comment by thavlik** [comment]
@erikd please keep this thread updated and let us know when your fixes are complete. Building from scratch takes *way* too long!

Thank you!

**Comment by twilightrus** [comment]
We build release 11.0.0 from zip sources instead of master and it works

**Comment by erikd** [comment]
> We build release 11.0.0 from zip sources instead of master and it works

The `11.0.0` release probably does not have the fix for this.
