### ISSUE TITLE
Take more frequent state snapshots

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#860]
Currently when `db-sync` is stopped and restarted it rolls back to the start of the epoch. This is done to prevent the loss of volatile data that is in-memory but has not yet been inserted into the database.

Currently (at epoch 292) it takes over 5 hours to sync a single epoch. Ideally, after a rollback, the worst case re-start re-sync would be an hour.

There is a partial solution in #840 .

Possible solutions:

* Periodically write this volatile data to disk. This idea's major problem is that it adds complexity and fragility. In the worst, problem `A` has solution `B`, which also has problems to which solution `C` is added ad infinitum.
* Implement #850 and add a dynamic block size to aim to get the volatile data inserted as quickly as possible to that the partial fix in #840 is more effective.
* Have `ledger-specs` provide partial stake distribution and epoch rewards so that this data does not need to be stored in queues.

**Comment by kderme** [comment]
The existing solution may be adequate for this. We insert 1000 rewards per block. So even if there are 1000000 rewards, it will take 1000 blocks to insert them. This is the interval we can't take ledger snapshots, but it is not that big. We already take snapshots every 500 blocks while following, so this makes us lose 2-3 snapshots.

**Comment by erikd** [comment]
Yes, you may be correct. I will merge #840 and do some more testing.

**Comment by erikd** [comment]
I still think longer term we should explore the third option, having `legder-specs` provide partial rewards so that we can drop the queues all together.

**Comment by kderme** [comment]
We now have incremental rewards, which allow more frequent snapshots.
