### ISSUE TITLE
Test harness for `db-sync`

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-db-sync#871]
Numerous problems over the last several months have shown that currently we do not do enough testing for correctness. The *only* reason for this is that testing `db-sync` is difficult to do comprehensively and efficiently. Currently we have some unit tests, but the majority of the testing is done by running a full sync of `db-sync` on mainnet or one of the testnets. Since a full sync of
mainnet (at epoch 294) takes more than two days, even testing on mainnet takes **way** too long. On top of that, there is no guarantee that syncing mainnet is a comprehensive test. There are already a number of instances of new bugs found after mainnet has been synced.

Theoretically, it would be possible to construct a complete blockchain that includes every possible test scenario and run it into `db-sync`. Unfortunately it would be far from easy to create such blockchain and difficult to extend it to new scenarios.

A better solution would be to make it easy to create valid blockchain fragments (as Haskell code) which could then be wrapped with a simple component that emulates the local chain sync protocol and plays back the blockchain fragment through the local chain protocol allowing the testing of `db-sync` on the chain fragment.

We could then write many of these blockchain fragments and then run the tests across all of the chain fragments. The test hardness should provide as much functionality as possible to make the writing of new tests as easy as possible and make new tests require as little boilerplate as possible.

**Comment by kderme** [comment]
Unit tests that cover many scenarios are in place now.
