### ISSUE TITLE
db-sync fails to restart with `Error: Shelley.validateGenesisDistribution`

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-db-sync#877]
**OS**
Fedora 34

**Versions**
`12.0.0-pre2` and current master: `15a434be9df084d04b8d2bf18df833470befecc8`
PostgreSQL version: 11.11

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: nix

**Additional context**
The cardano node is on latest master, Alonzo era, Protocol Version 6.

**Problem Report**
Db-sync is running without any issues until restarted. After restart it fails to start with
stdout:
```
[db-sync-node:Info:6] [2021-10-08 14:20:14.56 UTC] Schema migration files validated
[db-sync-node:Info:6] [2021-10-08 14:20:14.56 UTC] Running database migrations
[db-sync-node:Info:6] [2021-10-08 14:20:14.81 UTC] Using byron genesis file from: "./state-cluster0/byron/genesis.json"
[db-sync-node:Info:6] [2021-10-08 14:20:14.81 UTC] Using shelley genesis file from: "./state-cluster0/shelley/genesis.json"
[db-sync-node:Info:6] [2021-10-08 14:20:14.81 UTC] Using alonzo genesis file from: "./state-cluster0/shelley/genesis.alonzo.json"
[db-sync-node:Info:6] [2021-10-08 14:20:14.82 UTC] NetworkMagic: 42
[db-sync-node:Info:6] [2021-10-08 14:20:14.82 UTC] Initial genesis distribution present and correct
[db-sync-node:Info:6] [2021-10-08 14:20:14.82 UTC] Total genesis supply of Ada: 45000000000.000000
[db-sync-node:Info:6] [2021-10-08 14:20:14.82 UTC] Validating Genesis distribution
```

stderr:
```
Error: Shelley.validateGenesisDistribution: Expected initial block to have 1 but got 2
```

Might be related to https://github.com/input-output-hk/cardano-db-sync/pull/766 however my local network has
```
"TestShelleyHardForkAtEpoch": 1
```
(not "0").

It is a regression, with the same node and db-sync configuration it is possible to restart db-sync `11.0.4` with no issue.

**Comment by erikd** [comment]
Where is the config you are using?

**Comment by erikd** [comment]
> Error: Shelley.validateGenesisDistribution: Expected initial block to have 1 but got 2

This error suggests something is wrong with the config or than that database was not dropped before this was run.

**Comment by kderme** [comment]
I found this comment in the consensus code:
```
-- NOTE: the initial staking and funds in the 'ShelleyGenesis' are ignored,
-- /unless/ configured to skip the Byron era and hard fork to Shelley or a later
-- era from the start using @TriggerHardForkAtEpoch 0@ for testing purposes.
```
So it seems the node ignores these fields. I would suggest that db-sync does not support these kind of configuration and it requires `"TestShelleyHardForkAtEpoch": 0` when there are initial staking or funds.

**Comment by erikd** [comment]
We should detect this invalid configuration (`TestShelleyHardForkAtEpoch /= 0` but with a Shelley staking and funds defined) and `panicAbort` on it, with a good error message.
