### ISSUE TITLE
Upcoming Hard Fork Question

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-db-sync#887]
Does cardano-graphql (or db-sync) expose the time / slot an upcoming hard fork event will occur? There's a param_proposal table in db-sync but I can't see anything useful in there.

I'm looking at adding it as an alert, maybe like a push service. 

Thanks!

**Comment by erikd** [comment]
My understanding is that for a hard fork to occur it first has to be proposed on the chain, and any parameter proposal on the chain will end up in the `param_proposal` table.

**Comment by rdlrt** [comment]
> So if this is a voting record, is there a way to determine that the proposal was rejected?

Actually, as per my understanding - if the count of signed records is >= `updateQuorum` (shelley genesis parameter: 5 on mainnet), the "vote" is accepted. Though I could be wrong, but I do remember having tested the proposal method when we went live with shelley - not via dbsync

(Feel free to correct me @erikd if above is incorrect)

**Comment by erikd** [comment]
@CyberCyclone Can this be closed?
