### ISSUE TITLE
Inconsistent (missing) "reserve", "treasury" reward in reward table

### ISSUE THREAD

**Issue by kikai-user** [input-output-hk/cardano-db-sync#892]
**OS**
Your OS: Ubuntu 20.04.3 LTS

**Versions**
cardano-db-sync version: 15a434be9df084d04b8d2bf18df833470befecc8
PostgreSQL version: 12.8 

**Build/Install Method**
nix-build -A cardano-db-sync -o db-sync-node

**Problem Report**
I believe that some "reserve" and "treasury" rewards are missing from reward table. I think the number of rows in reserve table should be equal to the number of rows in the reward table with type = 'reserves'. However, I got different results:
```
cexplorer=# select count(*) from reward where type = 'reserves';
 count 
-------
 54823
(1 row)

cexplorer=# select count(*) from reserve;
 count 
-------
 86906
(1 row)
```
I tried to investigate a bit further and found an example of what's missing.  It's the reserve reward from transaction  `\xad664478fbff01cdb64d555ab6896c4370c337cda35c416f5c898fb15bcdafd5`:
```
cexplorer=# select A.amount, A.spendable_epoch from reward A, stake_address B 
cexplorer-# where A.addr_id = B.id 
cexplorer-#       and type = 'reserves' 
cexplorer-#       and B.view = 'stake1u8s27etuhx4nt69cwd9wev3h3mrxkph9cwmhyuqchmfmdcc9e050h';
  amount  | spendable_epoch 
----------+-----------------
 22359414 |             286
(1 row)

cexplorer=# select A.amount, B.hash from reserve A, tx B, stake_address C
cexplorer-# where A.tx_id = B.id and A.addr_id = C.id
cexplorer-#       and C.view = 'stake1u8s27etuhx4nt69cwd9wev3h3mrxkph9cwmhyuqchmfmdcc9e050h';
  amount  |                                hash                                
----------+--------------------------------------------------------------------
 72822172 | \xad664478fbff01cdb64d555ab6896c4370c337cda35c416f5c898fb15bcdafd5
 22359414 | \xfb8e870a76dbd64999d986dead30815152307c3cdc7df1f6cef05a8cdc942f8e
(2 rows)
```
I found the same issue with the treasury reward:
```
cexplorer=# select count(*) from treasury;
 count 
-------
 24029
(1 row)

cexplorer=# select count(*) from reward where type = 'treasury';
 count 
-------
 24026
(1 row)
```
I might be wrong about the stuffs each table tracking. But, if you group all kinds of rewards into the reward table, you can get rid of two tables treasury and reserve, right?

**Comment by WubbleWobble** [comment]
Sorry for commenting on this old issue, but I was hoping you could help provide a little clarity.

I have found a pre-Alonzo entry (addr_id 1237210 / epoch 285) where the reserve table has two payments, and indeed only the last of those is reflected in the rewards table as per your explanation above.

Does the rewards table then provide the actual true representation of what happened on the blockchain with regards to payments made?

(i.e. Only one payment was actually made (the latter); The reserve table shows two intended payments on the same epoch, but only one was actioned?)

**Comment by erikd** [comment]
@WubbleWobble This should probably be its own issue.

> I have found a pre-Alonzo entry (addr_id 1237210 / epoch 285) where the reserve table has two payments, and indeed only the last of those is reflected in the rewards table as per your explanation above.

Before Alonzo, only a single payment to any address is allowed per epoch. That would explain what you are seeing. I think this changed in a later epoch.

**Comment by WubbleWobble** [comment]
@erikd Brilliant - previously I just wasn't sure whether what you were describing pertained to Cardano, or a quirk of db-sync, so this has cleared things up for me.

Many thanks! :)

**Comment by erikd** [comment]
@WubbleWobble can this be closed now?

**Comment by WubbleWobble** [comment]
@erikd Yes - thank you (it's already closed?)
