### ISSUE TITLE
Track the index of a transaction within a block

### ISSUE THREAD

**Issue by wkoder** [input-output-hk/cardano-db-sync#91]
Hi, the Atala Prism team has started integrating with `cardano-db-sync` and could not find a way to order transactions within a block. Can we plan on adding a column to track the transaction index?

Or, as a workaround or perhaps definite way, can we just sort by the sequential `tx.id`?

Thanks!

**Comment by erikd** [comment]
`tx.id` are generated by Postgres. They are not reliably monotonic.

I agree 100% that the index should be added.

**Comment by kevinhammond** [comment]
OK.  Let's add this.  How urgent is it?  What are you actually trying to do - ensure that transactions have been processed in the right order?

**Comment by erikd** [comment]
If one wants to build a transaction, they need to know the exact index in the tx output.

**Comment by wkoder** [comment]
Thank you, @erikd !
