### ISSUE TITLE
[SMASH] Results returned by `retired` endpoint differ between "new" and "old" versions of SMASH

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-db-sync#933]
**OS**
Your OS: Linux Mint 20.2

**Versions**
The `db-sync` version : `tag: 12.0.0-pre3`
```
db-sync-node-extended/bin/cardano-db-sync-extended --version
cardano-db-sync-extended 12.0.0 - linux-x86_64 - ghc-8.10
git revision 6e594658780bcd21b94808861177db1284aa168d
```

PostgreSQL version: 12.8

**Build/Install Method**
The method you use to build or install `cardano-db-sync`:
`cardano-db-sync` and `smash` were built with `nix` using official instruction docs.

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):

```
PGPASSFILE=config/pgpass-testnet db-sync-node-extended/bin/cardano-db-sync-extended --config config/testnet-config.yaml --socket-path ../cardano-node/state-node-testnet/node.socket --schema-dir schema/ --state-dir ledger-state/testnet_new_smash
```

```
PGPASSFILE=config/pgpass-testnet ./cardano-smash-server_      --config config/testnet-config.yaml      --port 3101      --admins admins.txt
[smash-server:Info:6] [2021-10-28 13:47:07.72 UTC] SMASH listening on port 3101
```

**Additional context**
Discovered during testing new SMASH ported to `cardano-db-sync`

**Problem Report**

Results returned by `retired` endpoint differ between "new" and "old" **SMASH**

"New" smash uses here port `3101` and "old one `3100`

curl --header "Content-Type: application/json" http://localhost:3100/api/v1/retired | jq . > old_smash_retired_pools.json
curl --header "Content-Type: application/json" http://localhost:3101/api/v1/retired | jq . > new_smash_retired_pools.json

cat  new_smash_retired_pools.json | wc -l
893
cat old_smash_retired_pools.json | wc -l
857

Attaching files:

[new_smash_retired_pools_json.txt](https://github.com/input-output-hk/cardano-db-sync/files/7442443/new_smash_retired_pools_json.txt)
[old_smash_retired_pools_json.txt](https://github.com/input-output-hk/cardano-db-sync/files/7442444/old_smash_retired_pools_json.txt)

**Comment by kderme** [comment]
Diff of files, after being sorted
```
24,26d23
<     "poolId": "0689175328f30a436530cedfffce4725007407940d67976ed1fcc3f8"
<   },
<   {
51,53d47
<     "poolId": "0c0e3830ec345fef257a98eaa24d3f221b1bb777595c3b1f5cefc7fe"
<   },
<   {
117,119d110
<     "poolId": "221b9375906ce443445679f6234ec215915563a20a5121846aff5e69"
<   },
<   {
185a177,179
>     "poolId": "331e12b25988de55f70a56ee89c10f38f69dd006eb50894d3304702a"
>   },
>   {
225,227d218
<     "poolId": "3f112e1bbea2109776c605be9d1ba84c9f49e273de4d9dd3c67e2fc7"
<   },
<   {
324,326d314
<     "poolId": "5dc7ae26397005c7c296a84e2b2270f48233252468a6842ea79384a3"
<   },
<   {
411,413d398
<     "poolId": "71d4c756ad50463d75bc31a4f418a0619f377786696c768740131ff0"
<   },
<   {
476a462,464
>     "poolId": "8602dfd6dfdd9a23cc7774845c97a9aea0f4ae0ee3b645606deaa864"
>   },
>   {
507,509d494
<     "poolId": "92885623f518d96b7d7e1a7fc9aeecebaa5501dc25df956a2c99da74"
<   },
<   {
531,533d515
<     "poolId": "980f4dd756d12602d60c2bbead8815616749ab4ccf8cf33f4a4c2c1c"
<   },
<   {
639,644d620
<     "poolId": "bbb5e372a89e6c4095d0eaf9c02a192f6c4d30f909f52a5b494f2ddc"
<   },
<   {
<     "poolId": "bc301429e1ae9ad491016c550cda260084023654093fff15ad233bce"
<   },
<   {
651,653d626
<     "poolId": "be16886306d89c359193ca64aaca6c147175a0b52148ab808a3585a5"
<   },
<   {
723,725d695
<     "poolId": "d071fcbc973a4ea26292b59ad79e2fa2bbb1747a66da8ca85d372f2a"
<   },
<   {
750,752d719
<     "poolId": "d5472390a5790a9ee3f335da3bd5ce418298b64cebf7424ad516885a"
<   },
<   {
768,770d734
<     "poolId": "d7e9b4ff530274ebc92a32f9fe4b3e804257bf84593a68338ddbdfc5"
<   },
<   {
876,878d839
<     "poolId": "fbe75972661c6e40c76f2fd511cc0c61f3dfbd0a9d60c9e673be5f74"
<   },
<   {
888a850,852
>   },
>   {
>     "poolId": "ff333b3efd1406d92bb7d37b6bb2aef3cd08b2ba17222b9e0d4b41d6"
```

**Comment by kderme** [comment]
Was old smash fully synced in you examples? I repeated them today and I got 893 lines for new smash and 887 for old. The diff shows 5 pools that are only retired on new smash:
```
0c0e3830ec345fef257a98eaa24d3f221b1bb777595c3b1f5cefc7fe
24b9368615d54bbc3f4204818159c042a2085e01c5cdd119e2ac92c7
```

**Comment by ArturWieczorek** [comment]
> Was old smash fully synced in your examples?
I believe so. At that time it was at:

```
[smash-node:Info:60] [2021-10-31 12:34:09.23 UTC] Cardano.Db tip is at slot 41147138, block 3029762
```
which gives epoch 165, and it was not pulling any new data then. 

However after starting it today and waiting for some time I see this number has changed:

```
curl --header "Content-Type: application/json" http://localhost:3100/api/v1/retired | jq . > old_smash_retired_pools.json

cat old_smash_retired_pools.json | wc -l
863
```
I think it will grow and probably reach the number you mentioned above (887).

Hmm, so it looks OK and those entries on old SMASH shouldn't be really retired.

**Comment by kderme** [comment]
I verified that new smash returns the correct results.

```
The diff shows 6 pools that are only retired on new smash:

0c0e3830ec345fef257a98eaa24d3f221b1bb777595c3b1f5cefc7fe
24b9368615d54bbc3f4204818159c042a2085e01c5cdd119e2ac92c7
3264bc4a13f433d70d97981fac2b8bb153457dc8b27f35d17de5f435
5a4ea6bd3472f3b1a2a9e0017b642fee6f8f317993d33335bc676b6e
71d4c756ad50463d75bc31a4f418a0619f377786696c768740131ff0
92885623f518d96b7d7e1a7fc9aeecebaa5501dc25df956a2c99da74
```
These pools should be retired but don't appear as such on old smash. Actually al above pools expired on epoch 122, so maybe some systematic issue in old smash.

```
and 4 pools only retired on old smash:

331e12b25988de55f70a56ee89c10f38f69dd006eb50894d3304702a
ac61417525f7b803bf3b7b93bd218aace588996a23a3505b6ea04a08
8602dfd6dfdd9a23cc7774845c97a9aea0f4ae0ee3b645606deaa864
ff333b3efd1406d92bb7d37b6bb2aef3cd08b2ba17222b9e0d4b41d6
```
Pools that are retired only on old smash are instances of https://github.com/input-output-hk/smash/issues/186

I also verified that the differences in Artur's example work properly for new smash.

**Comment by ArturWieczorek** [comment]
Closing this as differences were caused by incorrect behavior of old SMASH.
