### ISSUE TITLE
Add an option/table to find/log the "reward accounting issues" per epoch when using the snapshots on Mainnet

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-db-sync#948]
**OS**
Linux

**Run method**
Sync db-sync state on Mainnet from a snapshot.

**Additional context**
At this moment the "reward accounting issues" (like https://github.com/input-output-hk/cardano-db-sync/issues/947) are visible only when syncing from a clean state (not using a snapshot) but this is extremely slow on Mainnet. 

It would be useful to be able to spot the "reward accounting issues" also when db-sync state is fully synced (from snapshot = much faster, and the recommending way of doing this). 

Idea: we can have a new table with 3 columns: 
- epoch_no
- expected rewards
- effective rewards
That way we would be able to compare the values of the last 2 columns in order to validate the rewards per epoch.

**Comment by erikd** [comment]
When `db-sync` is restored from a snapshot, this bug **WILL NOT BE TRIGGERED** because the buggy code is never executed.

**Comment by erikd** [comment]
There is no way to do this other than by implementing a test with the test framewrok we are working on.

Closing.

**Comment by dorin100** [comment]
Considering that there is a way to automate this check through a test, it would be useful to keep this ticket open (for tracking purposes) until the test is implemented otherwise there is a high risk of losing it.
cc @vhulchenko-iohk , @vfrsilva

**Comment by erikd** [comment]
https://github.com/input-output-hk/cardano-db-sync/issues/959
