### ISSUE TITLE
Inconsistency in the tx_metadata field

### ISSUE THREAD

**Issue by vargasmontero** [input-output-hk/cardano-db-sync#95]
Hi, after a discussion with Kevin, it seems that the metadata field needs to be configured as an ARRAY in the txs table instead of a single file.
This is how it looks like as an array:
```
CREATE TABLE txs (
  txid            hash                   PRIMARY KEY,
  in_blockid      hash                   NOT NULL REFERENCES blocks (blockid) ON DELETE CASCADE,
  fee             lovelace               NOT NULL,
  withdrawals     withdrawal ARRAY,                   
  metadata        tx_metadata  ARRAY                     
);
CREATE TYPE tx_metadata as (
    label         uinteger,
    metadata      jsonb
);
```
In this case, a transaction has a list of metadata types each with a label and a json. The metadata described in Appendix E of the shelley design spec (https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/delegationDesignSpec/latest/download-by-type/doc-pdf/delegation_design_spec), which we can call 'user-defined metadata' is a single map from uints keys to 64 byte values. Hence, declaring metadata as an array sugests that we will have other types of metadata. In this case a transaction will really have an array of 'labeled' maps. Is this correct?
If a single transaction can only have a metadata field, then the correct design would be more like this:
```
CREATE TABLE txs (
  txid            hash                   PRIMARY KEY,
  in_blockid      hash                   NOT NULL REFERENCES blocks (blockid) ON DELETE CASCADE,
  fee             lovelace               NOT NULL,
  withdrawals     withdrawal ARRAY,                   
  metadata        jsonb                     
);
```
Which means that there’s only one type of metadata, there's no label for it and it is encoded in json.

However, this is the current state:
```
CREATE TABLE txs (
  txid            hash                   PRIMARY KEY,
  in_blockid      hash                   NOT NULL REFERENCES blocks (blockid) ON DELETE CASCADE,
  fee             lovelace               NOT NULL,
  withdrawals     withdrawal ARRAY,                   
  metadata        tx_metadata                      
);
CREATE TYPE tx_metadata as (
    label         uinteger,
    metadata      jsonb
);
```
One transaction has one metadata label and one metadata map (encoded as json). The label in this case loses its purpose.

**Comment by erikd** [comment]
@vargasmontero Please be aware that you are looking at a straw man specification of the Shelley schema. The *actual* schema will be different to what you are currently looking at. 

The Persistent library we use to access Postgres from Haskell does not support arrays.

**Comment by vargasmontero** [comment]
@erikd thank you for the explanation.
Let me, then, share with you our core requirements and please let us know if we're aligned.

We basically need a way to filter by txid and metadata key. From the Shelley design doc, metadata is a map from uint keys to 64byte values.

This can be achieved if we get something like this:
```
CREATE TABLE tx_metadata (
  txid       hash REFERENCES txs(txid),
  key        uint,
  value     bytea,
)
```
Or by using a `jsonb` type if the map keys within the jsonb can be indexed. In this case, we would be looking at something like this:
```
CREATE TABLE txs (
  txid            hash                   PRIMARY KEY,
  in_blockid      hash                   NOT NULL REFERENCES blocks (blockid) ON DELETE CASCADE,
  fee             lovelace               NOT NULL,
  withdrawals     withdrawal ARRAY,                   
  metadata        jsonb                     
);
```

Why do we care about this?
We will all utilize metadata for varied purposes (Track & Trace, Product Authentication, New Balance, identities, credentials verification). How do we store data is different for all of us, but what doesn't change is our querying pattern. We will all look a the txid for data authentication (is this tx part of my HD wallet, etc) and we will all look at the keys for the specific information we want to have. How to interpret the values is a concern of a higher layer (application itself).

More information about all our use cases is here: https://input-output.atlassian.net/wiki/spaces/PSG/pages/1197080787/Metadata+Requirements

Please lmk if there are any questions.

**Comment by kevinhammond** [comment]
Yes, @erikd is right that you'll need to restructure the arrays into e.g. tables to do this, since the library doesn't support native arrays.  This should still be searchable.  I am assuming that the library supports jsonb, but this might also be unavailable?

The underlying issue is that @vargasmontero is asking for the metadata to be replicated (so a missing array in the straw man, or a missing table in the actual schema) - needs to be checked against the ledger spec and then added.

**Comment by erikd** [comment]
@vargasmontero I think https://github.com/input-output-hk/cardano-db-sync/pull/229 addresses this.

**Comment by erikd** [comment]
Closing this.
