### ISSUE TITLE
Postgresql db is not local and it gets filled, but db-sync server fills 100gb of storage anyway?

### ISSUE THREAD

**Issue by matcnft** [input-output-hk/cardano-db-sync#956]
**OS**
Your OS: Amazon Linux 2 for the server and AWS Postgresql for the database

**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):
PostgreSQL version: 11.5 (AWS RDS Postgresql)

**Build/Install Method**
The method you use to build or install `cardano-db-sync`: edited the Docker file to use the remote Postgresql and then installed using Docker

**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none): Docker

**Additional context**
Server (EC2) is running the db-sync and writes to the remote database Postgresql. The writing to the DB is working correctly, but the server where db-sync is running is storing lot of data even if the DB is not inside the server anymore.
Why does it happen? Is it a bug of db-sync code? Any way to avoid allocating hundreds of gigabytes in the server?
Thank you!

**Comment by erikd** [comment]
Writing to a Postgres server that is not on the same machine as `db-sync` will likely be 4 times or more slower. IT is not even a tested or supported configuration.

 If you still want to pursue this untested and unsupported configuration then its up to you to figure out what is wrong. However `db-sync` only connects to a single postgres instance. I suspect the Docker stuff restores a snapshot to the local instance and then syncs from scratch to the remote instance.

**Comment by erikd** [comment]
Also, last time I check (less that 3 weeks ago) the size of the PostgreSQL database as 53 Gig. Not sure where you are getting this 100G figure.

**Comment by erikd** [comment]
Can this be closed?

**Comment by matcnft** [comment]
Hello @erikd , sorry for my late reply!

> Writing to a Postgres server that is not on the same machine as `db-sync` will likely be 4 times or more slower. It is not even a tested or supported configuration.
> 
> If you still want to pursue this untested and unsupported configuration then its up to you to figure out what is wrong. However `db-sync` only connects to a single postgres instance. I suspect the Docker stuff restores a snapshot to the local instance and then syncs from scratch to the remote instance.

Our db-sync has taken days for the syncing as we have the PostgreSQL on a different instance of the db-sync process. This is because we have several services that need to query the PostgreSQL continuoslty and in this way we can create read replicas to reduce the amount of queries to a single DB instance.

Could you elaborate the second part of the message, please? I see 50+GB of storage used in the db-sync machine. What are these snapshots exactly? Are they worth being backed up in case we would need to restore the db-sync/postgresql processes?

Thank you and have a great weekend!

**Comment by matcnft** [comment]
Hello @erikd , any news on this? We need to understand if we should backup the 50GB of db-sync data, thanks! :)
