### ISSUE TITLE
Minor spelling issue in autogenerated migration files

### ISSUE THREAD

**Issue by oneEdoubleD** [input-output-hk/cardano-db-sync#96]
The auto-generated SQL in the migration files have 'CREATe' instead of 'CREATE'. 

Example: https://github.com/input-output-hk/cardano-db-sync/blob/a85b14bc1ae6bd4d2c5e8d863a2be21f7efaff6e/schema/migration-2-0001-20200517.sql

This is very minor but can we clean this up?

**Comment by erikd** [comment]
These files are autogenerated by the the Persistent web framework. Changing them requires changes to Persistent. Sorry, its not worth it.

**Comment by oneEdoubleD** [comment]
Fair enough!
