### ISSUE TITLE
db-sync freezes on mir rewards handling

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#973]
One of the db-sync tests I'm currently writing https://github.com/input-output-hk/cardano-db-sync/pull/960/files#diff-81ed75e31cf74322027442ff4ea28726ba4ee68c26b7cc0006545c5b42d94989R235 freezes when the first block of the second epoch arrives. Debugging shows that this freeze happens in the `stashMirRewards` function, exactly at `putTMVar`. It seems the TMVar is not cleaned from the previous epoch. Probably we should assume no order between events `LedgerRewardDist` and `LedgerMirDist`.

Since it's a test, I'm not sure how realistic this scenario is.

**Comment by kderme** [comment]
In tests this was probably related to the configuration (k and f). So unlikely to happen in mainnet/testnet.

**Comment by erikd** [comment]
> Probably we should assume no order between events LedgerRewardDist and LedgerMirDist.

If you look at the two `stash*` functions, you will see that there is not order assumed but that **both** must arrive or it hangs. Unfortunatley `legder-specs` make handling this stuff difficult.

**Comment by erikd** [comment]
#953 has been closed so this one should be too.
