### ISSUE TITLE
docker health-check script  

### ISSUE THREAD

**Issue by stakelovelace** [input-output-hk/cardano-db-sync#983]
**OS**
Your OS:
Debian
**Versions**
The `db-sync` version (eg `cardano-db-sync --version`):
PostgreSQL version:
13.4
**Build/Install Method**
The method you use to build or install `cardano-db-sync`:
build
**Run method**
The method you used to run `cardano-db-sync` (eg Nix/Docker/systemd/none):
Docker
**Additional context**

**Problem Report**
Please do not include screenshots or images, but instead cut and paste any relevant log messages
or errors.
I guess would be nice to have an have an health check script within the db-sync official docker image (nix).

I am experiencing db-sync container losing connection with the node.socket and not recovering it ( I am going to open an other issue for it) and the health script can help recover the container without manual intervention.

**Comment by tmcgilchrist** [comment]
Hi @stakelovelace 

Something like the following script could be used as a health-check for db-sync.
It makes some assumptions about host names based off the [docker-compose.yml](https://github.com/input-output-hk/cardano-db-sync/blob/master/docker-compose.yml) available in this repository and the deployment being docker containers. 

The core checks are:
 * Is the service listening on EKG port? If not the service hasn't started yet.
 * Does the IPC socket exist for db-sync?
 
Along with the `healthcheck`  blocks in the docker config you could have:
``` yaml
    healthcheck:
      test: ["SHELL", "scripts/health-check.sh", "--check"]
      interval: 60s
      timeout: 10s
      retries: 5
```

``` bash
#!/usr/bin/env bash

# Unoffical bash strict mode.
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -u
set -o pipefail
IFS=$'\n\t'

progname="$0"

function die {
    echo "$1"
    exit 1
}

function check_cardano_db_sync {
    # Check EKG port is listening
    curl -f cardano-db-sync:12788 2>&1 || die "Error : Cardano DB Sync not listening on EKG port 12788."

    # Make sure we have a socket from cardano-node
    IPC_SOCKET="/node-ipc/node.socket"
    [ -f ${IPC_SOCKET} ] || die "Error : Cardano Node IPC socket missing at '${IPC_SOCKET}'."
}

function check_cardano_node {

    # Check cardano_node EKG port
    curl -f cardano-node:12788 2>&1 || die "Error : Cardano Node not listening on EKG port 12788."
}

function usage_exit {
    echo
    echo "Usage:"
    echo "    $progname --check             - Check health of db-sync."
    exit 0
}

case "${1:-""}" in
    --check)
        check_cardano_node
        check_cardano_db_sync
        ;;
    *)
	usage_exit
	;;
esac

echo "All good!"
exit 0
```

More detailed checks would need to take into account how the service has been deployed but I could imagine adding Postgres connectivity checks using `pg_isready -U postgres`  or specific queries.

**Comment by tmcgilchrist** [comment]
Resolved, a more specific health check script requires knowledge about the deployment environment.
