### ISSUE TITLE
Two consecutive Rewards or Mir events freeze db-sync.

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#994]
If two consecutive MirEvent or RewardEvent come db-sync freezes in
```liftIO . atomically $ putTMVar (lePoolRewards lenv) rmap```
or
```liftIO . atomically $ putTMVar (leMirRewards lenv) mirMap```

We could instead just append the rewards, instead of trying to rewrite.

This case is very impossible to happen in testnet/mainnet, because that's how ledger works right now. But it could change and we should assume nothing comming from the ledger since there is not a stable api.

**Comment by erikd** [comment]
This is a symptom of `ledger-specs` not providing this data in a form which is easy for `db-sync` to consume.

**Comment by kderme** [comment]
Fixed in https://github.com/input-output-hk/cardano-db-sync/pull/1094
