### ISSUE TITLE
[SMASH] Incorrect git revision for cardano-smash-server --version when built with cabal

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-db-sync#996]
**OS:**
Your OS: Linux Mint 20.2 Cinnamon
Linux Kernel: 5.4.0-90-generic

**Machine Specs:**
Processor: AMD Ryzen 9 3900X 12-Core Processor × 12
RAM: 32 GB

**Build/Install Method:**

Built on master, commit c45b954

`cabal build cardano-smash-server`

**Run method:**

```sh
./dist-newstyle/build/x86_64-linux/ghc-8.10.4/cardano-smash-server-12.0.0/build/cardano-smash-server/cardano-smash-server --version
cardano-smash-server 12.0.0 - linux-x86_64 - ghc-8.10
git revision 8996feff62f87bff9480d2267fa6a397edcdcb34
```

**Problem Report:**

I built `cardano-smash-server` on master, which has rev `c45b954d8a889b1e977c024e61dea2f166d7f40b`. When I ran
`cardano-smash-server --version` it reports `git revision 8996feff62f87bff9480d2267fa6a397edcdcb34`.

I did `cabal build all` and checked `db-sync` executables, they report the same revision as branch:

```sh
cabal run -- cardano-db-sync --version
Up to date
cardano-db-sync 12.0.0 - linux-x86_64 - ghc-8.10
git revision c45b954d8a889b1e977c024e61dea2f166d7f40b
```

```sh
cabal run -- cardano-db-tool version
Up to date
cardano-db-tool 12.0.0 - linux-x86_64 - ghc-8.10
git revision c45b954d8a889b1e977c024e61dea2f166d7f40b
```

**Comment by ArturWieczorek** [comment]
@kderme Maybe we can use this template for `SMASH` too ? https://github.com/input-output-hk/cardano-db-sync/pull/945
Or we already use it but the issue lies in the template ?

**Comment by erikd** [comment]
`cardano-smash-server` should use exactly the same method to display the git rev as `cardano-db=sync` and `cardano-db-tool` because these latter two seem to be correct at least when they are built with `cabal`.
